In [2]:
import pandas as pd

In [ ]:
df_co = pd.read_csv("../../02_Data/raw/gamefound_488_comments.csv")

In [41]:
df_co

,project_ID,comment_id,parent_id,depth_level,author_id,author_name,creator_id,is_pledge_master,is_backer,backer_number,is_prior_backer,is_pathfinder,has_children,children_count,text,created_at,likes
0,5787,1691589,NaN,0,1456332,BlackSiteStudios,1,False,False,NaN,False,False,False,0,WELCOME TO EDEN!\n\nPlease check the FAQ and t...,2025-06-01T23:14:35.6Z,26
1,5787,2617125,NaN,0,1744120,TheRealNedry,0,False,True,1016.0,False,False,False,0,I didn't see the email until now and it needs ...,2026-06-04T02:04:40.78Z,0
2,5787,2616975,NaN,0,495054,tdlowe44,0,False,True,1038.0,False,False,True,1,I received the emails with the links. I clicke...,2026-06-03T22:44:14.413Z,0
3,5787,2617025,2616975.0,1,1456332,BlackSiteStudios,1,False,False,NaN,False,False,False,0,Hmm thats odd. The files we have on Drivethru ...,2026-06-03T23:48:01.403Z,0
4,5787,2607093,NaN,0,78722,SinisterHobby,0,False,True,NaN,False,False,False,0,Fingers crossed the physical book orders are a...,2026-05-29T18:16:59.173Z,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
897051,1143,98174,NaN,0,457997,RiggedDiceGames,0,True,False,NaN,False,False,True,2,Hello! This game looks very interesting. Do yo...,2021-08-05T20:57:21.32Z,2
897052,1143,98616,98174.0,1,542570,Klabater,1,False,False,NaN,False,False,False,0,Hi there RiggedDiceGames. Currently TBC. Howev...,2021-08-06T09:21:26.337Z,2
897053,1143,99582,98174.0,1,457997,RiggedDiceGames,0,True,False,NaN,False,False,False,0,Looking forward to it!,2021-08-09T00:35:44.433Z,1
897054,1143,96836,NaN,0,49686,Mycha,0,False,False,NaN,False,False,True,1,"Please, do not let this game to be as unpolish...",2021-08-04T16:28:33.583Z,3
897055,1143,97582,96836.0,1,542570,Klabater,1,False,False,NaN,False,False,False,0,"Hi Mycha, thanks for the feedback, we apprecia...",2021-08-05T09:53:33.003Z,2

In [44]:
df_co.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 897056 entries, 0 to 897055
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   project_ID        897056 non-null  int64
 1   comment_id        897056 non-null  int64
 2   parent_id         621563 non-null  float64
 3   depth_level       897056 non-null  int64
 4   author_id         897056 non-null  int64
 5   author_name       897053 non-null  object
 6   creator_id        897056 non-null  int64
 7   is_pledge_master  897056 non-null  bool
 8   is_backer         897056 non-null  bool
 9   backer_number     569626 non-null  float64
 10  is_prior_backer   897056 non-null  bool
 11  is_pathfinder     897056 non-null  bool
 12  has_children      897056 non-null  bool
 13  children_count    897056 non-null  int64
 14  text              896974 non-null  object
 15  created_at        897056 non-null  object
 16  likes             897056 non-null  int64
dtypes: bool(5), float64(2), int64(7), object(3)
memory usage: 86.4+ MB

In [42]:
df_list = pd.read_csv("data/final_gamefound_list.csv")

In [43]:
df_list

,name,projectID,project_url,creator,creatorID,homeUrl,currencySymbol,campaignGoal,fundsGathered,backersCount,...,minPlayers,maxPlayers,minAge,playTime,playTimeUnit,fundedInSeconds,imageUrl,pledgeManagerSoftCloseDeadline,projectTags,originalType
0,We Played God - A Survival Miniatures Game,5787,https://gamefound.com:443/en/projects/black-si...,Black Site Studios,5252,https://gamefound.com/creators/black-site-studios,$,10000.0,393538.44,1567,...,NaN,NaN,NaN,NaN,0,628,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-02T15:00:00Z,"Exploration, Horror, Modern, Science Fiction, ...",1
1,CARNIVORE,6481,https://gamefound.com:443/en/projects/buer-gam...,Buer Games,6737,https://gamefound.com/creators/buer-games,$,20000.0,247988.30,1075,...,1.0,4.0,13.0,90.0,0,2716,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-01T14:00:00Z,"History, Strategy, Wargame, Action, Collectibl...",1
2,1809: Talavera,8024,https://gamefound.com:443/en/projects/tactical...,Tactical Workshop,5141,https://gamefound.com/creators/tactical-workshop,$,7000.0,23091.47,215,...,1.0,2.0,12.0,8.0,1,56442,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"History, Strategy, Wargame",1
3,Comber Cat,8225,https://gamefound.com:443/en/projects/gamedolf...,Gamedolf Limited,8739,https://gamefound.com/creators/gamedolflimited,$,300.0,645.66,12,...,2.0,5.0,8.0,15.0,0,2409627,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Card Game, Strategy, Party game, Family",1
4,Jano - A Pawsome Adventure,5995,https://gamefound.com:443/en/projects/aszaki/j...,aszaki,7221,https://gamefound.com/creators/aszaki,€,1000.0,4042.67,89,...,2.0,6.0,8.0,20.0,0,14439,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-11T13:00:00Z,"Strategy, Resource management, Family, Worker ...",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
483,Tectonia,2109,https://gamefound.com:443/en/projects/hagen-be...,Hagen Behr,2703,https://gamefound.com/creators/hagen-behr,€,20000.0,8001.00,113,...,2.0,4.0,14.0,180.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Strategy, Wargame, Dice Game, Area Control, Co...",1
484,Invasion Cards,2149,https://gamefound.com:443/en/projects/lawrence...,Lawrence Lyle,2742,https://gamefound.com/creators/lawrence-lyle,€,9800.0,70.00,2,...,2.0,4.0,5.0,25.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Strategy, Humor",1
485,MOOGH,1919,https://gamefound.com:443/en/projects/nuts-pub...,Nuts! Publishing,2363,https://gamefound.com/creators/nuts-publishing,€,10000.0,6285.00,143,...,1.0,4.0,14.0,30.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Dice Game, Multiplayer, Competitive, Campaign",1
486,Crossroads Inn: The Board Game,1143,https://gamefound.com:443/en/projects/klabater...,Klabater,1510,https://gamefound.com/creators/klabater,€,20000.0,13420.63,158,...,2.0,4.0,12.0,120.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Strategy, Terrain Building, Humor",1
487,Goldenstar: The Galactic Tournament,1325,https://gamefound.com:443/en/projects/gindi/go...,Gindi,64,https://gamefound.com/creators/gindi,€,30000.0,10890.00,148,...,2.0,4.0,14.0,60.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Science Fiction, Area Control, Deck Building",1

In [12]:
df_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 488 entries, 0 to 487
Data columns (total 24 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   name                            488 non-null    object
 1   projectID                       488 non-null    int64
 2   project_url                     488 non-null    object
 3   creator                         488 non-null    object
 4   creatorID                       488 non-null    int64
 5   homeUrl                         488 non-null    object
 6   currencySymbol                  488 non-null    object
 7   campaignGoal                    488 non-null    float64
 8   fundsGathered                   488 non-null    float64
 9   backersCount                    488 non-null    int64
 10  campaignStart                   488 non-null    object
 11  campaignEnd                     488 non-null    object
 12  phaseLabel                      488 non-null    object
 13  enableBoardGameProperties       488 non-null    bool
 14  minPlayers                      474 non-null    float64
 15  maxPlayers                      474 non-null    float64
 16  minAge                          457 non-null    float64
 17  playTime                        461 non-null    float64
 18  playTimeUnit                    488 non-null    int64
 19  fundedInSeconds                 488 non-null    int64
 20  imageUrl                        488 non-null    object
 21  pledgeManagerSoftCloseDeadline  304 non-null    object
 22  projectTags                     488 non-null    object
 23  originalType                    488 non-null    int64
dtypes: bool(1), float64(6), int64(6), object(11)
memory usage: 88.3+ KB

In [45]:
df_co.rename(columns={'project_ID':'projectID'}, inplace=True)

#### merge

In [46]:
df_co = df_co.merge(
    df_list[['projectID', 'phaseLabel','campaignStart','campaignEnd']],
    on='projectID',
    how='left'
)

In [47]:
df_co.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 897056 entries, 0 to 897055
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   projectID         897056 non-null  int64
 1   comment_id        897056 non-null  int64
 2   parent_id         621563 non-null  float64
 3   depth_level       897056 non-null  int64
 4   author_id         897056 non-null  int64
 5   author_name       897053 non-null  object
 6   creator_id        897056 non-null  int64
 7   is_pledge_master  897056 non-null  bool
 8   is_backer         897056 non-null  bool
 9   backer_number     569626 non-null  float64
 10  is_prior_backer   897056 non-null  bool
 11  is_pathfinder     897056 non-null  bool
 12  has_children      897056 non-null  bool
 13  children_count    897056 non-null  int64
 14  text              896974 non-null  object
 15  created_at        897056 non-null  object
 16  likes             897056 non-null  int64
 17  phaseLabel        897056 non-null  object
 18  campaignStart     897056 non-null  object
 19  campaignEnd       897056 non-null  object
dtypes: bool(5), float64(2), int64(7), object(6)
memory usage: 106.9+ MB

In [19]:
df_co

,projectID,comment_id,parent_id,depth_level,author_id,author_name,creator_id,is_pledge_master,is_backer,backer_number,is_prior_backer,is_pathfinder,has_children,children_count,text,created_at,likes,phaseLabel
0,5787,1691589,NaN,0,1456332,BlackSiteStudios,1,False,False,NaN,False,False,False,0,WELCOME TO EDEN!\n\nPlease check the FAQ and t...,2025-06-01T23:14:35.6Z,26,Pledge manager - Closed
1,5787,2617125,NaN,0,1744120,TheRealNedry,0,False,True,1016.0,False,False,False,0,I didn't see the email until now and it needs ...,2026-06-04T02:04:40.78Z,0,Pledge manager - Closed
2,5787,2616975,NaN,0,495054,tdlowe44,0,False,True,1038.0,False,False,True,1,I received the emails with the links. I clicke...,2026-06-03T22:44:14.413Z,0,Pledge manager - Closed
3,5787,2617025,2616975.0,1,1456332,BlackSiteStudios,1,False,False,NaN,False,False,False,0,Hmm thats odd. The files we have on Drivethru ...,2026-06-03T23:48:01.403Z,0,Pledge manager - Closed
4,5787,2607093,NaN,0,78722,SinisterHobby,0,False,True,NaN,False,False,False,0,Fingers crossed the physical book orders are a...,2026-05-29T18:16:59.173Z,2,Pledge manager - Closed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
897051,1143,98174,NaN,0,457997,RiggedDiceGames,0,True,False,NaN,False,False,True,2,Hello! This game looks very interesting. Do yo...,2021-08-05T20:57:21.32Z,2,Crowdfunding - Unsuccessful
897052,1143,98616,98174.0,1,542570,Klabater,1,False,False,NaN,False,False,False,0,Hi there RiggedDiceGames. Currently TBC. Howev...,2021-08-06T09:21:26.337Z,2,Crowdfunding - Unsuccessful
897053,1143,99582,98174.0,1,457997,RiggedDiceGames,0,True,False,NaN,False,False,False,0,Looking forward to it!,2021-08-09T00:35:44.433Z,1,Crowdfunding - Unsuccessful
897054,1143,96836,NaN,0,49686,Mycha,0,False,False,NaN,False,False,True,1,"Please, do not let this game to be as unpolish...",2021-08-04T16:28:33.583Z,3,Crowdfunding - Unsuccessful
897055,1143,97582,96836.0,1,542570,Klabater,1,False,False,NaN,False,False,False,0,"Hi Mycha, thanks for the feedback, we apprecia...",2021-08-05T09:53:33.003Z,2,Crowdfunding - Unsuccessful

In [39]:
df_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 488 entries, 0 to 487
Data columns (total 24 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   name                            488 non-null    object
 1   projectID                       488 non-null    int64
 2   project_url                     488 non-null    object
 3   creator                         488 non-null    object
 4   creatorID                       488 non-null    int64
 5   homeUrl                         488 non-null    object
 6   currencySymbol                  488 non-null    object
 7   campaignGoal                    488 non-null    float64
 8   fundsGathered                   488 non-null    float64
 9   backersCount                    488 non-null    int64
 10  campaignStart                   488 non-null    object
 11  campaignEnd                     488 non-null    object
 12  phaseLabel                      488 non-null    object
 13  enableBoardGameProperties       488 non-null    bool
 14  minPlayers                      474 non-null    float64
 15  maxPlayers                      474 non-null    float64
 16  minAge                          457 non-null    float64
 17  playTime                        461 non-null    float64
 18  playTimeUnit                    488 non-null    int64
 19  fundedInSeconds                 488 non-null    int64
 20  imageUrl                        488 non-null    object
 21  pledgeManagerSoftCloseDeadline  304 non-null    object
 22  projectTags                     488 non-null    object
 23  originalType                    488 non-null    int64
dtypes: bool(1), float64(6), int64(6), object(11)
memory usage: 88.3+ KB

#### merge check

In [48]:
check = df_co[['projectID', 'phaseLabel','campaignStart','campaignEnd']].merge(
    df_list[['projectID', 'phaseLabel','campaignStart','campaignEnd']],
    on='projectID',
    how='left',
    suffixes=('_df_co', '_df_list')
)

(check['phaseLabel_df_co'] == check['phaseLabel_df_list']).value_counts(dropna=False)

True    897056
Name: count, dtype: int64

In [49]:
df_co.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 897056 entries, 0 to 897055
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   projectID         897056 non-null  int64
 1   comment_id        897056 non-null  int64
 2   parent_id         621563 non-null  float64
 3   depth_level       897056 non-null  int64
 4   author_id         897056 non-null  int64
 5   author_name       897053 non-null  object
 6   creator_id        897056 non-null  int64
 7   is_pledge_master  897056 non-null  bool
 8   is_backer         897056 non-null  bool
 9   backer_number     569626 non-null  float64
 10  is_prior_backer   897056 non-null  bool
 11  is_pathfinder     897056 non-null  bool
 12  has_children      897056 non-null  bool
 13  children_count    897056 non-null  int64
 14  text              896974 non-null  object
 15  created_at        897056 non-null  object
 16  likes             897056 non-null  int64
 17  phaseLabel        897056 non-null  object
 18  campaignStart     897056 non-null  object
 19  campaignEnd       897056 non-null  object
dtypes: bool(5), float64(2), int64(7), object(6)
memory usage: 106.9+ MB

In [50]:
df_co[['created_at','campaignStart','campaignEnd']]

,created_at,campaignStart,campaignEnd
0,2025-06-01T23:14:35.6Z,2025-06-17T14:30:00Z,2025-07-19T00:50:35.25Z
1,2026-06-04T02:04:40.78Z,2025-06-17T14:30:00Z,2025-07-19T00:50:35.25Z
2,2026-06-03T22:44:14.413Z,2025-06-17T14:30:00Z,2025-07-19T00:50:35.25Z
3,2026-06-03T23:48:01.403Z,2025-06-17T14:30:00Z,2025-07-19T00:50:35.25Z
4,2026-05-29T18:16:59.173Z,2025-06-17T14:30:00Z,2025-07-19T00:50:35.25Z
...,...,...,...
897051,2021-08-05T20:57:21.32Z,2021-10-28T14:00:00Z,2021-11-30T15:00:00Z
897052,2021-08-06T09:21:26.337Z,2021-10-28T14:00:00Z,2021-11-30T15:00:00Z
897053,2021-08-09T00:35:44.433Z,2021-10-28T14:00:00Z,2021-11-30T15:00:00Z
897054,2021-08-04T16:28:33.583Z,2021-10-28T14:00:00Z,2021-11-30T15:00:00Z
897055,2021-08-05T09:53:33.003Z,2021-10-28T14:00:00Z,2021-11-30T15:00:00Z

In [24]:
df_co['phaseLabel'].unique()

array(['Pledge manager - Closed', 'Crowdfunding - Funded',
       'Crowdfunding - Unsuccessful'], dtype=object)

In [52]:
df_co['created_at'] = pd.to_datetime(df_co['created_at'], format='ISO8601', utc=True, errors='coerce')
df_co['campaignStart'] = pd.to_datetime(df_co['campaignStart'], format='ISO8601', utc=True, errors='coerce')
df_co['campaignEnd'] = pd.to_datetime(df_co['campaignEnd'], format='ISO8601', utc=True, errors='coerce')

df_co_14 = df_co[
    (df_co['created_at'] >= df_co['campaignStart']) &
    (df_co['created_at'] <= df_co['campaignStart'] + pd.Timedelta(days=14))
].copy()

df_co_14

,projectID,comment_id,parent_id,depth_level,author_id,author_name,creator_id,is_pledge_master,is_backer,backer_number,is_prior_backer,is_pathfinder,has_children,children_count,text,created_at,likes,phaseLabel,campaignStart,campaignEnd
384,5787,1763089,NaN,0,826115,FossilPunkFoundry,0,False,True,61.0,False,False,True,2,Super excited for this! I pledged at the Eden ...,2025-06-30 21:00:47.050000+00:00,0,Pledge manager - Closed,2025-06-17 14:30:00+00:00,2025-07-19 00:50:35.250000+00:00
385,5787,1763408,1763089.0,1,1456332,BlackSiteStudios,1,False,False,NaN,False,False,False,0,Yep!,2025-06-30 23:46:42.830000+00:00,1,Pledge manager - Closed,2025-06-17 14:30:00+00:00,2025-07-19 00:50:35.250000+00:00
386,5787,1763658,1763089.0,1,826115,FossilPunkFoundry,0,False,True,61.0,False,False,False,0,Thanks! Really excited about this one!,2025-07-01 04:06:13.763000+00:00,1,Pledge manager - Closed,2025-06-17 14:30:00+00:00,2025-07-19 00:50:35.250000+00:00
387,5787,1760170,NaN,0,1742034,Willsee,0,False,True,544.0,False,False,True,3,"I'm personally excited for this game, I seen t...",2025-06-29 15:39:33.660000+00:00,3,Pledge manager - Closed,2025-06-17 14:30:00+00:00,2025-07-19 00:50:35.250000+00:00
388,5787,1760421,1760170.0,1,1032598,BSSDoug,1,False,False,NaN,False,False,False,0,1. This would cause pretty significant balance...,2025-06-29 18:36:59.670000+00:00,3,Pledge manager - Closed,2025-06-17 14:30:00+00:00,2025-07-19 00:50:35.250000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
896992,1143,133243,133074.0,1,542570,Klabater,1,False,False,NaN,False,False,False,0,Player tokens are already in both editions.,2021-10-28 17:59:35.247000+00:00,0,Crowdfunding - Unsuccessful,2021-10-28 14:00:00+00:00,2021-11-30 15:00:00+00:00
896993,1143,133247,133074.0,1,306895,The_Rycorian_Ambassador,0,True,True,63.0,False,False,False,0,@klabater\n\nHi! You say the 3D player models ...,2021-10-28 18:05:56.203000+00:00,0,Crowdfunding - Unsuccessful,2021-10-28 14:00:00+00:00,2021-11-30 15:00:00+00:00
896995,1143,133208,132958.0,1,542570,Klabater,1,False,False,NaN,False,False,False,0,Dziękujemy za wsparcie! Koszt przesyłki to 2 E...,2021-10-28 17:03:09.493000+00:00,2,Crowdfunding - Unsuccessful,2021-10-28 14:00:00+00:00,2021-11-30 15:00:00+00:00
896999,1143,133056,132685.0,1,401450,bossofbosses,0,False,False,NaN,False,False,False,0,Then why is his chin half-shaven? Stop pretend...,2021-10-28 14:10:26.820000+00:00,0,Crowdfunding - Unsuccessful,2021-10-28 14:00:00+00:00,2021-11-30 15:00:00+00:00
897007,1143,133109,132650.0,1,275216,Yadayada,0,False,False,NaN,False,False,False,0,"Son: Dad, what's a cuckold?\nFather: ""A man wh...",2021-10-28 15:20:20.597000+00:00,0,Crowdfunding - Unsuccessful,2021-10-28 14:00:00+00:00,2021-11-30 15:00:00+00:00

### 기간 csv 저장

In [ ]:
df_co_14.to_csv('../../02_Data/processed/comments_14days.csv', index=False,
    encoding="utf-8-sig")

In [53]:
df_co[['created_at', 'campaignStart', 'campaignEnd']].isna().sum()

created_at       0
campaignStart    0
campaignEnd      0
dtype: int64