In [1]:
import pandas as pd

df = pd.read_csv("../../02_Data/raw/gamefound_list.csv")

In [2]:
df.columns

Index(['name', 'projectID', 'creator', 'creatorID', 'homeUrl',
       'currencySymbol', 'campaignGoal', 'fundsGathered', 'backersCount',
       'campaignStart', 'campaignEnd', 'description', 'project_url',
       'phaseLabel', 'enableBoardGameProperties', 'minPlayers', 'maxPlayers',
       'minAge', 'playTime', 'playTimeDescription', 'playTimeUnit',
       'pledgeManagerAvailability', 'fundedInSeconds', 'imageUrl',
       'pledgeManagerSoftCloseDeadline', 'projectTags',
       'enableShippingOnlyMode', 'originalType'],
      dtype='object')

In [4]:
a_list = ['name', 'projectID', 'creator', 'creatorID', 'homeUrl',
       'currencySymbol', 'campaignGoal', 'fundsGathered', 'backersCount',
       'campaignStart', 'campaignEnd',
       'phaseLabel', 'enableBoardGameProperties', 'minPlayers', 'maxPlayers',
       'minAge', 'playTime', 'playTimeUnit',
       'fundedInSeconds', 'imageUrl',
       'pledgeManagerSoftCloseDeadline', 'projectTags',
       'originalType']

In [5]:
pd.set_option('display.max_columns', None)
df = df[a_list]

In [6]:
df.loc[df['originalType']==0]

,name,projectID,creator,creatorID,homeUrl,currencySymbol,campaignGoal,fundsGathered,backersCount,campaignStart,campaignEnd,phaseLabel,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,playTimeUnit,fundedInSeconds,imageUrl,pledgeManagerSoftCloseDeadline,projectTags,originalType
440,Escape From mars,10054,Dark Frontier Games,4262,https://gamefound.com/creators/dfg,£,NaN,41989.04,705,NaN,NaN,Late Pledge - Open for all,True,1.0,4.0,14.0,80.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Horror, Science Fiction, Survival, Dice Game, ...",0
442,Beat Box Party,10072,Boiling Point Games,8720,https://gamefound.com/creators/boiling-point-g...,$,NaN,8290.00,65,NaN,NaN,Pledge manager - Open for all,True,3.0,10.0,14.0,15.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,2026-08-31T17:00:00Z,Party game,0
446,Travel Bug Card Game,11304,DominoTracks,8807,https://gamefound.com/creators/dominotracks,$,NaN,4584.00,21,NaN,NaN,Late Pledge - Open for all,True,2.0,4.0,8.0,15.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Card Game, Adventure, Family",0
448,The Malice of Light Adventures Pledge Manager,10154,Twin Tale Studios,7366,https://gamefound.com/creators/twin-tale-studios,$,NaN,78301.58,727,NaN,NaN,Pledge manager - Open for all,True,1.0,4.0,14.0,90.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Card Game, Fantasy, Dice Game, Strategy, Coope...",0
455,The Cats of New Orleans,9843,Raybox Games,278,https://gamefound.com/creators/rayboxgames,C$,NaN,201031.73,1069,NaN,NaN,Pledge manager - Open for all,True,1.0,4.0,14.0,30.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Mythology, Digital, Adventure, Paint",0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2281,GKR: Heavy Hitters,13,Weta Workshop,11,https://gamefound.com/creators/weta-workshop,$,NaN,0.00,0,NaN,NaN,Pledge manager - Closed,False,NaN,NaN,NaN,NaN,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Wargame, Science Fiction, Dice Game, Area Control",0
2282,Endure The Stars,12,Grimlord Games,10,https://gamefound.com/creators/grimlord-games,£,NaN,0.00,0,NaN,NaN,Pledge manager - Closed,False,NaN,NaN,NaN,NaN,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Science Fiction, Survival",0
2283,Star Scrappers: Cave-In,9,Hexy Studio,7,https://gamefound.com/creators/hexy-studio,$,NaN,0.00,0,NaN,NaN,Pledge manager - Closed,False,NaN,NaN,NaN,NaN,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Card Game, Science Fiction, Deck Building",0
2284,Board&Dice,8,Board&Dice,6,https://gamefound.com/creators/board-and-dice,$,NaN,0.00,0,NaN,NaN,Pledge manager - Closed,False,NaN,NaN,NaN,NaN,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Exploration, Fantasy, Card Game, History, Stra...",0
2285,BATTALIA: The Stormgates,3,Fantasmagoria Games LLC,5,https://gamefound.com/creators/fantasmagoria-g...,$,NaN,0.00,0,NaN,NaN,Pledge manager - Closed,False,NaN,NaN,NaN,NaN,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Card Game, Fantasy, Strategy, Terrain Building...",0

In [7]:
df.loc[df['originalType']==1]

,name,projectID,creator,creatorID,homeUrl,currencySymbol,campaignGoal,fundsGathered,backersCount,campaignStart,campaignEnd,phaseLabel,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,playTimeUnit,fundedInSeconds,imageUrl,pledgeManagerSoftCloseDeadline,projectTags,originalType
0,Bloodstone,8454,Druid City Games,8843,https://gamefound.com/creators/druid-city-games,$,50000.0,95253.93,479,2026-06-02T13:00:00Z,2026-06-19T22:00:00Z,Crowdfunding,True,1.0,5.0,14.0,60.0,0,7770,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Multiplayer, Competitive, Dice Game, ...",1
2,A Life,9816,Skellig Games,2434,https://gamefound.com/creators/skellig-games,€,10000.0,22796.57,203,2026-06-02T15:00:00Z,2026-06-25T18:00:00Z,Crowdfunding,True,1.0,4.0,8.0,60.0,0,3756,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Set Collection, Competitive, Family, Narrative...",1
3,Growing Season Deluxe Edition,8617,Undigital,5415,https://gamefound.com/creators/undigital,€,8000.0,15291.46,361,2026-06-02T16:00:00Z,2026-06-22T22:00:00Z,Crowdfunding,True,1.0,4.0,8.0,30.0,0,4725,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Card Game, Strategy, Video Game Theme, Multipl...",1
4,Stonesaga Second Printing,9678,Open Owl Studios,474,https://gamefound.com/creators/oomm-games,$,25000.0,154784.30,1791,2026-05-26T15:00:00Z,2026-06-20T00:00:00Z,Crowdfunding,True,1.0,4.0,NaN,90.0,0,1764,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Mythology, Cooperative, Campaign, Civ...",1
5,Beast: Ashfall,8330,Studio Midhall,2936,https://gamefound.com/creators/studio-midhall,€,50000.0,490554.96,3420,2026-05-05T15:00:00Z,2026-06-03T22:00:00Z,Crowdfunding,True,2.0,5.0,14.0,120.0,0,3645,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Strategy, Multiplayer, Competitive, A...",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2585,Spring and Autumn: Story of China,1446,Mr. B. Games,1954,https://gamefound.com/creators/mr-b-games,$,30000.0,38009.00,219,2021-12-01T15:00:00Z,2022-01-04T22:00:00Z,Crowdfunding - Canceled,True,1.0,5.0,13.0,120.0,0,182152,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Exploration, History, Strategy, Area Control",1
2586,Crossroads Inn: The Board Game,1143,Klabater,1510,https://gamefound.com/creators/klabater,€,20000.0,13420.63,158,2021-10-28T14:00:00Z,2021-11-30T15:00:00Z,Crowdfunding - Unsuccessful,True,2.0,4.0,12.0,120.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Strategy, Terrain Building, Humor",1
2587,PACHAMAMA,1170,SitDown,1514,https://gamefound.com/creators/sitdown,€,25000.0,16048.00,318,2021-10-19T17:00:00Z,2021-11-09T18:00:00Z,Crowdfunding - Canceled,True,1.0,4.0,14.0,60.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Exploration, Logical, Deduction, Terrain Building",1
2588,Taverns & Dragons (Canceled),1314,Lord Raccoon Games,356,https://gamefound.com/creators/thelastbottle,€,20000.0,20954.00,470,2021-10-12T13:00:00Z,2021-11-03T22:00:00Z,Crowdfunding - Canceled,True,2.0,5.0,10.0,60.0,0,433495,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Exploration, Card Game, Fantasy, Dice Game, St...",1
2589,Goldenstar: The Galactic Tournament,1325,Gindi,64,https://gamefound.com/creators/gindi,€,30000.0,10890.00,148,2021-10-05T16:00:00Z,2021-10-29T16:00:00Z,Crowdfunding - Unsuccessful,True,2.0,4.0,14.0,60.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Science Fiction, Area Control, Deck Building",1

In [8]:
df.loc[df['originalType']==1]['phaseLabel'].value_counts()

Upcoming                         389
Pledge manager - Closed          322
Pledge manager - Limited         148
Crowdfunding - Canceled          136
Crowdfunding - Unsuccessful      124
Pledge manager - Open for all    112
Late Pledge - Open for all        89
Crowdfunding - Funded             42
Crowdfunding                      39
Late Pledge - Ended                1
Name: phaseLabel, dtype: int64

In [9]:
target_list = ["Pledge manager - Closed","Crowdfunding - Unsuccessful","Crowdfunding - Funded"]

In [10]:
df = df.loc[(df['originalType']==1)&(df['phaseLabel'].isin(target_list))].reset_index(drop=True)

In [12]:
df.to_csv("../../02_data/processed/final_gamefound_list.csv", index=False, encoding="utf-8-sig")

In [11]:
df

,name,projectID,creator,creatorID,homeUrl,currencySymbol,campaignGoal,fundsGathered,backersCount,campaignStart,campaignEnd,phaseLabel,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,playTimeUnit,fundedInSeconds,imageUrl,pledgeManagerSoftCloseDeadline,projectTags,originalType
0,We Played God - A Survival Miniatures Game,5787,Black Site Studios,5252,https://gamefound.com/creators/black-site-studios,$,10000.0,393538.44,1567,2025-06-17T14:30:00Z,2025-07-19T00:50:35.25Z,Pledge manager - Closed,False,NaN,NaN,NaN,NaN,0,628,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-02T15:00:00Z,"Exploration, Horror, Modern, Science Fiction, ...",1
1,CARNIVORE,6481,Buer Games,6737,https://gamefound.com/creators/buer-games,$,20000.0,247988.30,1075,2026-02-25T16:00:00Z,2026-03-31T15:57:23.953Z,Pledge manager - Closed,True,1.0,4.0,13.0,90.0,0,2716,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-01T14:00:00Z,"History, Strategy, Wargame, Action, Collectibl...",1
2,1809: Talavera,8024,Tactical Workshop,5141,https://gamefound.com/creators/tactical-workshop,$,7000.0,23091.47,215,2026-03-01T05:00:00Z,2026-04-01T05:00:00Z,Pledge manager - Closed,True,1.0,2.0,12.0,8.0,1,56442,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"History, Strategy, Wargame",1
3,Comber Cat,8225,Gamedolf Limited,8739,https://gamefound.com/creators/gamedolflimited,$,300.0,645.66,12,2026-02-02T13:00:00Z,2026-03-02T13:00:00Z,Pledge manager - Closed,True,2.0,5.0,8.0,15.0,0,2409627,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Card Game, Strategy, Party game, Family",1
4,Jano - A Pawsome Adventure,5995,aszaki,7221,https://gamefound.com/creators/aszaki,€,1000.0,4042.67,89,2026-01-16T12:00:00Z,2026-02-28T12:00:00Z,Pledge manager - Closed,True,2.0,6.0,8.0,20.0,0,14439,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-11T13:00:00Z,"Strategy, Resource management, Family, Worker ...",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
483,Tectonia,2109,Hagen Behr,2703,https://gamefound.com/creators/hagen-behr,€,20000.0,8001.00,113,2022-07-05T18:00:00Z,2022-07-26T18:00:00Z,Crowdfunding - Unsuccessful,True,2.0,4.0,14.0,180.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Strategy, Wargame, Dice Game, Area Control, Co...",1
484,Invasion Cards,2149,Lawrence Lyle,2742,https://gamefound.com/creators/lawrence-lyle,€,9800.0,70.00,2,2022-07-04T10:00:00Z,2022-08-03T21:00:00Z,Crowdfunding - Unsuccessful,True,2.0,4.0,5.0,25.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Strategy, Humor",1
485,MOOGH,1919,Nuts! Publishing,2363,https://gamefound.com/creators/nuts-publishing,€,10000.0,6285.00,143,2022-04-26T16:00:00Z,2022-05-12T16:00:00Z,Crowdfunding - Unsuccessful,True,1.0,4.0,14.0,30.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Dice Game, Multiplayer, Competitive, Campaign",1
486,Crossroads Inn: The Board Game,1143,Klabater,1510,https://gamefound.com/creators/klabater,€,20000.0,13420.63,158,2021-10-28T14:00:00Z,2021-11-30T15:00:00Z,Crowdfunding - Unsuccessful,True,2.0,4.0,12.0,120.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Strategy, Terrain Building, Humor",1
487,Goldenstar: The Galactic Tournament,1325,Gindi,64,https://gamefound.com/creators/gindi,€,30000.0,10890.00,148,2021-10-05T16:00:00Z,2021-10-29T16:00:00Z,Crowdfunding - Unsuccessful,True,2.0,4.0,14.0,60.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Science Fiction, Area Control, Deck Building",1