In [1]:
import pandas as pd

df = pd.read_csv("../../02_Data/raw/gamefound_list.csv")

In [2]:
df.columns

Index(['name', 'projectID', 'creator', 'creatorID', 'homeUrl',
       'currencySymbol', 'campaignGoal', 'fundsGathered', 'backersCount',
       'campaignStart', 'campaignEnd', 'description', 'project_url',
       'phaseLabel', 'enableBoardGameProperties', 'minPlayers', 'maxPlayers',
       'minAge', 'playTime', 'playTimeDescription', 'playTimeUnit',
       'pledgeManagerAvailability', 'fundedInSeconds', 'imageUrl',
       'pledgeManagerSoftCloseDeadline', 'projectTags',
       'enableShippingOnlyMode', 'originalType'],
      dtype='object')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2590 entries, 0 to 2589
Data columns (total 28 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   name                            2590 non-null   object
 1   projectID                       2590 non-null   int64
 2   creator                         2590 non-null   object
 3   creatorID                       2590 non-null   int64
 4   homeUrl                         2590 non-null   object
 5   currencySymbol                  2590 non-null   object
 6   campaignGoal                    1381 non-null   float64
 7   fundsGathered                   2590 non-null   float64
 8   backersCount                    2590 non-null   int64
 9   campaignStart                   1035 non-null   object
 10  campaignEnd                     1187 non-null   object
 11  description                     2587 non-null   object
 12  project_url                     2590 non-null   object
 13  phaseLabel                      2590 non-null   object
 14  enableBoardGameProperties       2590 non-null   bool
 15  minPlayers                      2277 non-null   float64
 16  maxPlayers                      2275 non-null   float64
 17  minAge                          2121 non-null   float64
 18  playTime                        2146 non-null   float64
 19  playTimeDescription             0 non-null      float64
 20  playTimeUnit                    2590 non-null   int64
 21  pledgeManagerAvailability       1689 non-null   float64
 22  fundedInSeconds                 2590 non-null   int64
 23  imageUrl                        2590 non-null   object
 24  pledgeManagerSoftCloseDeadline  560 non-null    object
 25  projectTags                     2558 non-null   object
 26  enableShippingOnlyMode          1689 non-null   object
 27  originalType                    2590 non-null   int64
dtypes: bool(1), float64(8), int64(6), object(13)
memory usage: 549.0+ KB

In [4]:
pd.set_option('display.max_columns', None)
df.head()

,name,projectID,creator,creatorID,homeUrl,currencySymbol,campaignGoal,fundsGathered,backersCount,campaignStart,campaignEnd,description,project_url,phaseLabel,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,playTimeDescription,playTimeUnit,pledgeManagerAvailability,fundedInSeconds,imageUrl,pledgeManagerSoftCloseDeadline,projectTags,enableShippingOnlyMode,originalType
0,Bloodstone,8454,Druid City Games,8843,https://gamefound.com/creators/druid-city-games,$,50000.0,95253.93,479,2026-06-02T13:00:00Z,2026-06-19T22:00:00Z,Bloodstone throws you into Vanira’s deadly are...,https://gamefound.com:443/en/projects/druid-ci...,Crowdfunding,True,1.0,5.0,14.0,60.0,NaN,0,NaN,7770,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Multiplayer, Competitive, Dice Game, ...",NaN,1
1,Aeolis,8619,Meeple Pug,3547,https://gamefound.com/creators/meeple-pug,€,NaN,33881.89,315,2026-06-02T15:00:00Z,2026-06-11T19:00:00Z,Aeolis is a fully cooperative kingdom-building...,https://gamefound.com:443/en/projects/meeple-p...,Express crowdfunding,True,1.0,7.0,14.0,60.0,NaN,0,NaN,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Area Control, Cooperative, Multiplayer, Campaign",NaN,2
2,A Life,9816,Skellig Games,2434,https://gamefound.com/creators/skellig-games,€,10000.0,22796.57,203,2026-06-02T15:00:00Z,2026-06-25T18:00:00Z,"In ""A Life"" 1-4 players play through a lifetim...",https://gamefound.com:443/en/projects/skellig-...,Crowdfunding,True,1.0,4.0,8.0,60.0,NaN,0,NaN,3756,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Set Collection, Competitive, Family, Narrative...",NaN,1
3,Growing Season Deluxe Edition,8617,Undigital,5415,https://gamefound.com/creators/undigital,€,8000.0,15291.46,361,2026-06-02T16:00:00Z,2026-06-22T22:00:00Z,Turn a quiet field into a thriving farm in thi...,https://gamefound.com:443/en/projects/undigita...,Crowdfunding,True,1.0,4.0,8.0,30.0,NaN,0,NaN,4725,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Card Game, Strategy, Video Game Theme, Multipl...",NaN,1
4,Stonesaga Second Printing,9678,Open Owl Studios,474,https://gamefound.com/creators/oomm-games,$,25000.0,154784.30,1791,2026-05-26T15:00:00Z,2026-06-20T00:00:00Z,Build a civilization across epochs in a cooper...,https://gamefound.com:443/en/projects/oomm-gam...,Crowdfunding,True,1.0,4.0,NaN,90.0,NaN,0,NaN,1764,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Mythology, Cooperative, Campaign, Civ...",NaN,1

In [5]:
a_list = ['name', 'projectID', 'project_url','creator', 'creatorID', 'homeUrl',
       'currencySymbol', 'campaignGoal', 'fundsGathered', 'backersCount',
       'campaignStart', 'campaignEnd',
       'phaseLabel', 'enableBoardGameProperties', 'minPlayers', 'maxPlayers',
       'minAge', 'playTime', 'playTimeUnit',
       'fundedInSeconds', 'imageUrl',
       'pledgeManagerSoftCloseDeadline', 'projectTags',
       'originalType']

In [6]:
df = df[a_list]

In [7]:
#타입 0: 1:
df['originalType'].value_counts()

originalType
 1    1402
 0    1115
-1      42
-2      22
 2       9
Name: count, dtype: int64

In [8]:
pd.set_option('display.max_columns', None)
print(len(df.loc[(df['originalType']==0)]))
print(len(df.loc[(df['originalType']==0) & (df['campaignStart'].isnull())]))
print(len(df.loc[(df['originalType']==0) & (df['campaignEnd'].isnull())]))

1115
1115
1115

In [9]:
df.loc[df['originalType']==1]

,name,projectID,project_url,creator,creatorID,homeUrl,currencySymbol,campaignGoal,fundsGathered,backersCount,campaignStart,campaignEnd,phaseLabel,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,playTimeUnit,fundedInSeconds,imageUrl,pledgeManagerSoftCloseDeadline,projectTags,originalType
0,Bloodstone,8454,https://gamefound.com:443/en/projects/druid-ci...,Druid City Games,8843,https://gamefound.com/creators/druid-city-games,$,50000.0,95253.93,479,2026-06-02T13:00:00Z,2026-06-19T22:00:00Z,Crowdfunding,True,1.0,5.0,14.0,60.0,0,7770,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Multiplayer, Competitive, Dice Game, ...",1
2,A Life,9816,https://gamefound.com:443/en/projects/skellig-...,Skellig Games,2434,https://gamefound.com/creators/skellig-games,€,10000.0,22796.57,203,2026-06-02T15:00:00Z,2026-06-25T18:00:00Z,Crowdfunding,True,1.0,4.0,8.0,60.0,0,3756,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Set Collection, Competitive, Family, Narrative...",1
3,Growing Season Deluxe Edition,8617,https://gamefound.com:443/en/projects/undigita...,Undigital,5415,https://gamefound.com/creators/undigital,€,8000.0,15291.46,361,2026-06-02T16:00:00Z,2026-06-22T22:00:00Z,Crowdfunding,True,1.0,4.0,8.0,30.0,0,4725,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Card Game, Strategy, Video Game Theme, Multipl...",1
4,Stonesaga Second Printing,9678,https://gamefound.com:443/en/projects/oomm-gam...,Open Owl Studios,474,https://gamefound.com/creators/oomm-games,$,25000.0,154784.30,1791,2026-05-26T15:00:00Z,2026-06-20T00:00:00Z,Crowdfunding,True,1.0,4.0,NaN,90.0,0,1764,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Mythology, Cooperative, Campaign, Civ...",1
5,Beast: Ashfall,8330,https://gamefound.com:443/en/projects/studio-m...,Studio Midhall,2936,https://gamefound.com/creators/studio-midhall,€,50000.0,490554.96,3420,2026-05-05T15:00:00Z,2026-06-03T22:00:00Z,Crowdfunding,True,2.0,5.0,14.0,120.0,0,3645,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Strategy, Multiplayer, Competitive, A...",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2585,Spring and Autumn: Story of China,1446,https://gamefound.com:443/en/projects/mr-b-gam...,Mr. B. Games,1954,https://gamefound.com/creators/mr-b-games,$,30000.0,38009.00,219,2021-12-01T15:00:00Z,2022-01-04T22:00:00Z,Crowdfunding - Canceled,True,1.0,5.0,13.0,120.0,0,182152,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Exploration, History, Strategy, Area Control",1
2586,Crossroads Inn: The Board Game,1143,https://gamefound.com:443/en/projects/klabater...,Klabater,1510,https://gamefound.com/creators/klabater,€,20000.0,13420.63,158,2021-10-28T14:00:00Z,2021-11-30T15:00:00Z,Crowdfunding - Unsuccessful,True,2.0,4.0,12.0,120.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Strategy, Terrain Building, Humor",1
2587,PACHAMAMA,1170,https://gamefound.com:443/en/projects/sitdown/...,SitDown,1514,https://gamefound.com/creators/sitdown,€,25000.0,16048.00,318,2021-10-19T17:00:00Z,2021-11-09T18:00:00Z,Crowdfunding - Canceled,True,1.0,4.0,14.0,60.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Exploration, Logical, Deduction, Terrain Building",1
2588,Taverns & Dragons (Canceled),1314,https://gamefound.com:443/en/projects/thelastb...,Lord Raccoon Games,356,https://gamefound.com/creators/thelastbottle,€,20000.0,20954.00,470,2021-10-12T13:00:00Z,2021-11-03T22:00:00Z,Crowdfunding - Canceled,True,2.0,5.0,10.0,60.0,0,433495,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Exploration, Card Game, Fantasy, Dice Game, St...",1
2589,Goldenstar: The Galactic Tournament,1325,https://gamefound.com:443/en/projects/gindi/go...,Gindi,64,https://gamefound.com/creators/gindi,€,30000.0,10890.00,148,2021-10-05T16:00:00Z,2021-10-29T16:00:00Z,Crowdfunding - Unsuccessful,True,2.0,4.0,14.0,60.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Science Fiction, Area Control, Deck Building",1

In [10]:
df.loc[df['originalType']==1]['phaseLabel'].value_counts()

phaseLabel
Upcoming                         389
Pledge manager - Closed          322
Pledge manager - Limited         148
Crowdfunding - Canceled          136
Crowdfunding - Unsuccessful      124
Pledge manager - Open for all    112
Late Pledge - Open for all        89
Crowdfunding - Funded             42
Crowdfunding                      39
Late Pledge - Ended                1
Name: count, dtype: int64

In [11]:
target_list = ["Pledge manager - Closed","Crowdfunding - Unsuccessful","Crowdfunding - Funded"]

In [12]:
df = df.loc[(df['originalType']==1)&(df['phaseLabel'].isin(target_list))].reset_index(drop=True)

In [13]:
df.to_csv("../../02_data/processed/final_gamefound_list.csv", index=False, encoding="utf-8-sig")