In [1]:
import pandas as pd

df1 = pd.read_csv("../../02_Data/raw/rewards.csv")

In [7]:
df1 = df1.drop('Unnamed: 0', axis=1)
df1

,main_name,projectID_id,raw_url,anchorRelativeUrl,backgroundUrl,deliveryDateRemarks,estimatedDeliveryAt,hasDetails,isExposed,isMostPopular,...,isFeatured,name,price,productCanBePurchased,productCanBePurchasedDescription,productID,projectID,remainingStockLimit,url,productState
0,Bloodstone,8454,https://gamefound.com/api/projectContents/getR...,gameplay-all-in-deluxe-pledge-107665,https://imgcdn.gamefound.com/productimage/proj...,NaN,2027-05-30T00:00:00Z,False,False,False,...,True,Gameplay All-In Deluxe Pledge,230.0,True,NaN,107665,8454,NaN,/en/projects/druid-city-games/bloodstone#/prod...,2
1,Bloodstone,8454,https://gamefound.com/api/projectContents/getR...,retail-base-edition--108009,https://imgcdn.gamefound.com/productimage/proj...,NaN,2025-06-01T00:00:00Z,False,False,False,...,False,Retail Base Edition,75.0,True,NaN,108009,8454,NaN,/en/projects/druid-city-games/bloodstone#/prod...,2
2,Bloodstone,8454,https://gamefound.com/api/projectContents/getR...,deluxe-base-edition-107663,https://imgcdn.gamefound.com/productimage/proj...,NaN,2027-05-30T00:00:00Z,False,False,False,...,False,Deluxe Base Edition,140.0,True,NaN,107663,8454,NaN,/en/projects/druid-city-games/bloodstone#/prod...,2
3,Aeolis,8619,https://gamefound.com/api/projectContents/getR...,aeolis-with-metal-coins-english-version--107326,https://imgcdn.gamefound.com/productimage/proj...,NaN,2026-06-09T00:00:00Z,False,False,False,...,True,Aeolis with Metal Coins - English Version 🇬🇧,199.0,True,NaN,107326,8619,6.0,/en/projects/meeple-pug/aeolis#/product/107326,2
4,Aeolis,8619,https://gamefound.com/api/projectContents/getR...,aeolis-english-version--107324,https://imgcdn.gamefound.com/productimage/proj...,NaN,2026-06-09T00:00:00Z,False,False,False,...,False,Aeolis - English Version 🇬🇧,169.0,True,NaN,107324,8619,0.0,/en/projects/meeple-pug/aeolis#/product/107324,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11141,Taverns & Dragons (Canceled),1314,https://gamefound.com/api/projectContents/getR...,group-pledge-17696,https://imgcdn.gamefound.com/productimage/proj...,<div>This is an estimated delivery time.</div>,2022-09-01T00:00:00Z,False,False,False,...,False,Group Pledge,264.0,False,You can't add items to your pledge because thi...,17696,1314,NaN,/en/projects/thelastbottle/taverns-and-dragons...,2
11142,Goldenstar: The Galactic Tournament,1325,https://gamefound.com/api/projectContents/getR...,champion-gameplay-all-in-18047,https://imgcdn.gamefound.com/productimage/proj...,NaN,2022-06-01T00:00:00Z,False,False,False,...,True,Champion (Gameplay All-in),72.0,False,You can't add items to your pledge because thi...,18047,1325,NaN,/en/projects/gindi/goldenstar-the-galactic-tou...,2
11143,Goldenstar: The Galactic Tournament,1325,https://gamefound.com/api/projectContents/getR...,goldenstar-core-pledge-17700,https://imgcdn.gamefound.com/productimage/proj...,NaN,2022-06-01T00:00:00Z,False,False,False,...,False,Goldenstar Core Pledge,43.0,False,You can't add items to your pledge because thi...,17700,1325,NaN,/en/projects/gindi/goldenstar-the-galactic-tou...,2
11144,Goldenstar: The Galactic Tournament,1325,https://gamefound.com/api/projectContents/getR...,challenger-18042,https://imgcdn.gamefound.com/productimage/proj...,NaN,2022-06-01T00:00:00Z,False,False,False,...,False,Challenger,69.0,False,You can't add items to your pledge because thi...,18042,1325,NaN,/en/projects/gindi/goldenstar-the-galactic-tou...,2
11145,Goldenstar: The Galactic Tournament,1325,https://gamefound.com/api/projectContents/getR...,legend-all-in-18052,https://imgcdn.gamefound.com/productimage/proj...,NaN,2022-06-01T00:00:00Z,False,False,False,...,False,Legend (All-in),97.0,False,You can't add items to your pledge because thi...,18052,1325,NaN,/en/projects/gindi/goldenstar-the-galactic-tou...,2

In [19]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11146 entries, 0 to 11145
Data columns (total 34 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   main_name                         11146 non-null  object
 1   projectID_id                      11146 non-null  int64
 2   raw_url                           11146 non-null  object
 3   anchorRelativeUrl                 11146 non-null  object
 4   backgroundUrl                     11146 non-null  object
 5   deliveryDateRemarks               5008 non-null   object
 6   estimatedDeliveryAt               9559 non-null   object
 7   hasDetails                        11146 non-null  bool
 8   isExposed                         11146 non-null  bool
 9   isMostPopular                     11146 non-null  bool
 10  purchasedCopiesCount              11146 non-null  int64
 11  additionalInfoUrl                 0 non-null      float64
 12  hasInstallmentsAvailable          11146 non-null  bool
 13  installmentCost                   1444 non-null   float64
 14  installmentMinPayment             4551 non-null   float64
 15  abstract                          10755 non-null  object
 16  categoryID                        11146 non-null  int64
 17  effectivePrice                    11146 non-null  float64
 18  hasLimitedStock                   11146 non-null  bool
 19  hasRetailerAccess                 11146 non-null  bool
 20  hasSpecialAccess                  11146 non-null  bool
 21  imageUrl                          11146 non-null  object
 22  isDigital                         11146 non-null  bool
 23  isDiscounted                      11146 non-null  bool
 24  isFeatured                        11146 non-null  bool
 25  name                              11146 non-null  object
 26  price                             11146 non-null  float64
 27  productCanBePurchased             11146 non-null  bool
 28  productCanBePurchasedDescription  9379 non-null   object
 29  productID                         11146 non-null  int64
 30  projectID                         11146 non-null  int64
 31  remainingStockLimit               1993 non-null   float64
 32  url                               11146 non-null  object
 33  productState                      11146 non-null  int64
dtypes: bool(11), float64(6), int64(6), object(11)
memory usage: 2.1+ MB

In [18]:
test_columns = ['main_name', 'projectID_id', 'anchorRelativeUrl', 'name', 'price', 'isDiscounted', 'effectivePrice',
       'isDigital', 'isFeatured' , 'estimatedDeliveryAt','isExposed', 'isMostPopular', 'purchasedCopiesCount', 'abstract', 'categoryID', 
       'hasLimitedStock', 'hasRetailerAccess', 'hasSpecialAccess',
       'productCanBePurchased', 'productCanBePurchasedDescription', 'remainingStockLimit', 'productState']

In [20]:
df1[test_columns]

,main_name,projectID_id,anchorRelativeUrl,name,price,isDiscounted,effectivePrice,isDigital,isFeatured,estimatedDeliveryAt,...,purchasedCopiesCount,abstract,categoryID,hasLimitedStock,hasRetailerAccess,hasSpecialAccess,productCanBePurchased,productCanBePurchasedDescription,remainingStockLimit,productState
0,Bloodstone,8454,gameplay-all-in-deluxe-pledge-107665,Gameplay All-In Deluxe Pledge,230.0,True,179.0,False,True,2027-05-30T00:00:00Z,...,456,Enter the Arena with the Gameplay All-In Delux...,18887,False,False,False,True,NaN,NaN,2
1,Bloodstone,8454,retail-base-edition--108009,Retail Base Edition,75.0,True,69.0,False,False,2025-06-01T00:00:00Z,...,9,Enter the Arena with the Retail Base Edition o...,18887,False,False,False,True,NaN,NaN,2
2,Bloodstone,8454,deluxe-base-edition-107663,Deluxe Base Edition,140.0,True,129.0,False,False,2027-05-30T00:00:00Z,...,7,Enter the Arena with the Deluxe Base Edition o...,18887,False,False,False,True,NaN,NaN,2
3,Aeolis,8619,aeolis-with-metal-coins-english-version--107326,Aeolis with Metal Coins - English Version 🇬🇧,199.0,False,199.0,False,True,2026-06-09T00:00:00Z,...,54,Aeolis is a fully cooperative kingdom-building...,19268,True,False,False,True,NaN,6.0,2
4,Aeolis,8619,aeolis-english-version--107324,Aeolis - English Version 🇬🇧,169.0,False,169.0,False,False,2026-06-09T00:00:00Z,...,5,Aeolis is a fully cooperative kingdom-building...,19268,True,False,False,True,NaN,0.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11141,Taverns & Dragons (Canceled),1314,group-pledge-17696,Group Pledge,264.0,True,220.0,False,False,2022-09-01T00:00:00Z,...,0,Buy 5 copies of Taverns & Dragons and get one ...,3054,False,False,False,False,You can't add items to your pledge because thi...,NaN,2
11142,Goldenstar: The Galactic Tournament,1325,champion-gameplay-all-in-18047,Champion (Gameplay All-in),72.0,False,72.0,False,True,2022-06-01T00:00:00Z,...,0,"This pledge includes Goldenstar Core Box, Crow...",3066,False,False,False,False,You can't add items to your pledge because thi...,NaN,2
11143,Goldenstar: The Galactic Tournament,1325,goldenstar-core-pledge-17700,Goldenstar Core Pledge,43.0,False,43.0,False,False,2022-06-01T00:00:00Z,...,0,"This pledge includes Goldenstar Core Box, incl...",3066,False,False,False,False,You can't add items to your pledge because thi...,NaN,2
11144,Goldenstar: The Galactic Tournament,1325,challenger-18042,Challenger,69.0,False,69.0,False,False,2022-06-01T00:00:00Z,...,0,"This pledge includes Goldenstar Core Box, Crow...",3066,False,False,False,False,You can't add items to your pledge because thi...,NaN,2
11145,Goldenstar: The Galactic Tournament,1325,legend-all-in-18052,Legend (All-in),97.0,False,97.0,False,False,2022-06-01T00:00:00Z,...,0,"This pledge includes Goldenstar Core Box, Crow...",3066,False,False,False,False,You can't add items to your pledge because thi...,NaN,2

In [22]:
df1[test_columns]['productCanBePurchasedDescription'].value_counts()

productCanBePurchasedDescription
You can't add items to your pledge at this time.                                                            7470
You can't add items to your pledge because this project is closed.                                           894
You can't add items to the pledge because the project hasn't been launched yet.                              817
You can't add items to your pledge because the Pledge Manager for this project hasn't been launched yet.     198
Name: count, dtype: int64

In [23]:
df1[test_columns]['remainingStockLimit'].value_counts()

remainingStockLimit
0.0      807
396.0    104
1.0       61
79.0      53
100.0     47
        ...
90.0       1
197.0      1
221.0      1
116.0      1
186.0      1
Name: count, Length: 250, dtype: int64

In [24]:
df1[test_columns]['hasLimitedStock'].value_counts()

hasLimitedStock
False    10585
True       561
Name: count, dtype: int64

In [ ]:
# 판매 중지는 없나? 다 2번
df1[test_columns]['productState'].value_counts()

productState
2    11146
Name: count, dtype: int64