In [ ]:
!pip install google-generativeai pandas

Collecting google-generativeai
  Downloading google_generativeai-0.8.6-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: pandas in c:\users\nt551_11th\anaconda3\lib\site-packages (2.3.3)
Collecting google-ai-generativelanguage==0.6.15 (from google-generativeai)
  Downloading google_ai_generativelanguage-0.6.15-py3-none-any.whl.metadata (5.7 kB)
Collecting google-api-core (from google-generativeai)
  Downloading google_api_core-2.31.0-py3-none-any.whl.metadata (3.2 kB)
Collecting google-api-python-client (from google-generativeai)
  Downloading google_api_python_client-2.197.0-py3-none-any.whl.metadata (7.0 kB)
Collecting google-auth>=2.15.0 (from google-generativeai)
  Downloading google_auth-2.53.0-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: protobuf in c:\users\nt551_11th\anaconda3\lib\site-packages (from google-generativeai) (5.29.3)
Requirement already satisfied: pydantic in c:\users\nt551_11th\anaconda3\lib\site-packages (from google-generativeai) (2.12.4)
Requirement already satisfied: tqdm in c:\users\nt551_11th\anaconda3\lib\site-packages (from google-generativeai) (4.67.1)
Requirement already satisfied: typing-extensions in c:\users\nt551_11th\anaconda3\lib\site-packages (from google-generativeai) (4.15.0)
Collecting proto-plus<2.0.0dev,>=1.22.3 (from google-ai-generativelanguage==0.6.15->google-generativeai)
  Downloading proto_plus-1.28.0-py3-none-any.whl.metadata (2.2 kB)
Collecting googleapis-common-protos<2.0.0,>=1.63.2 (from google-api-core->google-generativeai)
  Downloading googleapis_common_protos-1.75.0-py3-none-any.whl.metadata (8.6 kB)
Collecting protobuf (from google-generativeai)
  Downloading protobuf-5.29.6-cp310-abi3-win_amd64.whl.metadata (592 bytes)
Collecting requests<3.0.0,>=2.33.0 (from google-api-core->google-generativeai)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting grpcio<2.0.0,>=1.41.0 (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai)
  Downloading grpcio-1.81.0-cp313-cp313-win_amd64.whl.metadata (3.8 kB)
Collecting grpcio-status<2.0.0,>=1.41.0 (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai)
  Downloading grpcio_status-1.81.0-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\nt551_11th\anaconda3\lib\site-packages (from google-auth>=2.15.0->google-generativeai) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in c:\users\nt551_11th\anaconda3\lib\site-packages (from google-auth>=2.15.0->google-generativeai) (46.0.3)
INFO: pip is looking at multiple versions of grpcio-status to determine which version is compatible with other requirements. This could take a while.
  Downloading grpcio_status-1.80.0-py3-none-any.whl.metadata (1.3 kB)
  Downloading grpcio_status-1.78.0-py3-none-any.whl.metadata (1.3 kB)
  Downloading grpcio_status-1.76.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.75.1-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.75.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.74.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.73.1-py3-none-any.whl.metadata (1.1 kB)
INFO: pip is still looking at multiple versions of grpcio-status to determine which version is compatible with other requirements. This could take a while.
  Downloading grpcio_status-1.73.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.72.2-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.72.1-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.71.2-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\nt551_11th\anaconda3\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core->google-generativeai) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\nt551_11th\anaconda3\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core->google-generativeai) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\nt551_11th\anaconda3\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core->google-generativeai) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\nt551_11th\anaconda3\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core->google-generativeai) (2026.4.22)
Requirement already satisfied: numpy>=1.26.0 in c:\users\nt551_11th\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\nt551_11th\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\nt551_11th\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\nt551_11th\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: cffi>=2.0.0 in c:\users\nt551_11th\anaconda3\lib\site-packages (from cryptography>=38.0.3->google-auth>=2.15.0->google-generativeai) (2.0.0)
Requirement already satisfied: pycparser in c:\users\nt551_11th\anaconda3\lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth>=2.15.0->google-generativeai) (2.23)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\users\nt551_11th\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai) (0.6.1)
Requirement already satisfied: six>=1.5 in c:\users\nt551_11th\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Collecting httplib2<1.0.0,>=0.19.0 (from google-api-python-client->google-generativeai)
  Downloading httplib2-0.31.2-py3-none-any.whl.metadata (2.2 kB)
Collecting google-auth-httplib2<1.0.0,>=0.2.0 (from google-api-python-client->google-generativeai)
  Downloading google_auth_httplib2-0.4.0-py3-none-any.whl.metadata (3.0 kB)
Collecting uritemplate<5,>=3.0.1 (from google-api-python-client->google-generativeai)
  Downloading uritemplate-4.2.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: pyparsing<4,>=3.1 in c:\users\nt551_11th\anaconda3\lib\site-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client->google-generativeai) (3.2.5)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\nt551_11th\anaconda3\lib\site-packages (from pydantic->google-generativeai) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\nt551_11th\anaconda3\lib\site-packages (from pydantic->google-generativeai) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\nt551_11th\anaconda3\lib\site-packages (from pydantic->google-generativeai) (0.4.2)
Requirement already satisfied: colorama in c:\users\nt551_11th\anaconda3\lib\site-packages (from tqdm->google-generativeai) (0.4.6)
Downloading google_generativeai-0.8.6-py3-none-any.whl (155 kB)
Downloading google_ai_generativelanguage-0.6.15-py3-none-any.whl (1.3 MB)
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 1.3/1.3 MB 34.6 MB/s  0:00:00
Downloading google_api_core-2.31.0-py3-none-any.whl (173 kB)
Downloading google_auth-2.53.0-py3-none-any.whl (246 kB)
Downloading googleapis_common_protos-1.75.0-py3-none-any.whl (300 kB)
Downloading grpcio-1.81.0-cp313-cp313-win_amd64.whl (4.9 MB)
   ---------------------------------------- 0.0/4.9 MB ? eta -:--:--
   ---------------------------------------- 4.9/4.9 MB 66.7 MB/s  0:00:00
Downloading grpcio_status-1.71.2-py3-none-any.whl (14 kB)
Downloading proto_plus-1.28.0-py3-none-any.whl (50 kB)
Downloading protobuf-5.29.6-cp310-abi3-win_amd64.whl (435 kB)
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
Downloading google_api_python_client-2.197.0-py3-none-any.whl (15.3 MB)
   ---------------------------------------- 0.0/15.3 MB ? eta -:--:--
   ---------------------------------------  15.2/15.3 MB 91.3 MB/s eta 0:00:01
   ---------------------------------------- 15.3/15.3 MB 73.4 MB/s  0:00:00
Downloading google_auth_httplib2-0.4.0-py3-none-any.whl (9.5 kB)
Downloading httplib2-0.31.2-py3-none-any.whl (91 kB)
Downloading uritemplate-4.2.0-py3-none-any.whl (11 kB)
Installing collected packages: uritemplate, requests, protobuf, httplib2, grpcio, proto-plus, googleapis-common-protos, grpcio-status, google-auth, google-auth-httplib2, google-api-core, google-api-python-client, google-ai-generativelanguage, google-generativeai

  Attempting uninstall: requests

    Found existing installation: requests 2.32.5

    Uninstalling requests-2.32.5:

      Successfully uninstalled requests-2.32.5

   -- -------------------------------------  1/14 [requests]
  Attempting uninstall: protobuf
   -- -------------------------------------  1/14 [requests]
    Found existing installation: protobuf 5.29.3
   -- -------------------------------------  1/14 [requests]
    Uninstalling protobuf-5.29.3:
   -- -------------------------------------  1/14 [requests]
   ----- ----------------------------------  2/14 [protobuf]
      Successfully uninstalled protobuf-5.29.3
   ----- ----------------------------------  2/14 [protobuf]
   ----- ----------------------------------  2/14 [protobuf]
   ----- ----------------------------------  2/14 [protobuf]
   ----- ----------------------------------  2/14 [protobuf]
   ----------- ----------------------------  4/14 [grpcio]
   ----------- ----------------------------  4/14 [grpcio]
   ----------- ----------------------------  4/14 [grpcio]
   -------------- -------------------------  5/14 [proto-plus]
   ----------------- ----------------------  6/14 [googleapis-common-protos]
   ----------------- ----------------------  6/14 [googleapis-common-protos]
   ----------------- ----------------------  6/14 [googleapis-common-protos]
   -------------------- -------------------  7/14 [grpcio-status]
   ---------------------- -----------------  8/14 [google-auth]
   ---------------------- -----------------  8/14 [google-auth]
   ---------------------- -----------------  8/14 [google-auth]
   ---------------------------- ----------- 10/14 [google-api-core]
   ---------------------------- ----------- 10/14 [google-api-core]
   ---------------------------- ----------- 10/14 [google-api-core]
   ------------------------------- -------- 11/14 [google-api-python-client]
   ------------------------------- -------- 11/14 [google-api-python-client]
   ------------------------------- -------- 11/14 [google-api-python-client]
   ------------------------------- -------- 11/14 [google-api-python-client]
   ------------------------------- -------- 11/14 [google-api-python-client]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   --------------------------------- ----- 12/14 [google-ai-generativelanguage]
   ------------------------------------- -- 13/14 [google-generativeai]
   ------------------------------------- -- 13/14 [google-generativeai]
   ------------------------------------- -- 13/14 [google-generativeai]
   ------------------------------------- -- 13/14 [google-generativeai]
   ------------------------------------- -- 13/14 [google-generativeai]
   ---------------------------------------- 14/14 [google-generativeai]

Successfully installed google-ai-generativelanguage-0.6.15 google-api-core-2.31.0 google-api-python-client-2.197.0 google-auth-2.53.0 google-auth-httplib2-0.4.0 google-generativeai-0.8.6 googleapis-common-protos-1.75.0 grpcio-1.81.0 grpcio-status-1.71.2 httplib2-0.31.2 proto-plus-1.28.0 protobuf-5.29.6 requests-2.34.2 uritemplate-4.2.0

In [11]:
!pip install google-generativeai

Requirement already satisfied: google-generativeai in c:\users\nt551_11th\anaconda3\lib\site-packages (0.8.6)
Requirement already satisfied: google-ai-generativelanguage==0.6.15 in c:\users\nt551_11th\anaconda3\lib\site-packages (from google-generativeai) (0.6.15)
Requirement already satisfied: google-api-core in c:\users\nt551_11th\anaconda3\lib\site-packages (from google-generativeai) (2.31.0)
Requirement already satisfied: google-api-python-client in c:\users\nt551_11th\anaconda3\lib\site-packages (from google-generativeai) (2.197.0)
Requirement already satisfied: google-auth>=2.15.0 in c:\users\nt551_11th\anaconda3\lib\site-packages (from google-generativeai) (2.53.0)
Requirement already satisfied: protobuf in c:\users\nt551_11th\anaconda3\lib\site-packages (from google-generativeai) (5.29.6)
Requirement already satisfied: pydantic in c:\users\nt551_11th\anaconda3\lib\site-packages (from google-generativeai) (2.12.4)
Requirement already satisfied: tqdm in c:\users\nt551_11th\anaconda3\lib\site-packages (from google-generativeai) (4.67.1)
Requirement already satisfied: typing-extensions in c:\users\nt551_11th\anaconda3\lib\site-packages (from google-generativeai) (4.15.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in c:\users\nt551_11th\anaconda3\lib\site-packages (from google-ai-generativelanguage==0.6.15->google-generativeai) (1.28.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in c:\users\nt551_11th\anaconda3\lib\site-packages (from google-api-core->google-generativeai) (1.75.0)
Requirement already satisfied: requests<3.0.0,>=2.33.0 in c:\users\nt551_11th\anaconda3\lib\site-packages (from google-api-core->google-generativeai) (2.34.2)
Requirement already satisfied: grpcio<2.0.0,>=1.41.0 in c:\users\nt551_11th\anaconda3\lib\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.81.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.41.0 in c:\users\nt551_11th\anaconda3\lib\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.71.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\nt551_11th\anaconda3\lib\site-packages (from google-auth>=2.15.0->google-generativeai) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in c:\users\nt551_11th\anaconda3\lib\site-packages (from google-auth>=2.15.0->google-generativeai) (46.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\nt551_11th\anaconda3\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core->google-generativeai) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\nt551_11th\anaconda3\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core->google-generativeai) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\nt551_11th\anaconda3\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core->google-generativeai) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\nt551_11th\anaconda3\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core->google-generativeai) (2026.4.22)
Requirement already satisfied: cffi>=2.0.0 in c:\users\nt551_11th\anaconda3\lib\site-packages (from cryptography>=38.0.3->google-auth>=2.15.0->google-generativeai) (2.0.0)
Requirement already satisfied: pycparser in c:\users\nt551_11th\anaconda3\lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth>=2.15.0->google-generativeai) (2.23)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\users\nt551_11th\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai) (0.6.1)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in c:\users\nt551_11th\anaconda3\lib\site-packages (from google-api-python-client->google-generativeai) (0.31.2)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in c:\users\nt551_11th\anaconda3\lib\site-packages (from google-api-python-client->google-generativeai) (0.4.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in c:\users\nt551_11th\anaconda3\lib\site-packages (from google-api-python-client->google-generativeai) (4.2.0)
Requirement already satisfied: pyparsing<4,>=3.1 in c:\users\nt551_11th\anaconda3\lib\site-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client->google-generativeai) (3.2.5)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\nt551_11th\anaconda3\lib\site-packages (from pydantic->google-generativeai) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\nt551_11th\anaconda3\lib\site-packages (from pydantic->google-generativeai) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\nt551_11th\anaconda3\lib\site-packages (from pydantic->google-generativeai) (0.4.2)
Requirement already satisfied: colorama in c:\users\nt551_11th\anaconda3\lib\site-packages (from tqdm->google-generativeai) (0.4.6)

In [3]:
import pandas as pd


thread_df = pd.read_csv("../../02_Data/processed/comments_merged_thread_add_tag.csv")

In [4]:
thread_df

,Unnamed: 0,projectID,thread_id,group,comment_ids,n_comments,merged_comment,creator_id,is_pledge_master,is_backer,is_prior_backer,is_pathfinder,likes
0,0,5787,1691589,0,[1691589],1,WELCOME TO EDEN! Please check the FAQ and the...,1,0,0,0,0,26
1,1,5787,1725920,0,"[1725920, 1726005]",2,@BlackSiteStudios Could a person use larger di...,1,1,1,0,0,0
2,2,5787,1725876,0,[1725876],1,about an hour left to go,0,1,1,1,0,1
3,3,5787,1725671,0,[1725671],1,Man 2 hours to go worth staying up to midnight...,0,0,0,0,0,3
4,4,5787,1725512,0,[1725512],1,5 hours to go! Hold on to your butts!,0,0,1,1,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
73434,73434,1143,133497,1,"[133497, 133510, 134222]",3,"Hello. Will it be in Spanish? and if not, woul...",1,2,0,0,0,4
73435,73435,1143,133314,1,"[133314, 133507]",2,Not sure if people get notifications for repli...,1,1,1,0,0,4
73436,73436,1143,133207,1,"[133207, 133219]",2,The project looks interesting! Who is the desi...,1,0,0,0,0,0
73437,73437,1143,133159,1,"[133159, 133202, 133500]",3,"Hi, is there the future possibility of a solo ...",1,1,0,0,0,11
73438,73438,1143,133074,1,"[133074, 133211, 133243, 133247]",4,Question about the standard vs. innkeepers edi...,2,2,1,0,0,3

In [23]:
thread_df.loc[thread_df['projectID']==1476]

Empty DataFrame
Columns: [Unnamed: 0, projectID, thread_id, group, comment_ids, n_comments, merged_comment, creator_id, is_pledge_master, is_backer, is_prior_backer, is_pathfinder, likes]
Index: []

In [6]:
thread_df["merged_comment"][1]

"@BlackSiteStudios Could a person use larger dinosaur figures as long as they scale up the battle mat area to fit them?|Sure! The game is designed for a 2x2ft play area, so you'll need to do some balance yourself. The rules will tell you what base size a particular dinosaur will have, so if the models you have fit on that, then you should be good."

In [1]:
# 테스트 30개
#test_df = thread_df.sample(n=30, random_state=42).copy()

In [ ]:
import time
import pandas as pd
import google.generativeai as genai
from concurrent.futures import ThreadPoolExecutor
from tqdm import tqdm

# API 설정 (api키는 각자 발급받아 .txt 파일로 저장 후 진행해야함)
try:
    with open("api_key.txt", "r") as file:
        api_key = file.read().strip() 
    genai.configure(api_key=api_key)
except FileNotFoundError:
    print("api_key.txt 파일 오류.")
    exit()

# 비용 가장 저렴
model = genai.GenerativeModel('gemini-3.1-flash-lite')

target_df = thread_df.copy().reset_index(drop=True)

# 프롬포트 입력
system_prompt = """You are an expert community manager for a global crowdfunding platform.
Your task is to analyze user comments and classify the core intent into exactly ONE of the following categories:

[Categories]
1. Shipping_Fulfillment
2. Product_Question
3. Praise_Support
4. Complaint_Refund
5. Suggestion_Idea
6. Spam_Irrelevant

[Rules]
- Read the entire conversation thread and select the ONE category that best fits the CORE intent.
- Lines starting with '|' are replies to the main comment.
- DO NOT provide any explanation.
- ONLY output the exact name of the category."""

# 시간 오래 걸려 병렬처리
def classify_row(args):
    seq_idx, row = args
    try:
        full_prompt = f"{system_prompt}\n\n[Thread Text]\n{row['merged_comment']}"
        response = model.generate_content(full_prompt)
        return seq_idx, response.text.strip()
    except Exception:
        return seq_idx, "Error"

print(f" 총 {len(target_df)}개 분류 시작")

results_dict = {}

# 원하는 최종 컬럼 순서 지정
#['Unnamed: 0', 'projectID', 'thread_id', 'group', 'comment_ids',
#       'n_comments', 'merged_comment', 'creator_id', 'is_pledge_master',
#       'is_backer', 'is_prior_backer', 'is_pathfinder', 'likes']
selected_columns = ['thread_id', 'projectID', 'group', 'n_comments', 'merged_comment', 'creator_id', 'is_pledge_master','is_backer', 'is_prior_backer', 'is_pathfinder', 'likes','category']

# 50개의 스레드를 동시에 사용하여 구글 서버에 요청
with ThreadPoolExecutor(max_workers=50) as executor:
    futures = [executor.submit(classify_row, (seq_idx, row)) for seq_idx, (_, row) in enumerate(target_df.iterrows())]
    
    for future in tqdm(futures, total=len(target_df), desc="분류 진행중"):
        seq_idx, category = future.result()
        results_dict[seq_idx] = category

# 최종 저장
target_df['category'] = [results_dict[i] for i in range(len(target_df))]
final_df = target_df[selected_columns]

final_df.to_csv("../../02_Data/processed/final_all_results.csv", index=False, encoding="utf-8-sig")
print("----완료-----")

In [14]:
target_df.groupby('group')['category'].value_counts()
target_df.groupby(['group', 'category']).size()
result_df = target_df.groupby('group')['category'].value_counts().reset_index(name='count')
result_df

    group                                           category  count
0       0                                   Product_Question  13816
1       0                                    Suggestion_Idea   9672
2       0                                     Praise_Support   6431
3       0                               Shipping_Fulfillment   2184
4       0                                    Spam_Irrelevant   1374
5       0                                   Complaint_Refund   1085
6       0  Please provide the thread text you would like ...      5
7       0  Please provide the [Thread Text] you would lik...      1
8       0  Please provide the full thread text you would ...      1
9       0  Please provide the text you would like me to a...      1
10      0  Please provide the text you would like me to c...      1
11      0  Please provide the thread text, and I will cla...      1
12      1                                   Product_Question  18722
13      1                                    Suggestion_Idea   9450
14      1                                     Praise_Support   4477
15      1                               Shipping_Fulfillment   3442
16      1                                   Complaint_Refund   1899
17      1                                    Spam_Irrelevant    874
18      1  Please provide the thread text you would like ...      2
19      1  Please provide the text you would like me to a...      1

In [20]:
target_df.head()

,Unnamed: 0,projectID,thread_id,group,comment_ids,n_comments,merged_comment,creator_id,is_pledge_master,is_backer,is_prior_backer,is_pathfinder,likes,category
0,0,5787,1691589,0,[1691589],1,WELCOME TO EDEN! Please check the FAQ and the...,1,0,0,0,0,26,Praise_Support
1,1,5787,1725920,0,"[1725920, 1726005]",2,@BlackSiteStudios Could a person use larger di...,1,1,1,0,0,0,Product_Question
2,2,5787,1725876,0,[1725876],1,about an hour left to go,0,1,1,1,0,1,Spam_Irrelevant
3,3,5787,1725671,0,[1725671],1,Man 2 hours to go worth staying up to midnight...,0,0,0,0,0,3,Praise_Support
4,4,5787,1725512,0,[1725512],1,5 hours to go! Hold on to your butts!,0,0,1,1,0,5,Praise_Support

In [ ]:
final_df['category'].value_counts()

category
Product_Question                                                     32538
Suggestion_Idea                                                      19122
Praise_Support                                                       10908
Shipping_Fulfillment                                                  5626
Complaint_Refund                                                      2984
Spam_Irrelevant                                                       2248
Please provide the thread text you would like me to analyze.             7
Please provide the [Thread Text] you would like me to analyze.           1
Please provide the thread text, and I will classify it for you.          1
Please provide the text you would like me to classify.                   1
Please provide the text you would like me to analyze.                    1
Please provide the full thread text you would like me to analyze.        1
Please provide the text you would like me to analyze!                    1
Name: count, dtype: int64