In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/drive/MyDrive/comments_merged.csv")

In [3]:
df.head()

,projectID,comment_id,parent_id,depth_level,author_id,author_name,creator_id,is_pledge_master,is_backer,backer_number,...,is_pathfinder,has_children,children_count,text,created_at,likes,phaseLabel,campaignStart,campaignEnd,group
0,5787,1691589,NaN,0,1456332,BlackSiteStudios,1,False,False,NaN,...,False,False,0,WELCOME TO EDEN!\n\nPlease check the FAQ and t...,2025-06-01 23:14:35.600000+00:00,26,Pledge manager - Closed,2025-06-17 14:30:00+00:00,2025-07-19 00:50:35.250000+00:00,0
1,5787,1725920,NaN,0,9482,Yug_the_Juggernaut,0,True,True,1.0,...,False,True,1,@BlackSiteStudios\nCould a person use larger d...,2025-06-17 13:42:18.150000+00:00,0,Pledge manager - Closed,2025-06-17 14:30:00+00:00,2025-07-19 00:50:35.250000+00:00,0
2,5787,1726005,1725920.0,1,1456332,BlackSiteStudios,1,False,False,NaN,...,False,False,0,Sure! The game is designed for a 2x2ft play ar...,2025-06-17 14:09:27.980000+00:00,0,Pledge manager - Closed,2025-06-17 14:30:00+00:00,2025-07-19 00:50:35.250000+00:00,0
3,5787,1725876,NaN,0,137438,Terry_van_Leeuwen,0,True,True,13.0,...,False,False,0,about an hour left to go,2025-06-17 13:26:09.743000+00:00,1,Pledge manager - Closed,2025-06-17 14:30:00+00:00,2025-07-19 00:50:35.250000+00:00,0
4,5787,1725671,NaN,0,12163,Haro4Life,0,False,False,NaN,...,False,False,0,Man 2 hours to go worth staying up to midnight...,2025-06-17 11:42:57.760000+00:00,3,Pledge manager - Closed,2025-06-17 14:30:00+00:00,2025-07-19 00:50:35.250000+00:00,0

In [4]:
df.columns.tolist()

['projectID',
 'comment_id',
 'parent_id',
 'depth_level',
 'author_id',
 'author_name',
 'creator_id',
 'is_pledge_master',
 'is_backer',
 'backer_number',
 'is_prior_backer',
 'is_pathfinder',
 'has_children',
 'children_count',
 'text',
 'created_at',
 'likes',
 'phaseLabel',
 'campaignStart',
 'campaignEnd',
 'group']

In [5]:
len(df)

212988

In [6]:
# 1. 설치
!pip install -U FlagEmbedding bertopic umap-learn hdbscan

Collecting FlagEmbedding
  Downloading flagembedding-1.4.0-py3-none-any.whl.metadata (23 kB)
Collecting bertopic
  Downloading bertopic-0.17.4-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: umap-learn in /usr/local/lib/python3.12/dist-packages (0.5.12)
Requirement already satisfied: hdbscan in /usr/local/lib/python3.12/dist-packages (0.8.44)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from FlagEmbedding) (2.11.0+cu128)
Requirement already satisfied: transformers<6.0.0,>=4.44.2 in /usr/local/lib/python3.12/dist-packages (from FlagEmbedding) (5.9.0)
Requirement already satisfied: datasets>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from FlagEmbedding) (4.0.0)
Requirement already satisfied: accelerate>=0.20.1 in /usr/local/lib/python3.12/dist-packages (from FlagEmbedding) (1.13.0)
Requirement already satisfied: sentence_transformers in /usr/local/lib/python3.12/dist-packages (from FlagEmbedding) (5.5.1)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (from FlagEmbedding) (0.19.1)
Collecting ir-datasets (from FlagEmbedding)
  Downloading ir_datasets-0.5.11-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from FlagEmbedding) (0.2.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from FlagEmbedding) (5.29.6)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.0.2)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (1.6.1)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (4.67.3)
Requirement already satisfied: llvmlite>0.36.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.43.0)
Requirement already satisfied: scipy>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from umap-learn) (1.16.3)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.12/dist-packages (from umap-learn) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.12/dist-packages (from umap-learn) (0.6.0)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan) (1.5.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.20.1->FlagEmbedding) (26.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.20.1->FlagEmbedding) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.20.1->FlagEmbedding) (6.0.3)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.20.1->FlagEmbedding) (1.17.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.20.1->FlagEmbedding) (0.7.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.19.0->FlagEmbedding) (3.29.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.19.0->FlagEmbedding) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.19.0->FlagEmbedding) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.19.0->FlagEmbedding) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=2.19.0->FlagEmbedding) (3.7.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.19.0->FlagEmbedding) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.19.0->FlagEmbedding) (2025.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2026.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (9.1.4)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers->FlagEmbedding) (4.15.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->FlagEmbedding) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->FlagEmbedding) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->FlagEmbedding) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->FlagEmbedding) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->FlagEmbedding) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->FlagEmbedding) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->FlagEmbedding) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->FlagEmbedding) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->FlagEmbedding) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->FlagEmbedding) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->FlagEmbedding) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->FlagEmbedding) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->FlagEmbedding) (12.8.90)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.44.2->FlagEmbedding) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.44.2->FlagEmbedding) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.44.2->FlagEmbedding) (0.25.1)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /usr/local/lib/python3.12/dist-packages (from ir-datasets->FlagEmbedding) (4.13.5)
Collecting inscriptis>=2.2.0 (from ir-datasets->FlagEmbedding)
  Downloading inscriptis-2.7.1-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: lxml>=4.5.2 in /usr/local/lib/python3.12/dist-packages (from ir-datasets->FlagEmbedding) (6.1.1)
Collecting trec-car-tools>=2.5.4 (from ir-datasets->FlagEmbedding)
  Downloading trec_car_tools-2.6-py3-none-any.whl.metadata (640 bytes)
Collecting lz4>=3.1.10 (from ir-datasets->FlagEmbedding)
  Downloading lz4-4.4.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Collecting warc3-wet>=0.2.3 (from ir-datasets->FlagEmbedding)
  Downloading warc3_wet-0.2.5-py3-none-any.whl.metadata (2.2 kB)
Collecting warc3-wet-clueweb09>=0.2.5 (from ir-datasets->FlagEmbedding)
  Downloading warc3-wet-clueweb09-0.2.5.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting zlib-state>=0.1.3 (from ir-datasets->FlagEmbedding)
  Downloading zlib_state-0.1.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.5 kB)
Collecting ijson>=3.1.3 (from ir-datasets->FlagEmbedding)
  Downloading ijson-3.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (23 kB)
Collecting unlzw3>=0.2.1 (from ir-datasets->FlagEmbedding)
  Downloading unlzw3-0.2.3-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.4.1->ir-datasets->FlagEmbedding) (2.8.4)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.6.0->FlagEmbedding) (1.5.5)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.19.0->FlagEmbedding) (3.14.0)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=0.20.1->FlagEmbedding) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=0.20.1->FlagEmbedding) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=0.20.1->FlagEmbedding) (0.28.1)
Collecting lxml>=4.5.2 (from ir-datasets->FlagEmbedding)
  Downloading lxml-6.0.4-cp312-cp312-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl.metadata (3.1 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=2.19.0->FlagEmbedding) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=2.19.0->FlagEmbedding) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=2.19.0->FlagEmbedding) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=2.19.0->FlagEmbedding) (2026.5.20)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.6.0->FlagEmbedding) (1.3.0)
Collecting cbor>=1.0.0 (from trec-car-tools>=2.5.4->ir-datasets->FlagEmbedding)
  Downloading cbor-1.0.0.tar.gz (20 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.44.2->FlagEmbedding) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.44.2->FlagEmbedding) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.44.2->FlagEmbedding) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.6.0->FlagEmbedding) (3.0.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.19.0->FlagEmbedding) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.19.0->FlagEmbedding) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.19.0->FlagEmbedding) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.19.0->FlagEmbedding) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.19.0->FlagEmbedding) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.19.0->FlagEmbedding) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.19.0->FlagEmbedding) (1.24.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=0.20.1->FlagEmbedding) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=0.20.1->FlagEmbedding) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=0.20.1->FlagEmbedding) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.44.2->FlagEmbedding) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.44.2->FlagEmbedding) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.44.2->FlagEmbedding) (0.1.2)
Downloading flagembedding-1.4.0-py3-none-any.whl (247 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 17.1 MB/s eta 0:00:00
Downloading bertopic-0.17.4-py3-none-any.whl (154 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 18.2 MB/s eta 0:00:00
Downloading ir_datasets-0.5.11-py3-none-any.whl (866 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 866.1/866.1 kB 31.7 MB/s eta 0:00:00
Downloading ijson-3.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (149 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.7/149.7 kB 14.9 MB/s eta 0:00:00
Downloading inscriptis-2.7.1-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 4.4 MB/s eta 0:00:00
Downloading lxml-6.0.4-cp312-cp312-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl (5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 18.8 MB/s eta 0:00:00
Downloading lz4-4.4.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 69.1 MB/s eta 0:00:00
Downloading trec_car_tools-2.6-py3-none-any.whl (8.4 kB)
Downloading unlzw3-0.2.3-py3-none-any.whl (6.7 kB)
Downloading warc3_wet-0.2.5-py3-none-any.whl (18 kB)
Downloading zlib_state-0.1.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (22 kB)
Building wheels for collected packages: warc3-wet-clueweb09, cbor
  Building wheel for warc3-wet-clueweb09 (setup.py) ... done
  Created wheel for warc3-wet-clueweb09: filename=warc3_wet_clueweb09-0.2.5-py3-none-any.whl size=18919 sha256=928d8b45e5e3f832513f241f2f28dd3dd44abe2d1633f0cf95f175297d45118f
  Stored in directory: /root/.cache/pip/wheels/f6/85/c2/9f0f621def52a1d5db7d29984f81e45f9fb6dfeb1a4eb6e31c
  Building wheel for cbor (setup.py) ... done
  Created wheel for cbor: filename=cbor-1.0.0-cp312-cp312-linux_x86_64.whl size=55022 sha256=d8c51a37a183d62a2f8b4663818f5d9ba44bafb4adeaac9937117f168884ed29
  Stored in directory: /root/.cache/pip/wheels/44/3e/21/a739cbcc331a1ab45c326d6edbdac6118de4402f6076e30ff1
Successfully built warc3-wet-clueweb09 cbor
Installing collected packages: warc3-wet-clueweb09, warc3-wet, cbor, zlib-state, unlzw3, trec-car-tools, lz4, lxml, ijson, inscriptis, ir-datasets, FlagEmbedding, bertopic
  Attempting uninstall: lxml
    Found existing installation: lxml 6.1.1
    Uninstalling lxml-6.1.1:
      Successfully uninstalled lxml-6.1.1
Successfully installed FlagEmbedding-1.4.0 bertopic-0.17.4 cbor-1.0.0 ijson-3.5.0 inscriptis-2.7.1 ir-datasets-0.5.11 lxml-6.0.4 lz4-4.4.5 trec-car-tools-2.6 unlzw3-0.2.3 warc3-wet-0.2.5 warc3-wet-clueweb09-0.2.5 zlib-state-0.1.12

In [7]:
import numpy as np
import torch
import gdown
import os
from FlagEmbedding import BGEM3FlagModel
from bertopic import BERTopic
from umap import UMAP
from hdbscan import HDBSCAN
import gdown

In [8]:
# 2. 원본 보호
data = df.copy()

In [9]:
from bertopic import BERTopic
from umap import UMAP
from hdbscan import HDBSCAN

In [10]:
# 1. thread_df 불러오기
thread_df = pd.read_csv("/content/drive/MyDrive/comments_merged_thread_add_tag.csv")

print(thread_df.columns.tolist())
print(thread_df.head())

['Unnamed: 0', 'projectID', 'thread_id', 'group', 'comment_ids', 'n_comments', 'merged_comment', 'creator_id', 'is_pledge_master', 'is_backer', 'is_prior_backer', 'is_pathfinder']
   Unnamed: 0  projectID  thread_id  group         comment_ids  n_comments  \
0           0       5787    1691589      0           [1691589]           1
1           1       5787    1725920      0  [1725920, 1726005]           2
2           2       5787    1725876      0           [1725876]           1
3           3       5787    1725671      0           [1725671]           1
4           4       5787    1725512      0           [1725512]           1

                                      merged_comment  creator_id  \
0  WELCOME TO EDEN!  Please check the FAQ and the...           1
1  @BlackSiteStudios Could a person use larger di...           1
2                           about an hour left to go           0
3  Man 2 hours to go worth staying up to midnight...           0
4             5 hours to go!  Hold on to your butts!           0

   is_pledge_master  is_backer  is_prior_backer  is_pathfinder
0                 0          0                0              0
1                 1          1                0              0
2                 1          1                1              0
3                 0          0                0              0
4                 0          1                1              0

In [11]:
thread_df.columns

Index(['Unnamed: 0', 'projectID', 'thread_id', 'group', 'comment_ids',
       'n_comments', 'merged_comment', 'creator_id', 'is_pledge_master',
       'is_backer', 'is_prior_backer', 'is_pathfinder'],
      dtype='object')

In [12]:
sample_thread_df = thread_df.copy().reset_index(drop=True)

sample_thread_df["merged_comment"] = (
    sample_thread_df["merged_comment"]
    .fillna("")
    .astype(str)
    .str.strip()
)

print("빈 merged_comment 수:", (sample_thread_df["merged_comment"] == "").sum())

빈 merged_comment 수: 1

In [13]:
sample_thread_df[
    sample_thread_df["merged_comment"].astype(str).str.strip() == ""
]

,Unnamed: 0,projectID,thread_id,group,comment_ids,n_comments,merged_comment,creator_id,is_pledge_master,is_backer,is_prior_backer,is_pathfinder
21031,21031,222,3196,0,[3196],1,,0,1,1,1,0

In [16]:
thread_df.loc[
    thread_df["merged_comment"].isna() |
    (thread_df["merged_comment"].astype(str).str.strip() == ""),
    ["projectID", "thread_id", "merged_comment"]
]

       projectID  thread_id merged_comment
21031        222       3196            NaN

In [14]:
texts = sample_thread_df["merged_comment"].tolist()
print("전체 thread_df:", len(thread_df))
print("sample_thread_df:", len(sample_thread_df))
print("texts:", len(texts))
print("프로젝트 수:", sample_thread_df["projectID"].nunique())

전체 thread_df: 73439
sample_thread_df: 73439
texts: 73439
프로젝트 수: 473

In [14]:
print("원본 thread 수:", len(thread_df))
print("NaN/빈 댓글 제거 후:", len(sample_thread_df))
print("제거된 수:", len(thread_df) - len(sample_thread_df))

원본 thread 수: 73439
NaN/빈 댓글 제거 후: 73439
제거된 수: 0

In [15]:
sample_thread_df = sample_thread_df[
    sample_thread_df["merged_comment"] != ""
].copy()

sample_thread_df.reset_index(drop=True, inplace=True)

In [16]:
print("원본 thread 수:", len(thread_df))
print("NaN/빈 댓글 제거 후:", len(sample_thread_df))
print("제거된 수:", len(thread_df) - len(sample_thread_df))

원본 thread 수: 73439
NaN/빈 댓글 제거 후: 73438
제거된 수: 1

빈 thread 1개 제거

In [17]:
texts = sample_thread_df["merged_comment"].tolist()
print("프로젝트 수:", sample_thread_df["projectID"].nunique())

display(sample_thread_df["projectID"].value_counts().head(20))

프로젝트 수: 473

projectID
3890    2616
8203    1812
222     1778
1927    1612
1032    1486
1926    1469
3176    1466
2758    1449
1318    1449
3848    1278
2757    1229
5386    1153
2295    1092
3849    1058
5030    1008
2225     980
1114     972
3313     891
889      874
3006     788
Name: count, dtype: int64

In [18]:
# =========================
# group 확인 및 보정
# =========================

print("group 컬럼 존재 여부:", "group" in sample_thread_df.columns)

sample_thread_df["group"] = sample_thread_df["group"].fillna(0).astype(int)

print("group 값 분포")
display(sample_thread_df["group"].value_counts().sort_index())

print("프로젝트별 group 개수 분포")
project_group_count = (
    sample_thread_df.groupby("projectID")["group"]
    .nunique()
    .value_counts()
    .sort_index()
)

display(project_group_count)

print("group이 하나만 있는 프로젝트 수:", (sample_thread_df.groupby("projectID")["group"].nunique() == 1).sum())

only_one_group_projects = (
    sample_thread_df.groupby("projectID")["group"]
    .nunique()
    .reset_index(name="n_group")
    .query("n_group == 1")
)

display(only_one_group_projects.head(30))

group 컬럼 존재 여부: True
group 값 분포

group
0    34571
1    38867
Name: count, dtype: int64

프로젝트별 group 개수 분포

group
1     45
2    428
Name: count, dtype: int64

group이 하나만 있는 프로젝트 수: 45

     projectID  n_group
69        2081        1
78        2200        1
81        2217        1
87        2242        1
91        2275        1
94        2304        1
115       2519        1
129       2728        1
131       2735        1
141       2816        1
162       2977        1
164       2984        1
176       3135        1
184       3176        1
189       3236        1
191       3248        1
211       3478        1
228       3623        1
234       3723        1
279       4126        1
301       4439        1
302       4440        1
309       4566        1
310       4590        1
321       4672        1
324       4737        1
360       5211        1
361       5234        1
364       5275        1
369       5357        1

In [23]:
#3. BGE-M3 임베딩 생성
device = "cuda" if torch.cuda.is_available() else "cpu"
print("device:", device)

model = BGEM3FlagModel(
    "BAAI/bge-m3",
    use_fp16=True if device == "cuda" else False
)

device: cuda

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/687 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/444 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 30 files:   0%|          | 0/30 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

In [19]:
lengths = thread_df["merged_comment"].astype(str).str.split().str.len()

print(lengths.describe())

count    73439.000000
mean        91.293863
std        174.191273
min          1.000000
25%         19.000000
50%         44.000000
75%         96.000000
max       9875.000000
Name: merged_comment, dtype: float64

In [20]:
sample_thread_df["merged_comment"].map(type).value_counts()

merged_comment
<class 'str'>    73438
Name: count, dtype: int64

In [26]:
embeddings = model.encode(
    texts,
    batch_size=32,
    max_length=1024
)["dense_vecs"]

embeddings = np.array(embeddings)

print(embeddings.shape)

pre tokenize:   0%|          | 0/2295 [00:00<?, ?it/s]
pre tokenize:   0%|          | 6/2295 [00:00<00:40, 56.26it/s]
pre tokenize:   1%|          | 14/2295 [00:00<00:32, 69.74it/s]
pre tokenize:   1%|          | 22/2295 [00:00<00:30, 73.61it/s]
pre tokenize:   1%|▏         | 32/2295 [00:00<00:27, 83.76it/s]
pre tokenize:   2%|▏         | 42/2295 [00:00<00:25, 87.76it/s]
pre tokenize:   2%|▏         | 51/2295 [00:00<00:25, 87.47it/s]
pre tokenize:   3%|▎         | 69/2295 [00:00<00:19, 115.23it/s]
pre tokenize:   4%|▎         | 81/2295 [00:00<00:22, 99.72it/s]
pre tokenize:   4%|▍         | 92/2295 [00:01<00:32, 68.62it/s]
pre tokenize:   4%|▍         | 101/2295 [00:01<00:30, 71.19it/s]
pre tokenize:   5%|▌         | 117/2295 [00:01<00:24, 90.29it/s]
pre tokenize:   6%|▌         | 128/2295 [00:01<00:25, 86.67it/s]
pre tokenize:   6%|▌         | 138/2295 [00:01<00:25, 83.34it/s]
pre tokenize:   7%|▋         | 151/2295 [00:01<00:23, 92.85it/s]
pre tokenize:   7%|▋         | 161/2295 [00:01<00:25, 84.08it/s]
pre tokenize:   7%|▋         | 172/2295 [00:02<00:24, 87.80it/s]
pre tokenize:   8%|▊         | 186/2295 [00:02<00:20, 100.76it/s]
pre tokenize:   9%|▊         | 197/2295 [00:02<00:20, 102.82it/s]
pre tokenize:   9%|▉         | 208/2295 [00:02<00:20, 100.71it/s]
pre tokenize:  10%|▉         | 219/2295 [00:02<00:25, 82.71it/s]
pre tokenize:  10%|▉         | 228/2295 [00:02<00:27, 74.64it/s]
pre tokenize:  10%|█         | 240/2295 [00:02<00:24, 85.10it/s]
pre tokenize:  11%|█         | 250/2295 [00:02<00:23, 86.76it/s]
pre tokenize:  11%|█▏        | 260/2295 [00:03<00:26, 77.62it/s]
pre tokenize:  12%|█▏        | 269/2295 [00:03<00:27, 72.94it/s]
pre tokenize:  12%|█▏        | 277/2295 [00:03<00:28, 70.69it/s]
pre tokenize:  13%|█▎        | 291/2295 [00:03<00:23, 86.01it/s]
pre tokenize:  13%|█▎        | 301/2295 [00:03<00:24, 80.38it/s]
pre tokenize:  14%|█▎        | 312/2295 [00:03<00:22, 86.36it/s]
pre tokenize:  14%|█▍        | 321/2295 [00:03<00:23, 83.55it/s]
pre tokenize:  14%|█▍        | 332/2295 [00:03<00:21, 89.79it/s]
pre tokenize:  15%|█▍        | 342/2295 [00:04<00:22, 85.23it/s]
pre tokenize:  15%|█▌        | 354/2295 [00:04<00:20, 93.16it/s]
pre tokenize:  16%|█▌        | 366/2295 [00:04<00:19, 100.11it/s]
pre tokenize:  17%|█▋        | 379/2295 [00:04<00:17, 107.08it/s]
pre tokenize:  17%|█▋        | 390/2295 [00:04<00:18, 104.54it/s]
pre tokenize:  17%|█▋        | 401/2295 [00:04<00:20, 93.48it/s]
pre tokenize:  18%|█▊        | 411/2295 [00:04<00:23, 81.84it/s]
pre tokenize:  18%|█▊        | 420/2295 [00:04<00:27, 68.15it/s]
pre tokenize:  19%|█▊        | 428/2295 [00:05<00:28, 64.73it/s]
pre tokenize:  19%|█▉        | 437/2295 [00:05<00:27, 66.76it/s]
pre tokenize:  19%|█▉        | 445/2295 [00:05<00:26, 68.61it/s]
pre tokenize:  20%|█▉        | 453/2295 [00:05<00:28, 64.76it/s]
pre tokenize:  20%|██        | 460/2295 [00:05<00:37, 48.35it/s]
pre tokenize:  20%|██        | 466/2295 [00:05<00:41, 44.60it/s]
pre tokenize:  21%|██        | 471/2295 [00:06<00:40, 44.67it/s]
pre tokenize:  21%|██        | 478/2295 [00:06<00:36, 50.11it/s]
pre tokenize:  21%|██        | 485/2295 [00:06<00:33, 53.69it/s]
pre tokenize:  21%|██▏       | 491/2295 [00:06<00:36, 48.93it/s]
pre tokenize:  22%|██▏       | 497/2295 [00:06<00:41, 43.80it/s]
pre tokenize:  22%|██▏       | 502/2295 [00:06<00:39, 45.02it/s]
pre tokenize:  22%|██▏       | 511/2295 [00:06<00:32, 54.60it/s]
pre tokenize:  23%|██▎       | 518/2295 [00:06<00:30, 57.48it/s]
pre tokenize:  23%|██▎       | 527/2295 [00:06<00:27, 64.15it/s]
pre tokenize:  23%|██▎       | 534/2295 [00:07<00:26, 65.23it/s]
pre tokenize:  24%|██▎       | 541/2295 [00:07<00:33, 52.38it/s]
pre tokenize:  24%|██▍       | 547/2295 [00:07<00:33, 52.64it/s]
pre tokenize:  24%|██▍       | 557/2295 [00:07<00:27, 62.79it/s]
pre tokenize:  25%|██▍       | 565/2295 [00:07<00:26, 65.89it/s]
pre tokenize:  25%|██▌       | 574/2295 [00:07<00:24, 69.14it/s]
pre tokenize:  25%|██▌       | 585/2295 [00:07<00:22, 76.64it/s]
pre tokenize:  26%|██▌       | 595/2295 [00:07<00:20, 82.64it/s]
pre tokenize:  26%|██▋       | 604/2295 [00:08<00:25, 65.59it/s]
pre tokenize:  27%|██▋       | 612/2295 [00:08<00:32, 52.20it/s]
pre tokenize:  27%|██▋       | 620/2295 [00:08<00:29, 57.69it/s]
pre tokenize:  27%|██▋       | 627/2295 [00:08<00:31, 53.73it/s]
pre tokenize:  28%|██▊       | 638/2295 [00:08<00:25, 64.29it/s]
pre tokenize:  28%|██▊       | 650/2295 [00:08<00:21, 76.70it/s]
pre tokenize:  29%|██▊       | 659/2295 [00:08<00:20, 79.44it/s]
pre tokenize:  29%|██▉       | 672/2295 [00:09<00:17, 92.63it/s]
pre tokenize:  30%|██▉       | 684/2295 [00:09<00:16, 95.54it/s]
pre tokenize:  30%|███       | 696/2295 [00:09<00:15, 101.70it/s]
pre tokenize:  31%|███       | 708/2295 [00:09<00:14, 106.76it/s]
pre tokenize:  31%|███▏      | 719/2295 [00:09<00:15, 102.53it/s]
pre tokenize:  32%|███▏      | 731/2295 [00:09<00:14, 105.88it/s]
pre tokenize:  32%|███▏      | 742/2295 [00:09<00:15, 101.15it/s]
pre tokenize:  33%|███▎      | 756/2295 [00:09<00:13, 110.84it/s]
pre tokenize:  33%|███▎      | 768/2295 [00:09<00:14, 102.36it/s]
pre tokenize:  34%|███▍      | 790/2295 [00:10<00:11, 132.21it/s]
pre tokenize:  35%|███▌      | 804/2295 [00:10<00:12, 122.44it/s]
pre tokenize:  36%|███▌      | 817/2295 [00:10<00:16, 89.28it/s]
pre tokenize:  36%|███▌      | 828/2295 [00:10<00:19, 75.84it/s]
pre tokenize:  37%|███▋      | 840/2295 [00:10<00:17, 83.74it/s]
pre tokenize:  37%|███▋      | 850/2295 [00:10<00:16, 86.81it/s]
pre tokenize:  38%|███▊      | 861/2295 [00:10<00:15, 90.71it/s]
pre tokenize:  38%|███▊      | 872/2295 [00:11<00:15, 90.04it/s]
pre tokenize:  39%|███▊      | 885/2295 [00:11<00:14, 99.36it/s]
pre tokenize:  39%|███▉      | 897/2295 [00:11<00:13, 101.54it/s]
pre tokenize:  40%|███▉      | 908/2295 [00:11<00:13, 99.41it/s]
pre tokenize:  40%|████      | 919/2295 [00:11<00:13, 101.30it/s]
pre tokenize:  41%|████      | 932/2295 [00:11<00:12, 107.88it/s]
pre tokenize:  41%|████▏     | 947/2295 [00:11<00:11, 118.99it/s]
pre tokenize:  42%|████▏     | 960/2295 [00:11<00:11, 115.70it/s]
pre tokenize:  42%|████▏     | 972/2295 [00:11<00:12, 107.11it/s]
pre tokenize:  43%|████▎     | 983/2295 [00:12<00:16, 79.34it/s]
pre tokenize:  43%|████▎     | 994/2295 [00:12<00:15, 85.31it/s]
pre tokenize:  44%|████▎     | 1004/2295 [00:12<00:17, 72.29it/s]
pre tokenize:  44%|████▍     | 1013/2295 [00:12<00:18, 69.84it/s]
pre tokenize:  45%|████▍     | 1023/2295 [00:12<00:16, 76.08it/s]
pre tokenize:  45%|████▍     | 1032/2295 [00:12<00:17, 74.09it/s]
pre tokenize:  45%|████▌     | 1044/2295 [00:13<00:14, 84.02it/s]
pre tokenize:  46%|████▌     | 1055/2295 [00:13<00:13, 89.10it/s]
pre tokenize:  46%|████▋     | 1065/2295 [00:13<00:13, 89.16it/s]
pre tokenize:  47%|████▋     | 1078/2295 [00:13<00:12, 98.55it/s]
pre tokenize:  47%|████▋     | 1089/2295 [00:13<00:13, 91.64it/s]
pre tokenize:  48%|████▊     | 1099/2295 [00:13<00:13, 85.74it/s]
pre tokenize:  48%|████▊     | 1109/2295 [00:13<00:13, 88.05it/s]
pre tokenize:  49%|████▉     | 1119/2295 [00:13<00:13, 89.98it/s]
pre tokenize:  49%|████▉     | 1129/2295 [00:13<00:12, 92.21it/s]
pre tokenize:  50%|████▉     | 1139/2295 [00:14<00:12, 93.15it/s]
pre tokenize:  50%|█████     | 1150/2295 [00:14<00:11, 96.42it/s]
pre tokenize:  51%|█████     | 1161/2295 [00:14<00:11, 99.42it/s]
pre tokenize:  51%|█████     | 1172/2295 [00:14<00:12, 87.72it/s]
pre tokenize:  52%|█████▏    | 1182/2295 [00:14<00:13, 80.70it/s]
pre tokenize:  52%|█████▏    | 1192/2295 [00:14<00:13, 83.61it/s]
pre tokenize:  52%|█████▏    | 1203/2295 [00:14<00:12, 89.83it/s]
pre tokenize:  53%|█████▎    | 1213/2295 [00:14<00:13, 82.99it/s]
pre tokenize:  53%|█████▎    | 1222/2295 [00:15<00:13, 80.24it/s]
pre tokenize:  54%|█████▎    | 1231/2295 [00:15<00:13, 79.04it/s]
pre tokenize:  54%|█████▍    | 1241/2295 [00:15<00:12, 84.10it/s]
pre tokenize:  55%|█████▍    | 1251/2295 [00:15<00:12, 86.06it/s]
pre tokenize:  55%|█████▍    | 1260/2295 [00:15<00:12, 81.38it/s]
pre tokenize:  55%|█████▌    | 1270/2295 [00:15<00:11, 86.11it/s]
pre tokenize:  56%|█████▌    | 1281/2295 [00:15<00:11, 92.13it/s]
pre tokenize:  56%|█████▋    | 1291/2295 [00:15<00:10, 92.26it/s]
pre tokenize:  57%|█████▋    | 1301/2295 [00:15<00:11, 88.72it/s]
pre tokenize:  57%|█████▋    | 1310/2295 [00:16<00:12, 78.58it/s]
pre tokenize:  57%|█████▋    | 1319/2295 [00:16<00:12, 79.78it/s]
pre tokenize:  58%|█████▊    | 1328/2295 [00:16<00:11, 80.98it/s]
pre tokenize:  58%|█████▊    | 1338/2295 [00:16<00:11, 83.05it/s]
pre tokenize:  59%|█████▊    | 1347/2295 [00:16<00:11, 79.26it/s]
pre tokenize:  59%|█████▉    | 1356/2295 [00:16<00:12, 77.71it/s]
pre tokenize:  59%|█████▉    | 1364/2295 [00:16<00:12, 74.93it/s]
pre tokenize:  60%|█████▉    | 1373/2295 [00:16<00:11, 78.69it/s]
pre tokenize:  60%|██████    | 1381/2295 [00:16<00:12, 76.10it/s]
pre tokenize:  61%|██████    | 1389/2295 [00:17<00:11, 77.00it/s]
pre tokenize:  61%|██████    | 1397/2295 [00:17<00:12, 71.48it/s]
pre tokenize:  61%|██████▏   | 1406/2295 [00:17<00:11, 75.18it/s]
pre tokenize:  62%|██████▏   | 1414/2295 [00:17<00:12, 68.66it/s]
pre tokenize:  62%|██████▏   | 1424/2295 [00:17<00:11, 75.15it/s]
pre tokenize:  62%|██████▏   | 1434/2295 [00:17<00:10, 78.80it/s]
pre tokenize:  63%|██████▎   | 1443/2295 [00:17<00:10, 79.06it/s]
pre tokenize:  63%|██████▎   | 1454/2295 [00:17<00:09, 86.72it/s]
pre tokenize:  64%|██████▍   | 1464/2295 [00:18<00:09, 87.49it/s]
pre tokenize:  64%|██████▍   | 1474/2295 [00:18<00:09, 89.28it/s]
pre tokenize:  65%|██████▍   | 1484/2295 [00:18<00:09, 86.49it/s]
pre tokenize:  65%|██████▌   | 1493/2295 [00:18<00:10, 77.86it/s]
pre tokenize:  65%|██████▌   | 1501/2295 [00:18<00:10, 74.98it/s]
pre tokenize:  66%|██████▌   | 1510/2295 [00:18<00:10, 78.24it/s]
pre tokenize:  66%|██████▌   | 1520/2295 [00:18<00:09, 77.76it/s]
pre tokenize:  67%|██████▋   | 1528/2295 [00:18<00:11, 66.45it/s]
pre tokenize:  67%|██████▋   | 1535/2295 [00:19<00:15, 47.63it/s]
pre tokenize:  67%|██████▋   | 1541/2295 [00:19<00:17, 42.97it/s]
pre tokenize:  67%|██████▋   | 1549/2295 [00:19<00:14, 49.91it/s]
pre tokenize:  68%|██████▊   | 1555/2295 [00:19<00:14, 51.27it/s]
pre tokenize:  68%|██████▊   | 1562/2295 [00:19<00:13, 53.88it/s]
pre tokenize:  68%|██████▊   | 1568/2295 [00:19<00:15, 46.53it/s]
pre tokenize:  69%|██████▊   | 1574/2295 [00:19<00:15, 46.80it/s]
pre tokenize:  69%|██████▉   | 1582/2295 [00:20<00:13, 53.42it/s]
pre tokenize:  69%|██████▉   | 1589/2295 [00:20<00:12, 55.95it/s]
pre tokenize:  70%|██████▉   | 1596/2295 [00:20<00:11, 58.26it/s]
pre tokenize:  70%|██████▉   | 1605/2295 [00:20<00:11, 62.20it/s]
pre tokenize:  70%|███████   | 1612/2295 [00:20<00:11, 60.45it/s]
pre tokenize:  71%|███████   | 1619/2295 [00:20<00:11, 58.23it/s]
pre tokenize:  71%|███████   | 1625/2295 [00:20<00:12, 55.32it/s]
pre tokenize:  71%|███████   | 1631/2295 [00:20<00:11, 56.42it/s]
pre tokenize:  71%|███████▏  | 1639/2295 [00:21<00:10, 60.50it/s]
pre tokenize:  72%|███████▏  | 1646/2295 [00:21<00:12, 53.99it/s]
pre tokenize:  72%|███████▏  | 1652/2295 [00:21<00:11, 55.40it/s]
pre tokenize:  72%|███████▏  | 1659/2295 [00:21<00:10, 58.14it/s]
pre tokenize:  73%|███████▎  | 1665/2295 [00:21<00:11, 54.13it/s]
pre tokenize:  73%|███████▎  | 1673/2295 [00:21<00:10, 60.17it/s]
pre tokenize:  73%|███████▎  | 1680/2295 [00:21<00:10, 58.32it/s]
pre tokenize:  73%|███████▎  | 1686/2295 [00:21<00:10, 56.94it/s]
pre tokenize:  74%|███████▍  | 1694/2295 [00:21<00:09, 62.56it/s]
pre tokenize:  74%|███████▍  | 1701/2295 [00:22<00:09, 60.76it/s]
pre tokenize:  74%|███████▍  | 1708/2295 [00:22<00:09, 61.54it/s]
pre tokenize:  75%|███████▍  | 1715/2295 [00:22<00:09, 60.38it/s]
pre tokenize:  75%|███████▌  | 1722/2295 [00:22<00:10, 53.80it/s]
pre tokenize:  75%|███████▌  | 1728/2295 [00:22<00:11, 51.35it/s]
pre tokenize:  76%|███████▌  | 1734/2295 [00:22<00:13, 42.79it/s]
pre tokenize:  76%|███████▌  | 1740/2295 [00:22<00:12, 43.25it/s]
pre tokenize:  76%|███████▌  | 1745/2295 [00:23<00:13, 41.80it/s]
pre tokenize:  76%|███████▋  | 1755/2295 [00:23<00:09, 54.06it/s]
pre tokenize:  77%|███████▋  | 1763/2295 [00:23<00:09, 55.03it/s]
pre tokenize:  77%|███████▋  | 1769/2295 [00:23<00:12, 42.49it/s]
pre tokenize:  77%|███████▋  | 1774/2295 [00:23<00:12, 41.27it/s]
pre tokenize:  78%|███████▊  | 1786/2295 [00:23<00:08, 57.65it/s]
pre tokenize:  78%|███████▊  | 1795/2295 [00:23<00:07, 63.81it/s]
pre tokenize:  79%|███████▊  | 1805/2295 [00:24<00:06, 71.21it/s]
pre tokenize:  79%|███████▉  | 1813/2295 [00:24<00:06, 72.01it/s]
pre tokenize:  79%|███████▉  | 1821/2295 [00:24<00:08, 58.15it/s]
pre tokenize:  80%|███████▉  | 1828/2295 [00:24<00:10, 44.61it/s]
pre tokenize:  80%|████████  | 1843/2295 [00:24<00:07, 64.05it/s]
pre tokenize:  81%|████████  | 1854/2295 [00:24<00:06, 72.80it/s]
pre tokenize:  81%|████████  | 1864/2295 [00:24<00:05, 78.52it/s]
pre tokenize:  82%|████████▏ | 1874/2295 [00:25<00:05, 81.72it/s]
pre tokenize:  82%|████████▏ | 1883/2295 [00:25<00:05, 78.51it/s]
pre tokenize:  83%|████████▎ | 1894/2295 [00:25<00:04, 84.88it/s]
pre tokenize:  83%|████████▎ | 1903/2295 [00:25<00:04, 80.43it/s]
pre tokenize:  83%|████████▎ | 1912/2295 [00:25<00:04, 78.62it/s]
pre tokenize:  84%|████████▎ | 1921/2295 [00:25<00:04, 80.21it/s]
pre tokenize:  84%|████████▍ | 1931/2295 [00:25<00:04, 84.22it/s]
pre tokenize:  85%|████████▍ | 1941/2295 [00:25<00:04, 87.02it/s]
pre tokenize:  85%|████████▌ | 1951/2295 [00:25<00:03, 90.13it/s]
pre tokenize:  85%|████████▌ | 1961/2295 [00:26<00:04, 82.23it/s]
pre tokenize:  86%|████████▌ | 1972/2295 [00:26<00:03, 87.78it/s]
pre tokenize:  86%|████████▋ | 1982/2295 [00:26<00:03, 88.43it/s]
pre tokenize:  87%|████████▋ | 1994/2295 [00:26<00:03, 95.98it/s]
pre tokenize:  88%|████████▊ | 2009/2295 [00:26<00:02, 110.40it/s]
pre tokenize:  88%|████████▊ | 2021/2295 [00:26<00:02, 96.30it/s]
pre tokenize:  89%|████████▊ | 2032/2295 [00:26<00:02, 96.26it/s]
pre tokenize:  89%|████████▉ | 2042/2295 [00:26<00:02, 92.81it/s]
pre tokenize:  89%|████████▉ | 2054/2295 [00:27<00:02, 98.33it/s]
pre tokenize:  90%|████████▉ | 2065/2295 [00:27<00:02, 93.75it/s]
pre tokenize:  90%|█████████ | 2075/2295 [00:27<00:02, 91.56it/s]
pre tokenize:  91%|█████████ | 2085/2295 [00:27<00:02, 82.85it/s]
pre tokenize:  91%|█████████▏| 2096/2295 [00:27<00:02, 89.57it/s]
pre tokenize:  92%|█████████▏| 2109/2295 [00:27<00:01, 98.18it/s]
pre tokenize:  92%|█████████▏| 2120/2295 [00:27<00:01, 98.64it/s]
pre tokenize:  93%|█████████▎| 2131/2295 [00:27<00:01, 97.56it/s]
pre tokenize:  93%|█████████▎| 2142/2295 [00:27<00:01, 99.57it/s]
pre tokenize:  94%|█████████▍| 2153/2295 [00:28<00:01, 97.08it/s]
pre tokenize:  94%|█████████▍| 2163/2295 [00:28<00:01, 88.94it/s]
pre tokenize:  95%|█████████▍| 2173/2295 [00:28<00:01, 82.63it/s]
pre tokenize:  95%|█████████▌| 2184/2295 [00:28<00:01, 87.95it/s]
pre tokenize:  96%|█████████▌| 2196/2295 [00:28<00:01, 94.90it/s]
pre tokenize:  96%|█████████▌| 2206/2295 [00:28<00:00, 90.09it/s]
pre tokenize:  97%|█████████▋| 2216/2295 [00:28<00:00, 83.41it/s]
pre tokenize:  97%|█████████▋| 2225/2295 [00:28<00:00, 82.77it/s]
pre tokenize:  97%|█████████▋| 2234/2295 [00:29<00:00, 83.62it/s]
pre tokenize:  98%|█████████▊| 2243/2295 [00:29<00:00, 76.72it/s]
pre tokenize:  98%|█████████▊| 2254/2295 [00:29<00:00, 84.79it/s]
pre tokenize:  99%|█████████▊| 2265/2295 [00:29<00:00, 91.36it/s]
pre tokenize:  99%|█████████▉| 2275/2295 [00:29<00:00, 91.65it/s]
pre tokenize: 100%|██████████| 2295/2295 [00:29<00:00, 77.29it/s]

Inference Embeddings:   0%|          | 0/2295 [00:00<?, ?it/s]
Inference Embeddings:   0%|          | 1/2295 [00:01<44:05,  1.15s/it]
Inference Embeddings:   0%|          | 2/2295 [00:02<43:30,  1.14s/it]
Inference Embeddings:   0%|          | 3/2295 [00:03<43:59,  1.15s/it]
Inference Embeddings:   0%|          | 4/2295 [00:04<44:17,  1.16s/it]
Inference Embeddings:   0%|          | 5/2295 [00:05<44:29,  1.17s/it]
Inference Embeddings:   0%|          | 6/2295 [00:06<44:28,  1.17s/it]
Inference Embeddings:   0%|          | 7/2295 [00:08<44:28,  1.17s/it]
Inference Embeddings:   0%|          | 8/2295 [00:09<44:31,  1.17s/it]
Inference Embeddings:   0%|          | 9/2295 [00:10<44:34,  1.17s/it]
Inference Embeddings:   0%|          | 10/2295 [00:11<44:39,  1.17s/it]
Inference Embeddings:   0%|          | 11/2295 [00:12<44:44,  1.18s/it]
Inference Embeddings:   1%|          | 12/2295 [00:14<44:52,  1.18s/it]
Inference Embeddings:   1%|          | 13/2295 [00:15<45:00,  1.18s/it]
Inference Embeddings:   1%|          | 14/2295 [00:16<45:18,  1.19s/it]
Inference Embeddings:   1%|          | 15/2295 [00:17<45:35,  1.20s/it]
Inference Embeddings:   1%|          | 16/2295 [00:18<45:44,  1.20s/it]
Inference Embeddings:   1%|          | 17/2295 [00:20<45:53,  1.21s/it]
Inference Embeddings:   1%|          | 18/2295 [00:21<45:59,  1.21s/it]
Inference Embeddings:   1%|          | 19/2295 [00:22<46:02,  1.21s/it]
Inference Embeddings:   1%|          | 20/2295 [00:23<46:04,  1.22s/it]
Inference Embeddings:   1%|          | 21/2295 [00:24<46:09,  1.22s/it]
Inference Embeddings:   1%|          | 22/2295 [00:26<46:12,  1.22s/it]
Inference Embeddings:   1%|          | 23/2295 [00:27<46:11,  1.22s/it]
Inference Embeddings:   1%|          | 24/2295 [00:28<46:06,  1.22s/it]
Inference Embeddings:   1%|          | 25/2295 [00:30<48:45,  1.29s/it]
Inference Embeddings:   1%|          | 26/2295 [00:31<49:51,  1.32s/it]
Inference Embeddings:   1%|          | 27/2295 [00:32<50:16,  1.33s/it]
Inference Embeddings:   1%|          | 28/2295 [00:34<50:19,  1.33s/it]
Inference Embeddings:   1%|▏         | 29/2295 [00:35<49:08,  1.30s/it]
Inference Embeddings:   1%|▏         | 30/2295 [00:36<48:30,  1.29s/it]
Inference Embeddings:   1%|▏         | 31/2295 [00:37<47:54,  1.27s/it]
Inference Embeddings:   1%|▏         | 32/2295 [00:39<47:20,  1.26s/it]
Inference Embeddings:   1%|▏         | 33/2295 [00:40<46:44,  1.24s/it]
Inference Embeddings:   1%|▏         | 34/2295 [00:41<45:47,  1.22s/it]
Inference Embeddings:   2%|▏         | 35/2295 [00:42<45:00,  1.20s/it]
Inference Embeddings:   2%|▏         | 36/2295 [00:43<44:16,  1.18s/it]
Inference Embeddings:   2%|▏         | 37/2295 [00:44<44:07,  1.17s/it]
Inference Embeddings:   2%|▏         | 38/2295 [00:46<43:31,  1.16s/it]
Inference Embeddings:   2%|▏         | 39/2295 [00:47<42:35,  1.13s/it]
Inference Embeddings:   2%|▏         | 40/2295 [00:48<42:01,  1.12s/it]
Inference Embeddings:   2%|▏         | 41/2295 [00:49<41:08,  1.10s/it]
Inference Embeddings:   2%|▏         | 42/2295 [00:50<40:10,  1.07s/it]
Inference Embeddings:   2%|▏         | 43/2295 [00:51<39:16,  1.05s/it]
Inference Embeddings:   2%|▏         | 44/2295 [00:52<38:38,  1.03s/it]
Inference Embeddings:   2%|▏         | 45/2295 [00:53<37:52,  1.01s/it]
Inference Embeddings:   2%|▏         | 46/2295 [00:54<37:26,  1.00it/s]
Inference Embeddings:   2%|▏         | 47/2295 [00:55<37:09,  1.01it/s]
Inference Embeddings:   2%|▏         | 48/2295 [00:56<36:53,  1.01it/s]
Inference Embeddings:   2%|▏         | 49/2295 [00:57<36:15,  1.03it/s]
Inference Embeddings:   2%|▏         | 50/2295 [00:57<35:49,  1.04it/s]
Inference Embeddings:   2%|▏         | 51/2295 [00:58<35:30,  1.05it/s]
Inference Embeddings:   2%|▏         | 52/2295 [00:59<35:08,  1.06it/s]
Inference Embeddings:   2%|▏         | 53/2295 [01:00<34:38,  1.08it/s]
Inference Embeddings:   2%|▏         | 54/2295 [01:01<34:20,  1.09it/s]
Inference Embeddings:   2%|▏         | 55/2295 [01:02<33:54,  1.10it/s]
Inference Embeddings:   2%|▏         | 56/2295 [01:03<33:36,  1.11it/s]
Inference Embeddings:   2%|▏         | 57/2295 [01:04<33:14,  1.12it/s]
Inference Embeddings:   3%|▎         | 58/2295 [01:05<32:40,  1.14it/s]
Inference Embeddings:   3%|▎         | 59/2295 [01:05<32:22,  1.15it/s]
Inference Embeddings:   3%|▎         | 60/2295 [01:06<32:07,  1.16it/s]
Inference Embeddings:   3%|▎         | 61/2295 [01:07<31:52,  1.17it/s]

(73438, 1024)

In [28]:
np.save(
    "/content/drive/MyDrive/bge_m3_embeddings.npy",
    embeddings
)

In [22]:
embeddings = np.load("/content/drive/MyDrive/bge_m3_embeddings.npy")

In [23]:
# 4. 모델 설정
umap_model = UMAP(
    n_neighbors=15,
    n_components=10,
    min_dist=0.0,
    metric="cosine",
    random_state=42,
    low_memory=True
)

hdbscan_model = HDBSCAN(
    min_cluster_size=50,
    min_samples=3,
    metric="euclidean",
    cluster_selection_method="eom",
    prediction_data=True
)

topic_model_final = BERTopic(
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    language="multilingual",
    calculate_probabilities=False,
    verbose=True
)

In [24]:
# 모델 실행
topics, probs = topic_model_final.fit_transform(
    texts,
    embeddings
)

print("BERTopic 완료")
print("토픽 개수:", len(set(topics)))
print("-1 개수:", sum(np.array(topics) == -1))
print("-1 비율:", round((np.array(topics) == -1).mean() * 100, 2), "%")

2026-06-09 04:23:33,026 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-06-09 04:26:10,735 - BERTopic - Dimensionality - Completed ✓
2026-06-09 04:26:10,740 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-06-09 04:26:23,670 - BERTopic - Cluster - Completed ✓
2026-06-09 04:26:23,691 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-06-09 04:26:28,500 - BERTopic - Representation - Completed ✓

BERTopic 완료
토픽 개수: 193
-1 개수: 31001
-1 비율: 42.21 %

In [40]:
umap_model = UMAP(
    n_neighbors=15,
    n_components=10,
    min_dist=0.0,
    metric="cosine",
    random_state=42,
    low_memory=True
)

hdbscan_model = HDBSCAN(
    min_cluster_size=30,
    min_samples=1,
    metric="euclidean",
    cluster_selection_method="eom",
    prediction_data=True
)

topic_model_final_1 = BERTopic(
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    language="multilingual",
    calculate_probabilities=False,
    verbose=True
)

topics, probs = topic_model_final_1.fit_transform(
    texts,
    embeddings
)

print("BERTopic 완료")
print("토픽 개수:", len(set(topics)))
print("-1 개수:", sum(np.array(topics) == -1))
print("-1 비율:", round((np.array(topics) == -1).mean() * 100, 2), "%")

2026-06-09 04:38:20,468 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-06-09 04:40:34,656 - BERTopic - Dimensionality - Completed ✓
2026-06-09 04:40:34,660 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-06-09 04:40:47,115 - BERTopic - Cluster - Completed ✓
2026-06-09 04:40:47,136 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-06-09 04:40:53,261 - BERTopic - Representation - Completed ✓

BERTopic 완료
토픽 개수: 365
-1 개수: 27948
-1 비율: 38.06 %

In [25]:
topics_original_final = topics.copy()
np.save("/content/drive/MyDrive/topics_original_final_merged.npy", topics_original_final)

sample_thread_df["topic_original"] = topics_original_final
sample_thread_df["was_outlier"] = sample_thread_df["topic_original"] == -1

sample_thread_df.to_pickle("/content/drive/MyDrive/thread_df_topics_original_final_merged.pkl")

In [26]:
topics_original_info = topic_model_final.get_topic_info()
topics_original_info.head()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,31001,-1_the_to_and_of,"[the, to, and, of, it, you, in, that, for, is]","[As a total stalker-lore fan, who discovered v..."
1,0,2151,0_solo_mode_player_players,"[solo, mode, player, players, play, coop, co, ...","[Can we get a solo mode? :D, +1 for a solo mod..."
2,1,1884,1_excited_game_wait_this,"[excited, game, wait, this, looks, forward, th...",[This game looks awesome. Can't wait to get i...
3,2,1166,2_dc_batman_marvel_united,"[dc, batman, marvel, united, villains, charact...",[This will upset people but I'm Only here for ...
4,3,1102,3_shipping_eu_china_cost,"[shipping, eu, china, cost, costs, australia, ...",[Why for the love of everything holy is shippi...

In [27]:
topics_original_info = topic_model_final.get_topic_info()

topics_original_info.to_csv(
    "/content/drive/MyDrive/topics_original_info_merged.csv",
    index=False
)

In [28]:
# outlier 처리
topics_reassigned_final = topic_model_final.reduce_outliers(
    texts,
    topics_original_final,
    embeddings=embeddings,
    strategy="embeddings"
)

topics_reassigned_final = np.array(topics_reassigned_final)

sample_thread_df["topic_reassigned"] = topics_reassigned_final

np.save("/content/drive/MyDrive/topics_reassigned_final_merged.npy", topics_reassigned_final)

sample_thread_df.to_pickle("/content/drive/MyDrive/thread_df_topics_original_reassigned_final_merged.pkl")

print("재할당 후 -1 비율:", round((topics_reassigned_final == -1).mean() * 100, 2), "%")

재할당 후 -1 비율: 0.0 %

embedding similarity 기준으로 기존 토픽에 재할당 후 토픽 수 변화 비교

In [29]:
# 1. 토픽 의미/키워드 확인용
topic_info_original = topic_model_final.get_topic_info()

# 2. 재할당 후 최종 문서 수 확인용
topic_counts_final = (
    pd.Series(topics_reassigned_final)
    .value_counts()
    .reset_index()
)

topic_counts_final.columns = ["Topic", "Count_final"]

# 3. 둘 합치기
topic_info_final_view = topic_info_original.merge(
    topic_counts_final,
    on="Topic",
    how="left"
)

topic_info_final_view["Count_final"] = (
    topic_info_final_view["Count_final"]
    .fillna(0)
    .astype(int)
)

topic_info_final_view.head(20)

,Topic,Count,Name,Representation,Representative_Docs,Count_final
0,-1,31001,-1_the_to_and_of,"[the, to, and, of, it, you, in, that, for, is]","[As a total stalker-lore fan, who discovered v...",0
1,0,2151,0_solo_mode_player_players,"[solo, mode, player, players, play, coop, co, ...","[Can we get a solo mode? :D, +1 for a solo mod...",2326
2,1,1884,1_excited_game_wait_this,"[excited, game, wait, this, looks, forward, th...",[This game looks awesome. Can't wait to get i...,2971
3,2,1166,2_dc_batman_marvel_united,"[dc, batman, marvel, united, villains, charact...",[This will upset people but I'm Only here for ...,1548
4,3,1102,3_shipping_eu_china_cost,"[shipping, eu, china, cost, costs, australia, ...",[Why for the love of everything holy is shippi...,1541
5,4,1011,4_price_expensive_game_base,"[price, expensive, game, base, cost, this, is,...",[1. Lower the price 2. offer a less expensive ...,1842
6,5,936,5_stretch_goals_goal_daily,"[stretch, goals, goal, daily, unlocked, unlock...",[Will there be stretch goals or what we see is...,1092
7,6,864,6_playmat_mat_neoprene_mats,"[playmat, mat, neoprene, mats, playmats, board...",[Interesting to see the game mat being so expe...,995
8,7,863,7_sleeves_sleeved_sleeve_cards,"[sleeves, sleeved, sleeve, cards, fit, insert,...",[Will you offer card sleeves? And does the in...,915
9,8,832,8_launch_date_when_start,"[launch, date, when, start, campaign, live, se...",[When?|We didn't share the launch date yet. So...,1072
10,9,813,9_tiles_boards_board_tile,"[tiles, boards, board, tile, player, layer, du...","[Please please PLEASE, don't go to much overbo...",1403
11,10,758,10_box_boxes_big_storage,"[box, boxes, big, storage, fit, solution, ever...",[I'm just adding to the crowd request for a bi...,1477
12,11,751,11_pledge_all_add_apocalypse,"[pledge, all, add, apocalypse, ons, in, new, e...",[#question I pledged the Reprint All-In ($340....,1502
13,12,715,12_standees_minis_standee_acrylic,"[standees, minis, standee, acrylic, miniatures...",[Would the special edition include cardboard s...,852
14,13,667,13_delivery_date_2025_2024,"[delivery, date, 2025, 2024, estimated, months...",[What is the estimated delivery date of this c...,828
15,14,605,14_vat_eu_tax_pay,"[vat, eu, tax, pay, uk, taxes, shipping, sales...",[We are one of the first companies having to t...,721
16,15,603,15_sundrop_minis_paint_sundropped,"[sundrop, minis, paint, sundropped, wash, opti...","[Will there be sundrop?|+1|+1, Some miniatures...",669
17,16,602,16_spanish_español_en_please,"[spanish, español, en, please, favor, por, ver...","[Spanish?, Spanish?, #spanish spanish please !!!]",734
18,17,557,17_free_pledge_48_bird,"[free, pledge, 48, bird, early, gift, hours, f...",[Hmmm... The Renegade Hunter was not added to ...,848
19,18,531,18_italian_language_please_italiano,"[italian, language, please, italiano, translat...","[#italian Italian language, please!! 🇮🇹, Itali...",647

In [30]:
# 재할당 후 크게 늘어난 토픽
topic_info_final_view["increase"] = (
    topic_info_final_view["Count_final"] - topic_info_final_view["Count"]
)

topic_info_final_view["increase_ratio"] = (
    topic_info_final_view["Count_final"] / topic_info_final_view["Count"]
)

topic_info_final_view[
    ["Topic", "Count", "Count_final", "increase", "increase_ratio", "Name", "Representation"]
].sort_values("increase", ascending=False).head(20)

,Topic,Count,Count_final,increase,increase_ratio,Name,Representation
2,1,1884,2971,1087,1.576964,1_excited_game_wait_this,"[excited, game, wait, this, looks, forward, th..."
5,4,1011,1842,831,1.821958,4_price_expensive_game_base,"[price, expensive, game, base, cost, this, is,..."
74,73,152,952,800,6.263158,73_cards_faction_new_art,"[cards, faction, new, art, player, expansion, ..."
44,43,240,1033,793,4.304167,43_boss_difficulty_attack_action,"[boss, difficulty, attack, action, you, combat..."
12,11,751,1502,751,2.000000,11_pledge_all_add_apocalypse,"[pledge, all, add, apocalypse, ons, in, new, e..."
11,10,758,1477,719,1.948549,10_box_boxes_big_storage,"[box, boxes, big, storage, fit, solution, ever..."
10,9,813,1403,590,1.725707,9_tiles_boards_board_tile,"[tiles, boards, board, tile, player, layer, du..."
82,81,139,729,590,5.244604,81_available_campaign_base_previous,"[available, campaign, base, previous, first, w..."
75,74,152,699,547,4.598684,74_projects_communication_company_project,"[projects, communication, company, project, ga..."
137,136,80,619,539,7.737500,136_skyrim_eso_game_elder,"[skyrim, eso, game, elder, scrolls, rpg, like,..."
91,90,130,610,480,4.692308,90_edition_upgrade_1st_pack,"[edition, upgrade, 1st, pack, owners, kit, upd..."
4,3,1102,1541,439,1.398367,3_shipping_eu_china_cost,"[shipping, eu, china, cost, costs, australia, ..."
39,38,279,704,425,2.523297,38_retail_exclusive_available_gamefound,"[retail, exclusive, available, gamefound, will..."
61,60,188,612,424,3.255319,60_update_updates_week_next,"[update, updates, week, next, today, soon, com..."
56,55,200,604,404,3.020000,55_french_version_le_de,"[french, version, le, de, la, en, pour, est, p..."
3,2,1166,1548,382,1.327616,2_dc_batman_marvel_united,"[dc, batman, marvel, united, villains, charact..."
29,28,320,690,370,2.156250,28_campaign_luck_thank_excited,"[campaign, luck, thank, excited, support, good..."
64,63,185,549,364,2.967568,63_banned_pentaquark_handsome_books,"[banned, pentaquark, handsome, books, shy, tur..."
25,24,415,773,358,1.862651,24_shipping_group_copies_cost,"[shipping, group, copies, cost, pledge, multip..."
92,91,130,486,356,3.738462,91_welcome_back_happy_glad,"[welcome, back, happy, glad, here, aboard, exc..."

In [31]:
# 재할당으로 새로 붙은 댓글만 확인
sample_thread_df["topic_original"] = topics_original_final
sample_thread_df["topic_final"] = topics_reassigned_final
sample_thread_df["was_reassigned"] = (
    sample_thread_df["topic_original"] != sample_thread_df["topic_final"]
)

check_topics = [10, 1, 52, 8, 203, 85, 19, 49, 107, 55]

for tid in check_topics:
    print("=" * 80)
    print(f"Topic {tid}")

    temp = sample_thread_df[
        (sample_thread_df["topic_final"] == tid) &
        (sample_thread_df["was_reassigned"])
    ].copy()

    print("재할당으로 새로 붙은 thread 수:", len(temp))

    if len(temp) == 0:
        print("재할당된 thread 없음")
        continue

    display(
        temp[
            [
                "thread_id",
                "projectID",
                "group",
                "merged_comment",
                "topic_original",
                "topic_final"
            ]
        ].sample(
            n=min(5, len(temp)),
            random_state=42
        )
    )

================================================================================
Topic 10
재할당으로 새로 붙은 thread 수: 719

,thread_id,projectID,group,merged_comment,topic_original,topic_final
17066,206452,1926,0,Definitely all the expansions included in the ...,-1,10
25608,445285,2635,0,Sorry if this was asked and I missed it. I am ...,-1,10
5634,1050056,4065,0,Any idea if the Folded Space insert for the or...,-1,10
57355,90640,1078,1,What's the difference between the godly pledge...,-1,10
27839,813723,3830,0,will the new box be available separately?|A we...,-1,10

================================================================================
Topic 1
재할당으로 새로 붙은 thread 수: 1087

,thread_id,projectID,group,merged_comment,topic_original,topic_final
41386,899993,2969,1,I look forward to play Feudum! I was at work w...,-1,1
2016,1583950,5386,0,"Hi AR, the game looks very cool! I'm a big fan...",-1,1
34314,1921456,6381,0,"I saw this game yesterday, and while the idea ...",-1,1
53474,127531,1114,1,Update is live everyone! Also - thanks sooo mu...,-1,1
39150,784193,2225,1,Appena effettuato il pladge eternal. Complimen...,-1,1

================================================================================
Topic 52
재할당으로 새로 붙은 thread 수: 88

,thread_id,projectID,group,merged_comment,topic_original,topic_final
65012,752397,3261,1,"Will the ""moments on the path"" and ""errata"" pa...",-1,52
1176,1687868,4639,0,Friendly reminder If you want your language ...,-1,52
38200,1370655,2874,1,"Hey @Andrea_Godot, wieso konnte ich das Spiel ...",-1,52
36501,1617600,5386,1,I can't select language in the playmats|Source...,-1,52
22326,2017005,5644,0,What language versions are planed? Or are all ...,-1,52

================================================================================
Topic 8
재할당으로 새로 붙은 thread 수: 240

,thread_id,projectID,group,merged_comment,topic_original,topic_final
2783,1216580,4365,0,"Da kein neues Datum genannt wurde, heißt das, ...",-1,8
161,2238663,6481,0,Sorry if you've answered this already but I ca...,-1,8
16730,216630,1926,0,I’m new to gamefund but absolutely love Castle...,-1,8
19256,169670,1398,0,1 big question i do want to ask.. how long wil...,-1,8
18440,207675,1851,0,Campaign launch is coming in a meager four day...,-1,8

================================================================================
Topic 203
재할당으로 새로 붙은 thread 수: 0
재할당된 thread 없음
================================================================================
Topic 85
재할당으로 새로 붙은 thread 수: 33

,thread_id,projectID,group,merged_comment,topic_original,topic_final
66134,651747,3016,1,Are the Ships of Akarios the same as the 1.0 S...,-1,85
31613,72012,1032,0,I'm curious if any errata from the first campa...,-1,85
53773,208943,1725,1,Quick question if I go with the legenday versi...,-1,85
37391,1417384,4365,1,"Ich würde gerne noch mehr darüber erfahren, wa...",-1,85
23355,1832881,5920,0,Could you clarify whether combat encounters wi...,-1,85

================================================================================
Topic 19
재할당으로 새로 붙은 thread 수: 30

,thread_id,projectID,group,merged_comment,topic_original,topic_final
65693,761497,3547,1,+1 here for the option to add just the lighted...,-1,19
25534,1103091,4174,0,I love how janky the campaign graphics are! Th...,-1,19
44848,744043,3554,1,So I was looking forward to paying the 110 for...,-1,19
26340,897122,3890,0,Saldrá editado en español y abra strech pay?,-1,19
11810,490014,2757,0,French language and stretch pay +1 too. Can we...,-1,19

================================================================================
Topic 49
재할당으로 새로 붙은 thread 수: 119

,thread_id,projectID,group,merged_comment,topic_original,topic_final
9359,830621,3592,0,This looks exciting! Can’t wait to receive Mon...,-1,49
43554,868958,3818,1,"They say....""Goal reached in 2 hours and 41 mi...",-1,49
1557,596367,3723,0,So NA backers are still months away from recei...,-1,49
6962,651997,3176,0,when can we expect the localization for German...,-1,49
3647,160496,4590,0,Check the KS comments for updates on placed an...,-1,49

================================================================================
Topic 107
재할당으로 새로 붙은 thread 수: 288

,thread_id,projectID,group,merged_comment,topic_original,topic_final
11460,562461,2757,0,@AR_Jordan — in the One Stop Co-Op Shop (truly...,-1,107
44158,789745,3383,1,Still on the fence on whether to go for just t...,-1,107
65817,741184,3582,1,I have the 1st edition and have a few question...,-1,107
10690,395285,2264,0,I saw that there's 22 ship boards. Does that ...,-1,107
48974,422482,2295,1,the requirement for a sorcerer is to have a ma...,-1,107

================================================================================
Topic 55
재할당으로 새로 붙은 thread 수: 404

,thread_id,projectID,group,merged_comment,topic_original,topic_final
10365,731447,3554,0,#originalbackers Pourrait on avoir un update ...,-1,55
36831,723870,3278,1,"Bonjour, ça a sûrement déjà été précisé mais j...",-1,55
70081,64902,954,1,"Hi ! I do not find the info, but maybe i misse...",-1,55
4067,691633,3539,0,"Por el correo que me has enviado, vuelvo a seg...",-1,55
6180,1084285,3748,0,Hi all - Really nice to see that the cats will...,-1,55

In [43]:
sample_thread_df.columns

Index(['Unnamed: 0', 'projectID', 'thread_id', 'group', 'comment_ids',
       'n_comments', 'merged_comment', 'creator_id', 'is_pledge_master',
       'is_backer', 'is_prior_backer', 'is_pathfinder', 'topic_original',
       'was_outlier', 'topic_reassigned', 'topic_final', 'was_reassigned'],
      dtype='object')

In [44]:
print("topics:", len(topics))

try:
    print("new_topics:", len(new_topics))
except:
    print("new_topics 없음")

topics: 73438
new_topics 없음

In [33]:
topic_model_final.get_topic_info().head()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,31001,-1_the_to_and_of,"[the, to, and, of, it, you, in, that, for, is]","[As a total stalker-lore fan, who discovered v..."
1,0,2151,0_solo_mode_player_players,"[solo, mode, player, players, play, coop, co, ...","[Can we get a solo mode? :D, +1 for a solo mod..."
2,1,1884,1_excited_game_wait_this,"[excited, game, wait, this, looks, forward, th...",[This game looks awesome. Can't wait to get i...
3,2,1166,2_dc_batman_marvel_united,"[dc, batman, marvel, united, villains, charact...",[This will upset people but I'm Only here for ...
4,3,1102,3_shipping_eu_china_cost,"[shipping, eu, china, cost, costs, australia, ...",[Why for the love of everything holy is shippi...

In [34]:
# 5. BERTopic 결과 저장
sample_thread_df.to_csv(
    "comment_bertopic_thread_result.csv",
    index=False,
    encoding="utf-8-sig"
)

topic_info = topic_model_final.get_topic_info()

topic_info.to_csv(
    "bertopic_topic_info.csv",
    index=False,
    encoding="utf-8-sig"
)

display(topic_info.head(20))

,Topic,Count,Name,Representation,Representative_Docs
0,-1,31001,-1_the_to_and_of,"[the, to, and, of, it, you, in, that, for, is]","[As a total stalker-lore fan, who discovered v..."
1,0,2151,0_solo_mode_player_players,"[solo, mode, player, players, play, coop, co, ...","[Can we get a solo mode? :D, +1 for a solo mod..."
2,1,1884,1_excited_game_wait_this,"[excited, game, wait, this, looks, forward, th...",[This game looks awesome. Can't wait to get i...
3,2,1166,2_dc_batman_marvel_united,"[dc, batman, marvel, united, villains, charact...",[This will upset people but I'm Only here for ...
4,3,1102,3_shipping_eu_china_cost,"[shipping, eu, china, cost, costs, australia, ...",[Why for the love of everything holy is shippi...
5,4,1011,4_price_expensive_game_base,"[price, expensive, game, base, cost, this, is,...",[1. Lower the price 2. offer a less expensive ...
6,5,936,5_stretch_goals_goal_daily,"[stretch, goals, goal, daily, unlocked, unlock...",[Will there be stretch goals or what we see is...
7,6,864,6_playmat_mat_neoprene_mats,"[playmat, mat, neoprene, mats, playmats, board...",[Interesting to see the game mat being so expe...
8,7,863,7_sleeves_sleeved_sleeve_cards,"[sleeves, sleeved, sleeve, cards, fit, insert,...",[Will you offer card sleeves? And does the in...
9,8,832,8_launch_date_when_start,"[launch, date, when, start, campaign, live, se...",[When?|We didn't share the launch date yet. So...
10,9,813,9_tiles_boards_board_tile,"[tiles, boards, board, tile, player, layer, du...","[Please please PLEASE, don't go to much overbo..."
11,10,758,10_box_boxes_big_storage,"[box, boxes, big, storage, fit, solution, ever...",[I'm just adding to the crowd request for a bi...
12,11,751,11_pledge_all_add_apocalypse,"[pledge, all, add, apocalypse, ons, in, new, e...",[#question I pledged the Reprint All-In ($340....
13,12,715,12_standees_minis_standee_acrylic,"[standees, minis, standee, acrylic, miniatures...",[Would the special edition include cardboard s...
14,13,667,13_delivery_date_2025_2024,"[delivery, date, 2025, 2024, estimated, months...",[What is the estimated delivery date of this c...
15,14,605,14_vat_eu_tax_pay,"[vat, eu, tax, pay, uk, taxes, shipping, sales...",[We are one of the first companies having to t...
16,15,603,15_sundrop_minis_paint_sundropped,"[sundrop, minis, paint, sundropped, wash, opti...","[Will there be sundrop?|+1|+1, Some miniatures..."
17,16,602,16_spanish_español_en_please,"[spanish, español, en, please, favor, por, ver...","[Spanish?, Spanish?, #spanish spanish please !!!]"
18,17,557,17_free_pledge_48_bird,"[free, pledge, 48, bird, early, gift, hours, f...",[Hmmm... The Renegade Hunter was not added to ...
19,18,531,18_italian_language_please_italiano,"[italian, language, please, italiano, translat...","[#italian Italian language, please!! 🇮🇹, Itali..."

BERTopic-hierarchical_topics(): BERTopic이 토픽 간 유사도 계산하여 계층구조 생성

In [35]:
hierarchical_topics = topic_model_final.hierarchical_topics(texts)

100%|██████████| 191/191 [00:01<00:00, 159.18it/s]

In [36]:
topic_model_final.visualize_hierarchy()

In [37]:
hierarchical_topics.head()
print(hierarchical_topics.columns.tolist())

['Parent_ID', 'Parent_Name', 'Topics', 'Child_Left_ID', 'Child_Left_Name', 'Child_Right_ID', 'Child_Right_Name', 'Distance']

In [45]:
sample_thread_df["topic_original"] = sample_thread_df["topic_original"]
sample_thread_df["topic_final"] = sample_thread_df["topic_final"]

In [46]:
print("전체 행 수:", len(sample_thread_df))
print("topics 길이:", len(topics))
print("topic_final 결측:", sample_thread_df["topic_final"].isna().sum())

print("original -1 개수:", (sample_thread_df["topic_original"] == -1).sum())
print("final -1 개수:", (sample_thread_df["topic_final"] == -1).sum())
print("final -1 비율:", round((sample_thread_df["topic_final"] == -1).mean() * 100, 2), "%")

전체 행 수: 73438
topics 길이: 73438
topic_final 결측: 0
original -1 개수: 27948
final -1 개수: 0
final -1 비율: 0.0 %

In [47]:
sample_thread_df.to_csv(
    "comment_bertopic_thread_result_with_outlier_reduction.csv",
    index=False,
    encoding="utf-8-sig"
)

topic 20개로 압축 후 병합

In [48]:
# 1. hierarchy 복사

hier_df_20 = hierarchical_topics.copy()

def parse_topics_20(x):
    if isinstance(x, list):
        return x
    if isinstance(x, str):
        return ast.literal_eval(x)
    return x

hier_df_20["Topics_parsed"] = hier_df_20["Topics"].apply(parse_topics_20)
hier_df_20["Topics_set"] = hier_df_20["Topics_parsed"].apply(lambda x: frozenset(x))


# 2. 원본 토픽 목록 준비

base_topics_20 = sorted(
    topic_info_final_view[
        topic_info_final_view["Topic"] != -1
    ]["Topic"].tolist()
)

clusters_20 = [frozenset([t]) for t in base_topics_20]


# 3. BERTopic hierarchy 기준으로 20개가 될 때까지 병합

hier_df_sorted_20 = hier_df_20.sort_values("Distance", ascending=True)

for _, row in hier_df_sorted_20.iterrows():
    parent_set = row["Topics_set"]

    child_clusters = [
        c for c in clusters_20
        if c.issubset(parent_set)
    ]

    union_set = (
        frozenset().union(*child_clusters)
        if child_clusters
        else frozenset()
    )

    if union_set == parent_set and len(child_clusters) >= 2:
        clusters_20 = [
            c for c in clusters_20
            if c not in child_clusters
        ]

        clusters_20.append(parent_set)

    if len(clusters_20) == 20:
        break

print("현재 cluster 개수:", len(clusters_20))


# 4. 20개 MetaTopic 매핑표 생성

meta_rows_20 = []

for i, topic_set in enumerate(clusters_20, start=1):
    for topic in topic_set:
        meta_rows_20.append({
            "MetaTopic_20": i,
            "Topic": topic
        })

topic_meta_map_20 = pd.DataFrame(meta_rows_20)


# 5. topic_info_final_view와 병합

topic_meta_view_20 = topic_info_final_view.merge(
    topic_meta_map_20,
    on="Topic",
    how="left"
)

topic_meta_view_20[
    ["MetaTopic_20", "Topic", "Count_final", "Name", "Representation"]
].sort_values(
    ["MetaTopic_20", "Count_final"],
    ascending=[True, False]
)

현재 cluster 개수: 20

,MetaTopic_20,Topic,Count_final,Name,Representation
71,1.0,70,333,70_polish_language_version_poland,"[polish, language, version, poland, we, transl..."
83,1.0,82,209,82_polish_language_version_poland,"[polish, language, version, poland, please, ch..."
19,2.0,18,647,18_italian_language_please_italiano,"[italian, language, please, italiano, translat..."
37,2.0,36,474,36_italian_language_translation_languages,"[italian, language, translation, languages, it..."
166,3.0,165,212,165_backer_number_got_congrats,"[backer, number, got, congrats, seconds, damn,..."
...,...,...,...,...,...
142,20.0,141,88,141_mystica_terra_innovation_gaia,"[mystica, terra, innovation, gaia, tm, age, ao..."
170,20.0,169,87,169_vindication_vestige_neb_small,"[vindication, vestige, neb, small, oneb, compa..."
173,20.0,172,85,172_assent_stormsunder_wild_hunt,"[assent, stormsunder, wild, hunt, rising, lavo..."
187,20.0,186,80,186_1643_monolith_claustrophobia_demons,"[1643, monolith, claustrophobia, demons, style..."
0,NaN,-1,0,-1_the_to_and_of,"[the, to, and, of, it, you, in, that, for, is]"

In [49]:
for mt in sorted(topic_meta_view_20["MetaTopic_20"].dropna().unique()):
    print("=" * 80)
    print(f"MetaTopic {mt}")

    display(
        topic_meta_view_20[
            topic_meta_view_20["MetaTopic_20"] == mt
        ][
            ["Topic", "Count_final", "Name", "Representation"]
        ].sort_values("Count_final", ascending=False).head(15)
    )

================================================================================
MetaTopic 1.0

,Topic,Count_final,Name,Representation
71,70,333,70_polish_language_version_poland,"[polish, language, version, poland, we, transl..."
83,82,209,82_polish_language_version_poland,"[polish, language, version, poland, please, ch..."

================================================================================
MetaTopic 2.0

,Topic,Count_final,Name,Representation
19,18,647,18_italian_language_please_italiano,"[italian, language, please, italiano, translat..."
37,36,474,36_italian_language_translation_languages,"[italian, language, translation, languages, it..."

================================================================================
MetaTopic 3.0

,Topic,Count_final,Name,Representation
166,165,212,165_backer_number_got_congrats,"[backer, number, got, congrats, seconds, damn,..."
155,154,127,154_backer_woohoo_33rd_damn,"[backer, woohoo, 33rd, damn, club, 666, report..."

================================================================================
MetaTopic 4.0

,Topic,Count_final,Name,Representation
17,16,734,16_spanish_español_en_please,"[spanish, español, en, please, favor, por, ver..."
35,34,593,34_spanish_español_en_que,"[spanish, español, en, que, juego, el, maldito..."
120,119,322,119_spanish_french_yourlanguage_luis2023,"[spanish, french, yourlanguage, luis2023, birc..."

================================================================================
MetaTopic 5.0

,Topic,Count_final,Name,Representation
36,35,524,35_german_version_frosted_translation,"[german, version, frosted, translation, langua..."
38,37,391,37_german_version_please_translation,"[german, version, please, translation, languag..."
93,92,281,92_german_language_pack_translated,"[german, language, pack, translated, translati..."
131,130,111,130_spieleschmiede_german_spiele_offensive,"[spieleschmiede, german, spiele, offensive, sc..."

================================================================================
MetaTopic 6.0

,Topic,Count_final,Name,Representation
86,85,169,85_und_die_das_ich,"[und, die, das, ich, auch, der, nicht, es, ist..."
124,123,142,123_essen_spiel_booth_auf,"[essen, spiel, booth, auf, at, year, der, uns,..."
171,170,79,170_essen_pickup_spiel_pick,"[essen, pickup, spiel, pick, option, das, der,..."

================================================================================
MetaTopic 7.0

,Topic,Count_final,Name,Representation
57,56,528,56_hype_omg_lets_gooooo,"[hype, omg, lets, gooooo, oh, let, yes, meow, ..."
177,176,171,176_let_go_lets_gooooooooo,"[let, go, lets, gooooooooo, ho, goooooo, goooo..."
146,145,128,145_go_let_lets_here,"[go, let, lets, here, again, we, woohoo, marti..."

================================================================================
MetaTopic 8.0

,Topic,Count_final,Name,Representation
10,9,1403,9_tiles_boards_board_tile,"[tiles, boards, board, tile, player, layer, du..."
43,42,575,42_tokens_plastic_wood_wooden,"[tokens, plastic, wood, wooden, cardboard, acr..."
107,106,260,106_tiles_acrylic_hexes_cardboard,"[tiles, acrylic, hexes, cardboard, 3d, hex, ba..."
78,77,176,77_stickers_tiles_acrylic_text,"[stickers, tiles, acrylic, text, english, lang..."
114,113,127,113_stickers_reusable_eternal_reset,"[stickers, reusable, eternal, reset, map, stic..."
130,129,119,129_acrylic_fit_tiles_insert,"[acrylic, fit, tiles, insert, cardboard, token..."
192,191,107,191_tiles_bags_tile_hex,"[tiles, bags, tile, hex, bag, bakelite, holes,..."

================================================================================
MetaTopic 9.0

,Topic,Count_final,Name,Representation
2,1,2971,1_excited_game_wait_this,"[excited, game, wait, this, looks, forward, th..."
29,28,690,28_campaign_luck_thank_excited,"[campaign, luck, thank, excited, support, good..."
80,79,497,79_excited_wait_looks_this,"[excited, wait, looks, this, cant, fantastic, ..."
92,91,486,91_welcome_back_happy_glad,"[welcome, back, happy, glad, here, aboard, exc..."
54,53,392,53_wait_forward_cant_can,"[wait, forward, cant, can, looking, cannot, do..."
185,184,378,184_expansion_forward_looking_apartment,"[expansion, forward, looking, apartment, expan..."
141,140,254,140_pledge_pledged_pact_thank,"[pledge, pledged, pact, thank, promised, welco..."

================================================================================
MetaTopic 10.0

,Topic,Count_final,Name,Representation
9,8,1072,8_launch_date_when_start,"[launch, date, when, start, campaign, live, se..."
14,13,828,13_delivery_date_2025_2024,"[delivery, date, 2025, 2024, estimated, months..."
61,60,612,60_update_updates_week_next,"[update, updates, week, next, today, soon, com..."
50,49,348,49_tracking_received_frosted_yun,"[tracking, received, frosted, yun, ctg, usps, ..."
96,95,295,95_email_sent_replacement_ticket,"[email, sent, replacement, ticket, received, m..."
48,47,280,47_retailer_retailers_retail_group,"[retailer, retailers, retail, group, pledge, c..."
77,76,194,76_wave_split_shipping_single,"[wave, split, shipping, single, waves, core, 2..."
184,183,146,183_prices_pricing_launch_tiers,"[prices, pricing, launch, tiers, before, pledg..."
100,99,122,99_tanares_odalin_dragori_delivered,"[tanares, odalin, dragori, delivered, translat..."
127,126,111,126_address_support_chiptheorygames_ticket,"[address, support, chiptheorygames, ticket, ch..."
139,138,106,138_portal_robinson_rc_crusoe,"[portal, robinson, rc, crusoe, 2023, eproofs, ..."

================================================================================
MetaTopic 11.0

,Topic,Count_final,Name,Representation
4,3,1541,3_shipping_eu_china_cost,"[shipping, eu, china, cost, costs, australia, ..."
25,24,773,24_shipping_group_copies_cost,"[shipping, group, copies, cost, pledge, multip..."
15,14,721,14_vat_eu_tax_pay,"[vat, eu, tax, pay, uk, taxes, shipping, sales..."
34,33,373,33_canada_shipping_canadian_friendly,"[canada, shipping, canadian, friendly, canadia..."
89,88,247,88_price_expensive_insane_prices,"[price, expensive, insane, prices, pricing, ou..."
188,187,243,187_vat_price_retail_ps5,"[vat, price, retail, ps5, shipping, expensive,..."
143,142,137,142_price_pricing_much_cost,"[price, pricing, much, cost, how, yet, any, id..."
186,185,115,185_vat_shipping_price_60chf,"[vat, shipping, price, 60chf, high, 300, eu, e..."

================================================================================
MetaTopic 12.0

,Topic,Count_final,Name,Representation
27,26,491,26_dice_tray_tower_roll,"[dice, tray, tower, roll, alloy, they, leather..."
42,41,420,41_ctg_cloudspire_tmb_theory,"[ctg, cloudspire, tmb, theory, elder, scrolls,..."
63,62,249,62_decks_deck_personalized_starter,"[decks, deck, personalized, starter, keyforge,..."
73,72,243,72_chip_flip_chips_side,"[chip, flip, chips, side, used, dice, theory, ..."
60,59,202,59_strategist_strategists_pledge_ctg,"[strategist, strategists, pledge, ctg, email, ..."
70,69,166,69_dice_smell_ctg_flakes,"[dice, smell, ctg, flakes, quality, my, issues..."
115,114,135,114_keyforge_decks_gg_woe,"[keyforge, decks, gg, woe, galaxy, ghost, stor..."
116,115,120,115_victorum_remastered_pandora_hoplomachus,"[victorum, remastered, pandora, hoplomachus, c..."
169,168,108,168_sentinels_solar_20_dice,"[sentinels, solar, 20, dice, strong, tmb, deck..."
191,190,80,190_ctg_congratulations_congrats_million,"[ctg, congratulations, congrats, million, incr..."
180,179,70,179_strong_20_deck_cloudspire,"[strong, 20, deck, cloudspire, tanglewoods, ne..."

================================================================================
MetaTopic 13.0

,Topic,Count_final,Name,Representation
11,10,1477,10_box_boxes_big_storage,"[box, boxes, big, storage, fit, solution, ever..."
7,6,995,6_playmat_mat_neoprene_mats,"[playmat, mat, neoprene, mats, playmats, board..."
8,7,915,7_sleeves_sleeved_sleeve_cards,"[sleeves, sleeved, sleeve, cards, fit, insert,..."
46,45,329,45_kallax_box_dimensions_size,"[kallax, box, dimensions, size, fit, storage, ..."
52,51,252,51_trove_chest_trays_gearloc,"[trove, chest, trays, gearloc, tyrant, storage..."
69,68,189,68_rift_emperor_elemental_chest,"[rift, emperor, elemental, chest, uprising, re..."
123,122,142,122_fit_box_playmat_mats,"[fit, box, playmat, mats, mat, neoprene, playm..."
103,102,123,102_unbreakable_undertow_gearlocs_base,"[unbreakable, undertow, gearlocs, base, tmb, 4..."

================================================================================
MetaTopic 14.0

,Topic,Count_final,Name,Representation
65,64,418,64_looks_cool_interesting_awesome,"[looks, cool, interesting, awesome, great, ama..."
68,67,374,67_art_love_artwork_looks,"[art, love, artwork, looks, style, artist, cov..."
168,167,262,167_art_movie_artwork_stills,"[art, movie, artwork, stills, looks, ich, die,..."
182,181,219,181_looks_interesting_nice_thank,"[looks, interesting, nice, thank, thanks, incr..."
164,163,170,163_cover_art_box_deluxe,"[cover, art, box, deluxe, inside, artwork, fon..."

================================================================================
MetaTopic 15.0

,Topic,Count_final,Name,Representation
12,11,1502,11_pledge_all_add_apocalypse,"[pledge, all, add, apocalypse, ons, in, new, e..."
6,5,1092,5_stretch_goals_goal_daily,"[stretch, goals, goal, daily, unlocked, unlock..."
82,81,729,81_available_campaign_base_previous,"[available, campaign, base, previous, first, w..."
39,38,704,38_retail_exclusive_available_gamefound,"[retail, exclusive, available, gamefound, will..."
91,90,610,90_edition_upgrade_1st_pack,"[edition, upgrade, 1st, pack, owners, kit, upd..."
33,32,584,32_goals_stretch_exclusive_retail,"[goals, stretch, exclusive, retail, included, ..."
41,40,436,40_manager_available_pledge_add,"[manager, available, pledge, add, promo, pm, o..."
30,29,414,29_foil_ascension_ultimate_collector,"[foil, ascension, ultimate, collector, center,..."
67,66,399,66_stretch_goal_goals_would,"[stretch, goal, goals, would, stretchgoal, sug..."
81,80,394,80_islebound_caravan_creature_roam,"[islebound, caravan, creature, roam, below, ab..."
90,89,347,89_errata_pack_printing_cards,"[errata, pack, printing, cards, updated, ruleb..."
79,78,269,78_army_queen_feudum_ramparts,"[army, queen, feudum, ramparts, rudders, vesse..."
105,104,198,104_coins_metal_coin_add,"[coins, metal, coin, add, standard, an, embroi..."
150,149,156,149_tainted_grail_upgrade_pack,"[tainted, grail, upgrade, pack, upgradepack, e..."
133,132,137,132_city_tales_siege_ruined,"[city, tales, siege, ruined, heart, tactics, e..."

================================================================================
MetaTopic 16.0

,Topic,Count_final,Name,Representation
21,20,679,20_french_version_française_une,"[french, version, française, une, please, tran..."
56,55,604,55_french_version_le_de,"[french, version, le, de, la, en, pour, est, p..."
49,48,486,48_pdf_language_text_en,"[pdf, language, text, en, english, french, ind..."
151,150,417,150_english_french_languages_en,"[english, french, languages, en, le, anglais, ..."
53,52,301,52_language_manager_select_pledge,"[language, manager, select, pledge, el, choose..."
106,105,288,105_english_languages_only_spanish,"[english, languages, only, spanish, polish, fr..."
119,118,198,118_languages_language_idiomas_available,"[languages, language, idiomas, available, pl, ..."
121,120,168,120_french_version_game_jeux,"[french, version, game, jeux, sortent, le, hel..."
112,111,160,111_english_language_languages_months,"[english, language, languages, months, version..."

================================================================================
MetaTopic 17.0

,Topic,Count_final,Name,Representation
22,21,789,21_video_youtube_videos_gameplay,"[video, youtube, videos, gameplay, watch, http..."
40,39,379,39_rulebook_rules_download_link,"[rulebook, rules, download, link, draft, page,..."
174,173,244,173_rulebook_rule_book_rules,"[rulebook, rule, book, rules, updated, been, i..."
66,65,218,65_tts_simulator_tabletop_mod,"[tts, simulator, tabletop, mod, demo, tabletop..."
149,148,203,148_rulebook_updated_printed_book,"[rulebook, updated, printed, book, rule, rules..."
95,94,153,94_forteller_narration_audio_app,"[forteller, narration, audio, app, foreteller,..."
126,125,139,125_app_digital_storybook_book,"[app, digital, storybook, book, apps, physical..."
176,175,103,175_rolling_solo_playthrough_video,"[rolling, solo, playthrough, video, stop, shop..."

================================================================================
MetaTopic 18.0

,Topic,Count_final,Name,Representation
18,17,848,17_free_pledge_48_bird,"[free, pledge, 48, bird, early, gift, hours, f..."
20,19,555,19_pay_stretch_stretchpay_payments,"[pay, stretch, stretchpay, payments, payment, ..."
32,31,476,31_access_pledge_manager_pm,"[access, pledge, manager, pm, gamefound, late,..."
87,86,275,86_cancel_charged_pledge_paypal,"[cancel, charged, pledge, paypal, payment, edi..."
109,108,273,108_error_pledge_my_fixed,"[error, pledge, my, fixed, try, bug, add, issu..."
140,139,243,139_morning_tomorrow_sleep_night,"[morning, tomorrow, sleep, night, questions, d..."
134,133,178,133_pledge_upgrade_manager_pm,"[pledge, upgrade, manager, pm, change, yes, la..."
88,87,170,87_paypal_payment_credit_bank,"[paypal, payment, credit, bank, card, gamefoun..."
159,158,150,158_late_pledge_yes_pledges,"[late, pledge, yes, pledges, manager, will, ca..."
145,144,126,144_open_manager_pm_long,"[open, manager, pm, long, late, months, pledge..."
157,156,120,156_bug_follow_following_project,"[bug, follow, following, project, visual, proj..."
183,182,97,182_currency_usd_dollars_euros,"[currency, usd, dollars, euros, eur, conversio..."
178,177,63,177_night_deck_48h_24107,"[night, deck, 48h, 24107, redzen, 1920, scarfa..."

================================================================================
MetaTopic 19.0

,Topic,Count_final,Name,Representation
26,25,618,25_funded_congrats_congratulations_thank,"[funded, congrats, congratulations, thank, fun..."
64,63,549,63_banned_pentaquark_handsome_books,"[banned, pentaquark, handsome, books, shy, tur..."
45,44,389,44_money_take_wallet_my,"[money, take, wallet, my, shut, up, ready, wal..."
118,117,338,117_fog_countdown_coming_almost,"[fog, countdown, coming, almost, final, close,..."
59,58,289,58_minutes_hours_go_hour,"[minutes, hours, go, hour, left, mins, days, m..."
129,128,282,128_typo_typos_spelling_page,"[typo, typos, spelling, page, spelled, says, m..."
189,188,251,188_arrived_hypeeee_first_pokładzie,"[arrived, hypeeee, first, pokładzie, jestem, c..."
58,57,215,57_vfi_asia_south_africa,"[vfi, asia, south, africa, shipping, using, in..."
117,116,205,116_followers_backers_1000_000,"[followers, backers, 1000, 000, follower, wow,..."
72,71,200,71_brazil_ship_shipping_brasil,"[brazil, ship, shipping, brasil, brazilian, nã..."
122,121,194,121_woot_all_in_im,"[woot, all, in, im, mine, am, innnnnnnnnnnnnnn..."
162,161,193,161_realms_awaken_lite_elera,"[realms, awaken, lite, elera, games, my, proje..."
158,157,185,157_mexico_america_south_ship,"[mexico, america, south, ship, shipping, argen..."
125,124,148,124_war_hoi_spain_sweden,"[war, hoi, spain, sweden, poland, ww2, nations..."
104,103,135,103_hellas_lords_loh_ragnarok,"[hellas, lords, loh, ragnarok, ar_alicja, repr..."

================================================================================
MetaTopic 20.0

,Topic,Count_final,Name,Representation
1,0,2326,0_solo_mode_player_players,"[solo, mode, player, players, play, coop, co, ..."
5,4,1842,4_price_expensive_game_base,"[price, expensive, game, base, cost, this, is,..."
3,2,1548,2_dc_batman_marvel_united,"[dc, batman, marvel, united, villains, charact..."
44,43,1033,43_boss_difficulty_attack_action,"[boss, difficulty, attack, action, you, combat..."
74,73,952,73_cards_faction_new_art,"[cards, faction, new, art, player, expansion, ..."
13,12,852,12_standees_minis_standee_acrylic,"[standees, minis, standee, acrylic, miniatures..."
75,74,699,74_projects_communication_company_project,"[projects, communication, company, project, ga..."
24,23,692,23_gamefound_kickstarter_comments_platform,"[gamefound, kickstarter, comments, platform, k..."
16,15,669,15_sundrop_minis_paint_sundropped,"[sundrop, minis, paint, sundropped, wash, opti..."
28,27,663,27_scenarios_story_scenario_each,"[scenarios, story, scenario, each, hours, play..."
137,136,619,136_skyrim_eso_game_elder,"[skyrim, eso, game, elder, scrolls, rpg, like,..."
23,22,607,22_zombicide_fantasy_asmodee_zombies,"[zombicide, fantasy, asmodee, zombies, cmon, s..."
76,75,503,75_abomination_pirate_pirates_kraken,"[abomination, pirate, pirates, kraken, zombies..."
101,100,451,100_looks_mini_claudyne_look,"[looks, mini, claudyne, look, pose, art, minis..."
55,54,447,54_meeple_meeples_miniatures_version,"[meeple, meeples, miniatures, version, minis, ..."

In [50]:
# =========================
# 2. 7개 최종 카테고리 생성
# =========================

topic_category_df = topic_meta_view_20.copy()

topic_category_df["FinalCategory"] = "Other"

In [51]:
# =========================
# 3. MetaTopic 기준 1차 분류
# =========================

meta_to_final_category = {
    # 1. Language & Localization
    1: "Language & Localization",    # Polish
    2: "Language & Localization",    # Italian
    4: "Language & Localization",    # Spanish
    5: "Language & Localization",    # German
    6: "Language & Localization",    # German / Essen
    16: "Language & Localization",   # French / English / language

    # 2. Community Reaction
    3: "Community Reaction",         # backer number / congrats
    7: "Community Reaction",         # hype / let's go
    9: "Community Reaction",         # excited / wait / welcome
    14: "Community Reaction",        # looks / art / cool

    # 3. Components & Production
    8: "Components & Production",    # tiles / boards / tokens
    12: "Components & Production",   # dice / chip / decks / CTG-specific components
    13: "Components & Production",   # box / playmat / sleeves / storage

    # 4. Shipping / Price / Tax
    11: "Shipping / Price / Tax",    # shipping / VAT / price

    # 5. Campaign / Pledge
    15: "Campaign / Pledge",         # pledge / stretch goals / add-ons / retail
    18: "Campaign / Pledge",         # pledge manager / payment / late pledge

    # 6. Schedule / Updates
    10: "Schedule / Updates",        # launch / delivery / update / tracking

    # 7. Gameplay / Rules / Content
    17: "Gameplay / Rules / Content", # rulebook / video / TTS / app
    20: "Gameplay / Rules / Content"  # game-specific titles / content
}

topic_category_df["FinalCategory"] = (
    topic_category_df["MetaTopic_20"]
    .map(meta_to_final_category)
    .fillna("Other")
)

In [52]:
# =========================
# 4. 토픽 단위 수동 재분류
# =========================
# MetaTopic으로 크게 묶은 뒤, 이상하게 들어간 토픽만 여기서 덮어쓰기

manual_topic_to_final_category = {
    # 예시: price가 campaign 쪽에 들어갔으면 비용 쪽으로 이동
    4: "Shipping / Price / Tax",       # price_expensive_game_base

    # solo mode는 gameplay
    0: "Gameplay / Rules / Content",   # solo_mode_player_players

    # DC/Batman/Marvel 같은 IP/캐릭터 토픽은 content
    2: "Gameplay / Rules / Content",   # dc_batman_marvel_united

    # standees/minis는 구성품
    12: "Components & Production",     # standees_minis_standee_acrylic
    15: "Components & Production",     # sundrop_minis_paint_sundropped

    # delivery date는 일정/업데이트
    13: "Schedule / Updates",          # delivery_date_2025_2024

    # launch date도 일정/업데이트
    8: "Schedule / Updates",           # launch_date_when_start

    # VAT는 비용/배송/세금
    14: "Shipping / Price / Tax",      # vat_eu_tax_pay

    # shipping은 비용/배송/세금
    3: "Shipping / Price / Tax",       # shipping_eu_china_cost
}

for topic, category in manual_topic_to_final_category.items():
    topic_category_df.loc[
        topic_category_df["Topic"] == topic,
        "FinalCategory"
    ] = category

In [53]:
# =========================
# 5. 최종 확인
# =========================

display(
    topic_category_df[
        ["MetaTopic_20", "Topic", "Count_final", "Name", "FinalCategory"]
    ]
    .sort_values(
        ["FinalCategory", "Count_final"],
        ascending=[True, False]
    )
)

print("카테고리별 토픽 수")
display(topic_category_df["FinalCategory"].value_counts())

print("카테고리별 댓글 수")
display(
    topic_category_df
    .groupby("FinalCategory")["Count_final"]
    .sum()
    .sort_values(ascending=False)
)

,MetaTopic_20,Topic,Count_final,Name,FinalCategory
12,15.0,11,1502,11_pledge_all_add_apocalypse,Campaign / Pledge
6,15.0,5,1092,5_stretch_goals_goal_daily,Campaign / Pledge
18,18.0,17,848,17_free_pledge_48_bird,Campaign / Pledge
82,15.0,81,729,81_available_campaign_base_previous,Campaign / Pledge
39,15.0,38,704,38_retail_exclusive_available_gamefound,Campaign / Pledge
...,...,...,...,...,...
34,11.0,33,373,33_canada_shipping_canadian_friendly,Shipping / Price / Tax
89,11.0,88,247,88_price_expensive_insane_prices,Shipping / Price / Tax
188,11.0,187,243,187_vat_price_retail_ps5,Shipping / Price / Tax
143,11.0,142,137,142_price_pricing_much_cost,Shipping / Price / Tax
186,11.0,185,115,185_vat_shipping_price_60chf,Shipping / Price / Tax

카테고리별 토픽 수

FinalCategory
Gameplay / Rules / Content    51
Campaign / Pledge             32
Components & Production       28
Language & Localization       23
Other                         22
Community Reaction            17
Schedule / Updates            11
Shipping / Price / Tax         9
Name: count, dtype: int64

카테고리별 댓글 수

FinalCategory
Gameplay / Rules / Content    18895
Campaign / Pledge             11970
Components & Production       10994
Language & Localization        8310
Community Reaction             8277
Shipping / Price / Tax         5992
Other                          4886
Schedule / Updates             4114
Name: Count_final, dtype: int64

In [54]:
# 누락된 토픽 확인
unassigned_topics = topic_category_df[
    (topic_category_df["Topic"] != -1) &
    (
        (topic_category_df["FinalCategory"].isna()) |
        (topic_category_df["FinalCategory"] == "Other")
    )
][
    [
        "Topic",
        "Count_final",
        "Name",
        "Representation",
        "MetaTopic_20"
    ]
].sort_values(
    "Count_final",
    ascending=False
)

display(unassigned_topics)

,Topic,Count_final,Name,Representation,MetaTopic_20
26,25,618,25_funded_congrats_congratulations_thank,"[funded, congrats, congratulations, thank, fun...",19.0
64,63,549,63_banned_pentaquark_handsome_books,"[banned, pentaquark, handsome, books, shy, tur...",19.0
45,44,389,44_money_take_wallet_my,"[money, take, wallet, my, shut, up, ready, wal...",19.0
118,117,338,117_fog_countdown_coming_almost,"[fog, countdown, coming, almost, final, close,...",19.0
59,58,289,58_minutes_hours_go_hour,"[minutes, hours, go, hour, left, mins, days, m...",19.0
129,128,282,128_typo_typos_spelling_page,"[typo, typos, spelling, page, spelled, says, m...",19.0
189,188,251,188_arrived_hypeeee_first_pokładzie,"[arrived, hypeeee, first, pokładzie, jestem, c...",19.0
58,57,215,57_vfi_asia_south_africa,"[vfi, asia, south, africa, shipping, using, in...",19.0
117,116,205,116_followers_backers_1000_000,"[followers, backers, 1000, 000, follower, wow,...",19.0
72,71,200,71_brazil_ship_shipping_brasil,"[brazil, ship, shipping, brasil, brazilian, nã...",19.0
122,121,194,121_woot_all_in_im,"[woot, all, in, im, mine, am, innnnnnnnnnnnnnn...",19.0
162,161,193,161_realms_awaken_lite_elera,"[realms, awaken, lite, elera, games, my, proje...",19.0
158,157,185,157_mexico_america_south_ship,"[mexico, america, south, ship, shipping, argen...",19.0
125,124,148,124_war_hoi_spain_sweden,"[war, hoi, spain, sweden, poland, ww2, nations...",19.0
104,103,135,103_hellas_lords_loh_ragnarok,"[hellas, lords, loh, ragnarok, ar_alicja, repr...",19.0
179,178,134,178_bgg_boardgamegeek_page_entry,"[bgg, boardgamegeek, page, entry, com, https, ...",19.0
98,97,134,97_czech_language_cz_slovak,"[czech, language, cz, slovak, please, localiza...",19.0
113,112,132,112_chinese_version_agent_wanna,"[chinese, version, agent, wanna, language, par...",19.0
152,151,104,151_16_de_joueurs_paladins,"[16, de, joueurs, paladins, et, paladin, les, ...",19.0
132,131,99,131_russia_russian_ukraine_war,"[russia, russian, ukraine, war, government, co...",19.0
138,137,92,137_ukrainian_ukraine_russian_localization,"[ukrainian, ukraine, russian, localization, la...",19.0

In [55]:
# =========================
# MetaTopic 19 수동 재분류
# =========================

manual_topic_to_final_category.update({
    # Community Reaction
    25: "Community Reaction",   # funded / congrats
    44: "Community Reaction",   # money / wallet / shut up and take my money
    117: "Community Reaction",  # countdown / coming / almost
    58: "Community Reaction",   # minutes / hours left
    188: "Community Reaction",  # arrived / hype
    116: "Community Reaction",  # followers / backers milestone
    121: "Community Reaction",  # woot / all-in
    63: "Community Reaction",   # meme-like / off-topic excitement

    # Shipping / Price / Tax
    57: "Shipping / Price / Tax",   # Asia / South Africa shipping
    71: "Shipping / Price / Tax",   # Brazil shipping
    157: "Shipping / Price / Tax",  # Mexico / South America shipping

    # Language & Localization
    97: "Language & Localization",   # Czech / Slovak
    112: "Language & Localization",  # Chinese version
    137: "Language & Localization",  # Ukrainian localization
    151: "Language & Localization",  # French text / players

    # Gameplay / Rules / Content
    161: "Gameplay / Rules / Content",  # Realms Awaken / project-specific
    124: "Gameplay / Rules / Content",  # war / nations / theme
    103: "Gameplay / Rules / Content",  # Lords of Hellas / Ragnarok
    178: "Gameplay / Rules / Content",  # BGG page / boardgame info
    131: "Gameplay / Rules / Content",  # Russia / Ukraine / war theme

    # Schedule / Updates
    128: "Schedule / Updates",  # typo / spelling / page correction
})

In [56]:
for topic, category in manual_topic_to_final_category.items():
    topic_category_df.loc[
        topic_category_df["Topic"] == topic,
        "FinalCategory"
    ] = category

In [57]:
print("카테고리별 토픽 수")
display(topic_category_df["FinalCategory"].value_counts())

print("카테고리별 댓글 수")
display(
    topic_category_df
    .groupby("FinalCategory")["Count_final"]
    .sum()
    .sort_values(ascending=False)
)

print("Other 남은 토픽")
display(
    topic_category_df[
        topic_category_df["FinalCategory"] == "Other"
    ][["Topic", "Count_final", "Name", "Representation", "MetaTopic_20"]]
    .sort_values("Count_final", ascending=False)
)

카테고리별 토픽 수

FinalCategory
Gameplay / Rules / Content    56
Campaign / Pledge             32
Components & Production       28
Language & Localization       27
Community Reaction            25
Shipping / Price / Tax        12
Schedule / Updates            12
Other                          1
Name: count, dtype: int64

카테고리별 댓글 수

FinalCategory
Gameplay / Rules / Content    19604
Campaign / Pledge             11970
Community Reaction            11110
Components & Production       10994
Language & Localization        8772
Shipping / Price / Tax         6592
Schedule / Updates             4396
Other                             0
Name: Count_final, dtype: int64

Other 남은 토픽

,Topic,Count_final,Name,Representation,MetaTopic_20
0,-1,0,-1_the_to_and_of,"[the, to, and, of, it, you, in, that, for, is]",NaN

In [58]:
topic_category_df = topic_category_df[
    topic_category_df["Topic"] != -1
].copy()

In [59]:
print("카테고리별 토픽 수")
display(topic_category_df["FinalCategory"].value_counts())

print("카테고리별 댓글 수")
display(
    topic_category_df
    .groupby("FinalCategory")["Count_final"]
    .sum()
    .sort_values(ascending=False)
)

카테고리별 토픽 수

FinalCategory
Gameplay / Rules / Content    56
Campaign / Pledge             32
Components & Production       28
Language & Localization       27
Community Reaction            25
Shipping / Price / Tax        12
Schedule / Updates            12
Name: count, dtype: int64

카테고리별 댓글 수

FinalCategory
Gameplay / Rules / Content    19604
Campaign / Pledge             11970
Community Reaction            11110
Components & Production       10994
Language & Localization        8772
Shipping / Price / Tax         6592
Schedule / Updates             4396
Name: Count_final, dtype: int64

In [60]:
comment_final_df = sample_thread_df.merge(
    topic_category_df[["Topic", "FinalCategory"]],
    left_on="topic_final",
    right_on="Topic",
    how="left"
).drop(columns=["Topic"])

print("원본 행 수:", len(sample_thread_df))
print("병합 후 행 수:", len(comment_final_df))
print("FinalCategory 결측 수:", comment_final_df["FinalCategory"].isna().sum())

display(comment_final_df["FinalCategory"].value_counts(dropna=False))

원본 행 수: 73438
병합 후 행 수: 73438
FinalCategory 결측 수: 0

FinalCategory
Gameplay / Rules / Content    19604
Campaign / Pledge             11970
Community Reaction            11110
Components & Production       10994
Language & Localization        8772
Shipping / Price / Tax         6592
Schedule / Updates             4396
Name: count, dtype: int64

In [61]:
comment_final_df.head()

,Unnamed: 0,projectID,thread_id,group,comment_ids,n_comments,merged_comment,creator_id,is_pledge_master,is_backer,is_prior_backer,is_pathfinder,topic_original,was_outlier,topic_reassigned,topic_final,was_reassigned,FinalCategory
0,0,5787,1691589,0,[1691589],1,WELCOME TO EDEN! Please check the FAQ and the...,1,0,0,0,0,321,True,21,21,True,Gameplay / Rules / Content
1,1,5787,1725920,0,"[1725920, 1726005]",2,@BlackSiteStudios Could a person use larger di...,1,1,1,0,0,100,False,101,101,False,Gameplay / Rules / Content
2,2,5787,1725876,0,[1725876],1,about an hour left to go,0,1,1,1,0,39,False,58,58,False,Community Reaction
3,3,5787,1725671,0,[1725671],1,Man 2 hours to go worth staying up to midnight...,0,0,0,0,0,39,False,58,58,False,Community Reaction
4,4,5787,1725512,0,[1725512],1,5 hours to go! Hold on to your butts!,0,0,1,1,0,39,False,58,58,False,Community Reaction

In [62]:
# 카테고리 붙인 상태 저장
sample_thread_df.to_csv(
    "comment_bertopic_thread_result.csv",
    index=False,
    encoding="utf-8-sig"
)

In [64]:
# =========================
# 7. 수동 조정 후 데이터 불러오기
# =========================
comment_final_df["group"] = comment_final_df["group"].fillna(0).astype(int)

print(comment_final_df["group"].value_counts().sort_index())
print(comment_final_df["FinalCategory"].isna().sum())

group
0    34571
1    38867
Name: count, dtype: int64
0

In [65]:
# =========================
# 8. group 0/1 없는 경우도 0으로 채우기 위한 기준표
# =========================

all_projects = comment_final_df["projectID"].dropna().unique()
all_groups = [0, 1]
all_categories = sorted(comment_final_df["FinalCategory"].dropna().unique())

base_project_group_category = pd.MultiIndex.from_product(
    [all_projects, all_groups, all_categories],
    names=["projectID", "group", "FinalCategory"]
).to_frame(index=False)

base_project_category = pd.MultiIndex.from_product(
    [all_projects, all_categories],
    names=["projectID", "FinalCategory"]
).to_frame(index=False)

In [66]:
# =========================
# 9-1. 전/후 group별 카운트
# =========================

project_group_category_count = (
    comment_final_df
    .groupby(["projectID", "group", "FinalCategory"])
    .size()
    .reset_index(name="count")
)

project_group_category_count = (
    base_project_group_category
    .merge(
        project_group_category_count,
        on=["projectID", "group", "FinalCategory"],
        how="left"
    )
)

project_group_category_count["count"] = project_group_category_count["count"].fillna(0).astype(int)

project_group_category_count.to_csv(
    "project_group_category_count.csv",
    index=False,
    encoding="utf-8-sig"
)

display(project_group_category_count.head())

   projectID  group               FinalCategory  count
0       5787      0           Campaign / Pledge      1
1       5787      0          Community Reaction     17
2       5787      0     Components & Production      3
3       5787      0  Gameplay / Rules / Content     29
4       5787      0     Language & Localization     10

In [67]:
# =========================
# 9-2. 전/후 group별 비율
# =========================

project_group_category_ratio = project_group_category_count.copy()

project_group_category_ratio["total_count"] = (
    project_group_category_ratio
    .groupby(["projectID", "group"])["count"]
    .transform("sum")
)

project_group_category_ratio["ratio"] = np.where(
    project_group_category_ratio["total_count"] > 0,
    project_group_category_ratio["count"] / project_group_category_ratio["total_count"],
    0
)

project_group_category_ratio.to_csv(
    "project_group_category_ratio.csv",
    index=False,
    encoding="utf-8-sig"
)

display(project_group_category_ratio.head())

   projectID  group               FinalCategory  count  total_count     ratio
0       5787      0           Campaign / Pledge      1           68  0.014706
1       5787      0          Community Reaction     17           68  0.250000
2       5787      0     Components & Production      3           68  0.044118
3       5787      0  Gameplay / Rules / Content     29           68  0.426471
4       5787      0     Language & Localization     10           68  0.147059

In [68]:
# =========================
# 9-3. 통합 카운트
# =========================

project_category_count = (
    comment_final_df
    .groupby(["projectID", "FinalCategory"])
    .size()
    .reset_index(name="count")
)

project_category_count = (
    base_project_category
    .merge(
        project_category_count,
        on=["projectID", "FinalCategory"],
        how="left"
    )
)

project_category_count["count"] = project_category_count["count"].fillna(0).astype(int)

project_category_count.to_csv(
    "project_category_count.csv",
    index=False,
    encoding="utf-8-sig"
)

display(project_category_count.head())

   projectID               FinalCategory  count
0       5787           Campaign / Pledge     15
1       5787          Community Reaction     24
2       5787     Components & Production      9
3       5787  Gameplay / Rules / Content     66
4       5787     Language & Localization     14

In [69]:
# =========================
# 9-4. 통합 비율
# =========================

project_category_ratio = project_category_count.copy()

project_category_ratio["total_count"] = (
    project_category_ratio
    .groupby("projectID")["count"]
    .transform("sum")
)

project_category_ratio["ratio"] = np.where(
    project_category_ratio["total_count"] > 0,
    project_category_ratio["count"] / project_category_ratio["total_count"],
    0
)

project_category_ratio.to_csv(
    "project_category_ratio.csv",
    index=False,
    encoding="utf-8-sig"
)

display(project_category_ratio.head())

   projectID               FinalCategory  count  total_count     ratio
0       5787           Campaign / Pledge     15          144  0.104167
1       5787          Community Reaction     24          144  0.166667
2       5787     Components & Production      9          144  0.062500
3       5787  Gameplay / Rules / Content     66          144  0.458333
4       5787     Language & Localization     14          144  0.097222

In [70]:
check1 = (
    project_group_category_count
    .groupby(["projectID", "group"])
    .size()
)

print(check1.describe())
display(check1.value_counts().sort_index())

count    946.0
mean       7.0
std        0.0
min        7.0
25%        7.0
50%        7.0
75%        7.0
max        7.0
dtype: float64

7    946
Name: count, dtype: int64

In [71]:
ratio_check = (
    project_group_category_ratio
    .groupby(["projectID", "group"])["ratio"]
    .sum()
    .reset_index()
)

display(ratio_check.head())

   projectID  group  ratio
0        222      0    1.0
1        222      1    1.0
2        769      0    1.0
3        769      1    1.0
4        806      0    1.0

In [72]:
ratio_check["error"] = abs(ratio_check["ratio"] - 1)

display(
    ratio_check
    .sort_values("error", ascending=False)
    .head(20)
)

     projectID  group  ratio  error
469       3723      1    0.0    1.0
183       2275      1    0.0    1.0
844       6176      0    0.0    1.0
283       2816      1    0.0    1.0
329       2984      1    0.0    1.0
849       6194      1    0.0    1.0
188       2304      0    0.0    1.0
325       2977      1    0.0    1.0
643       4672      1    0.0    1.0
909       6867      1    0.0    1.0
720       5211      0    0.0    1.0
837       6088      1    0.0    1.0
457       3623      1    0.0    1.0
905       6758      1    0.0    1.0
759       5535      1    0.0    1.0
723       5234      1    0.0    1.0
558       4126      0    0.0    1.0
649       4737      1    0.0    1.0
230       2519      0    0.0    1.0
729       5275      1    0.0    1.0

In [73]:
# group 없는 프로젝트 0으로 채워졌는지 확인
single_group_projects = (
    comment_final_df
    .groupby("projectID")["group"]
    .nunique()
)

single_group_projects = single_group_projects[
    single_group_projects == 1
].index.tolist()

print("한쪽 group만 있는 프로젝트 수:", len(single_group_projects))

test_project = single_group_projects[0]

display(
    project_group_category_count[
        project_group_category_count["projectID"] == test_project
    ]
)

한쪽 group만 있는 프로젝트 수: 45

      projectID  group               FinalCategory  count
6538       2081      0           Campaign / Pledge      0
6539       2081      0          Community Reaction      0
6540       2081      0     Components & Production      0
6541       2081      0  Gameplay / Rules / Content      0
6542       2081      0     Language & Localization      0
6543       2081      0          Schedule / Updates      0
6544       2081      0      Shipping / Price / Tax      0
6545       2081      1           Campaign / Pledge      1
6546       2081      1          Community Reaction      0
6547       2081      1     Components & Production      0
6548       2081      1  Gameplay / Rules / Content      0
6549       2081      1     Language & Localization      0
6550       2081      1          Schedule / Updates      0
6551       2081      1      Shipping / Price / Tax      0

In [74]:
overall_ratio_check = (
    project_category_ratio
    .groupby("projectID")["ratio"]
    .sum()
)

print(
    "최소:", overall_ratio_check.min(),
    "최대:", overall_ratio_check.max()
)

최소: 0.9999999999999999 최대: 1.0

In [75]:
print(
    "원본 댓글 수:",
    len(comment_final_df)
)

print(
    "group 카운트 합:",
    project_group_category_count["count"].sum()
)

print(
    "통합 카운트 합:",
    project_category_count["count"].sum()
)

원본 댓글 수: 73438
group 카운트 합: 73438
통합 카운트 합: 73438

In [76]:
ratio_check = (
    project_group_category_ratio
    .groupby(["projectID", "group"])
    .agg(
        ratio_sum=("ratio", "sum"),
        total_count=("count", "sum")
    )
    .reset_index()
)

ratio_check["status"] = np.where(
    ratio_check["total_count"] == 0,
    "empty_group",
    np.where(
        np.isclose(ratio_check["ratio_sum"], 1),
        "ok",
        "check"
    )
)

display(ratio_check["status"].value_counts())

display(
    ratio_check[ratio_check["status"] == "check"]
)

status
ok             901
empty_group     45
Name: count, dtype: int64

Empty DataFrame
Columns: [projectID, group, ratio_sum, total_count, status]
Index: []

In [78]:
df3 = pd.read_csv("/content/project_group_category_ratio.csv")

In [79]:
df3.head()

   projectID  group               FinalCategory  count  total_count     ratio
0       5787      0           Campaign / Pledge      1           68  0.014706
1       5787      0          Community Reaction     17           68  0.250000
2       5787      0     Components & Production      3           68  0.044118
3       5787      0  Gameplay / Rules / Content     29           68  0.426471
4       5787      0     Language & Localization     10           68  0.147059

# wide

In [80]:
# 그룹 카운트
project_group_category_count_wide = (
    project_group_category_count
    .pivot_table(
        index=["projectID", "group"],
        columns="FinalCategory",
        values="count",
        fill_value=0
    )
    .reset_index()
)

project_group_category_count_wide.columns.name = None

display(project_group_category_count_wide.head())

project_group_category_count_wide.to_csv(
    "project_group_category_count_wide.csv",
    index=False,
    encoding="utf-8-sig"
)

,projectID,group,Campaign / Pledge,Community Reaction,Components & Production,Gameplay / Rules / Content,Language & Localization,Schedule / Updates,Shipping / Price / Tax
0,222,0,64.0,152.0,75.0,263.0,37.0,53.0,47.0
1,222,1,225.0,185.0,92.0,309.0,63.0,80.0,133.0
2,769,0,17.0,41.0,60.0,28.0,7.0,5.0,3.0
3,769,1,69.0,31.0,183.0,32.0,15.0,23.0,33.0
4,806,0,1.0,2.0,1.0,5.0,0.0,0.0,0.0

In [81]:
# 비율 wide
project_group_category_ratio_wide = (
    project_group_category_ratio
    .pivot_table(
        index=["projectID", "group"],
        columns="FinalCategory",
        values="ratio",
        fill_value=0
    )
    .reset_index()
)

project_group_category_ratio_wide.columns.name = None

display(project_group_category_ratio_wide.head())

project_group_category_ratio_wide.to_csv(
    "project_group_category_ratio_wide.csv",
    index=False,
    encoding="utf-8-sig"
)

,projectID,group,Campaign / Pledge,Community Reaction,Components & Production,Gameplay / Rules / Content,Language & Localization,Schedule / Updates,Shipping / Price / Tax
0,222,0,0.092619,0.219971,0.108538,0.380608,0.053546,0.076700,0.068017
1,222,1,0.206992,0.170193,0.084637,0.284269,0.057958,0.073597,0.122355
2,769,0,0.105590,0.254658,0.372671,0.173913,0.043478,0.031056,0.018634
3,769,1,0.178756,0.080311,0.474093,0.082902,0.038860,0.059585,0.085492
4,806,0,0.111111,0.222222,0.111111,0.555556,0.000000,0.000000,0.000000