### 리스트+리워드 조인

In [1]:
import pandas as pd
pd.set_option("display.max_columns",None)

list_df = pd.read_csv("../../02_Data/processed/final_gamefound_list.csv")
rewards_df = pd.read_csv("../../02_Data/processed/final_rewards_typical.csv")

In [2]:
list_df

,name,projectID,project_url,creator,creatorID,homeUrl,currencySymbol,campaignGoal,fundsGathered,backersCount,campaignStart,campaignEnd,phaseLabel,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,playTimeUnit,fundedInSeconds,imageUrl,pledgeManagerSoftCloseDeadline,projectTags,originalType
0,We Played God - A Survival Miniatures Game,5787,https://gamefound.com:443/en/projects/black-si...,Black Site Studios,5252,https://gamefound.com/creators/black-site-studios,$,10000.0,393538.44,1567,2025-06-17T14:30:00Z,2025-07-19T00:50:35.25Z,Pledge manager - Closed,False,NaN,NaN,NaN,NaN,0,628,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-02T15:00:00Z,"Exploration, Horror, Modern, Science Fiction, ...",1
1,CARNIVORE,6481,https://gamefound.com:443/en/projects/buer-gam...,Buer Games,6737,https://gamefound.com/creators/buer-games,$,20000.0,247988.30,1075,2026-02-25T16:00:00Z,2026-03-31T15:57:23.953Z,Pledge manager - Closed,True,1.0,4.0,13.0,90.0,0,2716,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-01T14:00:00Z,"History, Strategy, Wargame, Action, Collectibl...",1
2,1809: Talavera,8024,https://gamefound.com:443/en/projects/tactical...,Tactical Workshop,5141,https://gamefound.com/creators/tactical-workshop,$,7000.0,23091.47,215,2026-03-01T05:00:00Z,2026-04-01T05:00:00Z,Pledge manager - Closed,True,1.0,2.0,12.0,8.0,1,56442,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"History, Strategy, Wargame",1
3,Comber Cat,8225,https://gamefound.com:443/en/projects/gamedolf...,Gamedolf Limited,8739,https://gamefound.com/creators/gamedolflimited,$,300.0,645.66,12,2026-02-02T13:00:00Z,2026-03-02T13:00:00Z,Pledge manager - Closed,True,2.0,5.0,8.0,15.0,0,2409627,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Card Game, Strategy, Party game, Family",1
4,Jano - A Pawsome Adventure,5995,https://gamefound.com:443/en/projects/aszaki/j...,aszaki,7221,https://gamefound.com/creators/aszaki,€,1000.0,4042.67,89,2026-01-16T12:00:00Z,2026-02-28T12:00:00Z,Pledge manager - Closed,True,2.0,6.0,8.0,20.0,0,14439,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-11T13:00:00Z,"Strategy, Resource management, Family, Worker ...",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
483,Tectonia,2109,https://gamefound.com:443/en/projects/hagen-be...,Hagen Behr,2703,https://gamefound.com/creators/hagen-behr,€,20000.0,8001.00,113,2022-07-05T18:00:00Z,2022-07-26T18:00:00Z,Crowdfunding - Unsuccessful,True,2.0,4.0,14.0,180.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Strategy, Wargame, Dice Game, Area Control, Co...",1
484,Invasion Cards,2149,https://gamefound.com:443/en/projects/lawrence...,Lawrence Lyle,2742,https://gamefound.com/creators/lawrence-lyle,€,9800.0,70.00,2,2022-07-04T10:00:00Z,2022-08-03T21:00:00Z,Crowdfunding - Unsuccessful,True,2.0,4.0,5.0,25.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Strategy, Humor",1
485,MOOGH,1919,https://gamefound.com:443/en/projects/nuts-pub...,Nuts! Publishing,2363,https://gamefound.com/creators/nuts-publishing,€,10000.0,6285.00,143,2022-04-26T16:00:00Z,2022-05-12T16:00:00Z,Crowdfunding - Unsuccessful,True,1.0,4.0,14.0,30.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Dice Game, Multiplayer, Competitive, Campaign",1
486,Crossroads Inn: The Board Game,1143,https://gamefound.com:443/en/projects/klabater...,Klabater,1510,https://gamefound.com/creators/klabater,€,20000.0,13420.63,158,2021-10-28T14:00:00Z,2021-11-30T15:00:00Z,Crowdfunding - Unsuccessful,True,2.0,4.0,12.0,120.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Strategy, Terrain Building, Humor",1
487,Goldenstar: The Galactic Tournament,1325,https://gamefound.com:443/en/projects/gindi/go...,Gindi,64,https://gamefound.com/creators/gindi,€,30000.0,10890.00,148,2021-10-05T16:00:00Z,2021-10-29T16:00:00Z,Crowdfunding - Unsuccessful,True,2.0,4.0,14.0,60.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Science Fiction, Area Control, Deck Building",1

In [3]:
list_df['originalType'].value_counts()

originalType
1    488
Name: count, dtype: int64

In [4]:
list_df.loc[list_df['creator']=="Gabe-Barrett"]

,name,projectID,project_url,creator,creatorID,homeUrl,currencySymbol,campaignGoal,fundsGathered,backersCount,campaignStart,campaignEnd,phaseLabel,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,playTimeUnit,fundedInSeconds,imageUrl,pledgeManagerSoftCloseDeadline,projectTags,originalType
8,Drawing Dead [Solo Game of the Month],6605,https://gamefound.com:443/en/projects/gabe-bar...,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,83466.02,2010,2025-10-28T15:00:00Z,2025-11-15T06:15:03.567Z,Pledge manager - Closed,True,1.0,1.0,14.0,45.0,0,1444,https://imgcdn.gamefound.com/projectimage/proj...,NaN,Card Game,1
12,Mission: Drive [Solo Game of the Month],6435,https://gamefound.com:443/en/projects/gabe-bar...,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,44548.95,1180,2025-09-30T15:00:00Z,2025-10-18T04:00:00Z,Pledge manager - Closed,True,1.0,1.0,14.0,45.0,0,3731,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Card Game, Strategy, Logical, Action, Video Ga...",1
27,Storybook Saga [Solo Game of the Month],6225,https://gamefound.com:443/en/projects/gabe-bar...,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,96449.02,2546,2025-08-26T15:00:00Z,2025-09-13T04:00:00Z,Pledge manager - Closed,True,NaN,NaN,NaN,NaN,0,1267,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Card Game, Dice Game",1
35,Dice Commandos [Solo Game of the Month],6033,https://gamefound.com:443/en/projects/gabe-bar...,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,71116.85,1825,2025-07-22T15:00:00Z,2025-08-09T04:37:13.41Z,Pledge manager - Closed,True,1.0,1.0,14.0,30.0,0,1609,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-09T23:00:00Z,"Card Game, Modern, Dice Game, Action",1
55,Dicemancy [Solo Game of the Month],5536,https://gamefound.com:443/en/projects/gabe-bar...,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,90856.86,2383,2025-04-15T15:00:00Z,2025-05-03T04:44:52.423Z,Pledge manager - Closed,True,1.0,1.0,14.0,45.0,0,1052,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-09T16:00:00Z,"Card Game, Mythology, Dice Game",1
56,Knight Moves [Solo Game of the Month],5730,https://gamefound.com:443/en/projects/gabe-bar...,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,55777.24,1492,2025-05-20T15:00:00Z,2025-06-06T05:22:03.3Z,Pledge manager - Closed,True,1.0,1.0,14.0,45.0,0,1653,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-15T14:00:00Z,"Card Game, Video Game Theme, Logical",1
71,Rome: Fate of an Empire (DELUXE) [Solo Game of...,5198,https://gamefound.com:443/en/projects/gabe-bar...,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,185224.27,3273,2025-03-11T15:00:00Z,2025-03-29T05:06:11.233Z,Pledge manager - Closed,True,1.0,1.0,14.0,60.0,0,675,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-09T18:00:00Z,"Card Game, History, Strategy, Deck Building, E...",1
72,Paranormal [Solo Game of the Month],5197,https://gamefound.com:443/en/projects/gabe-bar...,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,88246.33,2570,2025-02-11T16:00:00Z,2025-03-01T04:00:00Z,Pledge manager - Closed,True,1.0,2.0,14.0,45.0,0,1214,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-09T19:00:00Z,"Horror, Dice Game, Action",1
82,Action Packed Double Feature [Solo Game of the...,5104,https://gamefound.com:443/en/projects/gabe-bar...,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,32954.47,926,2025-01-15T16:00:00Z,2025-02-01T05:00:00Z,Pledge manager - Closed,True,1.0,1.0,14.0,20.0,0,2787,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-13T16:00:00Z,Card Game,1
83,Small-Time Heroes [Solo Game of the Month],4983,https://gamefound.com:443/en/projects/gabe-bar...,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,88843.43,2032,2024-12-17T16:00:00Z,2025-01-03T05:00:00Z,Pledge manager - Closed,True,1.0,2.0,NaN,40.0,0,1002,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-11T17:00:00Z,"Card Game, Fantasy, Cooperative",1
92,Mech Bunny [Solo Game of the Month],4777,https://gamefound.com:443/en/projects/gabe-bar...,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,70312.30,2093,2024-11-19T16:00:00Z,2024-12-06T05:00:00Z,Pledge manager - Closed,True,1.0,1.0,NaN,40.0,0,1513,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-13T07:00:00Z,"Card Game, Action, Deck Building",1
117,Spooky Double Feature + Dieson Crusoe Reprint ...,4707,https://gamefound.com:443/en/projects/gabe-bar...,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,52970.69,1429,2024-10-15T15:00:00Z,2024-11-01T04:59:00Z,Pledge manager - Closed,True,1.0,1.0,14.0,20.0,0,2091,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-16T05:00:00Z,"Card Game, Horror",1
120,Hunted: North Pole (2nd Edition) [Solo Game of...,4543,https://gamefound.com:443/en/projects/gabe-bar...,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,22403.59,768,2024-09-17T15:00:00Z,2024-10-04T04:00:00Z,Pledge manager - Closed,True,1.0,2.0,14.0,20.0,0,5920,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-16T01:00:00Z,"Card Game, Dice Game, Adventure",1
126,7th Inning Stretch [Solo Game of the Month],4459,https://gamefound.com:443/en/projects/gabe-bar...,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,41192.09,1416,2024-08-13T15:00:00Z,2024-08-30T04:59:00Z,Pledge manager - Closed,True,1.0,2.0,14.0,45.0,0,3718,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-12T13:00:00Z,"Card Game, Modern, Dice Game, Competitive",1
143,The Cursed Castle [Solo Game of the Month],4346,https://gamefound.com:443/en/projects/gabe-bar...,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,67673.49,2326,2024-07-16T15:00:00Z,2024-08-02T04:59:00Z,Pledge manager - Closed,True,1.0,1.0,14.0,30.0,0,1379,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-10T06:00:00Z,"Card Game, Fantasy, Dice Game",1
152,Okinawa: The Last Battle of World War II [Solo...,4212,https://gamefound.com:443/en/projects/gabe-bar...,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,54929.43,1842,2024-06-11T15:00:00Z,2024-06-28T04:00:00Z,Pledge manager - Closed,True,1.0,1.0,14.0,40.0,0,4005,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-15T20:00:00Z,"Card Game, Dice Game, Strategy, History",1
158,Hunted: Mining Colony 415 (2nd Edition) [Solo ...,4078,https://gamefound.com:443/en/projects/gabe-bar...,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,61939.14,2239,2024-05-14T15:00:00Z,2024-05-31T04:59:00Z,Pledge manager - Closed,True,1.0,2.0,14.0,20.0,0,2313,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-14T10:00:00Z,"Card Game, Survival, Horror, Science Fiction, ...",1
170,Rome: Fate of an Empire [Solo Game of the Month],3997,https://gamefound.com:443/en/projects/gabe-bar...,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,88961.75,2993,2024-04-09T15:00:00Z,2024-04-26T04:59:00Z,Pledge manager - Closed,True,1.0,1.0,14.0,60.0,0,1681,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-10T19:00:00Z,"Card Game, Strategy, History, Deck Building, C...",1
180,Dieson Crusoe [Solo Game of the Month],3745,https://gamefound.com:443/en/projects/gabe-bar...,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,54509.76,1954,2024-02-13T16:00:00Z,2024-03-01T05:00:00Z,Pledge manager - Closed,True,1.0,1.0,12.0,30.0,0,3069,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-14T07:00:00Z,"Survival, Exploration, Dice Game, Adventure, W...",1
185,Hunted: Kobayashi Tower (2nd Edition) [Solo Ga...,3582,https://gamefound.com:443/en/projects/gabe-bar...,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,46620.21,1793,2024-01-09T16:00:00Z,2024-01-26T05:59:00Z,Pledge manager - Closed,True,NaN,NaN,NaN,NaN,0,7462,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-14T02:00:00Z,"Card Game, Modern, Cooperative, Action, Dice Game",1
324,Hunted: Wode Ridge 2E [Solo Game of the Month],10156,https://gamefound.com:443/en/projects/gabe-bar...,Gabe-Barrett,731,https://gamefound.com/creators/gabe-barrett,$,5000.0,30498.67,925,2026-05-12T15:00:00Z,2026-05-30T04:10:00Z,Crowdfunding - Funded,True,1.0,2.0,14.0,45.0,0,2322,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Card Game, Adventure, Cooperative, Print and Play",1

In [5]:
list_df.columns

Index(['name', 'projectID', 'project_url', 'creator', 'creatorID', 'homeUrl',
       'currencySymbol', 'campaignGoal', 'fundsGathered', 'backersCount',
       'campaignStart', 'campaignEnd', 'phaseLabel',
       'enableBoardGameProperties', 'minPlayers', 'maxPlayers', 'minAge',
       'playTime', 'playTimeUnit', 'fundedInSeconds', 'imageUrl',
       'pledgeManagerSoftCloseDeadline', 'projectTags', 'originalType'],
      dtype='object')

In [6]:
# creatorID -> 그 당시 몇개 만들었는지
# currencySymbol + campaignGoal, fundsGathered -> 단위 통일 하나 -> 조인 후 해야함
# campaignEnd- campaignStart -> 기간 만들고
# campaignStart 댓글 가지고 오는 용(시작 후 1주일?2주일)
# 'playTime', 'playTimeUnit' -> 1일경우에 시간으로 표시됨 하나로 통일
# pledgeManagerSoftCloseDeadline 있으면 1 없으면 0 -> 방치했나 신경썼나?
# projectTags -> 인코딩 ㅇㅇ

a_list = ['projectID',  'creatorID', 
       'currencySymbol', 'campaignGoal', 'fundsGathered', 'backersCount',
       'campaignStart', 'campaignEnd', 'phaseLabel',
       'enableBoardGameProperties', 'minPlayers', 'maxPlayers', 'minAge',
       'playTime', 'playTimeUnit', 'fundedInSeconds',
       'pledgeManagerSoftCloseDeadline', 'projectTags']

In [7]:
list_df = list_df[a_list]
list_df.head()

,projectID,creatorID,currencySymbol,campaignGoal,fundsGathered,backersCount,campaignStart,campaignEnd,phaseLabel,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,playTimeUnit,fundedInSeconds,pledgeManagerSoftCloseDeadline,projectTags
0,5787,5252,$,10000.0,393538.44,1567,2025-06-17T14:30:00Z,2025-07-19T00:50:35.25Z,Pledge manager - Closed,False,NaN,NaN,NaN,NaN,0,628,2026-06-02T15:00:00Z,"Exploration, Horror, Modern, Science Fiction, ..."
1,6481,6737,$,20000.0,247988.30,1075,2026-02-25T16:00:00Z,2026-03-31T15:57:23.953Z,Pledge manager - Closed,True,1.0,4.0,13.0,90.0,0,2716,2026-06-01T14:00:00Z,"History, Strategy, Wargame, Action, Collectibl..."
2,8024,5141,$,7000.0,23091.47,215,2026-03-01T05:00:00Z,2026-04-01T05:00:00Z,Pledge manager - Closed,True,1.0,2.0,12.0,8.0,1,56442,NaN,"History, Strategy, Wargame"
3,8225,8739,$,300.0,645.66,12,2026-02-02T13:00:00Z,2026-03-02T13:00:00Z,Pledge manager - Closed,True,2.0,5.0,8.0,15.0,0,2409627,NaN,"Card Game, Strategy, Party game, Family"
4,5995,7221,€,1000.0,4042.67,89,2026-01-16T12:00:00Z,2026-02-28T12:00:00Z,Pledge manager - Closed,True,2.0,6.0,8.0,20.0,0,14439,2026-06-11T13:00:00Z,"Strategy, Resource management, Family, Worker ..."

In [8]:
list_df['projectTags'].value_counts()

projectTags
Card Game                                                                   7
History, Wargame, Strategy, Area Control, Asymmetric                        2
Card Game, Strategy                                                         2
Wargame, Strategy, History                                                  2
History, Strategy, Wargame                                                  2
                                                                           ..
Strategy, Dice Game, Economic                                               1
Science Fiction, History, RPG, Cooperative, Multiplayer, Campaign, TTRPG    1
Card Game, Strategy, Humor, Educational, Asymmetric, Competitive, Family    1
Card Game, Survival, Horror, Science Fiction, Adventure, Dexterity          1
Science Fiction, Area Control, Deck Building                                1
Name: count, Length: 477, dtype: int64

In [9]:
rewards_df

,main_name,projectID,anchorRelativeUrl,price,isDiscounted,effectivePrice,isFeatured,purchasedCopiesCount,backgroundUrl,installmentCost,installmentMinPayment,hasLimitedStock,productCanBePurchased,productID,remainingStockLimit,single_item
0,We Played God - A Survival Miniatures Game,5787,core-rules-physical-pdf-80323,60.00,False,60.00,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,80323,NaN,1.0
1,CARNIVORE,6481,megapredator-digital-102621,57.00,False,57.00,False,0,https://imgcdn.gamefound.com/productimage/proj...,28.5,100.0,False,False,102621,NaN,1.0
2,1809: Talavera,8024,backers-copy-1809-talavera-99555,69.99,True,56.99,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,99555,NaN,1.0
3,Comber Cat,8225,cat-lovers-99754,20.00,False,20.00,True,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,99754,NaN,1.0
4,Jano - A Pawsome Adventure,5995,jano-board-game-92756,25.00,False,25.00,True,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,92756,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479,Tectonia,2109,tectonia-the-boardgame-with-all-unlocked-stret...,70.00,False,70.00,True,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,26743,NaN,1.0
480,Invasion Cards,2149,the-evil-earthworm--26496,19.90,True,13.90,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,26496,NaN,1.0
481,MOOGH,1919,moogh-the-basic-pledge-24022,36.00,True,23.00,True,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,24022,NaN,1.0
482,Crossroads Inn: The Board Game,1143,crossroads-inn-the-board-game-standard-edition...,50.00,False,50.00,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,19113,NaN,1.0
483,Goldenstar: The Galactic Tournament,1325,goldenstar-core-pledge-17700,43.00,False,43.00,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,17700,NaN,1.0

In [10]:
rewards_df['remainingStockLimit'].value_counts()

remainingStockLimit
0.0       31
1.0        3
25.0       2
1000.0     2
30.0       1
151.0      1
204.0      1
842.0      1
1057.0     1
396.0      1
1734.0     1
1487.0     1
247.0      1
108.0      1
300.0      1
43.0       1
120.0      1
20.0       1
192.0      1
1400.0     1
4500.0     1
989.0      1
100.0      1
70.0       1
199.0      1
69.0       1
934.0      1
9.0        1
2091.0     1
177.0      1
39.0       1
125.0      1
4.0        1
46.0       1
8.0        1
3.0        1
13.0       1
1562.0     1
57.0       1
36.0       1
733.0      1
494.0      1
413.0      1
691.0      1
3000.0     1
80.0       1
Name: count, dtype: int64

In [11]:
rewards_df.loc[rewards_df["isFeatured"]==True]["main_name"].value_counts()

main_name
Comber Cat                                                           1
Crown and War                                                        1
Falcon's Formula Racing - Relaunch                                   1
soccerone                                                            1
THE FAMILY DECK — Indestructible Mafia-Themed Poker Playing Cards    1
                                                                    ..
Assault Sicily 43 - Gela Beachhead                                   1
The Battle of Versailles                                             1
Bonaparte's Eastern Empire                                           1
Perseverance: Castaway Chronicles - Episodes 3&4                     1
MOOGH                                                                1
Name: count, Length: 237, dtype: int64

In [12]:
rewards_df.loc[rewards_df["main_name"]=="Goldenstar: The Galactic Tournament"]

,main_name,projectID,anchorRelativeUrl,price,isDiscounted,effectivePrice,isFeatured,purchasedCopiesCount,backgroundUrl,installmentCost,installmentMinPayment,hasLimitedStock,productCanBePurchased,productID,remainingStockLimit,single_item
483,Goldenstar: The Galactic Tournament,1325,goldenstar-core-pledge-17700,43.0,False,43.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,17700,NaN,1.0

In [13]:
rewards_df.columns

Index(['main_name', 'projectID', 'anchorRelativeUrl', 'price', 'isDiscounted',
       'effectivePrice', 'isFeatured', 'purchasedCopiesCount', 'backgroundUrl',
       'installmentCost', 'installmentMinPayment', 'hasLimitedStock',
       'productCanBePurchased', 'productID', 'remainingStockLimit',
       'single_item'],
      dtype='object')

In [14]:
# price 조인하고 처리해야함 단위 모름

b_list = ['projectID',  'price', 'isDiscounted',
       'effectivePrice', 'installmentMinPayment']

In [15]:
list(set(rewards_df['projectID']))

[6153,
 2057,
 8203,
 2063,
 2065,
 4120,
 2072,
 4126,
 6176,
 8225,
 2081,
 4134,
 6184,
 2098,
 6194,
 2108,
 2109,
 4164,
 8265,
 6221,
 4174,
 8271,
 6225,
 8277,
 2135,
 4188,
 6236,
 4189,
 2144,
 2149,
 2152,
 8302,
 6255,
 4212,
 2181,
 6277,
 4234,
 4235,
 4240,
 2200,
 2207,
 2213,
 2217,
 2219,
 2220,
 2225,
 6321,
 2235,
 2236,
 2242,
 2245,
 2246,
 2264,
 222,
 2275,
 8420,
 6374,
 2279,
 6378,
 6379,
 6381,
 4340,
 2295,
 4346,
 2304,
 2311,
 2314,
 2315,
 4364,
 4365,
 4368,
 6419,
 8475,
 6435,
 4399,
 4400,
 2352,
 6456,
 2362,
 4410,
 4412,
 4414,
 2371,
 8515,
 8517,
 2378,
 8526,
 6481,
 4434,
 2387,
 2389,
 2390,
 6486,
 4439,
 4440,
 2404,
 2407,
 2408,
 4457,
 4459,
 6510,
 6516,
 4475,
 6528,
 2435,
 2436,
 6544,
 4504,
 2460,
 4514,
 6562,
 6571,
 2486,
 2494,
 4543,
 6595,
 6605,
 2512,
 2518,
 4566,
 2519,
 2525,
 6626,
 6631,
 2536,
 4590,
 4591,
 4594,
 2554,
 6650,
 4609,
 6657,
 4618,
 4621,
 2573,
 2575,
 6676,
 4637,
 4639,
 4642,
 4649,
 4659,
 4664,
 4672,
 2635,
 2640,
 2643,
 2646,
 6743,
 4707,
 6758,
 2671,
 6773,
 4728,
 2684,
 4737,
 2689,
 4740,
 2702,
 4772,
 2728,
 4777,
 2729,
 4779,
 2735,
 4784,
 4804,
 2757,
 2758,
 2763,
 2771,
 6867,
 2782,
 2790,
 2793,
 4845,
 4849,
 2802,
 2801,
 2813,
 2816,
 6913,
 769,
 2823,
 4874,
 4879,
 2832,
 6941,
 2847,
 2850,
 806,
 2856,
 2857,
 4906,
 4916,
 6967,
 2874,
 2875,
 2879,
 2882,
 2893,
 4944,
 2905,
 2909,
 862,
 4973,
 2932,
 887,
 4983,
 2935,
 889,
 2939,
 2942,
 5009,
 2967,
 2969,
 2972,
 2977,
 5030,
 2983,
 2984,
 5041,
 2997,
 5047,
 3002,
 954,
 3006,
 3007,
 5059,
 5060,
 5064,
 3016,
 975,
 5077,
 5082,
 5084,
 5090,
 5097,
 5104,
 5108,
 3066,
 5125,
 1032,
 3082,
 5133,
 5142,
 1060,
 3112,
 1066,
 3119,
 3124,
 3125,
 1078,
 1081,
 5180,
 3135,
 3136,
 3144,
 5197,
 5198,
 5199,
 3151,
 1103,
 5202,
 3154,
 3161,
 1114,
 5211,
 3166,
 3175,
 3176,
 3183,
 5234,
 1143,
 1145,
 1148,
 5258,
 3211,
 5261,
 3215,
 5275,
 3232,
 5281,
 5284,
 3236,
 3244,
 3248,
 3252,
 3261,
 3273,
 5325,
 3278,
 3282,
 3285,
 1248,
 3298,
 5349,
 5357,
 1263,
 3313,
 1268,
 5386,
 3339,
 3340,
 5395,
 3347,
 1301,
 5401,
 3360,
 3365,
 1318,
 1320,
 1325,
 5423,
 5429,
 3383,
 1342,
 1348,
 5446,
 3402,
 5452,
 5454,
 5463,
 3425,
 3444,
 1398,
 3453,
 1405,
 3457,
 3459,
 3478,
 1430,
 3484,
 1438,
 5536,
 1442,
 3493,
 1449,
 3499,
 3503,
 3506,
 1460,
 3515,
 5563,
 1476,
 5584,
 3539,
 3546,
 3547,
 9693,
 3554,
 5609,
 5625,
 3582,
 1539,
 3588,
 3592,
 5640,
 5644,
 3612,
 3617,
 3618,
 5669,
 3623,
 5676,
 1599,
 5715,
 5719,
 3678,
 5730,
 3685,
 5737,
 5738,
 1643,
 3692,
 5739,
 5740,
 3695,
 1661,
 3711,
 3723,
 3724,
 3726,
 3731,
 3734,
 5787,
 1691,
 3745,
 3748,
 5802,
 3755,
 3766,
 1720,
 5817,
 1721,
 3771,
 5820,
 1725,
 3775,
 5838,
 3797,
 3803,
 1755,
 3810,
 5862,
 3815,
 1767,
 3818,
 3828,
 3830,
 1782,
 1790,
 5887,
 3844,
 5894,
 3847,
 3848,
 3849,
 1799,
 1804,
 5900,
 5906,
 5918,
 5920,
 3877,
 1837,
 3890,
 3895,
 3897,
 1851,
 10044,
 1856,
 3906,
 5956,
 5958,
 5969,
 3922,
 5971,
 8024,
 1888,
 3937,
 3941,
 1893,
 1897,
 5995,
 3949,
 6007,
 3960,
 1919,
 1926,
 1927,
 6026,
 6033,
 3988,
 6039,
 8091,
 3997,
 4003,
 4007,
 10156,
 4013,
 6064,
 4018,
 1977,
 4034,
 1986,
 8130,
 4037,
 1987,
 1991,
 6088,
 6087,
 4042,
 2002,
 6099,
 2005,
 8150,
 4065,
 6117,
 2023,
 4078,
 2032,
 4088,
 4093]

#### 빈 프로젝트 드랍

In [16]:
for i in list_df["projectID"]:
    if i not in list(set(rewards_df['projectID'])):
        print(i)

4358
7001
5535
5043

In [17]:
drop_ids = [4358, 7001, 5535, 5043]
list_df = list_df[~list_df['projectID'].isin(drop_ids)]

In [18]:
len(list_df)

484

In [19]:
rewards_df[b_list]

     projectID  price  isDiscounted  effectivePrice  installmentMinPayment
0         5787  60.00         False           60.00                   75.0
1         6481  57.00         False           57.00                  100.0
2         8024  69.99          True           56.99                    NaN
3         8225  20.00         False           20.00                    NaN
4         5995  25.00         False           25.00                    NaN
..         ...    ...           ...             ...                    ...
479       2109  70.00         False           70.00                    NaN
480       2149  19.90          True           13.90                    NaN
481       1919  36.00          True           23.00                    NaN
482       1143  50.00         False           50.00                    NaN
483       1325  43.00         False           43.00                    NaN

[484 rows x 5 columns]

조인

In [20]:
final_df = pd.merge(list_df, rewards_df, on='projectID', how='left')
final_df.head()

,projectID,creatorID,currencySymbol,campaignGoal,fundsGathered,backersCount,campaignStart,campaignEnd,phaseLabel,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,playTimeUnit,fundedInSeconds,pledgeManagerSoftCloseDeadline,projectTags,main_name,anchorRelativeUrl,price,isDiscounted,effectivePrice,isFeatured,purchasedCopiesCount,backgroundUrl,installmentCost,installmentMinPayment,hasLimitedStock,productCanBePurchased,productID,remainingStockLimit,single_item
0,5787,5252,$,10000.0,393538.44,1567,2025-06-17T14:30:00Z,2025-07-19T00:50:35.25Z,Pledge manager - Closed,False,NaN,NaN,NaN,NaN,0,628,2026-06-02T15:00:00Z,"Exploration, Horror, Modern, Science Fiction, ...",We Played God - A Survival Miniatures Game,core-rules-physical-pdf-80323,60.00,False,60.00,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,80323,NaN,1.0
1,6481,6737,$,20000.0,247988.30,1075,2026-02-25T16:00:00Z,2026-03-31T15:57:23.953Z,Pledge manager - Closed,True,1.0,4.0,13.0,90.0,0,2716,2026-06-01T14:00:00Z,"History, Strategy, Wargame, Action, Collectibl...",CARNIVORE,megapredator-digital-102621,57.00,False,57.00,False,0,https://imgcdn.gamefound.com/productimage/proj...,28.5,100.0,False,False,102621,NaN,1.0
2,8024,5141,$,7000.0,23091.47,215,2026-03-01T05:00:00Z,2026-04-01T05:00:00Z,Pledge manager - Closed,True,1.0,2.0,12.0,8.0,1,56442,NaN,"History, Strategy, Wargame",1809: Talavera,backers-copy-1809-talavera-99555,69.99,True,56.99,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,99555,NaN,1.0
3,8225,8739,$,300.0,645.66,12,2026-02-02T13:00:00Z,2026-03-02T13:00:00Z,Pledge manager - Closed,True,2.0,5.0,8.0,15.0,0,2409627,NaN,"Card Game, Strategy, Party game, Family",Comber Cat,cat-lovers-99754,20.00,False,20.00,True,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,99754,NaN,1.0
4,5995,7221,€,1000.0,4042.67,89,2026-01-16T12:00:00Z,2026-02-28T12:00:00Z,Pledge manager - Closed,True,2.0,6.0,8.0,20.0,0,14439,2026-06-11T13:00:00Z,"Strategy, Resource management, Family, Worker ...",Jano - A Pawsome Adventure,jano-board-game-92756,25.00,False,25.00,True,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,92756,NaN,1.0

### 파생 변수 생성

In [21]:
final_df['campaignStart'] = pd.to_datetime(final_df['campaignStart'])
final_df['campaignEnd'] = pd.to_datetime(final_df['campaignEnd'], format='ISO8601')


# creatorID -> 그 당시 몇개 만들었는지
final_df = final_df.sort_values(by='campaignStart')
final_df['previous_campaigns_count'] = final_df.groupby('creatorID').cumcount()
final_df = final_df.sort_index()

# 프로젝트 진행 기간 계산
final_df['duration_days'] = (final_df['campaignEnd'] - final_df['campaignStart']).dt.days

# 댓글 수집 기준일 계산 (시작일로부터 1주일, 2주일 뒤) 댓글 조인 후 날짜 잘라도?
#final_df['comment_target_1w'] = final_df['campaignStart'] + pd.Timedelta(days=7)

# playTime 단위 통일 (playTimeUnit이 1이면 시간 단위 -> 분으로 변환)
final_df.loc[final_df['playTimeUnit'] == 1, 'playTime'] = final_df['playTime'] * 60

# pledgeManagerSoftCloseDeadline 존재 여부 (방치 여부/관리 척도)
final_df['softclose'] = final_df['pledgeManagerSoftCloseDeadline'].notna().astype(int)

# projectTags 원핫인코딩
#tags_encoded = final_df['projectTags'].fillna('').str.get_dummies(sep=', ')
#final_df = pd.concat([final_df, tags_encoded], axis=1)

### 환율 통일(시점 달라지므로 될 수 있으면 실행X 파일 받아서 아래 read_csv로)

In [22]:
from datetime import date, timedelta
import requests
import numpy as np
import pandas as pd
import time

# ==========================================
# 1. 기준 날짜 세팅
# ==========================================
end_date = date.today()
start_date_1m = end_date - timedelta(days=30)
start_date_6m = end_date - timedelta(days=180)

# ==========================================
# 2. 지워진 환율 계산 함수 복구
# ==========================================
def get_avg_rates_to_usd(base_currency, start_1m, start_6m, end_dt):
    """
    한 번의 API 호출로 1개월, 6개월 평균 환율을 동시에 계산하여 반환
    """
    if base_currency == "USD" or pd.isna(base_currency):
        return 1.0, 1.0

    url = (
        f"https://api.frankfurter.app/"
        f"{start_6m}..{end_dt}"
        f"?base={base_currency}&symbols=USD"
    )

    res = requests.get(url)
    if res.status_code != 200:
        return np.nan, np.nan # 에러 발생 시 결측치 반환
        
    data = res.json()
    rates_1m = []
    rates_6m = []
    
    start_1m_str = start_1m.isoformat()

    for day, rate_info in data["rates"].items():
        if "USD" in rate_info:
            val = rate_info["USD"]
            rates_6m.append(val)
            if day >= start_1m_str:
                rates_1m.append(val)

    avg_1m = sum(rates_1m) / len(rates_1m) if rates_1m else np.nan
    avg_6m = sum(rates_6m) / len(rates_6m) if rates_6m else np.nan

    return avg_1m, avg_6m

In [23]:
# ==========================================
# 1. 만들어두신 통화 변환 코드 (그대로 사용!)
# ==========================================
symbol_to_code = {
    "$": "USD",
    "€": "EUR",
    "£": "GBP",
    "A$": "AUD",
    "C$": "CAD",
    "S$": "SGD",
    "zł": "PLN",
    "kr": "SEK",
    "kr.": "SEK",
    "Fr.": "CHF",
    "HK$": "HKD",
    "NZ$": "NZD",
    "Mex$": "MXN",
}

# 임시 정리용 컬럼 생성
final_df["_currencySymbol_clean"] = final_df["currencySymbol"].astype("string").str.strip()

# 최종으로 남길 currencyCode 컬럼 추가
final_df["currencyCode"] = final_df["_currencySymbol_clean"].map(symbol_to_code)

# 매핑 안 된 통화기호 확인
unmapped = final_df[final_df["currencyCode"].isna()]["currencySymbol"].drop_duplicates()
print("매핑 안 된 통화기호:")
print(unmapped)

# ==========================================
# 2. 환율 API 호출 및 데이터프레임 생성
# ==========================================
# NaN을 제외한 고유한 통화 코드만 리스트로 추출
currency_codes = final_df["currencyCode"].dropna().unique().tolist()
rates_data = []

print("\n환율 정보를 가져오는 중입니다...")
for code in currency_codes:
    # get_avg_rates_to_usd 함수와 날짜 변수들은 위 셀에서 실행해두셨다고 가정합니다.
    rate_1m, rate_6m = get_avg_rates_to_usd(code, start_date_1m, start_date_6m, end_date)
    
    rates_data.append({
        "currencyCode": code,
        "avg_rate_to_usd_1m": rate_1m,
        "avg_rate_to_usd_6m": rate_6m
    })
    
    time.sleep(1) # 차단 방지

rate_df = pd.DataFrame(rates_data)

# ==========================================
# 3. 원본 데이터(final_df)에 환율 데이터 병합(Merge)
# ==========================================
final_df = pd.merge(final_df, rate_df, on="currencyCode", how="left")

# ==========================================
# 4. 특수기호 제거 및 USD 환산 계산
# ==========================================
# 숫자 변환 (이전에 만들어둔 정규표현식 사용)
final_df["campaignGoal"] = pd.to_numeric(final_df["campaignGoal"].astype(str).str.replace(r'[^\d\.]', '', regex=True), errors="coerce")
final_df["fundsGathered"] = pd.to_numeric(final_df["fundsGathered"].astype(str).str.replace(r'[^\d\.]', '', regex=True), errors="coerce")
final_df["price"] = pd.to_numeric(final_df["price"].astype(str).str.replace(r'[^\d\.]', '', regex=True), errors="coerce")
final_df["effectivePrice"] = pd.to_numeric(final_df["effectivePrice"].astype(str).str.replace(r'[^\d\.]', '', regex=True), errors="coerce")


# 1달 기준 환산
final_df["campaignGoal_usd_1m"] = final_df["campaignGoal"] * final_df["avg_rate_to_usd_1m"]
final_df["fundsGathered_usd_1m"] = final_df["fundsGathered"] * final_df["avg_rate_to_usd_1m"]
final_df["price_usd_1m"] = final_df["price"] * final_df["avg_rate_to_usd_1m"]
final_df["effectivePrice"] = final_df["effectivePrice"] * final_df["avg_rate_to_usd_1m"]
# 6달 기준 환산
final_df["campaignGoal_usd_6m"] = final_df["campaignGoal"] * final_df["avg_rate_to_usd_6m"]
final_df["fundsGathered_usd_6m"] = final_df["fundsGathered"] * final_df["avg_rate_to_usd_6m"]
final_df["price_usd_6m"] = final_df["price"] * final_df["avg_rate_to_usd_6m"]
final_df["effectivePrice"] = final_df["effectivePrice"] * final_df["avg_rate_to_usd_6m"]

매핑 안 된 통화기호:
Series([], Name: currencySymbol, dtype: object)

환율 정보를 가져오는 중입니다...

In [24]:
final_df.head()

,projectID,creatorID,currencySymbol,campaignGoal,fundsGathered,backersCount,campaignStart,campaignEnd,phaseLabel,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,playTimeUnit,fundedInSeconds,pledgeManagerSoftCloseDeadline,projectTags,main_name,anchorRelativeUrl,price,isDiscounted,effectivePrice,isFeatured,purchasedCopiesCount,backgroundUrl,installmentCost,installmentMinPayment,hasLimitedStock,productCanBePurchased,productID,remainingStockLimit,single_item,previous_campaigns_count,duration_days,softclose,_currencySymbol_clean,currencyCode,avg_rate_to_usd_1m,avg_rate_to_usd_6m,campaignGoal_usd_1m,fundsGathered_usd_1m,price_usd_1m,campaignGoal_usd_6m,fundsGathered_usd_6m,price_usd_6m
0,5787,5252,$,10000.0,393538.44,1567,2025-06-17 14:30:00+00:00,2025-07-19 00:50:35.250000+00:00,Pledge manager - Closed,False,NaN,NaN,NaN,NaN,0,628,2026-06-02T15:00:00Z,"Exploration, Horror, Modern, Science Fiction, ...",We Played God - A Survival Miniatures Game,core-rules-physical-pdf-80323,60.00,False,60.000000,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,80323,NaN,1.0,0,31,1,$,USD,1.000000,1.000000,10000.000000,393538.44000,60.000000,10000.000000,393538.440000,60.000000
1,6481,6737,$,20000.0,247988.30,1075,2026-02-25 16:00:00+00:00,2026-03-31 15:57:23.953000+00:00,Pledge manager - Closed,True,1.0,4.0,13.0,90.0,0,2716,2026-06-01T14:00:00Z,"History, Strategy, Wargame, Action, Collectibl...",CARNIVORE,megapredator-digital-102621,57.00,False,57.000000,False,0,https://imgcdn.gamefound.com/productimage/proj...,28.5,100.0,False,False,102621,NaN,1.0,0,33,1,$,USD,1.000000,1.000000,20000.000000,247988.30000,57.000000,20000.000000,247988.300000,57.000000
2,8024,5141,$,7000.0,23091.47,215,2026-03-01 05:00:00+00:00,2026-04-01 05:00:00+00:00,Pledge manager - Closed,True,1.0,2.0,12.0,480.0,1,56442,NaN,"History, Strategy, Wargame",1809: Talavera,backers-copy-1809-talavera-99555,69.99,True,56.990000,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,99555,NaN,1.0,1,31,0,$,USD,1.000000,1.000000,7000.000000,23091.47000,69.990000,7000.000000,23091.470000,69.990000
3,8225,8739,$,300.0,645.66,12,2026-02-02 13:00:00+00:00,2026-03-02 13:00:00+00:00,Pledge manager - Closed,True,2.0,5.0,8.0,15.0,0,2409627,NaN,"Card Game, Strategy, Party game, Family",Comber Cat,cat-lovers-99754,20.00,False,20.000000,True,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,99754,NaN,1.0,0,28,0,$,USD,1.000000,1.000000,300.000000,645.66000,20.000000,300.000000,645.660000,20.000000
4,5995,7221,€,1000.0,4042.67,89,2026-01-16 12:00:00+00:00,2026-02-28 12:00:00+00:00,Pledge manager - Closed,True,2.0,6.0,8.0,20.0,0,14439,2026-06-11T13:00:00Z,"Strategy, Resource management, Family, Worker ...",Jano - A Pawsome Adventure,jano-board-game-92756,25.00,False,34.042277,True,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,92756,NaN,1.0,0,43,1,€,EUR,1.164032,1.169806,1164.031818,4705.79651,29.100795,1169.805738,4729.138562,29.245143

In [25]:
final_df = final_df.drop(columns=['creatorID','playTimeUnit','campaignGoal','fundsGathered','campaignStart','campaignEnd',
                                  'playTimeUnit', 'pledgeManagerSoftCloseDeadline','main_name','anchorRelativeUrl','price','effectivePrice',
                                  'purchasedCopiesCount','backgroundUrl','installmentCost','productID','single_item','remainingStockLimit','_currencySymbol_clean',
                                  'currencyCode','avg_rate_to_usd_1m','avg_rate_to_usd_6m'])

In [26]:
final_df

,projectID,currencySymbol,backersCount,phaseLabel,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,fundedInSeconds,projectTags,isDiscounted,isFeatured,installmentMinPayment,hasLimitedStock,productCanBePurchased,previous_campaigns_count,duration_days,softclose,campaignGoal_usd_1m,fundsGathered_usd_1m,price_usd_1m,campaignGoal_usd_6m,fundsGathered_usd_6m,price_usd_6m
0,5787,$,1567,Pledge manager - Closed,False,NaN,NaN,NaN,NaN,628,"Exploration, Horror, Modern, Science Fiction, ...",False,False,75.0,False,False,0,31,1,10000.000000,393538.440000,60.000000,10000.000000,393538.440000,60.000000
1,6481,$,1075,Pledge manager - Closed,True,1.0,4.0,13.0,90.0,2716,"History, Strategy, Wargame, Action, Collectibl...",False,False,100.0,False,False,0,33,1,20000.000000,247988.300000,57.000000,20000.000000,247988.300000,57.000000
2,8024,$,215,Pledge manager - Closed,True,1.0,2.0,12.0,480.0,56442,"History, Strategy, Wargame",True,False,NaN,False,False,1,31,0,7000.000000,23091.470000,69.990000,7000.000000,23091.470000,69.990000
3,8225,$,12,Pledge manager - Closed,True,2.0,5.0,8.0,15.0,2409627,"Card Game, Strategy, Party game, Family",False,True,NaN,False,False,0,28,0,300.000000,645.660000,20.000000,300.000000,645.660000,20.000000
4,5995,€,89,Pledge manager - Closed,True,2.0,6.0,8.0,20.0,14439,"Strategy, Resource management, Family, Worker ...",False,True,NaN,False,False,0,43,1,1164.031818,4705.796510,29.100795,1169.805738,4729.138562,29.245143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479,2109,€,113,Crowdfunding - Unsuccessful,True,2.0,4.0,14.0,180.0,0,"Strategy, Wargame, Dice Game, Area Control, Co...",False,True,NaN,False,False,0,21,0,23280.636364,9313.418577,81.482227,23396.114754,9359.615707,81.886402
480,2149,€,2,Crowdfunding - Unsuccessful,True,2.0,4.0,5.0,25.0,0,"Fantasy, Strategy, Humor",True,False,NaN,False,False,0,30,0,11407.511818,81.482227,23.164233,11464.096230,81.886402,23.279134
481,1919,€,143,Crowdfunding - Unsuccessful,True,1.0,4.0,14.0,30.0,0,"Dice Game, Multiplayer, Competitive, Campaign",True,True,NaN,False,False,0,16,0,11640.318182,7315.939977,41.905145,11698.057377,7352.229061,42.113007
482,1143,€,158,Crowdfunding - Unsuccessful,True,2.0,4.0,12.0,120.0,0,"Fantasy, Strategy, Terrain Building, Humor",False,False,NaN,False,False,0,33,0,23280.636364,15622.040340,58.201591,23396.114754,15699.529978,58.490287
483,1325,€,148,Crowdfunding - Unsuccessful,True,2.0,4.0,14.0,60.0,0,"Science Fiction, Area Control, Deck Building",False,False,NaN,False,False,0,24,0,34920.954545,12676.306500,50.053368,35094.172131,12739.184484,50.301647

In [ ]:
#final_df.to_csv("../../02_Data/processed/list+rewards_join.csv", index=False, encoding="utf-8-sig")

## 나머지 데이터 조인

In [ ]:
import pandas as pd

# 여기 부터 실행
final_df=pd.read_csv("../../02_Data/processed/list+rewards_join.csv")

voca_df = pd.read_csv('../../02_Data/raw/color_voca_최종.csv')
image_value_df = pd.read_csv('../../02_Data/raw/ML image values.csv')
rewards_count_df = pd.read_csv("../../02_Data/processed/final_rewards_tags.csv")

comment_df = pd.read_csv("../../02_Data/processed/final_all_results.csv")
comment2_df = pd.read_csv("../../02_Data/processed/텍스트_모델_긍정부정중립.csv")
comment3_df = pd.read_csv("../../02_Data/processed/project_group_category_count_wide.csv")

c:\Users\seon\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
c:\Users\seon\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [3]:
final_df

,projectID,currencySymbol,backersCount,phaseLabel,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,fundedInSeconds,...,productCanBePurchased,previous_campaigns_count,duration_days,softclose,campaignGoal_usd_1m,fundsGathered_usd_1m,price_usd_1m,campaignGoal_usd_6m,fundsGathered_usd_6m,price_usd_6m
0,5787,$,1567,Pledge manager - Closed,False,NaN,NaN,NaN,NaN,628,...,False,0,31,1,10000.000000,393538.440000,60.000000,10000.000000,393538.440000,60.000000
1,6481,$,1075,Pledge manager - Closed,True,1.0,4.0,13.0,90.0,2716,...,False,0,33,1,20000.000000,247988.300000,57.000000,20000.000000,247988.300000,57.000000
2,8024,$,215,Pledge manager - Closed,True,1.0,2.0,12.0,480.0,56442,...,False,1,31,0,7000.000000,23091.470000,69.990000,7000.000000,23091.470000,69.990000
3,8225,$,12,Pledge manager - Closed,True,2.0,5.0,8.0,15.0,2409627,...,False,0,28,0,300.000000,645.660000,20.000000,300.000000,645.660000,20.000000
4,5995,€,89,Pledge manager - Closed,True,2.0,6.0,8.0,20.0,14439,...,False,0,43,1,1164.031818,4705.796510,29.100795,1169.805738,4729.138562,29.245143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479,2109,€,113,Crowdfunding - Unsuccessful,True,2.0,4.0,14.0,180.0,0,...,False,0,21,0,23280.636364,9313.418577,81.482227,23396.114754,9359.615707,81.886402
480,2149,€,2,Crowdfunding - Unsuccessful,True,2.0,4.0,5.0,25.0,0,...,False,0,30,0,11407.511818,81.482227,23.164233,11464.096230,81.886402,23.279134
481,1919,€,143,Crowdfunding - Unsuccessful,True,1.0,4.0,14.0,30.0,0,...,False,0,16,0,11640.318182,7315.939977,41.905145,11698.057377,7352.229061,42.113007
482,1143,€,158,Crowdfunding - Unsuccessful,True,2.0,4.0,12.0,120.0,0,...,False,0,33,0,23280.636364,15622.040340,58.201591,23396.114754,15699.529978,58.490287
483,1325,€,148,Crowdfunding - Unsuccessful,True,2.0,4.0,14.0,60.0,0,...,False,0,24,0,34920.954545,12676.306500,50.053368,35094.172131,12739.184484,50.301647

### 프로젝트별 리워드 합치기

In [1]:
rewards_count_df

NameError: name 'rewards_count_df' is not defined

In [5]:
rewards_count_df['rewards_count'] = rewards_count_df.groupby('projectID')['projectID'].transform('count')

In [6]:
rewards_count_df=rewards_count_df[['projectID', 'rewards_count']].drop_duplicates()

### 이미지 RGB/ks_color/emotion 분리

In [7]:
voca_df

      Unnamed: 0  file_name            RGB ks_color emotion_adjective
0              0  10044.jpg        (3 2 4)    Black               무거운
1              1  10044.jpg     (73 95 50)    Green              이성적인
2              2  10044.jpg  (158 175 186)    White               잔잔한
3              3  10044.jpg   (210 137 94)   Orange                얕은
4              4  10156.jpg   (113 72 158)   Purple              감각적인
...          ...        ...            ...      ...               ...
1947        1947   9693.jpg   (190 117 24)   Orange              재미있는
1948        1948    975.jpg  (252 251 248)    White               연약한
1949        1949    975.jpg     (35 19 16)    Black               딱딱한
1950        1950    975.jpg    (142 70 51)    Brown              여유있는
1951        1951    975.jpg  (211 160 101)   Orange                얕은

[1952 rows x 5 columns]

In [8]:
voca_df['projectID'] = voca_df['file_name'].str.replace('.jpg', '', case=False)


voca_group_df = voca_df.groupby('projectID')['emotion_adjective'].apply(list).reset_index()

In [9]:
import pandas as pd


def parse_rgb(rgb_str):
    clean = rgb_str.replace('(', '').replace(')', '').strip()
    return [int(p) for p in clean.split()]

rgb_parsed = voca_df['RGB'].apply(parse_rgb)
voca_df['R'] = rgb_parsed.apply(lambda x: x[0])
voca_df['G'] = rgb_parsed.apply(lambda x: x[1])
voca_df['B'] = rgb_parsed.apply(lambda x: x[2])

voca_df['idx'] = voca_df.groupby('projectID').cumcount() + 1

pivot_rgb = voca_df.pivot(index='projectID', columns='idx', values=['R', 'G', 'B'])
pivot_rgb.columns = [f'{col[0]}{col[1]}' for col in pivot_rgb.columns]  # R1, G1, B1... 형태 변환

pivot_ks = voca_df.pivot(index='projectID', columns='idx', values='ks_color')
pivot_ks.columns = [f'ks_color_{col}' for col in pivot_ks.columns]

pivot_em = voca_df.pivot(index='projectID', columns='idx', values='emotion_adjective')
pivot_em.columns = [f'emotion_adjective_{col}' for col in pivot_em.columns]


final_voca_df = pd.concat([pivot_rgb, pivot_ks, pivot_em], axis=1).reset_index()

rgb_cols = []
for i in range(1, 5):
    rgb_cols.extend([f'R{i}', f'G{i}', f'B{i}'])
other_cols = [f'ks_color_{i}' for i in range(1, 5)] + [f'emotion_adjective_{i}' for i in range(1, 5)]

final_cols = ['projectID'] + rgb_cols + other_cols
final_voca_df = final_voca_df[final_cols]

In [10]:
final_voca_df

,projectID,R1,G1,B1,R2,G2,B2,R3,G3,B3,...,G4,B4,ks_color_1,ks_color_2,ks_color_3,ks_color_4,emotion_adjective_1,emotion_adjective_2,emotion_adjective_3,emotion_adjective_4
0,10044,3,2,4,73,95,50,158,175,186,...,137,94,Black,Green,White,Orange,무거운,이성적인,잔잔한,얕은
1,10156,113,72,158,8,5,10,210,89,155,...,193,203,Purple,Black,Pink,Pink,감각적인,깊은,여성적인,연약한
2,1032,24,26,29,92,92,93,179,3,4,...,189,182,Black,Grey,Red,White,탁한,정적인,젊은,약한
3,1060,249,195,126,74,51,40,169,116,89,...,163,218,Yellow,Black,Brown,Blue,가벼운,지적인,풍성한,즐거운
4,1066,251,252,248,35,50,51,202,200,130,...,122,82,White,Black,YellowGreen,Grey,연약한,견실한,자연적인,동양적인
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
483,887,91,90,90,35,22,20,146,151,155,...,233,233,Grey,Black,Grey,White,정적인,견고한,가지런한,약한
484,889,173,97,189,30,14,54,100,43,143,...,232,241,Purple,Indigo,Purple,White,친근한,강인한,한국적인,연약한
485,954,54,49,47,90,88,92,168,117,83,...,161,155,Black,Grey,Brown,Grey,우울한,정적인,풍성한,가지런한
486,9693,47,47,57,151,141,150,228,224,226,...,117,24,Indigo,Grey,White,Orange,나이든,그윽한,약한,재미있는
487,975,252,251,248,35,19,16,142,70,51,...,160,101,White,Black,Brown,Orange,연약한,딱딱한,여유있는,얕은

In [11]:
final_voca_df['projectID'] = final_voca_df['projectID'].astype(int)
voca_group_df['projectID'] = voca_group_df['projectID'].astype(int)

In [12]:
voca_group_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 488 entries, 0 to 487
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   projectID          488 non-null    int32
 1   emotion_adjective  488 non-null    object
dtypes: int32(1), object(1)
memory usage: 5.8+ KB

In [13]:
voca_group_df

     projectID       emotion_adjective
0        10044    [무거운, 이성적인, 잔잔한, 얕은]
1        10156   [감각적인, 깊은, 여성적인, 연약한]
2         1032       [탁한, 정적인, 젊은, 약한]
3         1060    [가벼운, 지적인, 풍성한, 즐거운]
4         1066  [연약한, 견실한, 자연적인, 동양적인]
..         ...                     ...
483        887    [정적인, 견고한, 가지런한, 약한]
484        889   [친근한, 강인한, 한국적인, 연약한]
485        954   [우울한, 정적인, 풍성한, 가지런한]
486       9693    [나이든, 그윽한, 약한, 재미있는]
487        975    [연약한, 딱딱한, 여유있는, 얕은]

[488 rows x 2 columns]

### 이미지 명도 채도

In [20]:
image_target=['file_name','edge_density','saturation','brightness','contrast']
image_value_df=image_value_df[image_target]
image_value_df = image_value_df.rename(columns={'file_name': 'projectID'})

In [21]:
image_value_df

     projectID  edge_density  saturation  brightness   contrast
0        10044      0.035953  151.934261  101.769988  72.865527
1        10156      0.098027   99.230996  139.983986  67.902555
2         1032      0.105622   89.842802   85.682818  57.622883
3         1060      0.079392  133.183312  179.929022  68.797804
4         1066      0.080177   81.220794  168.191708  85.505299
..         ...           ...         ...         ...        ...
483        887      0.109759   68.516292  112.346584  63.811391
484        889      0.073335  132.690955  160.486292  80.752542
485        954      0.111676   76.826663  105.876214  42.985940
486       9693      0.086024   84.710718  142.702398  73.063960
487        975      0.123035   91.411208  162.839959  95.628864

[488 rows x 5 columns]

### comment_df normal 태그 누락으로 추가

In [24]:
normal_df = pd.read_csv("../../02_Data/processed/comments_merged_thread_add_tag.csv")

In [25]:
df_normal_sum = (
    normal_df
    .groupby(["projectID", "thread_id"], as_index=False)
    .agg(is_normal=("is_normal", "sum"))
)

In [26]:
df_normal_sum

       projectID  thread_id  is_normal
0            222        970          0
1            222        971          0
2            222        972          0
3            222        973          0
4            222        974          0
...          ...        ...        ...
73434      10156    2556182          0
73435      10156    2557683          0
73436      10156    2560083          0
73437      10156    2560314          0
73438      10156    2563440          0

[73439 rows x 3 columns]

In [27]:
comment_df = pd.merge(comment_df, df_normal_sum, on=["projectID", "thread_id"], how="left")

In [28]:
comment_df

,thread_id,projectID,group,n_comments,merged_comment,creator_id,is_pledge_master,is_backer,is_prior_backer,is_pathfinder,likes,category,is_normal
0,1691589,5787,0,1,WELCOME TO EDEN! Please check the FAQ and the...,1,0,0,0,0,26,Praise_Support,0
1,1725920,5787,0,2,@BlackSiteStudios Could a person use larger di...,1,1,1,0,0,0,Product_Question,0
2,1725876,5787,0,1,about an hour left to go,0,1,1,1,0,1,Spam_Irrelevant,0
3,1725671,5787,0,1,Man 2 hours to go worth staying up to midnight...,0,0,0,0,0,3,Praise_Support,1
4,1725512,5787,0,1,5 hours to go! Hold on to your butts!,0,0,1,1,0,5,Praise_Support,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
73434,133497,1143,1,3,"Hello. Will it be in Spanish? and if not, woul...",1,2,0,0,0,4,Product_Question,0
73435,133314,1143,1,2,Not sure if people get notifications for repli...,1,1,1,0,0,4,Product_Question,0
73436,133207,1143,1,2,The project looks interesting! Who is the desi...,1,0,0,0,0,0,Product_Question,1
73437,133159,1143,1,3,"Hi, is there the future possibility of a solo ...",1,1,0,0,0,11,Suggestion_Idea,1
73438,133074,1143,1,4,Question about the standard vs. innkeepers edi...,2,2,1,0,0,3,Product_Question,0

In [29]:
len(set(comment_df['projectID']))

473

### 코멘트 그룹 분리(0:upcomming 1:start~+3)

In [30]:
import pandas as pd

sum_cols = ['creator_id', 'is_pledge_master', 'is_backer', 'is_prior_backer', 'is_pathfinder','is_normal','likes']
valid_categories = ['Product_Question', 'Suggestion_Idea', 'Praise_Support', 'Shipping_Fulfillment', 'Complaint_Refund', 'Spam_Irrelevant']


df_sums_group = comment_df.groupby(['projectID', 'group'])[sum_cols].sum().reset_index()
df_cat_group = comment_df.groupby(['projectID', 'group', 'category']).size().unstack(fill_value=0)
df_cat_group = df_cat_group.reindex(columns=valid_categories, fill_value=0).reset_index()


df_merged_group = pd.merge(df_sums_group, df_cat_group, on=['projectID', 'group'], how='outer')
rename_dict = {cat: f"{cat}_count" for cat in valid_categories}
df_merged_group = df_merged_group.rename(columns=rename_dict)


pivot_target_cols = [col for col in df_merged_group.columns if col not in ['projectID', 'group']]
df_pivot = df_merged_group.pivot(index='projectID', columns='group', values=pivot_target_cols)

df_pivot.columns = [f"{col[0]}_{col[1]}" for col in df_pivot.columns]
df_pivot = df_pivot.reset_index()

In [31]:
df_pivot

,projectID,creator_id_0,creator_id_1,is_pledge_master_0,is_pledge_master_1,is_backer_0,is_backer_1,is_prior_backer_0,is_prior_backer_1,is_pathfinder_0,...,Suggestion_Idea_count_0,Suggestion_Idea_count_1,Praise_Support_count_0,Praise_Support_count_1,Shipping_Fulfillment_count_0,Shipping_Fulfillment_count_1,Complaint_Refund_count_0,Complaint_Refund_count_1,Spam_Irrelevant_count_0,Spam_Irrelevant_count_1
0,222,3.0,56.0,883.0,1823.0,1569.0,3027.0,1694.0,3178.0,88.0,...,247.0,317.0,146.0,188.0,46.0,151.0,1.0,20.0,38.0,75.0
1,769,63.0,266.0,89.0,429.0,177.0,710.0,209.0,866.0,11.0,...,42.0,73.0,36.0,39.0,4.0,37.0,1.0,5.0,12.0,4.0
2,806,15.0,26.0,21.0,27.0,7.0,24.0,0.0,0.0,0.0,...,0.0,2.0,3.0,5.0,1.0,2.0,2.0,0.0,0.0,1.0
3,862,40.0,65.0,78.0,332.0,150.0,497.0,126.0,403.0,6.0,...,28.0,33.0,16.0,45.0,1.0,19.0,0.0,2.0,0.0,3.0
4,887,182.0,79.0,346.0,399.0,420.0,665.0,19.0,89.0,5.0,...,96.0,73.0,38.0,20.0,16.0,13.0,30.0,42.0,21.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
468,8515,13.0,6.0,11.0,2.0,9.0,1.0,9.0,1.0,0.0,...,2.0,0.0,1.0,2.0,1.0,1.0,0.0,0.0,0.0,0.0
469,8517,3.0,16.0,7.0,5.0,1.0,7.0,0.0,0.0,0.0,...,0.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
470,8526,0.0,3.0,356.0,386.0,337.0,357.0,464.0,442.0,38.0,...,98.0,50.0,38.0,7.0,4.0,9.0,8.0,7.0,11.0,5.0
471,9693,9.0,3.0,7.0,4.0,2.0,4.0,0.0,0.0,0.0,...,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
472,10156,8.0,25.0,29.0,79.0,19.0,46.0,32.0,85.0,0.0,...,0.0,2.0,5.0,10.0,3.0,5.0,0.0,1.0,0.0,1.0

### 코멘트2 (긍/부/중)

In [32]:
comment2_df.head()

,Unnamed: 0,projectID,thread_id,group,comment_ids,n_comments,merged_comment,creator_id,is_pledge_master,is_backer,is_prior_backer,is_pathfinder,merged_comment_clean,sentiment,sentiment_score,neg_prob,neu_prob,pos_prob
0,0,5787,1691589,0,[1691589],1,WELCOME TO EDEN! Please check the FAQ and the...,1,0,0,0,0,WELCOME TO EDEN! Please check the FAQ and the ...,중립,0.878054,0.017368,0.878054,0.104578
1,1,5787,1725920,0,"[1725920, 1726005]",2,@BlackSiteStudios Could a person use larger di...,1,1,1,0,0,@BlackSiteStudios Could a person use larger di...,중립,0.974757,0.008432,0.974757,0.016811
2,2,5787,1725876,0,[1725876],1,about an hour left to go,0,1,1,1,0,about an hour left to go,긍정,0.594570,0.017809,0.387621,0.594570
3,3,5787,1725671,0,[1725671],1,Man 2 hours to go worth staying up to midnight...,0,0,0,0,0,Man 2 hours to go worth staying up to midnight...,긍정,0.974869,0.010197,0.014934,0.974869
4,4,5787,1725512,0,[1725512],1,5 hours to go! Hold on to your butts!,0,0,1,1,0,5 hours to go! Hold on to your butts!,긍정,0.744915,0.087658,0.167427,0.744915

In [33]:
import pandas as pd

df_sent_group = comment2_df.groupby(['projectID', 'group', 'sentiment']).size().unstack(fill_value=0).reset_index()


sentiment_cols = ['긍정', '부정', '중립']
df_sent_pivot = df_sent_group.pivot(index='projectID', columns='group', values=sentiment_cols)


df_sent_pivot.columns = [f"{col[0]}_{col[1]}" for col in df_sent_pivot.columns]
df_sent_pivot = df_sent_pivot.reset_index()

In [34]:
df_sent_pivot

     projectID   긍정_0   긍정_1   부정_0   부정_1   중립_0   중립_1
0          222  273.0  336.0  141.0  299.0  278.0  452.0
1          769   81.0   84.0   17.0   66.0   63.0  236.0
2          806    3.0    7.0    3.0    3.0    3.0    8.0
3          862   42.0   76.0    2.0   15.0   38.0  113.0
4          887  120.0   72.0   63.0   97.0  186.0  163.0
..         ...    ...    ...    ...    ...    ...    ...
468       8515    6.0    3.0    1.0    1.0    5.0    2.0
469       8517    2.0    4.0    0.0    0.0    0.0    4.0
470       8526   98.0   39.0   40.0   32.0  126.0  102.0
471       9693    3.0    3.0    0.0    0.0    3.0    2.0
472      10156    6.0   13.0    3.0   12.0    8.0   17.0

[473 rows x 7 columns]

### 코멘트3(BERT 7중)

In [35]:
comment3_df.head()

,projectID,group,Campaign / Pledge,Community Reaction,Components & Production,Gameplay / Rules / Content,Language & Localization,Schedule / Updates,Shipping / Price / Tax
0,222,0,64.0,152.0,75.0,263.0,37.0,53.0,47.0
1,222,1,225.0,185.0,92.0,309.0,63.0,80.0,133.0
2,769,0,17.0,41.0,60.0,28.0,7.0,5.0,3.0
3,769,1,69.0,31.0,183.0,32.0,15.0,23.0,33.0
4,806,0,1.0,2.0,1.0,5.0,0.0,0.0,0.0

In [36]:
import pandas as pd

pivot_cols = [col for col in comment3_df.columns if col not in ['projectID', 'group']]
df_wide_pivot = comment3_df.pivot(index='projectID', columns='group', values=pivot_cols)

df_wide_pivot.columns = [f"{col[0]}_{col[1]}" for col in df_wide_pivot.columns]
df_wide_pivot = df_wide_pivot.reset_index()

In [37]:
df_wide_pivot

,projectID,Campaign / Pledge_0,Campaign / Pledge_1,Community Reaction_0,Community Reaction_1,Components & Production_0,Components & Production_1,Gameplay / Rules / Content_0,Gameplay / Rules / Content_1,Language & Localization_0,Language & Localization_1,Schedule / Updates_0,Schedule / Updates_1,Shipping / Price / Tax_0,Shipping / Price / Tax_1
0,222,64.0,225.0,152.0,185.0,75.0,92.0,263.0,309.0,37.0,63.0,53.0,80.0,47.0,133.0
1,769,17.0,69.0,41.0,31.0,60.0,183.0,28.0,32.0,7.0,15.0,5.0,23.0,3.0,33.0
2,806,1.0,2.0,2.0,6.0,1.0,0.0,5.0,6.0,0.0,1.0,0.0,1.0,0.0,2.0
3,862,7.0,47.0,16.0,40.0,3.0,11.0,39.0,70.0,15.0,8.0,1.0,7.0,1.0,21.0
4,887,14.0,93.0,49.0,18.0,21.0,39.0,139.0,92.0,85.0,41.0,43.0,11.0,18.0,38.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
468,8515,4.0,0.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,2.0,2.0,0.0,0.0,1.0
469,8517,0.0,0.0,1.0,1.0,0.0,1.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0
470,8526,35.0,38.0,53.0,15.0,57.0,53.0,72.0,48.0,28.0,9.0,15.0,6.0,4.0,4.0
471,9693,0.0,1.0,0.0,0.0,1.0,1.0,3.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0
472,10156,5.0,8.0,5.0,4.0,2.0,13.0,2.0,11.0,0.0,0.0,3.0,5.0,0.0,1.0

### merge 및 확인

In [38]:
import pandas as pd

df_final_merged = final_df.copy()

df_final_merged = pd.merge(df_final_merged, image_value_df, on='projectID', how='left')
df_final_merged = pd.merge(df_final_merged, rewards_count_df, on='projectID', how='left')
df_final_merged = pd.merge(df_final_merged, final_voca_df, on='projectID', how='left')
df_final_merged = pd.merge(df_final_merged, df_pivot, on='projectID', how='left')
df_final_merged = pd.merge(df_final_merged, df_sent_pivot, on='projectID', how='left')
df_final_merged = pd.merge(df_final_merged, df_wide_pivot, on='projectID', how='left')

In [39]:
df_final_merged

,projectID,currencySymbol,backersCount,phaseLabel,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,fundedInSeconds,...,Components & Production_0,Components & Production_1,Gameplay / Rules / Content_0,Gameplay / Rules / Content_1,Language & Localization_0,Language & Localization_1,Schedule / Updates_0,Schedule / Updates_1,Shipping / Price / Tax_0,Shipping / Price / Tax_1
0,5787,$,1567,Pledge manager - Closed,False,NaN,NaN,NaN,NaN,628,...,3.0,6.0,29.0,37.0,10.0,4.0,4.0,1.0,4.0,7.0
1,6481,$,1075,Pledge manager - Closed,True,1.0,4.0,13.0,90.0,2716,...,4.0,4.0,112.0,44.0,12.0,0.0,10.0,2.0,8.0,17.0
2,8024,$,215,Pledge manager - Closed,True,1.0,2.0,12.0,480.0,56442,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
3,8225,$,12,Pledge manager - Closed,True,2.0,5.0,8.0,15.0,2409627,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,5995,€,89,Pledge manager - Closed,True,2.0,6.0,8.0,20.0,14439,...,0.0,0.0,2.0,0.0,3.0,2.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479,2109,€,113,Crowdfunding - Unsuccessful,True,2.0,4.0,14.0,180.0,0,...,1.0,0.0,5.0,2.0,2.0,1.0,0.0,0.0,0.0,3.0
480,2149,€,2,Crowdfunding - Unsuccessful,True,2.0,4.0,5.0,25.0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
481,1919,€,143,Crowdfunding - Unsuccessful,True,1.0,4.0,14.0,30.0,0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
482,1143,€,158,Crowdfunding - Unsuccessful,True,2.0,4.0,12.0,120.0,0,...,3.0,0.0,7.0,4.0,1.0,2.0,1.0,0.0,2.0,1.0
483,1325,€,148,Crowdfunding - Unsuccessful,True,2.0,4.0,14.0,60.0,0,...,0.0,0.0,12.0,1.0,1.0,3.0,2.0,0.0,0.0,1.0

In [40]:
drop_ids = [1476]
df_final_merged = df_final_merged[~df_final_merged['projectID'].isin(drop_ids)]

In [41]:
df_final_merged

,projectID,currencySymbol,backersCount,phaseLabel,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,fundedInSeconds,...,Components & Production_0,Components & Production_1,Gameplay / Rules / Content_0,Gameplay / Rules / Content_1,Language & Localization_0,Language & Localization_1,Schedule / Updates_0,Schedule / Updates_1,Shipping / Price / Tax_0,Shipping / Price / Tax_1
0,5787,$,1567,Pledge manager - Closed,False,NaN,NaN,NaN,NaN,628,...,3.0,6.0,29.0,37.0,10.0,4.0,4.0,1.0,4.0,7.0
1,6481,$,1075,Pledge manager - Closed,True,1.0,4.0,13.0,90.0,2716,...,4.0,4.0,112.0,44.0,12.0,0.0,10.0,2.0,8.0,17.0
2,8024,$,215,Pledge manager - Closed,True,1.0,2.0,12.0,480.0,56442,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
3,8225,$,12,Pledge manager - Closed,True,2.0,5.0,8.0,15.0,2409627,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,5995,€,89,Pledge manager - Closed,True,2.0,6.0,8.0,20.0,14439,...,0.0,0.0,2.0,0.0,3.0,2.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479,2109,€,113,Crowdfunding - Unsuccessful,True,2.0,4.0,14.0,180.0,0,...,1.0,0.0,5.0,2.0,2.0,1.0,0.0,0.0,0.0,3.0
480,2149,€,2,Crowdfunding - Unsuccessful,True,2.0,4.0,5.0,25.0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
481,1919,€,143,Crowdfunding - Unsuccessful,True,1.0,4.0,14.0,30.0,0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
482,1143,€,158,Crowdfunding - Unsuccessful,True,2.0,4.0,12.0,120.0,0,...,3.0,0.0,7.0,4.0,1.0,2.0,1.0,0.0,2.0,1.0
483,1325,€,148,Crowdfunding - Unsuccessful,True,2.0,4.0,14.0,60.0,0,...,0.0,0.0,12.0,1.0,1.0,3.0,2.0,0.0,0.0,1.0

In [42]:
df_final_merged.isnull()

,projectID,currencySymbol,backersCount,phaseLabel,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,fundedInSeconds,...,Components & Production_0,Components & Production_1,Gameplay / Rules / Content_0,Gameplay / Rules / Content_1,Language & Localization_0,Language & Localization_1,Schedule / Updates_0,Schedule / Updates_1,Shipping / Price / Tax_0,Shipping / Price / Tax_1
0,False,False,False,False,False,True,True,True,True,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
480,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
481,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
482,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
483,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [43]:
df_final_merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 483 entries, 0 to 483
Data columns (total 96 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   projectID                     483 non-null    int64
 1   currencySymbol                483 non-null    object
 2   backersCount                  483 non-null    int64
 3   phaseLabel                    483 non-null    object
 4   enableBoardGameProperties     483 non-null    bool
 5   minPlayers                    469 non-null    float64
 6   maxPlayers                    469 non-null    float64
 7   minAge                        452 non-null    float64
 8   playTime                      456 non-null    float64
 9   fundedInSeconds               483 non-null    int64
 10  projectTags                   483 non-null    object
 11  isDiscounted                  483 non-null    bool
 12  isFeatured                    483 non-null    bool
 13  installmentMinPayment         253 non-null    float64
 14  hasLimitedStock               483 non-null    bool
 15  productCanBePurchased         483 non-null    bool
 16  previous_campaigns_count      483 non-null    int64
 17  duration_days                 483 non-null    int64
 18  softclose                     483 non-null    int64
 19  campaignGoal_usd_1m           483 non-null    float64
 20  fundsGathered_usd_1m          483 non-null    float64
 21  price_usd_1m                  483 non-null    float64
 22  campaignGoal_usd_6m           483 non-null    float64
 23  fundsGathered_usd_6m          483 non-null    float64
 24  price_usd_6m                  483 non-null    float64
 25  edge_density                  483 non-null    float64
 26  saturation                    483 non-null    float64
 27  brightness                    483 non-null    float64
 28  contrast                      483 non-null    float64
 29  rewards_count                 483 non-null    int64
 30  R1                            483 non-null    int64
 31  G1                            483 non-null    int64
 32  B1                            483 non-null    int64
 33  R2                            483 non-null    int64
 34  G2                            483 non-null    int64
 35  B2                            483 non-null    int64
 36  R3                            483 non-null    int64
 37  G3                            483 non-null    int64
 38  B3                            483 non-null    int64
 39  R4                            483 non-null    int64
 40  G4                            483 non-null    int64
 41  B4                            483 non-null    int64
 42  ks_color_1                    483 non-null    object
 43  ks_color_2                    483 non-null    object
 44  ks_color_3                    483 non-null    object
 45  ks_color_4                    483 non-null    object
 46  emotion_adjective_1           483 non-null    object
 47  emotion_adjective_2           483 non-null    object
 48  emotion_adjective_3           483 non-null    object
 49  emotion_adjective_4           483 non-null    object
 50  creator_id_0                  455 non-null    float64
 51  creator_id_1                  439 non-null    float64
 52  is_pledge_master_0            455 non-null    float64
 53  is_pledge_master_1            439 non-null    float64
 54  is_backer_0                   455 non-null    float64
 55  is_backer_1                   439 non-null    float64
 56  is_prior_backer_0             455 non-null    float64
 57  is_prior_backer_1             439 non-null    float64
 58  is_pathfinder_0               455 non-null    float64
 59  is_pathfinder_1               439 non-null    float64
 60  is_normal_0                   455 non-null    float64
 61  is_normal_1                   439 non-null    float64
 62  likes_0                       455 non-null    float64
 63  likes_1                       439 non-null    float64
 64  Product_Question_count_0      455 non-null    float64
 65  Product_Question_count_1      439 non-null    float64
 66  Suggestion_Idea_count_0       455 non-null    float64
 67  Suggestion_Idea_count_1       439 non-null    float64
 68  Praise_Support_count_0        455 non-null    float64
 69  Praise_Support_count_1        439 non-null    float64
 70  Shipping_Fulfillment_count_0  455 non-null    float64
 71  Shipping_Fulfillment_count_1  439 non-null    float64
 72  Complaint_Refund_count_0      455 non-null    float64
 73  Complaint_Refund_count_1      439 non-null    float64
 74  Spam_Irrelevant_count_0       455 non-null    float64
 75  Spam_Irrelevant_count_1       439 non-null    float64
 76  긍정_0                          455 non-null    float64
 77  긍정_1                          439 non-null    float64
 78  부정_0                          455 non-null    float64
 79  부정_1                          439 non-null    float64
 80  중립_0                          455 non-null    float64
 81  중립_1                          439 non-null    float64
 82  Campaign / Pledge_0           469 non-null    float64
 83  Campaign / Pledge_1           469 non-null    float64
 84  Community Reaction_0          469 non-null    float64
 85  Community Reaction_1          469 non-null    float64
 86  Components & Production_0     469 non-null    float64
 87  Components & Production_1     469 non-null    float64
 88  Gameplay / Rules / Content_0  469 non-null    float64
 89  Gameplay / Rules / Content_1  469 non-null    float64
 90  Language & Localization_0     469 non-null    float64
 91  Language & Localization_1     469 non-null    float64
 92  Schedule / Updates_0          469 non-null    float64
 93  Schedule / Updates_1          469 non-null    float64
 94  Shipping / Price / Tax_0      469 non-null    float64
 95  Shipping / Price / Tax_1      469 non-null    float64
dtypes: bool(5), float64(61), int64(19), object(11)
memory usage: 349.5+ KB

In [44]:
df_final_merged.to_csv('../../02_Data/processed/final_merged_projects.csv', index=False,encoding="utf-8-sig")

In [32]:
df_final_merged

,projectID,currencySymbol,backersCount,phaseLabel,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,fundedInSeconds,...,Components & Production_0,Components & Production_1,Gameplay / Rules / Content_0,Gameplay / Rules / Content_1,Language & Localization_0,Language & Localization_1,Schedule / Updates_0,Schedule / Updates_1,Shipping / Price / Tax_0,Shipping / Price / Tax_1
0,5787,$,1567,Pledge manager - Closed,False,NaN,NaN,NaN,NaN,628,...,3.0,6.0,29.0,37.0,10.0,4.0,4.0,1.0,4.0,7.0
1,6481,$,1075,Pledge manager - Closed,True,1.0,4.0,13.0,90.0,2716,...,4.0,4.0,112.0,44.0,12.0,0.0,10.0,2.0,8.0,17.0
2,8024,$,215,Pledge manager - Closed,True,1.0,2.0,12.0,480.0,56442,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
3,8225,$,12,Pledge manager - Closed,True,2.0,5.0,8.0,15.0,2409627,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,5995,€,89,Pledge manager - Closed,True,2.0,6.0,8.0,20.0,14439,...,0.0,0.0,2.0,0.0,3.0,2.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479,2109,€,113,Crowdfunding - Unsuccessful,True,2.0,4.0,14.0,180.0,0,...,1.0,0.0,5.0,2.0,2.0,1.0,0.0,0.0,0.0,3.0
480,2149,€,2,Crowdfunding - Unsuccessful,True,2.0,4.0,5.0,25.0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
481,1919,€,143,Crowdfunding - Unsuccessful,True,1.0,4.0,14.0,30.0,0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
482,1143,€,158,Crowdfunding - Unsuccessful,True,2.0,4.0,12.0,120.0,0,...,3.0,0.0,7.0,4.0,1.0,2.0,1.0,0.0,2.0,1.0
483,1325,€,148,Crowdfunding - Unsuccessful,True,2.0,4.0,14.0,60.0,0,...,0.0,0.0,12.0,1.0,1.0,3.0,2.0,0.0,0.0,1.0