In [1]:
import pandas as pd
df=pd.read_csv("../../02_Data/processed/final_merged_projects.csv")

In [2]:
df.columns

Index(['projectID', 'currencySymbol', 'backersCount', 'phaseLabel',
       'enableBoardGameProperties', 'minPlayers', 'maxPlayers', 'minAge',
       'playTime', 'fundedInSeconds', 'projectTags', 'isDiscounted',
       'isFeatured', 'installmentMinPayment', 'hasLimitedStock',
       'productCanBePurchased', 'previous_campaigns_count', 'duration_days',
       'softclose', 'campaignGoal_usd_1m', 'fundsGathered_usd_1m',
       'price_usd_1m', 'campaignGoal_usd_6m', 'fundsGathered_usd_6m',
       'price_usd_6m', 'R1', 'G1', 'B1', 'R2', 'G2', 'B2', 'R3', 'G3', 'B3',
       'R4', 'G4', 'B4', 'ks_color_1', 'ks_color_2', 'ks_color_3',
       'ks_color_4', 'emotion_adjective_1', 'emotion_adjective_2',
       'emotion_adjective_3', 'emotion_adjective_4', 'creator_id_0',
       'creator_id_1', 'is_pledge_master_0', 'is_pledge_master_1',
       'is_backer_0', 'is_backer_1', 'is_prior_backer_0', 'is_prior_backer_1',
       'is_pathfinder_0', 'is_pathfinder_1', 'is_normal_0', 'is_normal_1',
       'likes_0', 'likes_1', 'Product_Question_count_0',
       'Product_Question_count_1', 'Suggestion_Idea_count_0',
       'Suggestion_Idea_count_1', 'Praise_Support_count_0',
       'Praise_Support_count_1', 'Shipping_Fulfillment_count_0',
       'Shipping_Fulfillment_count_1', 'Complaint_Refund_count_0',
       'Complaint_Refund_count_1', 'Spam_Irrelevant_count_0',
       'Spam_Irrelevant_count_1', '긍정_0', '긍정_1', '부정_0', '부정_1', '중립_0',
       '중립_1', 'Campaign / Pledge_0', 'Campaign / Pledge_1',
       'Community Reaction_0', 'Community Reaction_1',
       'Components & Production_0', 'Components & Production_1',
       'Gameplay / Rules / Content_0', 'Gameplay / Rules / Content_1',
       'Language & Localization_0', 'Language & Localization_1',
       'Schedule / Updates_0', 'Schedule / Updates_1',
       'Shipping / Price / Tax_0', 'Shipping / Price / Tax_1'],
      dtype='object')

In [3]:
# pd.set_option('display.max_columns', None)
df

,projectID,currencySymbol,backersCount,phaseLabel,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,fundedInSeconds,...,Components & Production_0,Components & Production_1,Gameplay / Rules / Content_0,Gameplay / Rules / Content_1,Language & Localization_0,Language & Localization_1,Schedule / Updates_0,Schedule / Updates_1,Shipping / Price / Tax_0,Shipping / Price / Tax_1
0,5787,$,1567,Pledge manager - Closed,False,NaN,NaN,NaN,NaN,628,...,3.0,6.0,29.0,37.0,10.0,4.0,4.0,1.0,4.0,7.0
1,6481,$,1075,Pledge manager - Closed,True,1.0,4.0,13.0,90.0,2716,...,4.0,4.0,112.0,44.0,12.0,0.0,10.0,2.0,8.0,17.0
2,8024,$,215,Pledge manager - Closed,True,1.0,2.0,12.0,480.0,56442,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
3,8225,$,12,Pledge manager - Closed,True,2.0,5.0,8.0,15.0,2409627,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,5995,€,89,Pledge manager - Closed,True,2.0,6.0,8.0,20.0,14439,...,0.0,0.0,2.0,0.0,3.0,2.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
478,2109,€,113,Crowdfunding - Unsuccessful,True,2.0,4.0,14.0,180.0,0,...,1.0,0.0,5.0,2.0,2.0,1.0,0.0,0.0,0.0,3.0
479,2149,€,2,Crowdfunding - Unsuccessful,True,2.0,4.0,5.0,25.0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
480,1919,€,143,Crowdfunding - Unsuccessful,True,1.0,4.0,14.0,30.0,0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
481,1143,€,158,Crowdfunding - Unsuccessful,True,2.0,4.0,12.0,120.0,0,...,3.0,0.0,7.0,4.0,1.0,2.0,1.0,0.0,2.0,1.0
482,1325,€,148,Crowdfunding - Unsuccessful,True,2.0,4.0,14.0,60.0,0,...,0.0,0.0,12.0,1.0,1.0,3.0,2.0,0.0,0.0,1.0

In [4]:
pd.set_option('display.max_columns', None)
df.head()

,projectID,currencySymbol,backersCount,phaseLabel,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,fundedInSeconds,projectTags,isDiscounted,isFeatured,installmentMinPayment,hasLimitedStock,productCanBePurchased,previous_campaigns_count,duration_days,softclose,campaignGoal_usd_1m,fundsGathered_usd_1m,price_usd_1m,campaignGoal_usd_6m,fundsGathered_usd_6m,price_usd_6m,R1,G1,B1,R2,G2,B2,R3,G3,B3,R4,G4,B4,ks_color_1,ks_color_2,ks_color_3,ks_color_4,emotion_adjective_1,emotion_adjective_2,emotion_adjective_3,emotion_adjective_4,creator_id_0,creator_id_1,is_pledge_master_0,is_pledge_master_1,is_backer_0,is_backer_1,is_prior_backer_0,is_prior_backer_1,is_pathfinder_0,is_pathfinder_1,is_normal_0,is_normal_1,likes_0,likes_1,Product_Question_count_0,Product_Question_count_1,Suggestion_Idea_count_0,Suggestion_Idea_count_1,Praise_Support_count_0,Praise_Support_count_1,Shipping_Fulfillment_count_0,Shipping_Fulfillment_count_1,Complaint_Refund_count_0,Complaint_Refund_count_1,Spam_Irrelevant_count_0,Spam_Irrelevant_count_1,긍정_0,긍정_1,부정_0,부정_1,중립_0,중립_1,Campaign / Pledge_0,Campaign / Pledge_1,Community Reaction_0,Community Reaction_1,Components & Production_0,Components & Production_1,Gameplay / Rules / Content_0,Gameplay / Rules / Content_1,Language & Localization_0,Language & Localization_1,Schedule / Updates_0,Schedule / Updates_1,Shipping / Price / Tax_0,Shipping / Price / Tax_1
0,5787,$,1567,Pledge manager - Closed,False,NaN,NaN,NaN,NaN,628,"Exploration, Horror, Modern, Science Fiction, ...",False,False,75.0,False,False,0,31,1,10000.000000,393538.44000,60.000000,10000.000000,393538.440000,60.000000,25,37,39,84,85,88,131,143,140,227,227,226,Black,Grey,Grey,White,견실한,정적인,그윽한,약한,43.0,77.0,29.0,55.0,36.0,75.0,18.0,37.0,0.0,0.0,50.0,41.0,273.0,221.0,29.0,35.0,21.0,28.0,13.0,8.0,2.0,4.0,1.0,1.0,2.0,0.0,34.0,26.0,10.0,15.0,24.0,35.0,1.0,14.0,17.0,7.0,3.0,6.0,29.0,37.0,10.0,4.0,4.0,1.0,4.0,7.0
1,6481,$,1075,Pledge manager - Closed,True,1.0,4.0,13.0,90.0,2716,"History, Strategy, Wargame, Action, Collectibl...",False,False,100.0,False,False,0,33,1,20000.000000,247988.30000,57.000000,20000.000000,247988.300000,57.000000,28,34,34,94,52,40,205,27,34,172,144,107,Black,Brown,Red,Grey,탁한,하이테크한,재미있는,전원적인,216.0,81.0,45.0,43.0,87.0,74.0,9.0,11.0,0.0,0.0,153.0,58.0,765.0,513.0,111.0,42.0,23.0,15.0,33.0,7.0,10.0,2.0,0.0,16.0,3.0,1.0,95.0,25.0,17.0,19.0,68.0,39.0,6.0,11.0,28.0,5.0,4.0,4.0,112.0,44.0,12.0,0.0,10.0,2.0,8.0,17.0
2,8024,$,215,Pledge manager - Closed,True,1.0,2.0,12.0,480.0,56442,"History, Strategy, Wargame",True,False,NaN,False,False,1,31,0,7000.000000,23091.47000,69.990000,7000.000000,23091.470000,69.990000,60,72,40,122,101,68,220,200,173,174,147,109,Green,Brown,White,Grey,지적인,고급스러운,연약한,전원적인,8.0,5.0,5.0,1.0,12.0,4.0,3.0,1.0,0.0,0.0,0.0,0.0,37.0,13.0,0.0,0.0,0.0,0.0,6.0,3.0,1.0,1.0,0.0,0.0,0.0,0.0,6.0,3.0,0.0,0.0,1.0,1.0,0.0,0.0,4.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
3,8225,$,12,Pledge manager - Closed,True,2.0,5.0,8.0,15.0,2409627,"Card Game, Strategy, Party game, Family",False,True,NaN,False,False,0,28,0,300.000000,645.66000,20.000000,300.000000,645.660000,20.000000,163,231,225,105,100,126,163,146,158,246,249,249,White,Grey,Grey,White,투명한,심플한,가지런한,연약한,NaN,1.0,NaN,0.0,NaN,2.0,NaN,0.0,NaN,0.0,NaN,1.0,NaN,7.0,NaN,0.0,NaN,1.0,NaN,1.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,1.0,NaN,0.0,NaN,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,5995,€,89,Pledge manager - Closed,True,2.0,6.0,8.0,20.0,14439,"Strategy, Resource management, Family, Worker ...",False,True,NaN,False,False,0,43,1,1164.031818,4705.79651,29.100795,1169.805738,4729.138562,29.245143,61,53,34,98,187,210,181,136,78,206,226,229,Black,White,Orange,White,지적인,얕은,감성적인,연약한,12.0,12.0,4.0,9.0,4.0,12.0,0.0,0.0,0.0,0.0,6.0,2.0,22.0,21.0,3.0,3.0,2.0,0.0,6.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,8.0,0.0,0.0,5.0,1.0,0.0,0.0,5.0,6.0,0.0,0.0,2.0,0.0,3.0,2.0,1.0,0.0,0.0,1.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 483 entries, 0 to 482
Data columns (total 91 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   projectID                     483 non-null    int64
 1   currencySymbol                483 non-null    object
 2   backersCount                  483 non-null    int64
 3   phaseLabel                    483 non-null    object
 4   enableBoardGameProperties     483 non-null    bool
 5   minPlayers                    469 non-null    float64
 6   maxPlayers                    469 non-null    float64
 7   minAge                        452 non-null    float64
 8   playTime                      456 non-null    float64
 9   fundedInSeconds               483 non-null    int64
 10  projectTags                   483 non-null    object
 11  isDiscounted                  483 non-null    bool
 12  isFeatured                    483 non-null    bool
 13  installmentMinPayment         253 non-null    float64
 14  hasLimitedStock               483 non-null    bool
 15  productCanBePurchased         483 non-null    bool
 16  previous_campaigns_count      483 non-null    int64
 17  duration_days                 483 non-null    int64
 18  softclose                     483 non-null    int64
 19  campaignGoal_usd_1m           483 non-null    float64
 20  fundsGathered_usd_1m          483 non-null    float64
 21  price_usd_1m                  483 non-null    float64
 22  campaignGoal_usd_6m           483 non-null    float64
 23  fundsGathered_usd_6m          483 non-null    float64
 24  price_usd_6m                  483 non-null    float64
 25  R1                            483 non-null    int64
 26  G1                            483 non-null    int64
 27  B1                            483 non-null    int64
 28  R2                            483 non-null    int64
 29  G2                            483 non-null    int64
 30  B2                            483 non-null    int64
 31  R3                            483 non-null    int64
 32  G3                            483 non-null    int64
 33  B3                            483 non-null    int64
 34  R4                            483 non-null    int64
 35  G4                            483 non-null    int64
 36  B4                            483 non-null    int64
 37  ks_color_1                    483 non-null    object
 38  ks_color_2                    483 non-null    object
 39  ks_color_3                    483 non-null    object
 40  ks_color_4                    483 non-null    object
 41  emotion_adjective_1           483 non-null    object
 42  emotion_adjective_2           483 non-null    object
 43  emotion_adjective_3           483 non-null    object
 44  emotion_adjective_4           483 non-null    object
 45  creator_id_0                  455 non-null    float64
 46  creator_id_1                  439 non-null    float64
 47  is_pledge_master_0            455 non-null    float64
 48  is_pledge_master_1            439 non-null    float64
 49  is_backer_0                   455 non-null    float64
 50  is_backer_1                   439 non-null    float64
 51  is_prior_backer_0             455 non-null    float64
 52  is_prior_backer_1             439 non-null    float64
 53  is_pathfinder_0               455 non-null    float64
 54  is_pathfinder_1               439 non-null    float64
 55  is_normal_0                   455 non-null    float64
 56  is_normal_1                   439 non-null    float64
 57  likes_0                       455 non-null    float64
 58  likes_1                       439 non-null    float64
 59  Product_Question_count_0      455 non-null    float64
 60  Product_Question_count_1      439 non-null    float64
 61  Suggestion_Idea_count_0       455 non-null    float64
 62  Suggestion_Idea_count_1       439 non-null    float64
 63  Praise_Support_count_0        455 non-null    float64
 64  Praise_Support_count_1        439 non-null    float64
 65  Shipping_Fulfillment_count_0  455 non-null    float64
 66  Shipping_Fulfillment_count_1  439 non-null    float64
 67  Complaint_Refund_count_0      455 non-null    float64
 68  Complaint_Refund_count_1      439 non-null    float64
 69  Spam_Irrelevant_count_0       455 non-null    float64
 70  Spam_Irrelevant_count_1       439 non-null    float64
 71  긍정_0                          455 non-null    float64
 72  긍정_1                          439 non-null    float64
 73  부정_0                          455 non-null    float64
 74  부정_1                          439 non-null    float64
 75  중립_0                          455 non-null    float64
 76  중립_1                          439 non-null    float64
 77  Campaign / Pledge_0           469 non-null    float64
 78  Campaign / Pledge_1           469 non-null    float64
 79  Community Reaction_0          469 non-null    float64
 80  Community Reaction_1          469 non-null    float64
 81  Components & Production_0     469 non-null    float64
 82  Components & Production_1     469 non-null    float64
 83  Gameplay / Rules / Content_0  469 non-null    float64
 84  Gameplay / Rules / Content_1  469 non-null    float64
 85  Language & Localization_0     469 non-null    float64
 86  Language & Localization_1     469 non-null    float64
 87  Schedule / Updates_0          469 non-null    float64
 88  Schedule / Updates_1          469 non-null    float64
 89  Shipping / Price / Tax_0      469 non-null    float64
 90  Shipping / Price / Tax_1      469 non-null    float64
dtypes: bool(5), float64(57), int64(18), object(11)
memory usage: 327.0+ KB

In [6]:
df[['maxPlayers', 'minAge', 'playTime']].describe()

       maxPlayers      minAge     playTime
count  469.000000  452.000000   456.000000
mean     5.597015   12.241150    85.311404
std     11.085414    2.805093   200.627936
min      1.000000    3.000000     5.000000
25%      4.000000   10.000000    30.000000
50%      4.000000   14.000000    60.000000
75%      5.000000   14.000000    90.000000
max     99.000000   21.000000  3000.000000

In [7]:
df[['maxPlayers', 'minAge', 'playTime']].mode()

   maxPlayers  minAge  playTime
0         4.0    14.0      30.0

In [8]:
drop_list =['projectID','backersCount', 'phaseLabel', 'isFeatured', 'installmentMinPayment', 'hasLimitedStock', 'productCanBePurchased']
bool_list= ['enableBoardGameProperties','isDiscounted']

df.drop(columns=drop_list,inplace=True)
df[bool_list] = df[bool_list].astype(int)

In [9]:
# minplayers, maxplayers, minage, playtime
df['minPlayers'] = df['minPlayers'].fillna(1)
df['maxPlayers'] = df['maxPlayers'].fillna(4)
df['minAge'] = df['minAge'].fillna(14)
df['playTime'] = df['playTime'].fillna(30)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 483 entries, 0 to 482
Data columns (total 84 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   currencySymbol                483 non-null    object
 1   enableBoardGameProperties     483 non-null    int64
 2   minPlayers                    483 non-null    float64
 3   maxPlayers                    483 non-null    float64
 4   minAge                        483 non-null    float64
 5   playTime                      483 non-null    float64
 6   fundedInSeconds               483 non-null    int64
 7   projectTags                   483 non-null    object
 8   isDiscounted                  483 non-null    int64
 9   previous_campaigns_count      483 non-null    int64
 10  duration_days                 483 non-null    int64
 11  softclose                     483 non-null    int64
 12  campaignGoal_usd_1m           483 non-null    float64
 13  fundsGathered_usd_1m          483 non-null    float64
 14  price_usd_1m                  483 non-null    float64
 15  campaignGoal_usd_6m           483 non-null    float64
 16  fundsGathered_usd_6m          483 non-null    float64
 17  price_usd_6m                  483 non-null    float64
 18  R1                            483 non-null    int64
 19  G1                            483 non-null    int64
 20  B1                            483 non-null    int64
 21  R2                            483 non-null    int64
 22  G2                            483 non-null    int64
 23  B2                            483 non-null    int64
 24  R3                            483 non-null    int64
 25  G3                            483 non-null    int64
 26  B3                            483 non-null    int64
 27  R4                            483 non-null    int64
 28  G4                            483 non-null    int64
 29  B4                            483 non-null    int64
 30  ks_color_1                    483 non-null    object
 31  ks_color_2                    483 non-null    object
 32  ks_color_3                    483 non-null    object
 33  ks_color_4                    483 non-null    object
 34  emotion_adjective_1           483 non-null    object
 35  emotion_adjective_2           483 non-null    object
 36  emotion_adjective_3           483 non-null    object
 37  emotion_adjective_4           483 non-null    object
 38  creator_id_0                  455 non-null    float64
 39  creator_id_1                  439 non-null    float64
 40  is_pledge_master_0            455 non-null    float64
 41  is_pledge_master_1            439 non-null    float64
 42  is_backer_0                   455 non-null    float64
 43  is_backer_1                   439 non-null    float64
 44  is_prior_backer_0             455 non-null    float64
 45  is_prior_backer_1             439 non-null    float64
 46  is_pathfinder_0               455 non-null    float64
 47  is_pathfinder_1               439 non-null    float64
 48  is_normal_0                   455 non-null    float64
 49  is_normal_1                   439 non-null    float64
 50  likes_0                       455 non-null    float64
 51  likes_1                       439 non-null    float64
 52  Product_Question_count_0      455 non-null    float64
 53  Product_Question_count_1      439 non-null    float64
 54  Suggestion_Idea_count_0       455 non-null    float64
 55  Suggestion_Idea_count_1       439 non-null    float64
 56  Praise_Support_count_0        455 non-null    float64
 57  Praise_Support_count_1        439 non-null    float64
 58  Shipping_Fulfillment_count_0  455 non-null    float64
 59  Shipping_Fulfillment_count_1  439 non-null    float64
 60  Complaint_Refund_count_0      455 non-null    float64
 61  Complaint_Refund_count_1      439 non-null    float64
 62  Spam_Irrelevant_count_0       455 non-null    float64
 63  Spam_Irrelevant_count_1       439 non-null    float64
 64  긍정_0                          455 non-null    float64
 65  긍정_1                          439 non-null    float64
 66  부정_0                          455 non-null    float64
 67  부정_1                          439 non-null    float64
 68  중립_0                          455 non-null    float64
 69  중립_1                          439 non-null    float64
 70  Campaign / Pledge_0           469 non-null    float64
 71  Campaign / Pledge_1           469 non-null    float64
 72  Community Reaction_0          469 non-null    float64
 73  Community Reaction_1          469 non-null    float64
 74  Components & Production_0     469 non-null    float64
 75  Components & Production_1     469 non-null    float64
 76  Gameplay / Rules / Content_0  469 non-null    float64
 77  Gameplay / Rules / Content_1  469 non-null    float64
 78  Language & Localization_0     469 non-null    float64
 79  Language & Localization_1     469 non-null    float64
 80  Schedule / Updates_0          469 non-null    float64
 81  Schedule / Updates_1          469 non-null    float64
 82  Shipping / Price / Tax_0      469 non-null    float64
 83  Shipping / Price / Tax_1      469 non-null    float64
dtypes: float64(56), int64(18), object(10)
memory usage: 317.1+ KB

In [11]:
target_cols = df.loc[:, 'creator_id_0':'Shipping / Price / Tax_1'].columns
df[target_cols] = df[target_cols].fillna(0)

In [12]:
df

,currencySymbol,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,fundedInSeconds,projectTags,isDiscounted,previous_campaigns_count,duration_days,softclose,campaignGoal_usd_1m,fundsGathered_usd_1m,price_usd_1m,campaignGoal_usd_6m,fundsGathered_usd_6m,price_usd_6m,R1,G1,B1,R2,G2,B2,R3,G3,B3,R4,G4,B4,ks_color_1,ks_color_2,ks_color_3,ks_color_4,emotion_adjective_1,emotion_adjective_2,emotion_adjective_3,emotion_adjective_4,creator_id_0,creator_id_1,is_pledge_master_0,is_pledge_master_1,is_backer_0,is_backer_1,is_prior_backer_0,is_prior_backer_1,is_pathfinder_0,is_pathfinder_1,is_normal_0,is_normal_1,likes_0,likes_1,Product_Question_count_0,Product_Question_count_1,Suggestion_Idea_count_0,Suggestion_Idea_count_1,Praise_Support_count_0,Praise_Support_count_1,Shipping_Fulfillment_count_0,Shipping_Fulfillment_count_1,Complaint_Refund_count_0,Complaint_Refund_count_1,Spam_Irrelevant_count_0,Spam_Irrelevant_count_1,긍정_0,긍정_1,부정_0,부정_1,중립_0,중립_1,Campaign / Pledge_0,Campaign / Pledge_1,Community Reaction_0,Community Reaction_1,Components & Production_0,Components & Production_1,Gameplay / Rules / Content_0,Gameplay / Rules / Content_1,Language & Localization_0,Language & Localization_1,Schedule / Updates_0,Schedule / Updates_1,Shipping / Price / Tax_0,Shipping / Price / Tax_1
0,$,0,1.0,4.0,14.0,30.0,628,"Exploration, Horror, Modern, Science Fiction, ...",0,0,31,1,10000.000000,393538.440000,60.000000,10000.000000,393538.440000,60.000000,25,37,39,84,85,88,131,143,140,227,227,226,Black,Grey,Grey,White,견실한,정적인,그윽한,약한,43.0,77.0,29.0,55.0,36.0,75.0,18.0,37.0,0.0,0.0,50.0,41.0,273.0,221.0,29.0,35.0,21.0,28.0,13.0,8.0,2.0,4.0,1.0,1.0,2.0,0.0,34.0,26.0,10.0,15.0,24.0,35.0,1.0,14.0,17.0,7.0,3.0,6.0,29.0,37.0,10.0,4.0,4.0,1.0,4.0,7.0
1,$,1,1.0,4.0,13.0,90.0,2716,"History, Strategy, Wargame, Action, Collectibl...",0,0,33,1,20000.000000,247988.300000,57.000000,20000.000000,247988.300000,57.000000,28,34,34,94,52,40,205,27,34,172,144,107,Black,Brown,Red,Grey,탁한,하이테크한,재미있는,전원적인,216.0,81.0,45.0,43.0,87.0,74.0,9.0,11.0,0.0,0.0,153.0,58.0,765.0,513.0,111.0,42.0,23.0,15.0,33.0,7.0,10.0,2.0,0.0,16.0,3.0,1.0,95.0,25.0,17.0,19.0,68.0,39.0,6.0,11.0,28.0,5.0,4.0,4.0,112.0,44.0,12.0,0.0,10.0,2.0,8.0,17.0
2,$,1,1.0,2.0,12.0,480.0,56442,"History, Strategy, Wargame",1,1,31,0,7000.000000,23091.470000,69.990000,7000.000000,23091.470000,69.990000,60,72,40,122,101,68,220,200,173,174,147,109,Green,Brown,White,Grey,지적인,고급스러운,연약한,전원적인,8.0,5.0,5.0,1.0,12.0,4.0,3.0,1.0,0.0,0.0,0.0,0.0,37.0,13.0,0.0,0.0,0.0,0.0,6.0,3.0,1.0,1.0,0.0,0.0,0.0,0.0,6.0,3.0,0.0,0.0,1.0,1.0,0.0,0.0,4.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
3,$,1,2.0,5.0,8.0,15.0,2409627,"Card Game, Strategy, Party game, Family",0,0,28,0,300.000000,645.660000,20.000000,300.000000,645.660000,20.000000,163,231,225,105,100,126,163,146,158,246,249,249,White,Grey,Grey,White,투명한,심플한,가지런한,연약한,0.0,1.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,7.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,€,1,2.0,6.0,8.0,20.0,14439,"Strategy, Resource management, Family, Worker ...",0,0,43,1,1164.031818,4705.796510,29.100795,1169.805738,4729.138562,29.245143,61,53,34,98,187,210,181,136,78,206,226,229,Black,White,Orange,White,지적인,얕은,감성적인,연약한,12.0,12.0,4.0,9.0,4.0,12.0,0.0,0.0,0.0,0.0,6.0,2.0,22.0,21.0,3.0,3.0,2.0,0.0,6.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,8.0,0.0,0.0,5.0,1.0,0.0,0.0,5.0,6.0,0.0,0.0,2.0,0.0,3.0,2.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
478,€,1,2.0,4.0,14.0,180.0,0,"Strategy, Wargame, Dice Game, Area Control, Co...",0,0,21,0,23280.636364,9313.418577,81.482227,23396.114754,9359.615707,81.886402,46,99,122,22,38,48,116,172,192,98,67,46,Blue,Black,Grey,Brown,성숙한,기능적인,자연적인,이성적인,12.0,5.0,24.0,10.0,20.0,8.0,6.0,3.0,1.0,0.0,1.0,2.0,18.0,11.0,5.0,2.0,3.0,2.0,4.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,7.0,5.0,0.0,0.0,5.0,3.0,1.0,0.0,3.0,2.0,1.0,0.0,5.0,2.0,2.0,1.0,0.0,0.0,0.0,3.0
479,€,1,2.0,4.0,5.0,25.0,0,"Fantasy, Strategy, Humor",1,0,30,0,11407.511818,81.482227,23.164233,11464.096230,81.886402,23.279134,46,42,30,124,108,79,6,80,118,193,186,167,Black,Grey,Blue,White,견실한,동양적인,돋보이는,잔잔한,4.0,0.0,3.0,2.0,3.0,2.0,0.0,0.0,0.0,0.0,4.0,1.0,4.0,2.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
480,€,1,1.0,4.0,14.0,30.0,0,"Dice Game, Multiplayer, Competitive, Campaign",1,0,16,0,11640.318182,7315.939977,41.905145,11698.057377,7352.229061,42.113007,231,230,208,211,189,150,107,62,43,155,125,95,White,White,Brown,Grey,연약한,순수한,시원한,편리한,1.0,6.0,0.0,5.0,0.0,3.0,0.0,0.0,0.0,0.0,1.0,2.0,2.0,19.0,0.0,5.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,4.0,0.0,2.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
481,€,1,2.0,4.0,12.0,120.0,0,"Fantasy, Strategy, Terrain Building, Humor",0,0,33,0,23280.636364,15622.040340,58.201591,23396.114754,15699.529978,58.490287,254,253,253,43,31,25,110,75,49,199,133,78,White,Black,Brown,Orange,연약한,견고한,시원한,여성적인,21.0,11.0,10.0,13.0,0.0,2.0,1.0,0.0,0.0,0.0,31.0,6.0,91.0,66.0,6.0,5.0,7.0,1.0,4.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,11.0,4.0,4.0,1.0,4.0,3.0,1.0,1.0,4.0,0.0,3.0,0.0,7.0,4.0,1.0,2.0,1.0,0.0,2.0,1.0
482,€,1,2.0,4.0,14.0,60.0,0,"Science Fiction, Area Control, Deck Building",0,0,24,0,34920.954545,12676.306500,50.053368,35094.172131,12739.184484,50.301647,84,55,65,249,251,250,212,164,72,136,113,161,ReddishPurple,White,Yellow,Grey,보수적인,연약한,신선한,간편한,10.0,8.0,11.0,11.0,7.0,12.0,8.0,3.0,0.0,0.0,12.0,2.0,15.0,30.0,5.0,6.0,10.0,1.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,7.0,5.0,1.0,5.0,3.0,0.0,2.0,2.0,4.0,0.0,0.0,12.0,1.0,1.0,3.0,2.0,0.0,0.0,1.0

In [13]:
df['currencySymbol'].value_counts()

currencySymbol
€     218
$     192
£      49
A$     10
C$      7
zł      7
Name: count, dtype: int64

In [14]:
print(df['currencySymbol'].unique())

['$' '€' 'C$' '£' 'A$' 'zł']

In [15]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

currency_map = {
    '€': 'EUR',
    '$': 'USD',
    '£': 'GBP',
    'A$': 'AUD',
    'C$': 'CAD',
    'zł': 'PLN'
}
df['currencySymbol'] = df['currencySymbol'].map(currency_map)

try:
    encoder = OneHotEncoder(sparse_output=False, dtype=int)
except TypeError:
    encoder = OneHotEncoder(sparse=False, dtype=int)

encoded_array = encoder.fit_transform(df[['currencySymbol']])

encoded_df = pd.DataFrame(
    encoded_array, 
    columns=encoder.get_feature_names_out(['currencySymbol']),
    index=df.index
)

df = pd.concat([df.drop(columns=['currencySymbol']), encoded_df], axis=1)

In [16]:
from sklearn.preprocessing import MultiLabelBinarizer
import pandas as pd

df['projectTags'] = df['projectTags'].apply(lambda x: [tag.strip() for tag in x.split(',') if tag.strip()])

mlb = MultiLabelBinarizer()
tags_encoded = mlb.fit_transform(df['projectTags'])

df_tags = pd.DataFrame(tags_encoded, columns=mlb.classes_)

df = pd.concat([df.drop(columns=['projectTags']), df_tags], axis=1)

In [17]:
df

,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,fundedInSeconds,isDiscounted,previous_campaigns_count,duration_days,softclose,campaignGoal_usd_1m,fundsGathered_usd_1m,price_usd_1m,campaignGoal_usd_6m,fundsGathered_usd_6m,price_usd_6m,R1,G1,B1,R2,G2,B2,R3,G3,B3,R4,G4,B4,ks_color_1,ks_color_2,ks_color_3,ks_color_4,emotion_adjective_1,emotion_adjective_2,emotion_adjective_3,emotion_adjective_4,creator_id_0,creator_id_1,is_pledge_master_0,is_pledge_master_1,is_backer_0,is_backer_1,is_prior_backer_0,is_prior_backer_1,is_pathfinder_0,is_pathfinder_1,is_normal_0,is_normal_1,likes_0,likes_1,Product_Question_count_0,Product_Question_count_1,Suggestion_Idea_count_0,Suggestion_Idea_count_1,Praise_Support_count_0,Praise_Support_count_1,Shipping_Fulfillment_count_0,Shipping_Fulfillment_count_1,Complaint_Refund_count_0,Complaint_Refund_count_1,Spam_Irrelevant_count_0,Spam_Irrelevant_count_1,긍정_0,긍정_1,부정_0,부정_1,중립_0,중립_1,Campaign / Pledge_0,Campaign / Pledge_1,Community Reaction_0,Community Reaction_1,Components & Production_0,Components & Production_1,Gameplay / Rules / Content_0,Gameplay / Rules / Content_1,Language & Localization_0,Language & Localization_1,Schedule / Updates_0,Schedule / Updates_1,Shipping / Price / Tax_0,Shipping / Price / Tax_1,currencySymbol_AUD,currencySymbol_CAD,currencySymbol_EUR,currencySymbol_GBP,currencySymbol_PLN,currencySymbol_USD,4X,AR Next,ARNext26,Action,Adventure,Area Control,Asymmetric,Campaign,Card Game,Cats,Civilization,Collectible,Collectible Models,Competitive,Cooperative,Deck Building,Deduction,Dexterity,Dice Game,Digital,Economic,Educational,Exploration,Family,Fantasy,Feast,First-Timers,Game Components,History,Horror,Humor,Legacy,Logical,MOBA,Major Creators,Media,Modern,Multiplayer,Mythology,Narrative,OctoberFeast25,Paint,Party game,Political,Print and Play,RPG,Racing,Reprints,Resource management,Science Fiction,Set Collection,Sport,Strategy,Survival,TTRPG,Terrain Building,Tower Defense,Video Game,Video Game Theme,Wargame,WinterFeast2026,Worker placement,dinotuesday
0,0,1.0,4.0,14.0,30.0,628,0,0,31,1,10000.000000,393538.440000,60.000000,10000.000000,393538.440000,60.000000,25,37,39,84,85,88,131,143,140,227,227,226,Black,Grey,Grey,White,견실한,정적인,그윽한,약한,43.0,77.0,29.0,55.0,36.0,75.0,18.0,37.0,0.0,0.0,50.0,41.0,273.0,221.0,29.0,35.0,21.0,28.0,13.0,8.0,2.0,4.0,1.0,1.0,2.0,0.0,34.0,26.0,10.0,15.0,24.0,35.0,1.0,14.0,17.0,7.0,3.0,6.0,29.0,37.0,10.0,4.0,4.0,1.0,4.0,7.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,1
1,1,1.0,4.0,13.0,90.0,2716,0,0,33,1,20000.000000,247988.300000,57.000000,20000.000000,247988.300000,57.000000,28,34,34,94,52,40,205,27,34,172,144,107,Black,Brown,Red,Grey,탁한,하이테크한,재미있는,전원적인,216.0,81.0,45.0,43.0,87.0,74.0,9.0,11.0,0.0,0.0,153.0,58.0,765.0,513.0,111.0,42.0,23.0,15.0,33.0,7.0,10.0,2.0,0.0,16.0,3.0,1.0,95.0,25.0,17.0,19.0,68.0,39.0,6.0,11.0,28.0,5.0,4.0,4.0,112.0,44.0,12.0,0.0,10.0,2.0,8.0,17.0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1
2,1,1.0,2.0,12.0,480.0,56442,1,1,31,0,7000.000000,23091.470000,69.990000,7000.000000,23091.470000,69.990000,60,72,40,122,101,68,220,200,173,174,147,109,Green,Brown,White,Grey,지적인,고급스러운,연약한,전원적인,8.0,5.0,5.0,1.0,12.0,4.0,3.0,1.0,0.0,0.0,0.0,0.0,37.0,13.0,0.0,0.0,0.0,0.0,6.0,3.0,1.0,1.0,0.0,0.0,0.0,0.0,6.0,3.0,0.0,0.0,1.0,1.0,0.0,0.0,4.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0
3,1,2.0,5.0,8.0,15.0,2409627,0,0,28,0,300.000000,645.660000,20.000000,300.000000,645.660000,20.000000,163,231,225,105,100,126,163,146,158,246,249,249,White,Grey,Grey,White,투명한,심플한,가지런한,연약한,0.0,1.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,7.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
4,1,2.0,6.0,8.0,20.0,14439,0,0,43,1,1164.031818,4705.796510,29.100795,1169.805738,4729.138562,29.245143,61,53,34,98,187,210,181,136,78,206,226,229,Black,White,Orange,White,지적인,얕은,감성적인,연약한,12.0,12.0,4.0,9.0,4.0,12.0,0.0,0.0,0.0,0.0,6.0,2.0,22.0,21.0,3.0,3.0,2.0,0.0,6.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,8.0,0.0,0.0,5.0,1.0,0.0,0.0,5.0,6.0,0.0,0.0,2.0,0.0,3.0,2.0,1.0,0.0,0.0,1.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
478,1,2.0,4.0,14.0,180.0,0,0,0,21,0,23280.636364,9313.418577,81.482227,23396.114754,9359.615707,81.886402,46,99,122,22,38,48,116,172,192,98,67,46,Blue,Black,Grey,Brown,성숙한,기능적인,자연적인,이성적인,12.0,5.0,24.0,10.0,20.0,8.0,6.0,3.0,1.0,0.0,1.0,2.0,18.0,11.0,5.0,2.0,3.0,2.0,4.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,7.0,5.0,0.0,0.0,5.0,3.0,1.0,0.0,3.0,2.0,1.0,0.0,5.0,2.0,2.0,1.0,0.0,0.0,0.0,3.0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0
479,1,2.0,4.0,5.0,25.0,0,1,0,30,0,11407.511818,81.482227,23.164233,11464.096230,81.886402,23.279134,46,42,30,124,108,79,6,80,118,193,186,167,Black,Grey,Blue,White,견실한,동양적인,돋보이는,잔잔한,4.0,0.0,3.0,2.0,3.0,2.0,0.0,0.0,0.0,0.0,4.0,1.0,4.0,2.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
480,1,1.0,4.0,14.0,30.0,0,1,0,16,0,11640.318182,7315.939977,41.905145,11698.057377,7352.229061,42.113007,231,230,208,211,189,150,107,62,43,155,125,95,White,White,Brown,Grey,연약한,순수한,시원한,편리한,1.0,6.0,0.0,5.0,0.0,3.0,0.0,0.0,0.0,0.0,1.0,2.0,2.0,19.0,0.0,5.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,4.0,0.0,2.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
481,1,2.0,4.0,12.0,120.0,0,0,0,33,0,23280.636364,15622.040340,58.201591,23396.114754,15699.529978,58.490287,254,253,253,43,31,25,110,75,49,199,133,78,White,Black,Brown,Orange,연약한,견고한,시원한,여성적인,21.0,11.0,10.0,13.0,0.0,2.0,1.0,0.0,0.0,0.0,31.0,6.0,91.0,66.0,6.0,5.0,7.0,1.0,4.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,11.0,4.0,4.0,1.0,4.0,3.0,1.0,1.0,4.0,0.0,3.0,0.0,7.0,4.0,1.0,2.0,1.0,0.0,2.0,1.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0
482,1,2.0,4.0,14.0,60.0,0,0,0,24,0,34920.954545,12676.306500,50.053368,35094.172131,12739.184484,50.301647,84,55,65,249,251,250,212,164,72,136,113,161,ReddishPurple,White,Yellow,Grey,보수적인,연약한,신선한,간편한,10.0,8.0,11.0,11.0,7.0,12.0,8.0,3.0,0.0,0.0,12.0,2.0,15.0,30.0,5.0,6.0,10.0,1.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,7.0,5.0,1.0,5.0,3.0,0.0,2.0,2.0,4.0,0.0,0.0,12.0,1.0,1.0,3.0,2.0,0.0,0.0,1.0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0

In [18]:
from sklearn.preprocessing import LabelEncoder
all_unique_colors = pd.concat([
    df['ks_color_1'], 
    df['ks_color_2'], 
    df['ks_color_3'], 
    df['ks_color_4']
]).unique()

le_color = LabelEncoder()
le_color.fit(all_unique_colors)


color_cols = ['ks_color_1', 'ks_color_2', 'ks_color_3', 'ks_color_4']
for col in color_cols:
    df[col] = le_color.transform(df[col])

In [19]:
from sklearn.preprocessing import LabelEncoder
all_unique_emotion = pd.concat([
    df['emotion_adjective_1'], 
    df['emotion_adjective_2'], 
    df['emotion_adjective_3'], 
    df['emotion_adjective_4']
]).unique()

le_color = LabelEncoder()
le_color.fit(all_unique_emotion)


color_cols = ['emotion_adjective_1', 'emotion_adjective_2', 'emotion_adjective_3', 'emotion_adjective_4']
for col in color_cols:
    df[col] = le_color.transform(df[col])

In [21]:
df.to_csv('../../02_Data/processed/real_final_ml.csv', index=False, encoding="utf-8-sig")

In [20]:
df

,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,fundedInSeconds,isDiscounted,previous_campaigns_count,duration_days,softclose,campaignGoal_usd_1m,fundsGathered_usd_1m,price_usd_1m,campaignGoal_usd_6m,fundsGathered_usd_6m,price_usd_6m,R1,G1,B1,R2,G2,B2,R3,G3,B3,R4,G4,B4,ks_color_1,ks_color_2,ks_color_3,ks_color_4,emotion_adjective_1,emotion_adjective_2,emotion_adjective_3,emotion_adjective_4,creator_id_0,creator_id_1,is_pledge_master_0,is_pledge_master_1,is_backer_0,is_backer_1,is_prior_backer_0,is_prior_backer_1,is_pathfinder_0,is_pathfinder_1,is_normal_0,is_normal_1,likes_0,likes_1,Product_Question_count_0,Product_Question_count_1,Suggestion_Idea_count_0,Suggestion_Idea_count_1,Praise_Support_count_0,Praise_Support_count_1,Shipping_Fulfillment_count_0,Shipping_Fulfillment_count_1,Complaint_Refund_count_0,Complaint_Refund_count_1,Spam_Irrelevant_count_0,Spam_Irrelevant_count_1,긍정_0,긍정_1,부정_0,부정_1,중립_0,중립_1,Campaign / Pledge_0,Campaign / Pledge_1,Community Reaction_0,Community Reaction_1,Components & Production_0,Components & Production_1,Gameplay / Rules / Content_0,Gameplay / Rules / Content_1,Language & Localization_0,Language & Localization_1,Schedule / Updates_0,Schedule / Updates_1,Shipping / Price / Tax_0,Shipping / Price / Tax_1,currencySymbol_AUD,currencySymbol_CAD,currencySymbol_EUR,currencySymbol_GBP,currencySymbol_PLN,currencySymbol_USD,4X,AR Next,ARNext26,Action,Adventure,Area Control,Asymmetric,Campaign,Card Game,Cats,Civilization,Collectible,Collectible Models,Competitive,Cooperative,Deck Building,Deduction,Dexterity,Dice Game,Digital,Economic,Educational,Exploration,Family,Fantasy,Feast,First-Timers,Game Components,History,Horror,Humor,Legacy,Logical,MOBA,Major Creators,Media,Modern,Multiplayer,Mythology,Narrative,OctoberFeast25,Paint,Party game,Political,Print and Play,RPG,Racing,Reprints,Resource management,Science Fiction,Set Collection,Sport,Strategy,Survival,TTRPG,Terrain Building,Tower Defense,Video Game,Video Game Theme,Wargame,WinterFeast2026,Worker placement,dinotuesday
0,0,1.0,4.0,14.0,30.0,628,0,0,31,1,10000.000000,393538.440000,60.000000,10000.000000,393538.440000,60.000000,25,37,39,84,85,88,131,143,140,227,227,226,0,5,5,12,13,83,15,60,43.0,77.0,29.0,55.0,36.0,75.0,18.0,37.0,0.0,0.0,50.0,41.0,273.0,221.0,29.0,35.0,21.0,28.0,13.0,8.0,2.0,4.0,1.0,1.0,2.0,0.0,34.0,26.0,10.0,15.0,24.0,35.0,1.0,14.0,17.0,7.0,3.0,6.0,29.0,37.0,10.0,4.0,4.0,1.0,4.0,7.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,1
1,1,1.0,4.0,13.0,90.0,2716,0,0,33,1,20000.000000,247988.300000,57.000000,20000.000000,247988.300000,57.000000,28,34,34,94,52,40,205,27,34,172,144,107,0,3,10,5,94,101,77,78,216.0,81.0,45.0,43.0,87.0,74.0,9.0,11.0,0.0,0.0,153.0,58.0,765.0,513.0,111.0,42.0,23.0,15.0,33.0,7.0,10.0,2.0,0.0,16.0,3.0,1.0,95.0,25.0,17.0,19.0,68.0,39.0,6.0,11.0,28.0,5.0,4.0,4.0,112.0,44.0,12.0,0.0,10.0,2.0,8.0,17.0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1
2,1,1.0,2.0,12.0,480.0,56442,1,1,31,0,7000.000000,23091.470000,69.990000,7000.000000,23091.470000,69.990000,60,72,40,122,101,68,220,200,173,174,147,109,4,3,12,5,87,14,65,78,8.0,5.0,5.0,1.0,12.0,4.0,3.0,1.0,0.0,0.0,0.0,0.0,37.0,13.0,0.0,0.0,0.0,0.0,6.0,3.0,1.0,1.0,0.0,0.0,0.0,0.0,6.0,3.0,0.0,0.0,1.0,1.0,0.0,0.0,4.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0
3,1,2.0,5.0,8.0,15.0,2409627,0,0,28,0,300.000000,645.660000,20.000000,300.000000,645.660000,20.000000,163,231,225,105,100,126,163,146,158,246,249,249,12,5,5,12,95,56,2,65,0.0,1.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,7.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
4,1,2.0,6.0,8.0,20.0,14439,0,0,43,1,1164.031818,4705.796510,29.100795,1169.805738,4729.138562,29.245143,61,53,34,98,187,210,181,136,78,206,226,229,0,12,7,12,87,61,6,65,12.0,12.0,4.0,9.0,4.0,12.0,0.0,0.0,0.0,0.0,6.0,2.0,22.0,21.0,3.0,3.0,2.0,0.0,6.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,8.0,0.0,0.0,5.0,1.0,0.0,0.0,5.0,6.0,0.0,0.0,2.0,0.0,3.0,2.0,1.0,0.0,0.0,1.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
478,1,2.0,4.0,14.0,180.0,0,0,0,21,0,23280.636364,9313.418577,81.482227,23396.114754,9359.615707,81.886402,46,99,122,22,38,48,116,172,192,98,67,46,1,0,5,3,47,16,73,71,12.0,5.0,24.0,10.0,20.0,8.0,6.0,3.0,1.0,0.0,1.0,2.0,18.0,11.0,5.0,2.0,3.0,2.0,4.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,7.0,5.0,0.0,0.0,5.0,3.0,1.0,0.0,3.0,2.0,1.0,0.0,5.0,2.0,2.0,1.0,0.0,0.0,0.0,3.0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0
479,1,2.0,4.0,5.0,25.0,0,1,0,30,0,11407.511818,81.482227,23.164233,11464.096230,81.886402,23.279134,46,42,30,124,108,79,6,80,118,193,186,167,0,5,1,12,13,29,28,75,4.0,0.0,3.0,2.0,3.0,2.0,0.0,0.0,0.0,0.0,4.0,1.0,4.0,2.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
480,1,1.0,4.0,14.0,30.0,0,1,0,16,0,11640.318182,7315.939977,41.905145,11698.057377,7352.229061,42.113007,231,230,208,211,189,150,107,62,43,155,125,95,12,12,3,5,65,51,53,96,1.0,6.0,0.0,5.0,0.0,3.0,0.0,0.0,0.0,0.0,1.0,2.0,2.0,19.0,0.0,5.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,4.0,0.0,2.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
481,1,2.0,4.0,12.0,120.0,0,0,0,33,0,23280.636364,15622.040340,58.201591,23396.114754,15699.529978,58.490287,254,253,253,43,31,25,110,75,49,199,133,78,12,0,3,7,65,12,53,63,21.0,11.0,10.0,13.0,0.0,2.0,1.0,0.0,0.0,0.0,31.0,6.0,91.0,66.0,6.0,5.0,7.0,1.0,4.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,11.0,4.0,4.0,1.0,4.0,3.0,1.0,1.0,4.0,0.0,3.0,0.0,7.0,4.0,1.0,2.0,1.0,0.0,2.0,1.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0
482,1,2.0,4.0,14.0,60.0,0,0,0,24,0,34920.954545,12676.306500,50.053368,35094.172131,12739.184484,50.301647,84,55,65,249,251,250,212,164,72,136,113,161,11,12,13,5,38,65,54,3,10.0,8.0,11.0,11.0,7.0,12.0,8.0,3.0,0.0,0.0,12.0,2.0,15.0,30.0,5.0,6.0,10.0,1.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,7.0,5.0,1.0,5.0,3.0,0.0,2.0,2.0,4.0,0.0,0.0,12.0,1.0,1.0,3.0,2.0,0.0,0.0,1.0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0

In [27]:
df[['ks_color_1',	'ks_color_2',	'ks_color_3',	'ks_color_4',	'emotion_adjective_1',	'emotion_adjective_2',	'emotion_adjective_3',	'emotion_adjective_4']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 483 entries, 0 to 482
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ks_color_1           483 non-null    int64
 1   ks_color_2           483 non-null    int64
 2   ks_color_3           483 non-null    int64
 3   ks_color_4           483 non-null    int64
 4   emotion_adjective_1  483 non-null    int64
 5   emotion_adjective_2  483 non-null    int64
 6   emotion_adjective_3  483 non-null    int64
 7   emotion_adjective_4  483 non-null    int64
dtypes: int64(8)
memory usage: 30.3 KB