In [6]:
import pandas as pd

df = pd.read_csv("../../02_Data/processed/final_gamefound_list.csv")
rewards_df = pd.read_csv("../../02_Data/processed/final_rewards.csv")

In [10]:
df

,name,projectID,creator,creatorID,homeUrl,currencySymbol,campaignGoal,fundsGathered,backersCount,campaignStart,...,minPlayers,maxPlayers,minAge,playTime,playTimeUnit,fundedInSeconds,imageUrl,pledgeManagerSoftCloseDeadline,projectTags,originalType
0,We Played God - A Survival Miniatures Game,5787,Black Site Studios,5252,https://gamefound.com/creators/black-site-studios,$,10000.0,393538.44,1567,2025-06-17T14:30:00Z,...,NaN,NaN,NaN,NaN,0,628,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-02T15:00:00Z,"Exploration, Horror, Modern, Science Fiction, ...",1
1,CARNIVORE,6481,Buer Games,6737,https://gamefound.com/creators/buer-games,$,20000.0,247988.30,1075,2026-02-25T16:00:00Z,...,1.0,4.0,13.0,90.0,0,2716,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-01T14:00:00Z,"History, Strategy, Wargame, Action, Collectibl...",1
2,1809: Talavera,8024,Tactical Workshop,5141,https://gamefound.com/creators/tactical-workshop,$,7000.0,23091.47,215,2026-03-01T05:00:00Z,...,1.0,2.0,12.0,8.0,1,56442,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"History, Strategy, Wargame",1
3,Comber Cat,8225,Gamedolf Limited,8739,https://gamefound.com/creators/gamedolflimited,$,300.0,645.66,12,2026-02-02T13:00:00Z,...,2.0,5.0,8.0,15.0,0,2409627,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Card Game, Strategy, Party game, Family",1
4,Jano - A Pawsome Adventure,5995,aszaki,7221,https://gamefound.com/creators/aszaki,€,1000.0,4042.67,89,2026-01-16T12:00:00Z,...,2.0,6.0,8.0,20.0,0,14439,https://imgcdn.gamefound.com/projectimage/proj...,2026-06-11T13:00:00Z,"Strategy, Resource management, Family, Worker ...",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
483,Tectonia,2109,Hagen Behr,2703,https://gamefound.com/creators/hagen-behr,€,20000.0,8001.00,113,2022-07-05T18:00:00Z,...,2.0,4.0,14.0,180.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Strategy, Wargame, Dice Game, Area Control, Co...",1
484,Invasion Cards,2149,Lawrence Lyle,2742,https://gamefound.com/creators/lawrence-lyle,€,9800.0,70.00,2,2022-07-04T10:00:00Z,...,2.0,4.0,5.0,25.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Strategy, Humor",1
485,MOOGH,1919,Nuts! Publishing,2363,https://gamefound.com/creators/nuts-publishing,€,10000.0,6285.00,143,2022-04-26T16:00:00Z,...,1.0,4.0,14.0,30.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Dice Game, Multiplayer, Competitive, Campaign",1
486,Crossroads Inn: The Board Game,1143,Klabater,1510,https://gamefound.com/creators/klabater,€,20000.0,13420.63,158,2021-10-28T14:00:00Z,...,2.0,4.0,12.0,120.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Fantasy, Strategy, Terrain Building, Humor",1
487,Goldenstar: The Galactic Tournament,1325,Gindi,64,https://gamefound.com/creators/gindi,€,30000.0,10890.00,148,2021-10-05T16:00:00Z,...,2.0,4.0,14.0,60.0,0,0,https://imgcdn.gamefound.com/projectimage/proj...,NaN,"Science Fiction, Area Control, Deck Building",1

In [9]:
rewards_df

,main_name,projectID,anchorRelativeUrl,price,isDiscounted,effectivePrice,isFeatured,purchasedCopiesCount,backgroundUrl,installmentCost,installmentMinPayment,hasLimitedStock,productCanBePurchased,productID,remainingStockLimit
0,We Played God - A Survival Miniatures Game,5787,core-rules-physical-pdf-80323,60.0,False,60.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,80323,NaN
1,We Played God - A Survival Miniatures Game,5787,eden-visitor-digital-pdfs-digital-survivor-stl...,62.0,False,62.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,81221,NaN
2,We Played God - A Survival Miniatures Game,5787,eden-visitor-physical-core-rules-survivor-mini...,124.0,True,110.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,80326,NaN
3,We Played God - A Survival Miniatures Game,5787,eden-hacker-digital-all-in-81322,147.0,True,132.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,81322,NaN
4,We Played God - A Survival Miniatures Game,5787,eden-visitor-deluxe-physical-core-rules-surviv...,159.0,True,145.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,81320,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2102,Crossroads Inn: The Board Game,1143,6-x-crossroads-inn-the-board-game-standard-edi...,300.0,True,264.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,19155,NaN
2103,Goldenstar: The Galactic Tournament,1325,champion-gameplay-all-in-18047,72.0,False,72.0,True,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,18047,NaN
2104,Goldenstar: The Galactic Tournament,1325,goldenstar-core-pledge-17700,43.0,False,43.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,17700,NaN
2105,Goldenstar: The Galactic Tournament,1325,challenger-18042,69.0,False,69.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,18042,NaN
2106,Goldenstar: The Galactic Tournament,1325,legend-all-in-18052,97.0,False,97.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,18052,NaN

In [11]:
rewards_join_df = pd.merge(
    rewards_df, 
    df[['projectID', 'currencySymbol']], 
    on='projectID', 
    how='left'
)

In [12]:
rewards_join_df

,main_name,projectID,anchorRelativeUrl,price,isDiscounted,effectivePrice,isFeatured,purchasedCopiesCount,backgroundUrl,installmentCost,installmentMinPayment,hasLimitedStock,productCanBePurchased,productID,remainingStockLimit,currencySymbol
0,We Played God - A Survival Miniatures Game,5787,core-rules-physical-pdf-80323,60.0,False,60.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,80323,NaN,$
1,We Played God - A Survival Miniatures Game,5787,eden-visitor-digital-pdfs-digital-survivor-stl...,62.0,False,62.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,81221,NaN,$
2,We Played God - A Survival Miniatures Game,5787,eden-visitor-physical-core-rules-survivor-mini...,124.0,True,110.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,80326,NaN,$
3,We Played God - A Survival Miniatures Game,5787,eden-hacker-digital-all-in-81322,147.0,True,132.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,81322,NaN,$
4,We Played God - A Survival Miniatures Game,5787,eden-visitor-deluxe-physical-core-rules-surviv...,159.0,True,145.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,75.0,False,False,81320,NaN,$
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2102,Crossroads Inn: The Board Game,1143,6-x-crossroads-inn-the-board-game-standard-edi...,300.0,True,264.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,19155,NaN,€
2103,Goldenstar: The Galactic Tournament,1325,champion-gameplay-all-in-18047,72.0,False,72.0,True,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,18047,NaN,€
2104,Goldenstar: The Galactic Tournament,1325,goldenstar-core-pledge-17700,43.0,False,43.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,17700,NaN,€
2105,Goldenstar: The Galactic Tournament,1325,challenger-18042,69.0,False,69.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,18042,NaN,€
2106,Goldenstar: The Galactic Tournament,1325,legend-all-in-18052,97.0,False,97.0,False,0,https://imgcdn.gamefound.com/productimage/proj...,NaN,NaN,False,False,18052,NaN,€

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 488 entries, 0 to 487
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   name                            488 non-null    object
 1   projectID                       488 non-null    int64
 2   creator                         488 non-null    object
 3   creatorID                       488 non-null    int64
 4   homeUrl                         488 non-null    object
 5   currencySymbol                  488 non-null    object
 6   campaignGoal                    488 non-null    float64
 7   fundsGathered                   488 non-null    float64
 8   backersCount                    488 non-null    int64
 9   campaignStart                   488 non-null    object
 10  campaignEnd                     488 non-null    object
 11  phaseLabel                      488 non-null    object
 12  enableBoardGameProperties       488 non-null    bool
 13  minPlayers                      474 non-null    float64
 14  maxPlayers                      474 non-null    float64
 15  minAge                          457 non-null    float64
 16  playTime                        461 non-null    float64
 17  playTimeUnit                    488 non-null    int64
 18  fundedInSeconds                 488 non-null    int64
 19  imageUrl                        488 non-null    object
 20  pledgeManagerSoftCloseDeadline  304 non-null    object
 21  projectTags                     488 non-null    object
 22  originalType                    488 non-null    int64
dtypes: bool(1), float64(6), int64(6), object(10)
memory usage: 84.5+ KB

In [15]:
rewards_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2107 entries, 0 to 2106
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   main_name              2107 non-null   object
 1   projectID              2107 non-null   int64
 2   anchorRelativeUrl      2107 non-null   object
 3   price                  2107 non-null   float64
 4   isDiscounted           2107 non-null   bool
 5   effectivePrice         2107 non-null   float64
 6   isFeatured             2107 non-null   bool
 7   purchasedCopiesCount   2107 non-null   int64
 8   backgroundUrl          2107 non-null   object
 9   installmentCost        368 non-null    float64
 10  installmentMinPayment  1200 non-null   float64
 11  hasLimitedStock        2107 non-null   bool
 12  productCanBePurchased  2107 non-null   bool
 13  productID              2107 non-null   int64
 14  remainingStockLimit    476 non-null    float64
dtypes: bool(4), float64(5), int64(3), object(3)
memory usage: 189.4+ KB