In [ ]:
import requests
import pandas as pd

api_url = "https://gamefound.com/api/projectSearch/searchProjectsForCards"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

payload = {
    "creatorID": None,
    "creatorName": None,
    "sortType": 0,
    "term": "",
    "projectPhaseSearchTypes": [],
    "projectBenefits": [],
    "projectTags": [],
    "projectCatalogCategories": [11], #보드게임 카테고리 11번
    "playerAges": [],
    "playerCounts": [],
    "playTimes": [],
    "creator": {"creatorID": None, "name": None},
    "userCommunitySearchTypes": [],
    "source": 5,
    "pageIndex": 0 # 0페이지부터 시작 -> 이거 돌려야함
}

response = requests.post(api_url, headers=headers, json=payload)

# 응답 확인
if response.status_code == 200:
    data = response.json()
    print("성공")

else:
    print(f"실패 : {response.status_code}")

성공

In [32]:
temp  = data['projects']['pagedItems'][0]
temp

{'allowNewOrders': None,
 'campaignGoal': 25000,
 'coCreators': [],
 'creator': {'avatarUrl': 'https://imgcdn.gamefound.com/creatoricon/creators/474/704e7ea9-95bc-4ecc-9f72-e38484f4eccd.png',
  'homeUrl': 'https://gamefound.com/creators/oomm-games',
  'creatorID': 474,
  'imageFileName': '704e7ea9-95bc-4ecc-9f72-e38484f4eccd.png',
  'name': 'Open Owl Studios',
  'urlName': 'oomm-games'},
 'draftAccessKey': 'AS5GA0LMT7OGJC3IIUNV8DGE3BX',
 'enableShippingOnlyMode': None,
 'hasPromoItem': False,
 'lastUpdateTitle': None,
 'phaseLabel': 'Crowdfunding',
 'pledgeManagerAvailability': None,
 'pledgeManagerSoftCloseDeadline': None,
 'projectProperties': {'enableBoardGameProperties': True,
  'maxPlayers': 4,
  'minAge': None,
  'minPlayers': 1,
  'playTime': 90,
  'playTimeDescription': None,
  'playTimeUnit': 0},
 'projectUrlName': 'stonesaga-second-printing',
 'promoItemName': None,
 'useDraftAccessKey': False,
 'backersCount': 1658,
 'campaignEnd': '2026-06-20T00:00:00Z',
 'campaignStart': '2026-05-26T15:00:00Z',
 'campaignEndScheduledAt': '2026-06-20T00:00:00Z',
 'campaignOutcome': 0,
 'catalogCategory': {'projectCategory': 11,
  'name': 'Board & card games',
  'url': '/en/projects/search?projectCatalogCategories=BoardAndCardGames'},
 'currencySymbol': '$',
 'followerCount': 8843,
 'fundedInSeconds': 1764,
 'fundsGathered': 142095.28,
 'fundsGatheredPresentation': 0,
 'imageUrl': 'https://imgcdn.gamefound.com/projectimage/projects/9678/0e9a20f1-7e79-4057-9f51-2d957a571d56.png',
 'installmentCount': 4,
 'installmentMinPayment': 100.0,
 'name': 'Stonesaga Second Printing',
 'originalType': 1,
 'phase': 10,
 'phaseEndedAt': '2026-06-20T00:00:00Z',
 'phaseStartedAt': '2026-05-26T15:00:00Z',
 'platform': 0,
 'projectBadges': [0, 1],
 'projectID': 9678,
 'projectLabels': [],
 'projectTags': [{'projectTagID': 1,
   'isSystem': False,
   'isVisible': True,
   'name': 'Fantasy',
   'url': '/en/projects/search?projectTags=1',
   'urlName': 'fantasy'},
  {'projectTagID': 7,
   'isSystem': False,
   'isVisible': True,
   'name': 'Mythology',
   'url': '/en/projects/search?projectTags=7',
   'urlName': 'mythology'},
  {'projectTagID': 34,
   'isSystem': False,
   'isVisible': True,
   'name': 'Cooperative',
   'url': '/en/projects/search?projectTags=34',
   'urlName': 'cooperative'},
  {'projectTagID': 40,
   'isSystem': False,
   'isVisible': True,
   'name': 'Campaign',
   'url': '/en/projects/search?projectTags=40',
   'urlName': 'campaign'},
  {'projectTagID': 41,
   'isSystem': False,
   'isVisible': True,
   'name': 'Civilization',
   'url': '/en/projects/search?projectTags=41',
   'urlName': 'civilization'}],
 'shortDescription': 'Build a civilization across epochs in a cooperative survival crafting saga set in a persistent world shaped by your choices.',
 'type': 1,
 'url': 'https://gamefound.com:443/en/projects/oomm-games/stonesaga-second-printing',
 'relativeUrl': '/en/projects/oomm-games/stonesaga-second-printing',
 'version': 1,
 'visibility': 0}

In [ ]:
projects = data.get('projects').get('pagedItems')
game_list = []
    
for item in projects:
    game_dict = {
        'name': item.get('name'),                       # 프로젝트명
        'creator': item.get('creator').get('name'),     # 크리에이터 이름
        'currencySymbol': item.get('currencySymbol'),   # 화폐단위  ->  여러개임.....;;
        'campaignGoal': item.get('campaignGoal'),       # 목표 금액
        'fundsGathered': item.get('fundsGathered'),     # 모금액
        'backersCount': item.get('backersCount'),       # 후원자 수
        'campaignStart': item.get('campaignStart'),     # 시작일
        'campaignEnd': item.get('campaignEnd'),         # 마감일
        'description': item.get('shortDescription'),    # 설명
        'project_url': item.get('url'),                  # 프로젝트 링크 -> 이거로 추가 크롤링 해야함
        
        'enableBoardGameProperties': item.get('projectProperties').get('enableBoardGameProperties'), # ?
        'minPlayers': item.get('projectProperties').get('minPlayers'), # 최소인원
        'maxPlayers': item.get('projectProperties').get('maxPlayers'), # 최대인원
        'minAge': item.get('projectProperties').get('minAge'), # 연령제한
        'playTime': item.get('projectProperties').get('playTime'), # 플레이타임
        'playTimeDescription': item.get('projectProperties').get('playTimeDescription'), # 설명? 다 비어 있는거 같은데
        'playTimeUnit': item.get('projectProperties').get('playTimeUnit') # ?
    
    
    }
    game_list.append(game_dict)
    
df = pd.DataFrame(game_list)

In [31]:
df

,name,creator,currencySymbol,campaignGoal,fundsGathered,backersCount,campaignEnd,description,project_url,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,playTimeDescription,playTimeUnit
0,Stonesaga Second Printing,Open Owl Studios,$,25000,142095.28,1658,2026-06-20T00:00:00Z,Build a civilization across epochs in a cooper...,https://gamefound.com:443/en/projects/oomm-gam...,True,1,4,NaN,90,None,0
1,Beast: Ashfall,Studio Midhall,€,50000,376075.99,2496,2026-06-03T22:00:00Z,Skies of smoke. Lands of ash. Welcome back to ...,https://gamefound.com:443/en/projects/studio-m...,True,2,5,14.0,120,None,0
2,Capitals of Tactoria,ArcaneArchitect,€,17700,46505.70,463,2026-06-29T22:00:00Z,"Build kingdoms, battle friends, and enjoy fast...",https://gamefound.com:443/en/projects/capitals...,True,1,4,14.0,50,None,0
3,Fall Dawn,Dustiny Games,€,20000,63651.88,737,2026-06-16T17:00:00Z,Fall Dawn is a competitive dungeon-crawler car...,https://gamefound.com:443/en/projects/dustiny-...,True,1,4,14.0,60,None,0
4,VANEA: Guardians of the Eldertree (Relaunch),Forgotten Tales,€,59000,92689.70,534,2026-06-01T16:00:00Z,Welcome to VANEA. A mystical and fairytale - t...,https://gamefound.com:443/en/projects/forgotte...,True,1,4,10.0,90,None,0
5,Pasteles & Conservas: Exotic Tides,SaltandPepper,€,8500,93136.60,1933,2026-06-02T14:00:00Z,Pasteles is a standalone solo game (20–30 minu...,https://gamefound.com:443/en/projects/saltandp...,True,1,1,10.0,30,None,0
6,TATANKA,Creardo,€,5000,15626.11,181,2026-06-25T21:59:00Z,The wind sweeps across the Great Plains. \nThe...,https://gamefound.com:443/en/projects/creardo/...,True,1,4,12.0,80,None,0
7,"Possess Me, Satan",Falling Whale Games,$,10000,38233.40,638,2026-06-20T03:00:00Z,The chaotically fun social deduction game wher...,https://gamefound.com:443/en/projects/dukes-of...,True,5,16,16.0,30,None,0
8,Flockers,Odd Bird,$,25000,74847.88,698,2026-06-05T22:00:00Z,Fly your flock of snow geese southward in this...,https://gamefound.com:443/en/projects/odd-bird...,True,1,4,14.0,45,None,0
9,SYNCANITE FOUNDATION: Reprint + CRIMSON PROTOC...,SYNCANITE GAMES GmbH,€,20000,64346.19,414,2026-05-31T21:59:00Z,Discover SYNCANITE FOUNDATION as a new player ...,https://gamefound.com:443/en/projects/syncanit...,True,1,6,14.0,150,None,0
10,The 30s,Darkkena,€,4800,13637.93,281,2026-06-26T22:00:00Z,The 30s is a descent into horror within an old...,https://gamefound.com:443/en/projects/darkkena...,True,1,2,10.0,15,None,0
11,Ludicurrus,Iconiq Studios,£,10000,23108.65,266,2026-06-10T17:00:00Z,"Ludicurrus is a vibrant, fast-paced chariot ra...",https://gamefound.com:443/en/projects/iconiq-s...,True,1,4,8.0,40,None,0
12,Weasel Wars,dartfrog games,€,18000,39219.72,309,2026-06-08T22:00:00Z,Command ruthless weasel heroes in a living for...,https://gamefound.com:443/en/projects/dartfrog...,True,1,4,10.0,50,None,0
13,Button Shy Spring Collection - International,Button Shy Games,$,2000,7986.29,202,2026-06-06T14:30:00Z,"Choose from Astro ROVE, Jarl, Everything Machi...",https://gamefound.com:443/en/projects/button-s...,True,1,6,14.0,15,None,0
14,Orbital,Firmwar,€,40000,6908.60,26,2026-06-25T16:00:00Z,A cooperative electronic board game where astr...,https://gamefound.com:443/en/projects/firmwar/...,True,1,4,14.0,60,None,0
15,Jure Grando: The first Vampire,InterHuman games,€,4000,17622.80,181,2026-06-05T20:09:00Z,A Folk-Horror Cooperative board game of quiet ...,https://gamefound.com:443/en/projects/interhum...,True,1,4,14.0,60,None,0
16,Hideouts: Legends of The Forest,Weasel & Wolf,£,5000,2011.91,43,2026-06-28T16:00:00Z,"Hideouts is a tile drafting, strategy game for...",https://gamefound.com:443/en/projects/weasel--...,True,2,4,14.0,30,None,0
17,Race to Mars: Lunar Edition,Fur Balloon Games,€,15000,17086.00,469,2026-05-31T21:00:00Z,Race to put the first human being on Mars in t...,https://gamefound.com:443/en/projects/fur-ball...,True,1,4,14.0,75,None,0
18,Dwarf Emberforge,Mythic Ember,€,2450,6080.25,163,2026-06-10T19:00:00Z,Dwarf Emberforge is a fast 2–4-player card-pow...,https://gamefound.com:443/en/projects/mythicem...,True,2,4,12.0,40,None,0
19,Vermines - Deck Building Game,ctrlZEBRE,€,5000,1452.57,25,2026-07-19T21:59:00Z,Vermines is a 2-4 players deckbuilding game wh...,https://gamefound.com:443/en/projects/ctrlzebr...,True,2,4,10.0,40,None,0
20,Kangouroute,Pretexte_editions,€,28000,3631.20,52,2026-06-28T21:59:00Z,"Dans Kangouroute, les animaux de la forêt vois...",https://gamefound.com:443/en/projects/brandonp...,True,2,6,10.0,30,None,0
21,Fluffypede,ShyFinnGames,€,3000,4606.82,70,2026-06-09T15:00:00Z,"Build Fluffypedes together: the longer, the be...",https://gamefound.com:443/en/projects/shy-finn...,True,2,5,8.0,25,None,0
22,Iron Quest: The First Ember [Print & Play],Giza Games,A$,1000,4286.85,145,2026-06-09T12:00:00Z,A Viking sea adventure roll-and-write for 1–4 ...,https://gamefound.com:443/en/projects/giza-gam...,True,1,4,14.0,30,None,0
23,VENATOR: Heroes of the Arena,Red Kingdom Games,€,1000,4156.90,116,2026-06-17T15:00:00Z,"A strategic board game with deckbuilding, focu...",https://gamefound.com:443/en/projects/red-king...,True,2,4,14.0,60,None,0

In [25]:
temp.get('projectProperties')

{'enableBoardGameProperties': True,
 'maxPlayers': 4,
 'minAge': None,
 'minPlayers': 1,
 'playTime': 90,
 'playTimeDescription': None,
 'playTimeUnit': 0}

In [ ]:
import requests
import pandas as pd

api_url = "https://gamefound.com/api/projectSearch/searchProjectsForCards"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

payload = {
    "creatorID": None,
    "creatorName": None,
    "sortType": 0,
    "term": "",
    "projectPhaseSearchTypes": [],
    "projectBenefits": [],
    "projectTags": [],
    "projectCatalogCategories": [11], #보드게임 카테고리 11번
    "playerAges": [],
    "playerCounts": [],
    "playTimes": [],
    "creator": {"creatorID": None, "name": None},
    "userCommunitySearchTypes": [],
    "source": 5,
    "pageIndex": 0 # 0페이지부터 시작 -> 이거 돌려야함
}

response = requests.post(api_url, headers=headers, json=payload)

# 응답 확인
if response.status_code == 200:
    data = response.json()
    print("성공")

else:
    print(f"실패 : {response.status_code}")

In [34]:
data['projects']['totalPageCount']

108

In [ ]:
import requests
import pandas as pd
import time

api_url = "https://gamefound.com/api/projectSearch/searchProjectsForCards"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

payload = {
    "creatorID": None,
    "creatorName": None,
    "sortType": 0,
    "term": "",
    "projectPhaseSearchTypes": [],
    "projectBenefits": [],
    "projectTags": [],
    "projectCatalogCategories": [11], #보드게임 카테고리 11번
    "playerAges": [],
    "playerCounts": [],
    "playTimes": [],
    "creator": {"creatorID": None, "name": None},
    "userCommunitySearchTypes": [],
    "source": 5,
    "pageIndex": 0 # 0페이지부터 시작 -> 이거 돌려야함
}

response = requests.post(api_url, headers=headers, json=payload)

# 응답, 전체 페이지 확인
if response.status_code == 200:
    data = response.json()
    total_page =data.get('projects').get('totalPageCount')
    print(f"전체 페이지 : {total_page}")
    print("성공")

else:
    print(f"실패 : {response.status_code}")

print("----------------------------------------------")
# 전체페이지 for문 ㄱㄱ / 총 108페이지

game_list = []

for page in range(total_page):
    print(f"{page} 페이지 시작")

    payload['pageIndex'] = page

    res = requests.post(api_url, headers=headers, json=payload)

    if res.status_code == 200:
        page_data = res.json()
        projects = page_data.get('projects').get('pagedItems')
        
        projects_data = page_data.get('projects')
        first_num = projects_data.get('firstItemNumber')
        last_num = projects_data.get('lastItemNumber')
        print(f"{first_num}~{last_num}개 진행중")
 
        for item in projects:
            game_dict = {
                'name': item.get('name'),                       # 프로젝트명
                'creator': item.get('creator').get('name'),     # 크리에이터 이름
                'currencySymbol': item.get('currencySymbol'),   # 화폐단위  ->  여러개임.....;;
                'campaignGoal': item.get('campaignGoal'),       # 목표 금액
                'fundsGathered': item.get('fundsGathered'),     # 모금액
                'backersCount': item.get('backersCount'),       # 후원자 수
                'campaignStart': item.get('campaignStart'),     # 시작일
                'campaignEnd': item.get('campaignEnd'),         # 마감일
                'description': item.get('shortDescription'),    # 설명
                'project_url': item.get('url'),                  # 프로젝트 링크 -> 이거로 추가 크롤링 해야함
                
                'enableBoardGameProperties': item.get('projectProperties').get('enableBoardGameProperties'), # ?
                'minPlayers': item.get('projectProperties').get('minPlayers'), # 최소인원
                'maxPlayers': item.get('projectProperties').get('maxPlayers'), # 최대인원
                'minAge': item.get('projectProperties').get('minAge'), # 연령제한
                'playTime': item.get('projectProperties').get('playTime'), # 플레이타임
                'playTimeDescription': item.get('projectProperties').get('playTimeDescription'), # 설명? 다 비어 있는거 같은데
                'playTimeUnit': item.get('projectProperties').get('playTimeUnit') # ?
                        
            }
            game_list.append(game_dict)

    else:
        print(f"{page}페이지 실패")
        pass
    
    time.sleep(1.5)

df = pd.DataFrame(game_list)

전체 페이지 : 108
성공
----------------------------------------------
0 페이지 시작
1~24개 진행중
1 페이지 시작
25~48개 진행중
2 페이지 시작
49~72개 진행중
3 페이지 시작
73~96개 진행중
4 페이지 시작
97~120개 진행중
5 페이지 시작
121~144개 진행중
6 페이지 시작
145~168개 진행중
7 페이지 시작
169~192개 진행중
8 페이지 시작
193~216개 진행중
9 페이지 시작
217~240개 진행중
10 페이지 시작
241~264개 진행중
11 페이지 시작
265~288개 진행중
12 페이지 시작
289~312개 진행중
13 페이지 시작
313~336개 진행중
14 페이지 시작
337~360개 진행중
15 페이지 시작
361~384개 진행중
16 페이지 시작
385~408개 진행중
17 페이지 시작
409~432개 진행중
18 페이지 시작
433~456개 진행중
19 페이지 시작
457~480개 진행중
20 페이지 시작
481~504개 진행중
21 페이지 시작
505~528개 진행중
22 페이지 시작
529~552개 진행중
23 페이지 시작
553~576개 진행중
24 페이지 시작
577~600개 진행중
25 페이지 시작
601~624개 진행중
26 페이지 시작
625~648개 진행중
27 페이지 시작
649~672개 진행중
28 페이지 시작
673~696개 진행중
29 페이지 시작
697~720개 진행중
30 페이지 시작
721~744개 진행중
31 페이지 시작
745~768개 진행중
32 페이지 시작
769~792개 진행중
33 페이지 시작
793~816개 진행중
34 페이지 시작
817~840개 진행중
35 페이지 시작
841~864개 진행중
36 페이지 시작
865~888개 진행중
37 페이지 시작
889~912개 진행중
38 페이지 시작
913~936개 진행중
39 페이지 시작
937~960개 진행중
40 페이지 시작
961~984개 진행중
41 페이지 시작
985~1008개 진행중
42 페이지 시작
1009~1032개 진행중
43 페이지 시작
1033~1056개 진행중
44 페이지 시작
1057~1080개 진행중
45 페이지 시작
1081~1104개 진행중
46 페이지 시작
1105~1128개 진행중
47 페이지 시작
1129~1152개 진행중
48 페이지 시작
1153~1176개 진행중
49 페이지 시작
1177~1200개 진행중
50 페이지 시작
1201~1224개 진행중
51 페이지 시작
1225~1248개 진행중
52 페이지 시작
1249~1272개 진행중
53 페이지 시작
1273~1296개 진행중
54 페이지 시작
1297~1320개 진행중
55 페이지 시작
1321~1344개 진행중
56 페이지 시작
1345~1368개 진행중
57 페이지 시작
1369~1392개 진행중
58 페이지 시작
1393~1416개 진행중
59 페이지 시작
1417~1440개 진행중
60 페이지 시작
1441~1464개 진행중
61 페이지 시작
1465~1488개 진행중
62 페이지 시작
1489~1512개 진행중
63 페이지 시작
1513~1536개 진행중
64 페이지 시작
1537~1560개 진행중
65 페이지 시작
1561~1584개 진행중
66 페이지 시작
1585~1608개 진행중
67 페이지 시작
1609~1632개 진행중
68 페이지 시작
1633~1656개 진행중
69 페이지 시작
1657~1680개 진행중
70 페이지 시작
1681~1704개 진행중
71 페이지 시작
1705~1728개 진행중
72 페이지 시작
1729~1752개 진행중
73 페이지 시작
1753~1776개 진행중
74 페이지 시작
1777~1800개 진행중
75 페이지 시작
1801~1824개 진행중
76 페이지 시작
1825~1848개 진행중
77 페이지 시작
1849~1872개 진행중
78 페이지 시작
1873~1896개 진행중
79 페이지 시작
1897~1920개 진행중
80 페이지 시작
1921~1944개 진행중
81 페이지 시작
1945~1968개 진행중
82 페이지 시작
1969~1992개 진행중
83 페이지 시작
1993~2016개 진행중
84 페이지 시작
2017~2040개 진행중
85 페이지 시작
2041~2064개 진행중
86 페이지 시작
2065~2088개 진행중
87 페이지 시작
2089~2112개 진행중
88 페이지 시작
2113~2136개 진행중
89 페이지 시작
2137~2160개 진행중
90 페이지 시작
2161~2184개 진행중
91 페이지 시작
2185~2208개 진행중
92 페이지 시작
2209~2232개 진행중
93 페이지 시작
2233~2256개 진행중
94 페이지 시작
2257~2280개 진행중
95 페이지 시작
2281~2304개 진행중
96 페이지 시작
2305~2328개 진행중
97 페이지 시작
2329~2352개 진행중
98 페이지 시작
2353~2376개 진행중
99 페이지 시작
2377~2400개 진행중
100 페이지 시작
2401~2424개 진행중
101 페이지 시작
2425~2448개 진행중
102 페이지 시작
2449~2472개 진행중
103 페이지 시작
2473~2496개 진행중
104 페이지 시작
2497~2520개 진행중
105 페이지 시작
2521~2544개 진행중
106 페이지 시작
2545~2568개 진행중
107 페이지 시작
2569~2583개 진행중

In [72]:
df.head()

,name,creator,currencySymbol,campaignGoal,fundsGathered,backersCount,campaignStart,campaignEnd,description,project_url,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,playTimeDescription,playTimeUnit
0,Stonesaga Second Printing,Open Owl Studios,$,25000.0,142350.46,1661,2026-05-26T15:00:00Z,2026-06-20T00:00:00Z,Build a civilization across epochs in a cooper...,https://gamefound.com:443/en/projects/oomm-gam...,True,1.0,4.0,NaN,90.0,None,0
1,Beast: Ashfall,Studio Midhall,€,50000.0,377387.22,2502,2026-05-05T15:00:00Z,2026-06-03T22:00:00Z,Skies of smoke. Lands of ash. Welcome back to ...,https://gamefound.com:443/en/projects/studio-m...,True,2.0,5.0,14.0,120.0,None,0
2,Capitals of Tactoria,ArcaneArchitect,€,17700.0,46591.05,463,2026-05-26T15:00:00Z,2026-06-29T22:00:00Z,"Build kingdoms, battle friends, and enjoy fast...",https://gamefound.com:443/en/projects/capitals...,True,1.0,4.0,14.0,50.0,None,0
3,Fall Dawn,Dustiny Games,€,20000.0,63783.77,738,2026-05-19T14:00:00Z,2026-06-16T17:00:00Z,Fall Dawn is a competitive dungeon-crawler car...,https://gamefound.com:443/en/projects/dustiny-...,True,1.0,4.0,14.0,60.0,None,0
4,VANEA: Guardians of the Eldertree (Relaunch),Forgotten Tales,€,59000.0,92825.20,535,2026-05-12T16:00:00Z,2026-06-01T16:00:00Z,Welcome to VANEA. A mystical and fairytale - t...,https://gamefound.com:443/en/projects/forgotte...,True,1.0,4.0,10.0,90.0,None,0

In [52]:
df.tail()

,name,creator,currencySymbol,campaignGoal,fundsGathered,backersCount,campaignStart,campaignEnd,description,project_url,enableBoardGameProperties,minPlayers,maxPlayers,minAge,playTime,playTimeDescription,playTimeUnit
2578,Spring and Autumn: Story of China,Mr. B. Games,$,30000.0,38009.00,219,2021-12-01T15:00:00Z,2022-01-04T22:00:00Z,Welcome to Spring and Autumn: Story of China! ...,https://gamefound.com:443/en/projects/mr-b-gam...,True,1.0,5.0,13.0,120.0,None,0
2579,Crossroads Inn: The Board Game,Klabater,€,20000.0,13420.63,158,2021-10-28T14:00:00Z,2021-11-30T15:00:00Z,Folks! We keep playing games about dungeons an...,https://gamefound.com:443/en/projects/klabater...,True,2.0,4.0,12.0,120.0,None,0
2580,PACHAMAMA,SitDown,€,25000.0,16048.00,318,2021-10-19T17:00:00Z,2021-11-09T18:00:00Z,The Earth Goddess Pachamama constantly guides ...,https://gamefound.com:443/en/projects/sitdown/...,True,1.0,4.0,14.0,60.0,None,0
2581,Taverns & Dragons (Canceled),Lord Raccoon Games,€,20000.0,20954.00,470,2021-10-12T13:00:00Z,2021-11-03T22:00:00Z,Gather magic mushrooms and dragon eggs in the ...,https://gamefound.com:443/en/projects/thelastb...,True,2.0,5.0,10.0,60.0,None,0
2582,Goldenstar: The Galactic Tournament,Gindi,€,30000.0,10890.00,148,2021-10-05T16:00:00Z,2021-10-29T16:00:00Z,"Enter the Tournament in this Asymmetric, Deck ...",https://gamefound.com:443/en/projects/gindi/go...,True,2.0,4.0,14.0,60.0,None,0

In [ ]:
import os
current_dir = os.getcwd()
parent_dir = os.path.dirname(current_dir)

df.to_csv(parent_dir+"\\02_Data\\raw\\gamefound_list.csv", index=True, encoding="utf-8-sig")

세부 페이지 크롤링(코멘트)

In [1]:
import os
import pandas as pd
current_dir = os.getcwd()
parent_dir = os.path.dirname(current_dir)

In [2]:
df = pd.read_csv(parent_dir+"\\02_Data\\raw\\gamefound_list.csv")

In [4]:
df["project_url"][0]

'https://gamefound.com:443/en/projects/oomm-games/stonesaga-second-printing'

In [5]:
import requests
import pandas as pd

api_url = "https://gamefound.com/api/comments/getComments"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
}

# 위에 주소 말고 어딘가에 넘버로 있을듯?
payload = {
    "GetCommentsForCurrentUser": False,
    "commentID": None,
    "commentThreadID": 75760, # 이게 게임 고유값? 확인해봐야함
    "freshCommentID": None,
    "getCommentsWithCreatorInput": False,
    "highlightedCommentID": None,
    "lastFetchedCommentID": None,
    "lastPinnedAt": None,
    "lastScore": None,
    "selectedCommentFilter": None,
    "sortType": 0,  # 0 : recent 1 : popularr
    "tag": None
}

response = requests.post(api_url, headers=headers, json=payload)

In [6]:
data = response.json()
data

{'data': {'newMessagesCount': 0,
  'pagedItems': [{'authorID': 244541,
    'authorType': 1,
    'children': [],
    'childrenTotalCount': 0,
    'commentID': 2598484,
    'commentThreadID': 75760,
    'createdAt': '2026-05-26T15:30:56.06Z',
    'editedAt': None,
    'isDeleted': False,
    'isHidden': False,
    'isReportedByCreator': False,
    'likesCount': 11,
    'newerChildrenCount': 0,
    'newRepliesCount': 0,
    'parentID': None,
    'pinnedAt': '2026-05-26T15:30:58.357Z',
    'text': "Funded! Let's keep it going!",
    'userComment': None},
   {'authorID': 515392,
    'authorType': 0,
    'children': [],
    'childrenTotalCount': 0,
    'commentID': 2609072,
    'commentThreadID': 75760,
    'createdAt': '2026-05-31T04:51:54.227Z',
    'editedAt': None,
    'isDeleted': False,
    'isHidden': False,
    'isReportedByCreator': False,
    'likesCount': 0,
    'newerChildrenCount': 0,
    'newRepliesCount': 0,
    'parentID': None,
    'pinnedAt': None,
    'text': 'Shouldnt Errata pack include a free journal book as well? First printing recharge pack didnt include it, but it was meant for every legacy component. Right now I have to buy another Recharge pack although i actually need only the Journal, I already have tons of character and outpost cards.',
    'userComment': None},
   {'authorID': 1217273,
    'authorType': 0,
    'children': [{'authorID': 244541,
      'authorType': 1,
      'children': None,
      'childrenTotalCount': 0,
      'commentID': 2609939,
      'commentThreadID': 75760,
      'createdAt': '2026-05-31T20:10:05.677Z',
      'editedAt': None,
      'isDeleted': False,
      'isHidden': False,
      'isReportedByCreator': False,
      'likesCount': 2,
      'newerChildrenCount': 0,
      'newRepliesCount': 0,
      'parentID': 2608998,
      'pinnedAt': None,
      'text': 'We actually hired multiple people in the rulebook creation! Outside of the errata, we feel that the rulebook is actually quite good for the type and scope of game Stonesaga is!',
      'userComment': None}],
    'childrenTotalCount': 1,
    'commentID': 2608998,
    'commentThreadID': 75760,
    'createdAt': '2026-05-31T01:41:22.533Z',
    'editedAt': None,
    'isDeleted': False,
    'isHidden': False,
    'isReportedByCreator': False,
    'likesCount': 0,
    'newerChildrenCount': 0,
    'newRepliesCount': 0,
    'parentID': None,
    'pinnedAt': None,
    'text': "Would it be possible to hire an external rulebook reviewer like Paul Grogan, Stephan Brück or Chad Jensen to make sure it's top notch? I think it would be small investment but big ROI given the current reviews on BGG and youtube",
    'userComment': None},
   {'authorID': 23628,
    'authorType': 0,
    'children': [{'authorID': 2092016,
      'authorType': 1,
      'children': None,
      'childrenTotalCount': 0,
      'commentID': 2609458,
      'commentThreadID': 75760,
      'createdAt': '2026-05-31T13:48:08.993Z',
      'editedAt': None,
      'isDeleted': False,
      'isHidden': False,
      'isReportedByCreator': False,
      'likesCount': 0,
      'newerChildrenCount': 0,
      'newRepliesCount': 0,
      'parentID': 2608134,
      'pinnedAt': None,
      'text': 'Hi, Sparhawk. Everything is being produced together and will ship together.',
      'userComment': None},
     {'authorID': 23628,
      'authorType': 0,
      'children': None,
      'childrenTotalCount': 0,
      'commentID': 2609562,
      'commentThreadID': 75760,
      'createdAt': '2026-05-31T15:30:19.393Z',
      'editedAt': None,
      'isDeleted': False,
      'isHidden': False,
      'isReportedByCreator': False,
      'likesCount': 0,
      'newerChildrenCount': 0,
      'newRepliesCount': 0,
      'parentID': 2608134,
      'pinnedAt': None,
      'text': 'Is it possible to get it as a pdf, end 2026 is a long time',
      'userComment': None},
     {'authorID': 91320,
      'authorType': 0,
      'children': None,
      'childrenTotalCount': 0,
      'commentID': 2609765,
      'commentThreadID': 75760,
      'createdAt': '2026-05-31T18:06:20.053Z',
      'editedAt': None,
      'isDeleted': False,
      'isHidden': False,
      'isReportedByCreator': False,
      'likesCount': 1,
      'newerChildrenCount': 0,
      'newRepliesCount': 0,
      'parentID': 2608134,
      'pinnedAt': None,
      'text': '@Sparhawk: The PDFs are linked in Update #1.',
      'userComment': None}],
    'childrenTotalCount': 4,
    'commentID': 2608134,
    'commentThreadID': 75760,
    'createdAt': '2026-05-30T10:53:21.483Z',
    'editedAt': None,
    'isDeleted': False,
    'isHidden': False,
    'isReportedByCreator': False,
    'likesCount': 0,
    'newerChildrenCount': 0,
    'newRepliesCount': 0,
    'parentID': None,
    'pinnedAt': None,
    'text': 'Is it possible to send the upgrade pack sooner??',
    'userComment': None},
   {'authorID': 1350975,
    'authorType': 0,
    'children': [{'authorID': 1350975,
      'authorType': 0,
      'children': None,
      'childrenTotalCount': 0,
      'commentID': 2609081,
      'commentThreadID': 75760,
      'createdAt': '2026-05-31T05:15:29.937Z',
      'editedAt': None,
      'isDeleted': False,
      'isHidden': False,
      'isReportedByCreator': False,
      'likesCount': 0,
      'newerChildrenCount': 0,
      'newRepliesCount': 0,
      'parentID': 2608131,
      'pinnedAt': None,
      'text': "It's coming out in stores in June, and we still haven't received it",
      'userComment': None},
     {'authorID': 1217273,
      'authorType': 0,
      'children': None,
      'childrenTotalCount': 0,
      'commentID': 2609085,
      'commentThreadID': 75760,
      'createdAt': '2026-05-31T05:35:35.563Z',
      'editedAt': None,
      'isDeleted': False,
      'isHidden': False,
      'isReportedByCreator': False,
      'likesCount': 0,
      'newerChildrenCount': 0,
      'newRepliesCount': 0,
      'parentID': 2608131,
      'pinnedAt': None,
      'text': 'Really? I received that months ago 😮',
      'userComment': None},
     {'authorID': 1350975,
      'authorType': 0,
      'children': None,
      'childrenTotalCount': 0,
      'commentID': 2609087,
      'commentThreadID': 75760,
      'createdAt': '2026-05-31T05:39:18.603Z',
      'editedAt': None,
      'isDeleted': False,
      'isHidden': False,
      'isReportedByCreator': False,
      'likesCount': 0,
      'newerChildrenCount': 0,
      'newRepliesCount': 0,
      'parentID': 2608131,
      'pinnedAt': None,
      'text': 'French version for me',
      'userComment': None}],
    'childrenTotalCount': 4,
    'commentID': 2608131,
    'commentThreadID': 75760,
    'createdAt': '2026-05-30T10:52:49.09Z',
    'editedAt': None,
    'isDeleted': False,
    'isHidden': False,
    'isReportedByCreator': False,
    'likesCount': 0,
    'newerChildrenCount': 0,
    'newRepliesCount': 0,
    'parentID': None,
    'pinnedAt': None,
    'text': 'Attendez sa sortie en boutique, ça vaut mieux. Vu ce qui se passe pour Storyfold: Wildwoods',
    'userComment': None},
   {'authorID': 1287473,
    'authorType': 0,
    'children': [{'authorID': 244541,
      'authorType': 1,
      'children': None,
      'childrenTotalCount': 0,
      'commentID': 2609946,
      'commentThreadID': 75760,
      'createdAt': '2026-05-31T20:11:12.993Z',
      'editedAt': None,
      'isDeleted': False,
      'isHidden': False,
      'isReportedByCreator': False,
      'likesCount': 1,
      'newerChildrenCount': 0,
      'newRepliesCount': 0,
      'parentID': 2607414,
      'pinnedAt': None,
      'text': "We haven't opened retail orders for the second printing at all, so maybe this is still first printing?",
      'userComment': None}],
    'childrenTotalCount': 1,
    'commentID': 2607414,
    'commentThreadID': 75760,
    'createdAt': '2026-05-29T21:26:35.41Z',
    'editedAt': None,
    'isDeleted': False,
    'isHidden': False,
    'isReportedByCreator': False,
    'likesCount': 1,
    'newerChildrenCount': 0,
    'newRepliesCount': 0,
    'parentID': None,
    'pinnedAt': None,
    'text': 'why are kickstarter versions of Stonesaga pre-orders already available on websites for a cheaper cost with free shipping?',
    'userComment': None},
   {'authorID': 257291,
    'authorType': 0,
    'children': [{'authorID': 1359539,
      'authorType': 0,
      'children': None,
      'childrenTotalCount': 0,
      'commentID': 2608128,
      'commentThreadID': 75760,
      'createdAt': '2026-05-30T10:49:53.143Z',
      'editedAt': None,
      'isDeleted': False,
      'isHidden': False,
      'isReportedByCreator': False,
      'likesCount': 0,
      'newerChildrenCount': 0,
      'newRepliesCount': 0,
      'parentID': 2607034,
      'pinnedAt': None,
      'text': 'I may not have been clear.\xa0 Theblelather journal is just blank.\xa0 \xa0You could absolutely use it to take the same notes you would on the in game journal to track your societys cultural knowledge, discoveries, and challenge records.\xa0 It just wont have the formatting.\xa0 It isnjuat a nice little leatherbound journal with blank pages that can be used in whatever purpose you see fit.\n\nI was referring to a pdf of the actual game component in the corebox - journal with formatting and space to record info.',
      'userComment': None},
     {'authorID': 20049,
      'authorType': 0,
      'children': None,
      'childrenTotalCount': 0,
      'commentID': 2608142,
      'commentThreadID': 75760,
      'createdAt': '2026-05-30T11:01:09.577Z',
      'editedAt': None,
      'isDeleted': False,
      'isHidden': False,
      'isReportedByCreator': False,
      'likesCount': 0,
      'newerChildrenCount': 0,
      'newRepliesCount': 0,
      'parentID': 2607034,
      'pinnedAt': None,
      'text': "You don't need to add the journal. It's included in the core game.",
      'userComment': None},
     {'authorID': 257291,
      'authorType': 0,
      'children': None,
      'childrenTotalCount': 0,
      'commentID': 2608526,
      'commentThreadID': 75760,
      'createdAt': '2026-05-30T17:04:53.563Z',
      'editedAt': None,
      'isDeleted': False,
      'isHidden': False,
      'isReportedByCreator': False,
      'likesCount': 0,
      'newerChildrenCount': 0,
      'newRepliesCount': 0,
      'parentID': 2607034,
      'pinnedAt': None,
      'text': 'I see, Thank you',
      'userComment': None}],
    'childrenTotalCount': 5,
    'commentID': 2607034,
    'commentThreadID': 75760,
    'createdAt': '2026-05-29T17:49:11.357Z',
    'editedAt': None,
    'isDeleted': False,
    'isHidden': False,
    'isReportedByCreator': False,
    'likesCount': 0,
    'newerChildrenCount': 0,
    'newRepliesCount': 0,
    'parentID': None,
    'pinnedAt': None,
    'text': 'Regarding adons:\nWill there be a photo of Deluxe Dice?\xa0\nIs the journal expected to be used? Is there really a reason to write many things down during the campaign?',
    'userComment': None},
   {'authorID': 667418,
    'authorType': 0,
    'children': [{'authorID': 2092016,
      'authorType': 1,
      'children': None,
      'childrenTotalCount': 0,
      'commentID': 2606124,
      'commentThreadID': 75760,
      'createdAt': '2026-05-29T12:25:41.847Z',
      'editedAt': None,
      'isDeleted': False,
      'isHidden': False,
      'isReportedByCreator': False,
      'likesCount': 0,
      'newerChildrenCount': 0,
      'newRepliesCount': 0,
      'parentID': 2605950,
      'pinnedAt': None,
      'text': 'Hey Valen. STONESAGA is available in multiple languages through our partners in their regions.',
      'userComment': None}],
    'childrenTotalCount': 1,
    'commentID': 2605950,
    'commentThreadID': 75760,
    'createdAt': '2026-05-29T10:42:14.11Z',
    'editedAt': None,
    'isDeleted': False,
    'isHidden': False,
    'isReportedByCreator': False,
    'likesCount': 0,
    'newerChildrenCount': 0,
    'newRepliesCount': 0,
    'parentID': None,
    'pinnedAt': None,
    'text': 'This Project Looks awesome, i wonder If there will be a language kit available any time?',
    'userComment': None},
   {'authorID': 1260308,
    'authorType': 0,
    'children': [{'authorID': 244541,
      'authorType': 1,
      'children': None,
      'childrenTotalCount': 0,
      'commentID': 2606849,
      'commentThreadID': 75760,
      'createdAt': '2026-05-29T16:34:19.887Z',
      'editedAt': None,
      'isDeleted': False,
      'isHidden': False,
      'isReportedByCreator': False,
      'likesCount': 2,
      'newerChildrenCount': 0,
      'newRepliesCount': 0,
      'parentID': 2605852,
      'pinnedAt': None,
      'text': 'December! We are manufacturing everthing together',
      'userComment': None}],
    'childrenTotalCount': 1,
    'commentID': 2605852,
    'commentThreadID': 75760,
    'createdAt': '2026-05-29T10:05:43.683Z',
    'editedAt': None,
    'isDeleted': False,
    'isHidden': False,
    'isReportedByCreator': False,
    'likesCount': 0,
    'newerChildrenCount': 0,
    'newRepliesCount': 0,
    'parentID': None,
    'pinnedAt': None,
    'text': 'If i would order the errata and 1 or 2 recharge packs, how long would it take for these to ship?',
    'userComment': None},
   {'authorID': 1270970,
    'authorType': 0,
    'children': [{'authorID': 244541,
      'authorType': 1,
      'children': None,
      'childrenTotalCount': 0,
      'commentID': 2606853,
      'commentThreadID': 75760,
      'createdAt': '2026-05-29T16:34:30.007Z',
      'editedAt': None,
      'isDeleted': False,
      'isHidden': False,
      'isReportedByCreator': False,
      'likesCount': 0,
      'newerChildrenCount': 0,
      'newRepliesCount': 0,
      'parentID': 2604728,
      'pinnedAt': None,
      'text': 'The language editions have a majority of the changes already implemented!',
      'userComment': None}],
    'childrenTotalCount': 1,
    'commentID': 2604728,
    'commentThreadID': 75760,
    'createdAt': '2026-05-28T20:40:22.263Z',
    'editedAt': None,
    'isDeleted': False,
    'isHidden': False,
    'isReportedByCreator': False,
    'likesCount': 0,
    'newerChildrenCount': 0,
    'newRepliesCount': 0,
    'parentID': None,
    'pinnedAt': None,
    'text': 'No langages location for a second édition ? 😭',
    'userComment': None},
   {'authorID': 972557,
    'authorType': 0,
    'children': [{'authorID': 244541,
      'authorType': 1,
      'children': None,
      'childrenTotalCount': 0,
      'commentID': 2606855,
      'commentThreadID': 75760,
      'createdAt': '2026-05-29T16:34:53.383Z',
      'editedAt': None,
      'isDeleted': False,
      'isHidden': False,
      'isReportedByCreator': False,
      'likesCount': 1,
      'newerChildrenCount': 0,
      'newRepliesCount': 0,
      'parentID': 2604233,
      'pinnedAt': None,
      'text': 'Add-ons will be much harder to come by retail, but everything should be available on our website after in limited quantity.',
      'userComment': None}],
    'childrenTotalCount': 1,
    'commentID': 2604233,
    'commentThreadID': 75760,
    'createdAt': '2026-05-28T17:41:13.063Z',
    'editedAt': None,
    'isDeleted': False,
    'isHidden': False,
    'isReportedByCreator': False,
    'likesCount': 1,
    'newerChildrenCount': 0,
    'newRepliesCount': 0,
    'parentID': None,
    'pinnedAt': None,
    'text': 'Is there anything kickstarter exclusieve? Or will the game and components be the same as in retail?',
    'userComment': None},
   {'authorID': 1264608,
    'authorType': 0,
    'children': [{'authorID': 1264608,
      'authorType': 0,
      'children': None,
      'childrenTotalCount': 0,
      'commentID': 2607786,
      'commentThreadID': 75760,
      'createdAt': '2026-05-30T04:07:04.85Z',
      'editedAt': None,
      'isDeleted': False,
      'isHidden': False,
      'isReportedByCreator': False,
      'likesCount': 0,
      'newerChildrenCount': 0,
      'newRepliesCount': 0,
      'parentID': 2603760,
      'pinnedAt': None,
      'text': "You're welcome to have buyer's remorse, but I know what I want for me and that's why I asked for it\xa0\n\nI don't need every card to have a sleeve, but I do want it. I didn't even realize that was an add on last time or I would have gotten it. Additionally, I'm having a hard time finding each sleeve size in my local hobby stores, and don't want just a few things with sleeves.",
      'userComment': None},
     {'authorID': 1359539,
      'authorType': 0,
      'children': None,
      'childrenTotalCount': 0,
      'commentID': 2607811,
      'commentThreadID': 75760,
      'createdAt': '2026-05-30T04:40:26.137Z',
      'editedAt': None,
      'isDeleted': False,
      'isHidden': False,
      'isReportedByCreator': False,
      'likesCount': 0,
      'newerChildrenCount': 0,
      'newRepliesCount': 0,
      'parentID': 2603760,
      'pinnedAt': None,
      'text': "I don't have buyers remorse.\xa0 I was sharing my experience that the sleeve pack ended up giving me more sleeves than I ended up needing The sleeves were not unique in any way.\xa0 They are clear durable sleeves, easy to find online.",
      'userComment': None},
     {'authorID': 1264608,
      'authorType': 0,
      'children': None,
      'childrenTotalCount': 0,
      'commentID': 2607816,
      'commentThreadID': 75760,
      'createdAt': '2026-05-30T04:46:55.313Z',
      'editedAt': None,
      'isDeleted': False,
      'isHidden': False,
      'isReportedByCreator': False,
      'likesCount': 0,
      'newerChildrenCount': 0,
      'newRepliesCount': 0,
      'parentID': 2603760,
      'pinnedAt': None,
      'text': "I know I could buy them online, I'd rather support the developers, which is why I asked for it from them, yet you still suggest I do something other than that. Clearly we don't have the same viewpoint, yet you persist unnecessarily. It's ok to disagree, don't need your opinions on it ✌️",
      'userComment': None}],
    'childrenTotalCount': 5,
    'commentID': 2603760,
    'commentThreadID': 75760,
    'createdAt': '2026-05-28T15:45:56.033Z',
    'editedAt': None,
    'isDeleted': False,
    'isHidden': False,
    'isReportedByCreator': False,
    'likesCount': 2,
    'newerChildrenCount': 0,
    'newRepliesCount': 0,
    'parentID': None,
    'pinnedAt': None,
    'text': 'Can the card sleeve combo be added to the second printing for those of us that were foolish enough to skip it the first time',
    'userComment': None},
   {'authorID': 716133,
    'authorType': 0,
    'children': [{'authorID': 244541,
      'authorType': 1,
      'children': None,
      'childrenTotalCount': 0,
      'commentID': 2603712,
      'commentThreadID': 75760,
      'createdAt': '2026-05-28T15:35:48.637Z',
      'editedAt': None,
      'isDeleted': False,
      'isHidden': False,
      'isReportedByCreator': False,
      'likesCount': 0,
      'newerChildrenCount': 0,
      'newRepliesCount': 0,
      'parentID': 2602712,
      'pinnedAt': None,
      'text': 'Yes, it’s just blank inside!',
      'userComment': None}],
    'childrenTotalCount': 1,
    'commentID': 2602712,
    'commentThreadID': 75760,
    'createdAt': '2026-05-28T10:17:14.493Z',
    'editedAt': None,
    'isDeleted': False,
    'isHidden': False,
    'isReportedByCreator': False,
    'likesCount': 0,
    'newerChildrenCount': 0,
    'newRepliesCount': 0,
    'parentID': None,
    'pinnedAt': None,
    'text': "Question about the faux leather journal in the All In pledge. Is it the same as the regular journal, but with a nicer cover? I saw somewhere that it's just blank inside...",
    'userComment': None},
   {'authorID': 491035,
    'authorType': 0,
    'children': [],
    'childrenTotalCount': 0,
    'commentID': 2602663,
    'commentThreadID': 75760,
    'createdAt': '2026-05-28T09:55:30.11Z',
    'editedAt': None,
    'isDeleted': False,
    'isHidden': False,
    'isReportedByCreator': False,
    'likesCount': 1,
    'newerChildrenCount': 0,
    'newRepliesCount': 0,
    'parentID': None,
    'pinnedAt': None,

In [7]:
comments = data.get('data').get('pagedItems')
comments[0]

{'authorID': 244541,
 'authorType': 1,
 'children': [],
 'childrenTotalCount': 0,
 'commentID': 2598484,
 'commentThreadID': 75760,
 'createdAt': '2026-05-26T15:30:56.06Z',
 'editedAt': None,
 'isDeleted': False,
 'isHidden': False,
 'isReportedByCreator': False,
 'likesCount': 11,
 'newerChildrenCount': 0,
 'newRepliesCount': 0,
 'parentID': None,
 'pinnedAt': '2026-05-26T15:30:58.357Z',
 'text': "Funded! Let's keep it going!",
 'userComment': None}

In [8]:
if response.status_code == 200:
    data = response.json()
    
    comments = data.get('data').get('pagedItems') 
    
    comment_list = []
    
    for comment in comments:
        comment_list.append({
            'commentID' : comment.get('commentID'), # 아이디(고유번호로 뜨는듯)
            'createdAt' : comment.get('createdAt'), # 작성일
            'likesCount': comment.get('likesCount'),  # 좋아요 수
            #'pinnedAt': comment.get('pinnedAt'),       ??
            'text': comment.get('text')    # 댓글
        })
        
    df = pd.DataFrame(comment_list)
    print(df.head())
    
else:
    print(f"데이터를 가져오는데 실패했습니다. 상태 코드: {response.status_code}")

   commentID                 createdAt  likesCount  \
0    2598484   2026-05-26T15:30:56.06Z          11
1    2609072  2026-05-31T04:51:54.227Z           0
2    2608998  2026-05-31T01:41:22.533Z           0
3    2608134  2026-05-30T10:53:21.483Z           0
4    2608131   2026-05-30T10:52:49.09Z           0

                                                text
0                       Funded! Let's keep it going!
1  Shouldnt Errata pack include a free journal bo...
2  Would it be possible to hire an external ruleb...
3   Is it possible to send the upgrade pack sooner??
4  Attendez sa sortie en boutique, ça vaut mieux....

In [9]:
comments[1]

{'authorID': 515392,
 'authorType': 0,
 'children': [],
 'childrenTotalCount': 0,
 'commentID': 2609072,
 'commentThreadID': 75760,
 'createdAt': '2026-05-31T04:51:54.227Z',
 'editedAt': None,
 'isDeleted': False,
 'isHidden': False,
 'isReportedByCreator': False,
 'likesCount': 0,
 'newerChildrenCount': 0,
 'newRepliesCount': 0,
 'parentID': None,
 'pinnedAt': None,
 'text': 'Shouldnt Errata pack include a free journal book as well? First printing recharge pack didnt include it, but it was meant for every legacy component. Right now I have to buy another Recharge pack although i actually need only the Journal, I already have tons of character and outpost cards.',
 'userComment': None}

project 페이지 크롤링

In [10]:
import requests
from bs4 import BeautifulSoup

url = 'https://gamefound.com/en/projects/oomm-games/stonesaga-second-printing'

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, 'html.parser')

In [11]:
soup

<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, viewport-fit=cover, initial-scale=1 minimum-scale=1 maximum-scale=1" name="viewport"/>
<link crossorigin="" href="https://fonts.googleapis.com/" rel="preconnect"/>
<link href="https://fonts.googleapis.com/" rel="dns-prefetch"/>
<link crossorigin="" href="https://cdn.static.gamefound.com/content/" rel="preconnect"/>
<link href="https://cdn.static.gamefound.com/content/" rel="dns-prefetch"/>
<link crossorigin="" href="https://imgcdn.gamefound.com/" rel="preconnect"/>
<link href="https://imgcdn.gamefound.com/" rel="dns-prefetch"/>
<link crossorigin="" href="https://vcdn.gamefound.com/" rel="preconnect"/>
<link href="https://vcdn.gamefound.com/" rel="dns-prefetch"/>
<link href="https://fonts.googleapis.com/css?family=Roboto+Slab:700|Nunito+Sans:300,400,700,800" rel="stylesheet"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/lib/fontawesome-6.4.2/css/fontawesome-bundle.css" rel="stylesheet">
<meta content="no" name="msapplication-tap-highlight"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png">
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png">
<link href="/manifest.json" rel="manifest">
<link color="#5bbad5" href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/safari-pinned-tab.svg" rel="mask-icon">
<link href="/favicon.ico?v=1_szjInOnLLEcnJ4HqWv-ZjF7uilrJk0JZ8_5dgBaNM" rel="shortcut icon">
<meta content="#00aba9" name="msapplication-TileColor">
<meta content="#ffffff" name="theme-color">
<title>Stonesaga Second Printing by Open Owl Studios - Gamefound</title>
<meta content="Build a civilization across epochs in a cooperative survival crafting saga set in a persistent world shaped by your choices." name="description">
<meta name="keywords">
<meta content="en" http-equiv="Content-Language"/>
<link href="https://gamefound.com/en/projects/oomm-games/stonesaga-second-printing" rel="canonical">
<link href="https://gamefound.com/it/projects/oomm-games/stonesaga-second-printing" hreflang="it" rel="alternate">
<link href="https://gamefound.com/fr/projects/oomm-games/stonesaga-second-printing" hreflang="fr" rel="alternate">
<link href="https://gamefound.com/de/projects/oomm-games/stonesaga-second-printing" hreflang="de" rel="alternate">
<link href="https://gamefound.com/pl/projects/oomm-games/stonesaga-second-printing" hreflang="pl" rel="alternate">
<link href="https://gamefound.com/es/projects/oomm-games/stonesaga-second-printing" hreflang="es" rel="alternate">
<link href="https://gamefound.com/cs/projects/oomm-games/stonesaga-second-printing" hreflang="cs" rel="alternate">
<link href="https://gamefound.com/pt/projects/oomm-games/stonesaga-second-printing" hreflang="pt" rel="alternate">
<link href="https://gamefound.com/zh/projects/oomm-games/stonesaga-second-printing" hreflang="zh" rel="alternate">
<meta content="website" property="og:type"/>
<meta content="https://gamefound.com/en/projects/oomm-games/stonesaga-second-printing" property="og:url"/>
<meta content="Stonesaga Second Printing by Open Owl Studios - Gamefound" property="og:title"/>
<meta content="Build a civilization across epochs in a cooperative survival crafting saga set in a persistent world shaped by your choices." property="og:description"/>
<meta content="https://imgcdn.gamefound.com/og-image-fb/projects/9678/96d0a055-53fe-47ff-8973-cc6d1e239eca.png" property="og:image"/>
<meta content="1200" property="og:image:width"/>
<meta content="630" property="og:image:height"/>
<meta content="https://imgcdn.gamefound.com/og-image-square/projects/9678/0e9a20f1-7e79-4057-9f51-2d957a571d56.png" property="og:image"/>
<meta content="700" property="og:image:width"/>
<meta content="700" property="og:image:height"/>
<meta content="https://imgcdn.gamefound.com/og-image-fb/projects/9678/96d0a055-53fe-47ff-8973-cc6d1e239eca.png" name="twitter:image"/>
<meta content="summary_large_image" name="twitter:card">
<meta content="@Gamefound" name="twitter:site"/>
<meta content="Stonesaga Second Printing by Open Owl Studios - Gamefound" name="twitter:title"/>
<meta content="Build a civilization across epochs in a cooperative survival crafting saga set in a persistent world shaped by your choices." name="twitter:description"/>
<meta content="https://gamefound.com/en/projects/oomm-games/stonesaga-second-printing" name="twitter:url"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/styles/main-bundle.css" rel="stylesheet">
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/icons/main-icons-bundle.css" rel="stylesheet">
<script>
        (function (){
            const localStorageValue = JSON.parse(localStorage.getItem('store.webTheme'));
            if (localStorageValue && localStorageValue.theme) {
                document.documentElement.setAttribute('data-theme', localStorageValue.theme);
            }
            else {
                if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
                    document.documentElement.setAttribute('data-theme', 'dark');
                }
                else {
                    document.documentElement.setAttribute('data-theme', 'bright');
                }
            }
        })();
    </script>
<script>
    function pushNotificationHandler(event) {
        if (event && event.detail) {
            window.location.href = event.detail.actionUrl;
        }
    }

    window.addEventListener('push-notification', pushNotificationHandler);
    window.addEventListener('push-notification-tapped', pushNotificationHandler);
</script>
<script>
        if (window.Intl && window.location.href.indexOf('http') >= 0) {
            (function () {
                var ignoredErrors = [];
                var _rollbarConfig = {
                    accessToken: "9e559d4b594a4e25a4e5918f8f72ca3d",
                    captureUncaught: false,
                    captureUnhandledRejections: false,
                    payload: {
                        custom: {"analyticsSessionTrackingID":"08debf6bb79c33e6-8c75743a-56c7-4807-b03f-bebe62cd04af","browserSessionTrackingID":"be13a864-b134-4b01-8b8a-1df5018990b3","deviceTrackingID":"dd67cab7-120a-416c-8345-fb86016c73c0","facebookBrowserID":null,"facebookClickID":null,"requestTrackingID":"4000f82c-0004-e400-b63f-84710c7967bb","userTrackingID":"c4835fc9-f581-4283-b5fa-1047b92de019"},
                        environment: "Production",
                        person: null,
                        client: {
                            javascript: {
                                code_version: "https://cdn.static.gamefound.com/content/20260525.3-13/scripts/main.js",
                                guess_uncaught_frames: true,
                                source_map_enabled: true
                            },
                        }
                    },
                    ignoredMessages: ["Network Error", "Request failed with status code", "AxiosError"],
                    checkIgnore: function (isUncaught, args, payload) {
                        // Ignore main lib error after first occurence
                        if (payload && payload.body && payload.body.trace && payload.body.trace.exception) {
                            var message = payload.body.trace.exception.message;
                            if (ignoredErrors.includes(message)) {
                                return true;
                            }
                            if (typeof App === 'undefined') {
                                ignoredErrors.push(message);
                            }
                        }

                        // Attempt to exclude errors from external scripts
                        if (payload && payload.body && payload.body.trace
                            && payload.body.trace.frames && payload.body.trace.frames.length === 1 && payload.body.trace.frames[0].method == "[anonymous]"
                            && payload.body.trace.exception && payload.body.trace.exception.class == "(unknown)") {
                            return true;
                        }

                        return false;
                    },
                    transform: function(payload) {
                        // Extract area tag from error context if present
                        if (payload && payload.data && payload.data.custom) {
                            var error = arguments[0];
                            if (error && error._rollbarContext && error._rollbarContext.area) {
                                payload.data.custom.area = error._rollbarContext.area;
                            }
                        }
                    }
                };

                // Rollbar Snippet
                !function(r){var e={};function o(n){if(e[n])return e[n].exports;var t=e[n]={i:n,l:!1,exports:{}};return r[n].call(t.exports,t,t.exports,o),t.l=!0,t.exports}o.m=r,o.c=e,o.d=function(r,e,n){o.o(r,e)||Object.defineProperty(r,e,{enumerable:!0,get:n})},o.r=function(r){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(r,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(r,"__esModule",{value:!0})},o.t=function(r,e){if(1&e&&(r=o(r)),8&e)return r;if(4&e&&"object"==typeof r&&r&&r.__esModule)return r;var n=Object.create(null);if(o.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:r}),2&e&&"string"!=typeof r)for(var t in r)o.d(n,t,function(e){return r[e]}.bind(null,t));return n},o.n=function(r){var e=r&&r.__esModule?function(){return r.default}:function(){return r};return o.d(e,"a",e),e},o.o=function(r,e){return Object.prototype.hasOwnProperty.call(r,e)},o.p="",o(o.s=0)}([function(r,e,o){"use strict";var n=o(1),t=o(5);_rollbarConfig=_rollbarConfig||{},_rollbarConfig.rollbarJsUrl=_rollbarConfig.rollbarJsUrl||"https://cdn.rollbar.com/rollbarjs/refs/tags/v2.26.1/rollbar.min.js",_rollbarConfig.async=void 0===_rollbarConfig.async||_rollbarConfig.async;var a=n.setupShim(window,_rollbarConfig),l=t(_rollbarConfig);window.rollbar=n.Rollbar,a.loadFull(window,document,!_rollbarConfig.async,_rollbarConfig,l)},function(r,e,o){"use strict";var n=o(2),t=o(3);function a(r){return function(){try{return r.apply(this,arguments)}catch(r){try{console.error("[Rollbar]: Internal error",r)}catch(r){}}}}var l=0;function i(r,e){this.options=r,this._rollbarOldOnError=null;var o=l++;this.shimId=function(){return o},"undefined"!=typeof window&&window._rollbarShims&&(window._rollbarShims[o]={handler:e,messages:[]})}var s=o(4),d=function(r,e){return new i(r,e)},c=function(r){return new s(d,r)};function u(r){return a((function(){var e=this,o=Array.prototype.slice.call(arguments,0),n={shim:e,method:r,args:o,ts:new Date};window._rollbarShims[this.shimId()].messages.push(n)}))}i.prototype.loadFull=function(r,e,o,n,t){var l=!1,i=e.createElement("script"),s=e.getElementsByTagName("script")[0],d=s.parentNode;i.crossOrigin="",i.src=n.rollbarJsUrl,o||(i.async=!0),i.onload=i.onreadystatechange=a((function(){if(!(l||this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState)){i.onload=i.onreadystatechange=null;try{d.removeChild(i)}catch(r){}l=!0,function(){var e;if(void 0===r._rollbarDidLoad){e=new Error("rollbar.js did not load");for(var o,n,a,l,i=0;o=r._rollbarShims[i++];)for(o=o.messages||[];n=o.shift();)for(a=n.args||[],i=0;i<a.length;++i)if("function"==typeof(l=a[i])){l(e);break}}"function"==typeof t&&t(e)}()}})),d.insertBefore(i,s)},i.prototype.wrap=function(r,e,o){try{var n;if(n="function"==typeof e?e:function(){return e||{}},"function"!=typeof r)return r;if(r._isWrap)return r;if(!r._rollbar_wrapped&&(r._rollbar_wrapped=function(){o&&"function"==typeof o&&o.apply(this,arguments);try{return r.apply(this,arguments)}catch(o){var e=o;throw e&&("string"==typeof e&&(e=new String(e)),e._rollbarContext=n()||{},e._rollbarContext._wrappedSource=r.toString(),window._rollbarWrappedError=e),e}},r._rollbar_wrapped._isWrap=!0,r.hasOwnProperty))for(var t in r)r.hasOwnProperty(t)&&(r._rollbar_wrapped[t]=r[t]);return r._rollbar_wrapped}catch(e){return r}};for(var p="log,debug,info,warn,warning,error,critical,global,configure,handleUncaughtException,handleAnonymousErrors,handleUnhandledRejection,captureEvent,captureDomContentLoaded,captureLoad".split(","),f=0;f<p.length;++f)i.prototype[p[f]]=u(p[f]);r.exports={setupShim:function(r,e){if(r){var o=e.globalAlias||"Rollbar";if("object"==typeof r[o])return r[o];r._rollbarShims={},r._rollbarWrappedError=null;var l=new c(e);return a((function(){e.captureUncaught&&(l._rollbarOldOnError=r.onerror,n.captureUncaughtExceptions(r,l,!0),e.wrapGlobalEventHandlers&&t(r,l,!0)),e.captureUnhandledRejections&&n.captureUnhandledRejections(r,l,!0);var a=e.autoInstrument;return!1!==e.enabled&&(void 0===a||!0===a||function(r){return!("object"!=typeof r||void 0!==r.page&&!r.page)}(a))&&r.addEventListener&&(r.addEventListener("load",l.captureLoad.bind(l)),r.addEventListener("DOMContentLoaded",l.captureDomContentLoaded.bind(l))),r[o]=l,l}))()}},Rollbar:c}},function(r,e,o){"use strict";function n(r,e,o,n){r._rollbarWrappedError&&(n[4]||(n[4]=r._rollbarWrappedError),n[5]||(n[5]=r._rollbarWrappedError._rollbarContext),r._rollbarWrappedError=null);var t=e.handleUncaughtException.apply(e,n);o&&o.apply(r,n),"anonymous"===t&&(e.anonymousErrorsPending+=1)}r.exports={captureUncaughtExceptions:function(r,e,o){if(r){var t;if("function"==typeof e._rollbarOldOnError)t=e._rollbarOldOnError;else if(r.onerror){for(t=r.onerror;t._rollbarOldOnError;)t=t._rollbarOldOnError;e._rollbarOldOnError=t}e.handleAnonymousErrors();var a=function(){var o=Array.prototype.slice.call(arguments,0);n(r,e,t,o)};o&&(a._rollbarOldOnError=t),r.onerror=a}},captureUnhandledRejections:function(r,e,o){if(r){"function"==typeof r._rollbarURH&&r._rollbarURH.belongsToShim&&r.removeEventListener("unhandledrejection",r._rollbarURH);var n=function(r){var o,n,t;try{o=r.reason}catch(r){o=void 0}try{n=r.promise}catch(r){n="[unhandledrejection] error getting `promise` from event"}try{t=r.detail,!o&&t&&(o=t.reason,n=t.promise)}catch(r){}o||(o="[unhandledrejection] error getting `reason` from event"),e&&e.handleUnhandledRejection&&e.handleUnhandledRejection(o,n)};n.belongsToShim=o,r._rollbarURH=n,r.addEventListener("unhandledrejection",n)}}}},function(r,e,o){"use strict";function n(r,e,o){if(e.hasOwnProperty&&e.hasOwnProperty("addEventListener")){for(var n=e.addEventListener;n._rollbarOldAdd&&n.belongsToShim;)n=n._rollbarOldAdd;var t=function(e,o,t){n.call(this,e,r.wrap(o),t)};t._rollbarOldAdd=n,t.belongsToShim=o,e.addEventListener=t;for(var a=e.removeEventListener;a._rollbarOldRemove&&a.belongsToShim;)a=a._rollbarOldRemove;var l=function(r,e,o){a.call(this,r,e&&e._rollbar_wrapped||e,o)};l._rollbarOldRemove=a,l.belongsToShim=o,e.removeEventListener=l}}r.exports=function(r,e,o){if(r){var t,a,l="EventTarget,Window,Node,ApplicationCache,AudioTrackList,ChannelMergerNode,CryptoOperation,EventSource,FileReader,HTMLUnknownElement,IDBDatabase,IDBRequest,IDBTransaction,KeyOperation,MediaController,MessagePort,ModalWindow,Notification,SVGElementInstance,Screen,TextTrack,TextTrackCue,TextTrackList,WebSocket,WebSocketWorker,Worker,XMLHttpRequest,XMLHttpRequestEventTarget,XMLHttpRequestUpload".split(",");for(t=0;t<l.length;++t)r[a=l[t]]&&r[a].prototype&&n(e,r[a].prototype,o)}}},function(r,e,o){"use strict";function n(r,e){this.impl=r(e,this),this.options=e,function(r){for(var e=function(r){return function(){var e=Array.prototype.slice.call(arguments,0);if(this.impl[r])return this.impl[r].apply(this.impl,e)}},o="log,debug,info,warn,warning,error,critical,global,configure,handleUncaughtException,handleAnonymousErrors,handleUnhandledRejection,_createItem,wrap,loadFull,shimId,captureEvent,captureDomContentLoaded,captureLoad".split(","),n=0;n<o.length;n++)r[o[n]]=e(o[n])}(n.prototype)}n.prototype._swapAndProcessMessages=function(r,e){var o,n,t;for(this.impl=r(this.options);o=e.shift();)n=o.method,t=o.args,this[n]&&"function"==typeof this[n]&&("captureDomContentLoaded"===n||"captureLoad"===n?this[n].apply(this,[t[0],o.ts]):this[n].apply(this,t));return this},r.exports=n},function(r,e,o){"use strict";r.exports=function(r){return function(e){if(!e&&!window._rollbarInitialized){for(var o,n,t=(r=r||{}).globalAlias||"Rollbar",a=window.rollbar,l=function(r){return new a(r)},i=0;o=window._rollbarShims[i++];)n||(n=o.handler),o.handler._swapAndProcessMessages(l,o.messages);window[t]=n,window._rollbarInitialized=!0}}}}]);
                // End Rollbar Snippet
            })();
        }
    </script>
<script>

언어 확인 가능
디테일 페이지로 가면 주소 뒤에 추가로 /section/project-story
https://gamefound.com/en/projects/oomm-games/stonesaga-second-printing#/section/project-story

<link href="https://gamefound.com/en/projects/oomm-games/stonesaga-second-printing" rel="canonical">
<link href="https://gamefound.com/it/projects/oomm-games/stonesaga-second-printing" hreflang="it" rel="alternate">
<link href="https://gamefound.com/fr/projects/oomm-games/stonesaga-second-printing" hreflang="fr" rel="alternate">
<link href="https://gamefound.com/de/projects/oomm-games/stonesaga-second-printing" hreflang="de" rel="alternate">
<link href="https://gamefound.com/pl/projects/oomm-games/stonesaga-second-printing" hreflang="pl" rel="alternate">
<link href="https://gamefound.com/es/projects/oomm-games/stonesaga-second-printing" hreflang="es" rel="alternate">
<link href="https://gamefound.com/cs/projects/oomm-games/stonesaga-second-printing" hreflang="cs" rel="alternate">
<link href="https://gamefound.com/pt/projects/oomm-games/stonesaga-second-printing" hreflang="pt" rel="alternate">
<link href="https://gamefound.com/zh/projects/oomm-games/stonesaga-second-printing" hreflang="zh" rel="alternate">

In [15]:
import requests
from bs4 import BeautifulSoup

url = 'https://gamefound.com/api/products/getProductStockLimits'

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, 'html.parser')

print(response.status_code)

405

In [13]:
soup

<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, viewport-fit=cover, initial-scale=1 minimum-scale=1 maximum-scale=1" name="viewport"/>
<link crossorigin="" href="https://fonts.googleapis.com/" rel="preconnect"/>
<link href="https://fonts.googleapis.com/" rel="dns-prefetch"/>
<link crossorigin="" href="https://cdn.static.gamefound.com/content/" rel="preconnect"/>
<link href="https://cdn.static.gamefound.com/content/" rel="dns-prefetch"/>
<link crossorigin="" href="https://imgcdn.gamefound.com/" rel="preconnect"/>
<link href="https://imgcdn.gamefound.com/" rel="dns-prefetch"/>
<link crossorigin="" href="https://vcdn.gamefound.com/" rel="preconnect"/>
<link href="https://vcdn.gamefound.com/" rel="dns-prefetch"/>
<link href="https://fonts.googleapis.com/css?family=Roboto+Slab:700|Nunito+Sans:300,400,700,800" rel="stylesheet"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/lib/fontawesome-6.4.2/css/fontawesome-bundle.css" rel="stylesheet">
<meta content="no" name="msapplication-tap-highlight"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png">
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png">
<link href="/manifest.json" rel="manifest">
<link color="#5bbad5" href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/safari-pinned-tab.svg" rel="mask-icon">
<link href="/favicon.ico?v=1_szjInOnLLEcnJ4HqWv-ZjF7uilrJk0JZ8_5dgBaNM" rel="shortcut icon">
<meta content="#00aba9" name="msapplication-TileColor">
<meta content="#ffffff" name="theme-color">
<title>Stonesaga Second Printing by Open Owl Studios - Gamefound</title>
<meta content="Build a civilization across epochs in a cooperative survival crafting saga set in a persistent world shaped by your choices." name="description">
<meta name="keywords">
<meta content="en" http-equiv="Content-Language"/>
<link href="https://gamefound.com/en/projects/oomm-games/stonesaga-second-printing" rel="canonical">
<link href="https://gamefound.com/it/projects/oomm-games/stonesaga-second-printing" hreflang="it" rel="alternate">
<link href="https://gamefound.com/fr/projects/oomm-games/stonesaga-second-printing" hreflang="fr" rel="alternate">
<link href="https://gamefound.com/de/projects/oomm-games/stonesaga-second-printing" hreflang="de" rel="alternate">
<link href="https://gamefound.com/pl/projects/oomm-games/stonesaga-second-printing" hreflang="pl" rel="alternate">
<link href="https://gamefound.com/es/projects/oomm-games/stonesaga-second-printing" hreflang="es" rel="alternate">
<link href="https://gamefound.com/cs/projects/oomm-games/stonesaga-second-printing" hreflang="cs" rel="alternate">
<link href="https://gamefound.com/pt/projects/oomm-games/stonesaga-second-printing" hreflang="pt" rel="alternate">
<link href="https://gamefound.com/zh/projects/oomm-games/stonesaga-second-printing" hreflang="zh" rel="alternate">
<meta content="website" property="og:type"/>
<meta content="https://gamefound.com/en/projects/oomm-games/stonesaga-second-printing" property="og:url"/>
<meta content="Stonesaga Second Printing by Open Owl Studios - Gamefound" property="og:title"/>
<meta content="Build a civilization across epochs in a cooperative survival crafting saga set in a persistent world shaped by your choices." property="og:description"/>
<meta content="https://imgcdn.gamefound.com/og-image-fb/projects/9678/96d0a055-53fe-47ff-8973-cc6d1e239eca.png" property="og:image"/>
<meta content="1200" property="og:image:width"/>
<meta content="630" property="og:image:height"/>
<meta content="https://imgcdn.gamefound.com/og-image-square/projects/9678/0e9a20f1-7e79-4057-9f51-2d957a571d56.png" property="og:image"/>
<meta content="700" property="og:image:width"/>
<meta content="700" property="og:image:height"/>
<meta content="https://imgcdn.gamefound.com/og-image-fb/projects/9678/96d0a055-53fe-47ff-8973-cc6d1e239eca.png" name="twitter:image"/>
<meta content="summary_large_image" name="twitter:card">
<meta content="@Gamefound" name="twitter:site"/>
<meta content="Stonesaga Second Printing by Open Owl Studios - Gamefound" name="twitter:title"/>
<meta content="Build a civilization across epochs in a cooperative survival crafting saga set in a persistent world shaped by your choices." name="twitter:description"/>
<meta content="https://gamefound.com/en/projects/oomm-games/stonesaga-second-printing" name="twitter:url"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/styles/main-bundle.css" rel="stylesheet">
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/icons/main-icons-bundle.css" rel="stylesheet">
<script>
        (function (){
            const localStorageValue = JSON.parse(localStorage.getItem('store.webTheme'));
            if (localStorageValue && localStorageValue.theme) {
                document.documentElement.setAttribute('data-theme', localStorageValue.theme);
            }
            else {
                if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
                    document.documentElement.setAttribute('data-theme', 'dark');
                }
                else {
                    document.documentElement.setAttribute('data-theme', 'bright');
                }
            }
        })();
    </script>
<script>
    function pushNotificationHandler(event) {
        if (event && event.detail) {
            window.location.href = event.detail.actionUrl;
        }
    }

    window.addEventListener('push-notification', pushNotificationHandler);
    window.addEventListener('push-notification-tapped', pushNotificationHandler);
</script>
<script>
        if (window.Intl && window.location.href.indexOf('http') >= 0) {
            (function () {
                var ignoredErrors = [];
                var _rollbarConfig = {
                    accessToken: "9e559d4b594a4e25a4e5918f8f72ca3d",
                    captureUncaught: false,
                    captureUnhandledRejections: false,
                    payload: {
                        custom: {"analyticsSessionTrackingID":"08debf6c2e7e4ba7-653b6b93-f097-42ae-bbec-205554dcb281","browserSessionTrackingID":"eb534f78-075e-4334-8310-9c50b3bbd3da","deviceTrackingID":"3a28a868-e4e1-433e-9e3f-64206ad82701","facebookBrowserID":null,"facebookClickID":null,"requestTrackingID":"4005904a-0002-fe00-b63f-84710c7967bb","userTrackingID":"8f85997e-7459-482b-89dd-761a1bdbaff2"},
                        environment: "Production",
                        person: null,
                        client: {
                            javascript: {
                                code_version: "https://cdn.static.gamefound.com/content/20260525.3-13/scripts/main.js",
                                guess_uncaught_frames: true,
                                source_map_enabled: true
                            },
                        }
                    },
                    ignoredMessages: ["Network Error", "Request failed with status code", "AxiosError"],
                    checkIgnore: function (isUncaught, args, payload) {
                        // Ignore main lib error after first occurence
                        if (payload && payload.body && payload.body.trace && payload.body.trace.exception) {
                            var message = payload.body.trace.exception.message;
                            if (ignoredErrors.includes(message)) {
                                return true;
                            }
                            if (typeof App === 'undefined') {
                                ignoredErrors.push(message);
                            }
                        }

                        // Attempt to exclude errors from external scripts
                        if (payload && payload.body && payload.body.trace
                            && payload.body.trace.frames && payload.body.trace.frames.length === 1 && payload.body.trace.frames[0].method == "[anonymous]"
                            && payload.body.trace.exception && payload.body.trace.exception.class == "(unknown)") {
                            return true;
                        }

                        return false;
                    },
                    transform: function(payload) {
                        // Extract area tag from error context if present
                        if (payload && payload.data && payload.data.custom) {
                            var error = arguments[0];
                            if (error && error._rollbarContext && error._rollbarContext.area) {
                                payload.data.custom.area = error._rollbarContext.area;
                            }
                        }
                    }
                };

                // Rollbar Snippet
                !function(r){var e={};function o(n){if(e[n])return e[n].exports;var t=e[n]={i:n,l:!1,exports:{}};return r[n].call(t.exports,t,t.exports,o),t.l=!0,t.exports}o.m=r,o.c=e,o.d=function(r,e,n){o.o(r,e)||Object.defineProperty(r,e,{enumerable:!0,get:n})},o.r=function(r){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(r,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(r,"__esModule",{value:!0})},o.t=function(r,e){if(1&e&&(r=o(r)),8&e)return r;if(4&e&&"object"==typeof r&&r&&r.__esModule)return r;var n=Object.create(null);if(o.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:r}),2&e&&"string"!=typeof r)for(var t in r)o.d(n,t,function(e){return r[e]}.bind(null,t));return n},o.n=function(r){var e=r&&r.__esModule?function(){return r.default}:function(){return r};return o.d(e,"a",e),e},o.o=function(r,e){return Object.prototype.hasOwnProperty.call(r,e)},o.p="",o(o.s=0)}([function(r,e,o){"use strict";var n=o(1),t=o(5);_rollbarConfig=_rollbarConfig||{},_rollbarConfig.rollbarJsUrl=_rollbarConfig.rollbarJsUrl||"https://cdn.rollbar.com/rollbarjs/refs/tags/v2.26.1/rollbar.min.js",_rollbarConfig.async=void 0===_rollbarConfig.async||_rollbarConfig.async;var a=n.setupShim(window,_rollbarConfig),l=t(_rollbarConfig);window.rollbar=n.Rollbar,a.loadFull(window,document,!_rollbarConfig.async,_rollbarConfig,l)},function(r,e,o){"use strict";var n=o(2),t=o(3);function a(r){return function(){try{return r.apply(this,arguments)}catch(r){try{console.error("[Rollbar]: Internal error",r)}catch(r){}}}}var l=0;function i(r,e){this.options=r,this._rollbarOldOnError=null;var o=l++;this.shimId=function(){return o},"undefined"!=typeof window&&window._rollbarShims&&(window._rollbarShims[o]={handler:e,messages:[]})}var s=o(4),d=function(r,e){return new i(r,e)},c=function(r){return new s(d,r)};function u(r){return a((function(){var e=this,o=Array.prototype.slice.call(arguments,0),n={shim:e,method:r,args:o,ts:new Date};window._rollbarShims[this.shimId()].messages.push(n)}))}i.prototype.loadFull=function(r,e,o,n,t){var l=!1,i=e.createElement("script"),s=e.getElementsByTagName("script")[0],d=s.parentNode;i.crossOrigin="",i.src=n.rollbarJsUrl,o||(i.async=!0),i.onload=i.onreadystatechange=a((function(){if(!(l||this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState)){i.onload=i.onreadystatechange=null;try{d.removeChild(i)}catch(r){}l=!0,function(){var e;if(void 0===r._rollbarDidLoad){e=new Error("rollbar.js did not load");for(var o,n,a,l,i=0;o=r._rollbarShims[i++];)for(o=o.messages||[];n=o.shift();)for(a=n.args||[],i=0;i<a.length;++i)if("function"==typeof(l=a[i])){l(e);break}}"function"==typeof t&&t(e)}()}})),d.insertBefore(i,s)},i.prototype.wrap=function(r,e,o){try{var n;if(n="function"==typeof e?e:function(){return e||{}},"function"!=typeof r)return r;if(r._isWrap)return r;if(!r._rollbar_wrapped&&(r._rollbar_wrapped=function(){o&&"function"==typeof o&&o.apply(this,arguments);try{return r.apply(this,arguments)}catch(o){var e=o;throw e&&("string"==typeof e&&(e=new String(e)),e._rollbarContext=n()||{},e._rollbarContext._wrappedSource=r.toString(),window._rollbarWrappedError=e),e}},r._rollbar_wrapped._isWrap=!0,r.hasOwnProperty))for(var t in r)r.hasOwnProperty(t)&&(r._rollbar_wrapped[t]=r[t]);return r._rollbar_wrapped}catch(e){return r}};for(var p="log,debug,info,warn,warning,error,critical,global,configure,handleUncaughtException,handleAnonymousErrors,handleUnhandledRejection,captureEvent,captureDomContentLoaded,captureLoad".split(","),f=0;f<p.length;++f)i.prototype[p[f]]=u(p[f]);r.exports={setupShim:function(r,e){if(r){var o=e.globalAlias||"Rollbar";if("object"==typeof r[o])return r[o];r._rollbarShims={},r._rollbarWrappedError=null;var l=new c(e);return a((function(){e.captureUncaught&&(l._rollbarOldOnError=r.onerror,n.captureUncaughtExceptions(r,l,!0),e.wrapGlobalEventHandlers&&t(r,l,!0)),e.captureUnhandledRejections&&n.captureUnhandledRejections(r,l,!0);var a=e.autoInstrument;return!1!==e.enabled&&(void 0===a||!0===a||function(r){return!("object"!=typeof r||void 0!==r.page&&!r.page)}(a))&&r.addEventListener&&(r.addEventListener("load",l.captureLoad.bind(l)),r.addEventListener("DOMContentLoaded",l.captureDomContentLoaded.bind(l))),r[o]=l,l}))()}},Rollbar:c}},function(r,e,o){"use strict";function n(r,e,o,n){r._rollbarWrappedError&&(n[4]||(n[4]=r._rollbarWrappedError),n[5]||(n[5]=r._rollbarWrappedError._rollbarContext),r._rollbarWrappedError=null);var t=e.handleUncaughtException.apply(e,n);o&&o.apply(r,n),"anonymous"===t&&(e.anonymousErrorsPending+=1)}r.exports={captureUncaughtExceptions:function(r,e,o){if(r){var t;if("function"==typeof e._rollbarOldOnError)t=e._rollbarOldOnError;else if(r.onerror){for(t=r.onerror;t._rollbarOldOnError;)t=t._rollbarOldOnError;e._rollbarOldOnError=t}e.handleAnonymousErrors();var a=function(){var o=Array.prototype.slice.call(arguments,0);n(r,e,t,o)};o&&(a._rollbarOldOnError=t),r.onerror=a}},captureUnhandledRejections:function(r,e,o){if(r){"function"==typeof r._rollbarURH&&r._rollbarURH.belongsToShim&&r.removeEventListener("unhandledrejection",r._rollbarURH);var n=function(r){var o,n,t;try{o=r.reason}catch(r){o=void 0}try{n=r.promise}catch(r){n="[unhandledrejection] error getting `promise` from event"}try{t=r.detail,!o&&t&&(o=t.reason,n=t.promise)}catch(r){}o||(o="[unhandledrejection] error getting `reason` from event"),e&&e.handleUnhandledRejection&&e.handleUnhandledRejection(o,n)};n.belongsToShim=o,r._rollbarURH=n,r.addEventListener("unhandledrejection",n)}}}},function(r,e,o){"use strict";function n(r,e,o){if(e.hasOwnProperty&&e.hasOwnProperty("addEventListener")){for(var n=e.addEventListener;n._rollbarOldAdd&&n.belongsToShim;)n=n._rollbarOldAdd;var t=function(e,o,t){n.call(this,e,r.wrap(o),t)};t._rollbarOldAdd=n,t.belongsToShim=o,e.addEventListener=t;for(var a=e.removeEventListener;a._rollbarOldRemove&&a.belongsToShim;)a=a._rollbarOldRemove;var l=function(r,e,o){a.call(this,r,e&&e._rollbar_wrapped||e,o)};l._rollbarOldRemove=a,l.belongsToShim=o,e.removeEventListener=l}}r.exports=function(r,e,o){if(r){var t,a,l="EventTarget,Window,Node,ApplicationCache,AudioTrackList,ChannelMergerNode,CryptoOperation,EventSource,FileReader,HTMLUnknownElement,IDBDatabase,IDBRequest,IDBTransaction,KeyOperation,MediaController,MessagePort,ModalWindow,Notification,SVGElementInstance,Screen,TextTrack,TextTrackCue,TextTrackList,WebSocket,WebSocketWorker,Worker,XMLHttpRequest,XMLHttpRequestEventTarget,XMLHttpRequestUpload".split(",");for(t=0;t<l.length;++t)r[a=l[t]]&&r[a].prototype&&n(e,r[a].prototype,o)}}},function(r,e,o){"use strict";function n(r,e){this.impl=r(e,this),this.options=e,function(r){for(var e=function(r){return function(){var e=Array.prototype.slice.call(arguments,0);if(this.impl[r])return this.impl[r].apply(this.impl,e)}},o="log,debug,info,warn,warning,error,critical,global,configure,handleUncaughtException,handleAnonymousErrors,handleUnhandledRejection,_createItem,wrap,loadFull,shimId,captureEvent,captureDomContentLoaded,captureLoad".split(","),n=0;n<o.length;n++)r[o[n]]=e(o[n])}(n.prototype)}n.prototype._swapAndProcessMessages=function(r,e){var o,n,t;for(this.impl=r(this.options);o=e.shift();)n=o.method,t=o.args,this[n]&&"function"==typeof this[n]&&("captureDomContentLoaded"===n||"captureLoad"===n?this[n].apply(this,[t[0],o.ts]):this[n].apply(this,t));return this},r.exports=n},function(r,e,o){"use strict";r.exports=function(r){return function(e){if(!e&&!window._rollbarInitialized){for(var o,n,t=(r=r||{}).globalAlias||"Rollbar",a=window.rollbar,l=function(r){return new a(r)},i=0;o=window._rollbarShims[i++];)n||(n=o.handler),o.handler._swapAndProcessMessages(l,o.messages);window[t]=n,window._rollbarInitialized=!0}}}}]);
                // End Rollbar Snippet
            })();
        }
    </script>
<script>

In [27]:
import requests
from bs4 import BeautifulSoup
import re

url = "https://gamefound.com/en/projects/oomm-games/stonesaga-second-printing"

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'
}


response = requests.get(url, headers=headers)
#response.text

#정규표현식으로 검색을 해야는데...;;
# re.search(r'"projectTags"\s*:\s*(\[.+?\])\s*,\s*"projectProperties"', response.text)

if re.search(r'"projectTags"\s*:\s*(\[.+?\])\s*,\s*"projectProperties"', response.text):
    # 정규식으로 찾은 문자열(JSON 형태)
    tags_json_string = re.search(r'"projectTags"\s*:\s*(\[.+?\])\s*,\s*"projectProperties"', response.text).group(1)
    
    try:
        # 문자열을 파이썬 리스트/딕셔너리로 변환
        tags_data = json.loads(tags_json_string)
        
        # 각 태그 딕셔너리 안에서 'name' 키의 값만 추출
        extracted_tags = [tag['name'] for tag in tags_data if 'name' in tag]
        
    except json.JSONDecodeError as e:
        print(f"JSON 데이터를 변환하는 중 에러가 발생했습니다: {e}")
else:
    print("스크립트 내에서 태그 정보를 찾을 수 없습니다.")

# 결과 출력
print("수집된 태그:")
print(extracted_tags)

수집된 태그:
['fantasy', 'mythology', 'cooperative', 'campaign', 'civilization']

In [18]:
soup

<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, viewport-fit=cover, initial-scale=1 minimum-scale=1 maximum-scale=1" name="viewport"/>
<link crossorigin="" href="https://fonts.googleapis.com/" rel="preconnect"/>
<link href="https://fonts.googleapis.com/" rel="dns-prefetch"/>
<link crossorigin="" href="https://cdn.static.gamefound.com/content/" rel="preconnect"/>
<link href="https://cdn.static.gamefound.com/content/" rel="dns-prefetch"/>
<link crossorigin="" href="https://imgcdn.gamefound.com/" rel="preconnect"/>
<link href="https://imgcdn.gamefound.com/" rel="dns-prefetch"/>
<link crossorigin="" href="https://vcdn.gamefound.com/" rel="preconnect"/>
<link href="https://vcdn.gamefound.com/" rel="dns-prefetch"/>
<link href="https://fonts.googleapis.com/css?family=Roboto+Slab:700|Nunito+Sans:300,400,700,800" rel="stylesheet"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/lib/fontawesome-6.4.2/css/fontawesome-bundle.css" rel="stylesheet">
<meta content="no" name="msapplication-tap-highlight"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png">
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png">
<link href="/manifest.json" rel="manifest">
<link color="#5bbad5" href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/safari-pinned-tab.svg" rel="mask-icon">
<link href="/favicon.ico?v=1_szjInOnLLEcnJ4HqWv-ZjF7uilrJk0JZ8_5dgBaNM" rel="shortcut icon">
<meta content="#00aba9" name="msapplication-TileColor">
<meta content="#ffffff" name="theme-color">
<title>Stonesaga Second Printing by Open Owl Studios - Gamefound</title>
<meta content="Build a civilization across epochs in a cooperative survival crafting saga set in a persistent world shaped by your choices." name="description">
<meta name="keywords">
<meta content="en" http-equiv="Content-Language"/>
<link href="https://gamefound.com/en/projects/oomm-games/stonesaga-second-printing" rel="canonical">
<link href="https://gamefound.com/it/projects/oomm-games/stonesaga-second-printing" hreflang="it" rel="alternate">
<link href="https://gamefound.com/fr/projects/oomm-games/stonesaga-second-printing" hreflang="fr" rel="alternate">
<link href="https://gamefound.com/de/projects/oomm-games/stonesaga-second-printing" hreflang="de" rel="alternate">
<link href="https://gamefound.com/pl/projects/oomm-games/stonesaga-second-printing" hreflang="pl" rel="alternate">
<link href="https://gamefound.com/es/projects/oomm-games/stonesaga-second-printing" hreflang="es" rel="alternate">
<link href="https://gamefound.com/cs/projects/oomm-games/stonesaga-second-printing" hreflang="cs" rel="alternate">
<link href="https://gamefound.com/pt/projects/oomm-games/stonesaga-second-printing" hreflang="pt" rel="alternate">
<link href="https://gamefound.com/zh/projects/oomm-games/stonesaga-second-printing" hreflang="zh" rel="alternate">
<meta content="website" property="og:type"/>
<meta content="https://gamefound.com/en/projects/oomm-games/stonesaga-second-printing" property="og:url"/>
<meta content="Stonesaga Second Printing by Open Owl Studios - Gamefound" property="og:title"/>
<meta content="Build a civilization across epochs in a cooperative survival crafting saga set in a persistent world shaped by your choices." property="og:description"/>
<meta content="https://imgcdn.gamefound.com/og-image-fb/projects/9678/96d0a055-53fe-47ff-8973-cc6d1e239eca.png" property="og:image"/>
<meta content="1200" property="og:image:width"/>
<meta content="630" property="og:image:height"/>
<meta content="https://imgcdn.gamefound.com/og-image-square/projects/9678/0e9a20f1-7e79-4057-9f51-2d957a571d56.png" property="og:image"/>
<meta content="700" property="og:image:width"/>
<meta content="700" property="og:image:height"/>
<meta content="https://imgcdn.gamefound.com/og-image-fb/projects/9678/96d0a055-53fe-47ff-8973-cc6d1e239eca.png" name="twitter:image"/>
<meta content="summary_large_image" name="twitter:card">
<meta content="@Gamefound" name="twitter:site"/>
<meta content="Stonesaga Second Printing by Open Owl Studios - Gamefound" name="twitter:title"/>
<meta content="Build a civilization across epochs in a cooperative survival crafting saga set in a persistent world shaped by your choices." name="twitter:description"/>
<meta content="https://gamefound.com/en/projects/oomm-games/stonesaga-second-printing" name="twitter:url"/>
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/styles/main-bundle.css" rel="stylesheet">
<link href="https://cdn.static.gamefound.com/content/20260525.3-13/icons/main-icons-bundle.css" rel="stylesheet">
<script>
        (function (){
            const localStorageValue = JSON.parse(localStorage.getItem('store.webTheme'));
            if (localStorageValue && localStorageValue.theme) {
                document.documentElement.setAttribute('data-theme', localStorageValue.theme);
            }
            else {
                if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
                    document.documentElement.setAttribute('data-theme', 'dark');
                }
                else {
                    document.documentElement.setAttribute('data-theme', 'bright');
                }
            }
        })();
    </script>
<script>
    function pushNotificationHandler(event) {
        if (event && event.detail) {
            window.location.href = event.detail.actionUrl;
        }
    }

    window.addEventListener('push-notification', pushNotificationHandler);
    window.addEventListener('push-notification-tapped', pushNotificationHandler);
</script>
<script>
        if (window.Intl && window.location.href.indexOf('http') >= 0) {
            (function () {
                var ignoredErrors = [];
                var _rollbarConfig = {
                    accessToken: "9e559d4b594a4e25a4e5918f8f72ca3d",
                    captureUncaught: false,
                    captureUnhandledRejections: false,
                    payload: {
                        custom: {"analyticsSessionTrackingID":"08debf6e005e1a4d-4f63c322-fd1d-4f37-963d-b9492bb1b803","browserSessionTrackingID":"5c6bc1f1-4301-4ef1-acb7-78c017a8a354","deviceTrackingID":"b3982669-b13e-4ada-a512-6e1fc49a00f7","facebookBrowserID":null,"facebookClickID":null,"requestTrackingID":"40078780-0000-f300-b63f-84710c7967bb","userTrackingID":"b17d1830-febf-4f82-83f1-a4f1cbf39fd2"},
                        environment: "Production",
                        person: null,
                        client: {
                            javascript: {
                                code_version: "https://cdn.static.gamefound.com/content/20260525.3-13/scripts/main.js",
                                guess_uncaught_frames: true,
                                source_map_enabled: true
                            },
                        }
                    },
                    ignoredMessages: ["Network Error", "Request failed with status code", "AxiosError"],
                    checkIgnore: function (isUncaught, args, payload) {
                        // Ignore main lib error after first occurence
                        if (payload && payload.body && payload.body.trace && payload.body.trace.exception) {
                            var message = payload.body.trace.exception.message;
                            if (ignoredErrors.includes(message)) {
                                return true;
                            }
                            if (typeof App === 'undefined') {
                                ignoredErrors.push(message);
                            }
                        }

                        // Attempt to exclude errors from external scripts
                        if (payload && payload.body && payload.body.trace
                            && payload.body.trace.frames && payload.body.trace.frames.length === 1 && payload.body.trace.frames[0].method == "[anonymous]"
                            && payload.body.trace.exception && payload.body.trace.exception.class == "(unknown)") {
                            return true;
                        }

                        return false;
                    },
                    transform: function(payload) {
                        // Extract area tag from error context if present
                        if (payload && payload.data && payload.data.custom) {
                            var error = arguments[0];
                            if (error && error._rollbarContext && error._rollbarContext.area) {
                                payload.data.custom.area = error._rollbarContext.area;
                            }
                        }
                    }
                };

                // Rollbar Snippet
                !function(r){var e={};function o(n){if(e[n])return e[n].exports;var t=e[n]={i:n,l:!1,exports:{}};return r[n].call(t.exports,t,t.exports,o),t.l=!0,t.exports}o.m=r,o.c=e,o.d=function(r,e,n){o.o(r,e)||Object.defineProperty(r,e,{enumerable:!0,get:n})},o.r=function(r){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(r,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(r,"__esModule",{value:!0})},o.t=function(r,e){if(1&e&&(r=o(r)),8&e)return r;if(4&e&&"object"==typeof r&&r&&r.__esModule)return r;var n=Object.create(null);if(o.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:r}),2&e&&"string"!=typeof r)for(var t in r)o.d(n,t,function(e){return r[e]}.bind(null,t));return n},o.n=function(r){var e=r&&r.__esModule?function(){return r.default}:function(){return r};return o.d(e,"a",e),e},o.o=function(r,e){return Object.prototype.hasOwnProperty.call(r,e)},o.p="",o(o.s=0)}([function(r,e,o){"use strict";var n=o(1),t=o(5);_rollbarConfig=_rollbarConfig||{},_rollbarConfig.rollbarJsUrl=_rollbarConfig.rollbarJsUrl||"https://cdn.rollbar.com/rollbarjs/refs/tags/v2.26.1/rollbar.min.js",_rollbarConfig.async=void 0===_rollbarConfig.async||_rollbarConfig.async;var a=n.setupShim(window,_rollbarConfig),l=t(_rollbarConfig);window.rollbar=n.Rollbar,a.loadFull(window,document,!_rollbarConfig.async,_rollbarConfig,l)},function(r,e,o){"use strict";var n=o(2),t=o(3);function a(r){return function(){try{return r.apply(this,arguments)}catch(r){try{console.error("[Rollbar]: Internal error",r)}catch(r){}}}}var l=0;function i(r,e){this.options=r,this._rollbarOldOnError=null;var o=l++;this.shimId=function(){return o},"undefined"!=typeof window&&window._rollbarShims&&(window._rollbarShims[o]={handler:e,messages:[]})}var s=o(4),d=function(r,e){return new i(r,e)},c=function(r){return new s(d,r)};function u(r){return a((function(){var e=this,o=Array.prototype.slice.call(arguments,0),n={shim:e,method:r,args:o,ts:new Date};window._rollbarShims[this.shimId()].messages.push(n)}))}i.prototype.loadFull=function(r,e,o,n,t){var l=!1,i=e.createElement("script"),s=e.getElementsByTagName("script")[0],d=s.parentNode;i.crossOrigin="",i.src=n.rollbarJsUrl,o||(i.async=!0),i.onload=i.onreadystatechange=a((function(){if(!(l||this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState)){i.onload=i.onreadystatechange=null;try{d.removeChild(i)}catch(r){}l=!0,function(){var e;if(void 0===r._rollbarDidLoad){e=new Error("rollbar.js did not load");for(var o,n,a,l,i=0;o=r._rollbarShims[i++];)for(o=o.messages||[];n=o.shift();)for(a=n.args||[],i=0;i<a.length;++i)if("function"==typeof(l=a[i])){l(e);break}}"function"==typeof t&&t(e)}()}})),d.insertBefore(i,s)},i.prototype.wrap=function(r,e,o){try{var n;if(n="function"==typeof e?e:function(){return e||{}},"function"!=typeof r)return r;if(r._isWrap)return r;if(!r._rollbar_wrapped&&(r._rollbar_wrapped=function(){o&&"function"==typeof o&&o.apply(this,arguments);try{return r.apply(this,arguments)}catch(o){var e=o;throw e&&("string"==typeof e&&(e=new String(e)),e._rollbarContext=n()||{},e._rollbarContext._wrappedSource=r.toString(),window._rollbarWrappedError=e),e}},r._rollbar_wrapped._isWrap=!0,r.hasOwnProperty))for(var t in r)r.hasOwnProperty(t)&&(r._rollbar_wrapped[t]=r[t]);return r._rollbar_wrapped}catch(e){return r}};for(var p="log,debug,info,warn,warning,error,critical,global,configure,handleUncaughtException,handleAnonymousErrors,handleUnhandledRejection,captureEvent,captureDomContentLoaded,captureLoad".split(","),f=0;f<p.length;++f)i.prototype[p[f]]=u(p[f]);r.exports={setupShim:function(r,e){if(r){var o=e.globalAlias||"Rollbar";if("object"==typeof r[o])return r[o];r._rollbarShims={},r._rollbarWrappedError=null;var l=new c(e);return a((function(){e.captureUncaught&&(l._rollbarOldOnError=r.onerror,n.captureUncaughtExceptions(r,l,!0),e.wrapGlobalEventHandlers&&t(r,l,!0)),e.captureUnhandledRejections&&n.captureUnhandledRejections(r,l,!0);var a=e.autoInstrument;return!1!==e.enabled&&(void 0===a||!0===a||function(r){return!("object"!=typeof r||void 0!==r.page&&!r.page)}(a))&&r.addEventListener&&(r.addEventListener("load",l.captureLoad.bind(l)),r.addEventListener("DOMContentLoaded",l.captureDomContentLoaded.bind(l))),r[o]=l,l}))()}},Rollbar:c}},function(r,e,o){"use strict";function n(r,e,o,n){r._rollbarWrappedError&&(n[4]||(n[4]=r._rollbarWrappedError),n[5]||(n[5]=r._rollbarWrappedError._rollbarContext),r._rollbarWrappedError=null);var t=e.handleUncaughtException.apply(e,n);o&&o.apply(r,n),"anonymous"===t&&(e.anonymousErrorsPending+=1)}r.exports={captureUncaughtExceptions:function(r,e,o){if(r){var t;if("function"==typeof e._rollbarOldOnError)t=e._rollbarOldOnError;else if(r.onerror){for(t=r.onerror;t._rollbarOldOnError;)t=t._rollbarOldOnError;e._rollbarOldOnError=t}e.handleAnonymousErrors();var a=function(){var o=Array.prototype.slice.call(arguments,0);n(r,e,t,o)};o&&(a._rollbarOldOnError=t),r.onerror=a}},captureUnhandledRejections:function(r,e,o){if(r){"function"==typeof r._rollbarURH&&r._rollbarURH.belongsToShim&&r.removeEventListener("unhandledrejection",r._rollbarURH);var n=function(r){var o,n,t;try{o=r.reason}catch(r){o=void 0}try{n=r.promise}catch(r){n="[unhandledrejection] error getting `promise` from event"}try{t=r.detail,!o&&t&&(o=t.reason,n=t.promise)}catch(r){}o||(o="[unhandledrejection] error getting `reason` from event"),e&&e.handleUnhandledRejection&&e.handleUnhandledRejection(o,n)};n.belongsToShim=o,r._rollbarURH=n,r.addEventListener("unhandledrejection",n)}}}},function(r,e,o){"use strict";function n(r,e,o){if(e.hasOwnProperty&&e.hasOwnProperty("addEventListener")){for(var n=e.addEventListener;n._rollbarOldAdd&&n.belongsToShim;)n=n._rollbarOldAdd;var t=function(e,o,t){n.call(this,e,r.wrap(o),t)};t._rollbarOldAdd=n,t.belongsToShim=o,e.addEventListener=t;for(var a=e.removeEventListener;a._rollbarOldRemove&&a.belongsToShim;)a=a._rollbarOldRemove;var l=function(r,e,o){a.call(this,r,e&&e._rollbar_wrapped||e,o)};l._rollbarOldRemove=a,l.belongsToShim=o,e.removeEventListener=l}}r.exports=function(r,e,o){if(r){var t,a,l="EventTarget,Window,Node,ApplicationCache,AudioTrackList,ChannelMergerNode,CryptoOperation,EventSource,FileReader,HTMLUnknownElement,IDBDatabase,IDBRequest,IDBTransaction,KeyOperation,MediaController,MessagePort,ModalWindow,Notification,SVGElementInstance,Screen,TextTrack,TextTrackCue,TextTrackList,WebSocket,WebSocketWorker,Worker,XMLHttpRequest,XMLHttpRequestEventTarget,XMLHttpRequestUpload".split(",");for(t=0;t<l.length;++t)r[a=l[t]]&&r[a].prototype&&n(e,r[a].prototype,o)}}},function(r,e,o){"use strict";function n(r,e){this.impl=r(e,this),this.options=e,function(r){for(var e=function(r){return function(){var e=Array.prototype.slice.call(arguments,0);if(this.impl[r])return this.impl[r].apply(this.impl,e)}},o="log,debug,info,warn,warning,error,critical,global,configure,handleUncaughtException,handleAnonymousErrors,handleUnhandledRejection,_createItem,wrap,loadFull,shimId,captureEvent,captureDomContentLoaded,captureLoad".split(","),n=0;n<o.length;n++)r[o[n]]=e(o[n])}(n.prototype)}n.prototype._swapAndProcessMessages=function(r,e){var o,n,t;for(this.impl=r(this.options);o=e.shift();)n=o.method,t=o.args,this[n]&&"function"==typeof this[n]&&("captureDomContentLoaded"===n||"captureLoad"===n?this[n].apply(this,[t[0],o.ts]):this[n].apply(this,t));return this},r.exports=n},function(r,e,o){"use strict";r.exports=function(r){return function(e){if(!e&&!window._rollbarInitialized){for(var o,n,t=(r=r||{}).globalAlias||"Rollbar",a=window.rollbar,l=function(r){return new a(r)},i=0;o=window._rollbarShims[i++];)n||(n=o.handler),o.handler._swapAndProcessMessages(l,o.messages);window[t]=n,window._rollbarInitialized=!0}}}}]);
                // End Rollbar Snippet
            })();
        }
    </script>
<script>

In [21]:
response.text

'\r\n<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n    \r\n<meta charset="utf-8">\r\n<meta http-equiv="X-UA-Compatible" content="IE=edge">\r\n<meta name="viewport" content="width=device-width, viewport-fit=cover, initial-scale=1 minimum-scale=1 maximum-scale=1">\r\n<link rel="preconnect" href="https://fonts.googleapis.com/" crossorigin>\r\n<link rel="dns-prefetch" href="https://fonts.googleapis.com/">\r\n\r\n    <link rel="preconnect" href="https://cdn.static.gamefound.com/content/" crossorigin>\r\n    <link rel="dns-prefetch" href="https://cdn.static.gamefound.com/content/">\r\n    <link rel="preconnect" href="https://imgcdn.gamefound.com/" crossorigin>\r\n    <link rel="dns-prefetch" href="https://imgcdn.gamefound.com/">\r\n    <link rel="preconnect" href="https://vcdn.gamefound.com/" crossorigin>\r\n    <link rel="dns-prefetch" href="https://vcdn.gamefound.com/">\r\n<link href="https://fonts.googleapis.com/css?family=Roboto&#x2B;Slab:700|Nunito&#x2B;Sans:300,400,700,800" rel="stylesheet">\r\n<link href="https://cdn.static.gamefound.com/content/20260525.3-13/lib/fontawesome-6.4.2/css/fontawesome-bundle.css" rel="stylesheet" />\r\n<meta name="msapplication-tap-highlight" content="no">\r\n<link rel="apple-touch-icon" sizes="57x57" href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-57x57.png">\r\n<link rel="apple-touch-icon" sizes="72x72" href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-72x72.png">\r\n<link rel="apple-touch-icon" sizes="60x60" href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-60x60.png">\r\n<link rel="apple-touch-icon" sizes="76x76" href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-76x76.png">\r\n<link rel="apple-touch-icon" sizes="114x114" href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-114x114.png">\r\n<link rel="apple-touch-icon" sizes="120x120" href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-120x120.png">\r\n<link rel="apple-touch-icon" sizes="144x144" href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-144x144.png">\r\n<link rel="apple-touch-icon" sizes="152x152" href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-152x152.png">\r\n<link rel="apple-touch-icon" sizes="180x180" href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/ios/apple-touch-icon-180x180.png">\r\n<link rel="icon" type="image/png" sizes="32x32" href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/favicon-32x32.png" />\r\n<link rel="icon" type="image/png" sizes="16x16" href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/favicon-16x16.png" />\r\n<link rel="manifest" href="/manifest.json"/>\r\n<link rel="mask-icon" href="https://cdn.static.gamefound.com/content/20260525.3-13/images/favicon/safari-pinned-tab.svg" color="#5bbad5" />\r\n<link rel="shortcut icon" href="/favicon.ico?v=1_szjInOnLLEcnJ4HqWv-ZjF7uilrJk0JZ8_5dgBaNM" /> \r\n<meta name="msapplication-TileColor" content="#00aba9" />\r\n<meta name="theme-color" content="#ffffff" />\r\n<title>Stonesaga Second Printing by Open Owl Studios - Gamefound</title>\r\n<meta name="description" content="Build a civilization across epochs in a cooperative survival crafting saga set in a persistent world shaped by your choices." />\r\n<meta name="keywords" />\r\n<meta http-equiv="Content-Language" content="en" />\r\n<link rel="canonical" href="https://gamefound.com/en/projects/oomm-games/stonesaga-second-printing" />\r\n<link rel="alternate" href="https://gamefound.com/it/projects/oomm-games/stonesaga-second-printing" hreflang="it" /> \r\n<link rel="alternate" href="https://gamefound.com/fr/projects/oomm-games/stonesaga-second-printing" hreflang="fr" /> \r\n<link rel="alternate" href="https://gamefound.com/de/projects/oomm-games/stonesaga-second-printing" hreflang="de" /> \r\n<link rel="alternate" href="https://gamefound.com/pl/projects/oomm-games/stonesaga-second-printing" hreflang="pl" /> \r\n<link rel="alternate" href="https://gamefound.com/es/projects/oomm-games/stonesaga-second-printing" hreflang="es" /> \r\n<link rel="alternate" href="https://gamefound.com/cs/projects/oomm-games/stonesaga-second-printing" hreflang="cs" /> \r\n<link rel="alternate" href="https://gamefound.com/pt/projects/oomm-games/stonesaga-second-printing" hreflang="pt" /> \r\n<link rel="alternate" href="https://gamefound.com/zh/projects/oomm-games/stonesaga-second-printing" hreflang="zh" /> \r\n<meta property="og:type" content="website" />\r\n<meta property="og:url" content="https://gamefound.com/en/projects/oomm-games/stonesaga-second-printing" />\r\n<meta property="og:title" content="Stonesaga Second Printing by Open Owl Studios - Gamefound" />\r\n<meta property="og:description" content="Build a civilization across epochs in a cooperative survival crafting saga set in a persistent world shaped by your choices." />\r\n<meta property="og:image" content="https://imgcdn.gamefound.com/og-image-fb/projects/9678/96d0a055-53fe-47ff-8973-cc6d1e239eca.png" />\r\n<meta property="og:image:width" content="1200" />\r\n<meta property="og:image:height" content="630" />\r\n<meta property="og:image" content="https://imgcdn.gamefound.com/og-image-square/projects/9678/0e9a20f1-7e79-4057-9f51-2d957a571d56.png" />\r\n<meta property="og:image:width" content="700" />\r\n<meta property="og:image:height" content="700" />\r\n<meta name="twitter:image" content="https://imgcdn.gamefound.com/og-image-fb/projects/9678/96d0a055-53fe-47ff-8973-cc6d1e239eca.png">\r\n<meta name="twitter:card" content="summary_large_image"/>\r\n<meta name="twitter:site" content="@Gamefound" />\r\n<meta name="twitter:title" content="Stonesaga Second Printing by Open Owl Studios - Gamefound"/>\r\n<meta name="twitter:description" content="Build a civilization across epochs in a cooperative survival crafting saga set in a persistent world shaped by your choices."/>\r\n<meta name="twitter:url" content="https://gamefound.com/en/projects/oomm-games/stonesaga-second-printing"/>\r\n\r\n<link href="https://cdn.static.gamefound.com/content/20260525.3-13/styles/main-bundle.css" rel="stylesheet" />\r\n<link href="https://cdn.static.gamefound.com/content/20260525.3-13/icons/main-icons-bundle.css" rel="stylesheet" />\r\n\r\n\r\n\r\n    \r\n\r\n    <script>\r\n        (function (){\r\n            const localStorageValue = JSON.parse(localStorage.getItem(\'store.webTheme\'));\r\n            if (localStorageValue && localStorageValue.theme) {\r\n                document.documentElement.setAttribute(\'data-theme\', localStorageValue.theme);\r\n            }\r\n            else {\r\n                if (window.matchMedia && window.matchMedia(\'(prefers-color-scheme: dark)\').matches) {\r\n                    document.documentElement.setAttribute(\'data-theme\', \'dark\');\r\n                }\r\n                else {\r\n                    document.documentElement.setAttribute(\'data-theme\', \'bright\');\r\n                }\r\n            }\r\n        })();\r\n    </script>\r\n\r\n<script>\r\n    function pushNotificationHandler(event) {\r\n        if (event && event.detail) {\r\n            window.location.href = event.detail.actionUrl;\r\n        }\r\n    }\r\n\r\n    window.addEventListener(\'push-notification\', pushNotificationHandler);\r\n    window.addEventListener(\'push-notification-tapped\', pushNotificationHandler);\r\n</script>\r\n\r\n    <script>\r\n        if (window.Intl && window.location.href.indexOf(\'http\') >= 0) {\r\n            (function () {\r\n                var ignoredErrors = [];\r\n                var _rollbarConfig = {\r\n                    accessToken: "9e559d4b594a4e25a4e5918f8f72ca3d",\r\n                    captureUncaught: false,\r\n                    captureUnhandledRejections: false,\r\n                    payload: {\r\n                        custom: {"analyticsSessionTrackingID":"08debf6e4b970cd1-41c602b3-3da1-4365-99dc-647f9e7257fb","browserSessionTrackingID":"eee602fb-1fc5-4eff-b81c-e0b6400fa102","deviceTrackingID":"41448a75-7f4d-44b2-a731-4ce8d7f51436","facebookBrowserID":null,"facebookClickID":null,"requestTrackingID":"4005d01d-0002-e900-b63f-84710c7967bb","userTrackingID":"0f49d020-cfa7-4b39-a580-65f62a59d4c9"},\r\n                        environment: "Production",\r\n                        person: null,\r\n                        client: {\r\n                            javascript: {\r\n                                code_version: "https://cdn.static.gamefound.com/content/20260525.3-13/scripts/main.js",\r\n                                guess_uncaught_frames: true,\r\n                                source_map_enabled: true\r\n                            },\r\n                        }\r\n                    },\r\n                    ignoredMessages: ["Network Error", "Request failed with status code", "AxiosError"],\r\n                    checkIgnore: function (isUncaught, args, payload) {\r\n                        // Ignore main lib error after first occurence\r\n                        if (payload && payload.body && payload.body.trace && payload.body.trace.exception) {\r\n                            var message = payload.body.trace.exception.message;\r\n                            if (ignoredErrors.includes(message)) {\r\n                                return true;\r\n                            }\r\n                            if (typeof App === \'undefined\') {\r\n                                ignoredErrors.push(message);\r\n                            }\r\n                        }\r\n\r\n                        // Attempt to exclude errors from external scripts\r\n                        if (payload && payload.body && payload.body.trace\r\n                            && payload.body.trace.frames && payload.body.trace.frames.length === 1 && payload.body.trace.frames[0].method == "[anonymous]"\r\n                            && payload.body.trace.exception && payload.body.trace.exception.class == "(unknown)") {\r\n                            return true;\r\n                        }\r\n\r\n                        return false;\r\n                    },\r\n                    transform: function(payload) {\r\n                        // Extract area tag from error context if present\r\n                        if (payload && payload.data && payload.data.custom) {\r\n                            var error = arguments[0];\r\n                            if (error && error._rollbarContext && error._rollbarContext.area) {\r\n                                payload.data.custom.area = error._rollbarContext.area;\r\n                            }\r\n                        }\r\n                    }\r\n                };\r\n\r\n                // Rollbar Snippet\r\n                !function(r){var e={};function o(n){if(e[n])return e[n].exports;var t=e[n]={i:n,l:!1,exports:{}};return r[n].call(t.exports,t,t.exports,o),t.l=!0,t.exports}o.m=r,o.c=e,o.d=function(r,e,n){o.o(r,e)||Object.defineProperty(r,e,{enumerable:!0,get:n})},o.r=function(r){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(r,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(r,"__esModule",{value:!0})},o.t=function(r,e){if(1&e&&(r=o(r)),8&e)return r;if(4&e&&"object"==typeof r&&r&&r.__esModule)return r;var n=Object.create(null);if(o.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:r}),2&e&&"string"!=typeof r)for(var t in r)o.d(n,t,function(e){return r[e]}.bind(null,t));return n},o.n=function(r){var e=r&&r.__esModule?function(){return r.default}:function(){return r};return o.d(e,"a",e),e},o.o=function(r,e){return Object.prototype.hasOwnProperty.call(r,e)},o.p="",o(o.s=0)}([function(r,e,o){"use strict";var n=o(1),t=o(5);_rollbarConfig=_rollbarConfig||{},_rollbarConfig.rollbarJsUrl=_rollbarConfig.rollbarJsUrl||"https://cdn.rollbar.com/rollbarjs/refs/tags/v2.26.1/rollbar.min.js",_rollbarConfig.async=void 0===_rollbarConfig.async||_rollbarConfig.async;var a=n.setupShim(window,_rollbarConfig),l=t(_rollbarConfig);window.rollbar=n.Rollbar,a.loadFull(window,document,!_rollbarConfig.async,_rollbarConfig,l)},function(r,e,o){"use strict";var n=o(2),t=o(3);function a(r){return function(){try{return r.apply(this,arguments)}catch(r){try{console.error("[Rollbar]: Internal error",r)}catch(r){}}}}var l=0;function i(r,e){this.options=r,this._rollbarOldOnError=null;var o=l++;this.shimId=function(){return o},"undefined"!=typeof window&&window._rollbarShims&&(window._rollbarShims[o]={handler:e,messages:[]})}var s=o(4),d=function(r,e){return new i(r,e)},c=function(r){return new s(d,r)};function u(r){return a((function(){var e=this,o=Array.prototype.slice.call(arguments,0),n={shim:e,method:r,args:o,ts:new Date};window._rollbarShims[this.shimId()].messages.push(n)}))}i.prototype.loadFull=function(r,e,o,n,t){var l=!1,i=e.createElement("script"),s=e.getElementsByTagName("script")[0],d=s.parentNode;i.crossOrigin="",i.src=n.rollbarJsUrl,o||(i.async=!0),i.onload=i.onreadystatechange=a((function(){if(!(l||this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState)){i.onload=i.onreadystatechange=null;try{d.removeChild(i)}catch(r){}l=!0,function(){var e;if(void 0===r._rollbarDidLoad){e=new Error("rollbar.js did not load");for(var o,n,a,l,i=0;o=r._rollbarShims[i++];)for(o=o.messages||[];n=o.shift();)for(a=n.args||[],i=0;i<a.length;++i)if("function"==typeof(l=a[i])){l(e);break}}"function"==typeof t&&t(e)}()}})),d.insertBefore(i,s)},i.prototype.wrap=function(r,e,o){try{var n;if(n="function"==typeof e?e:function(){return e||{}},"function"!=typeof r)return r;if(r._isWrap)return r;if(!r._rollbar_wrapped&&(r._rollbar_wrapped=function(){o&&"function"==typeof o&&o.apply(this,arguments);try{return r.apply(this,arguments)}catch(o){var e=o;throw e&&("string"==typeof e&&(e=new String(e)),e._rollbarContext=n()||{},e._rollbarContext._wrappedSource=r.toString(),window._rollbarWrappedError=e),e}},r._rollbar_wrapped._isWrap=!0,r.hasOwnProperty))for(var t in r)r.hasOwnProperty(t)&&(r._rollbar_wrapped[t]=r[t]);return r._rollbar_wrapped}catch(e){return r}};for(var p="log,debug,info,warn,warning,error,critical,global,configure,handleUncaughtException,handleAnonymousErrors,handleUnhandledRejection,captureEvent,captureDomContentLoaded,captureLoad".split(","),f=0;f<p.length;++f)i.prototype[p[f]]=u(p[f]);r.exports={setupShim:function(r,e){if(r){var o=e.globalAlias||"Rollbar";if("object"==typeof r[o])return r[o];r._rollbarShims={},r._rollbarWrappedError=null;var l=new c(e);return a((function(){e.captureUncaught&&(l._rollbarOldOnError=r.onerror,n.captureUncaughtExceptions(r,l,!0),e.wrapGlobalEventHandlers&&t(r,l,!0)),e.captureUnhandledRejections&&n.captureUnhandledRejections(r,l,!0);var a=e.autoInstrument;return!1!==e.enabled&&(void 0===a||!0===a||function(r){return!("object"!=typeof r||void 0!==r.page&&!r.page)}(a))&&r.addEventListener&&(r.addEventListener("load",l.captureLoad.bind(l)),r.addEventListener("DOMContentLoaded",l.captureDomContentLoaded.bind(l))),r[o]=l,l}))()}},Rollbar:c}},function(r,e,o){"use strict";function n(r,e,o,n){r._rollbarWrappedError&&(n[4]||(n[4]=r._rollbarWrappedError),n[5]||(n[5]=r._rollbarWrappedError._rollbarContext),r._rollbarWrappedError=null);var t=e.handleUncaughtException.apply(e,n);o&&o.apply(r,n),"anonymous"===t&&(e.anonymousErrorsPending+=1)}r.exports={captureUncaughtExceptions:function(r,e,o){if(r){var t;if("function"==typeof e._rollbarOldOnError)t=e._rollbarOldOnError;else if(r.onerror){for(t=r.onerror;t._rollbarOldOnError;)t=t._rollbarOldOnError;e._rollbarOldOnError=t}e.handleAnonymousErrors();var a=function(){var o=Array.prototype.slice.call(arguments,0);n(r,e,t,o)};o&&(a._rollbarOldOnError=t),r.onerror=a}},captureUnhandledRejections:function(r,e,o){if(r){"function"==typeof r._rollbarURH&&r._rollbarURH.belongsToShim&&r.removeEventListener("unhandledrejection",r._rollbarURH);var n=function(r){var o,n,t;try{o=r.reason}catch(r){o=void 0}try{n=r.promise}catch(r){n="[unhandledrejection] error getting `promise` from event"}try{t=r.detail,!o&&t&&(o=t.reason,n=t.promise)}catch(r){}o||(o="[unhandledrejection] error getting `reason` from event"),e&&e.handleUnhandledRejection&&e.handleUnhandledRejection(o,n)};n.belongsToShim=o,r._rollbarURH=n,r.addEventListener("unhandledrejection",n)}}}},function(r,e,o){"use strict";function n(r,e,o){if(e.hasOwnProperty&&e.hasOwnProperty("addEventListener")){for(var n=e.addEventListener;n._rollbarOldAdd&&n.belongsToShim;)n=n._rollbarOldAdd;var t=function(e,o,t){n.call(this,e,r.wrap(o),t)};t._rollbarOldAdd=n,t.belongsToShim=o,e.addEventListener=t;for(var a=e.removeEventListener;a._rollbarOldRemove&&a.belongsToShim;)a=a._rollbarOldRemove;var l=function(r,e,o){a.call(this,r,e&&e._rollbar_wrapped||e,o)};l._rollbarOldRemove=a,l.belongsToShim=o,e.removeEventListener=l}}r.exports=function(r,e,o){if(r){var t,a,l="EventTarget,Window,Node,ApplicationCache,AudioTrackList,ChannelMergerNode,CryptoOperation,EventSource,FileReader,HTMLUnknownElement,IDBDatabase,IDBRequest,IDBTransaction,KeyOperation,MediaController,MessagePort,ModalWindow,Notification,SVGElementInstance,Screen,TextTrack,TextTrackCue,TextTrackList,WebSocket,WebSocketWorker,Worker,XMLHttpRequest,XMLHttpRequestEventTarget,XMLHttpRequestUpload".split(",");for(t=0;t<l.length;++t)r[a=l[t]]&&r[a].prototype&&n(e,r[a].prototype,o)}}},function(r,e,o){"use strict";function n(r,e){this.impl=r(e,this),this.options=e,function(r){for(var e=function(r){return function(){var e=Array.prototype.slice.call(arguments,0);if(this.impl[r])return this.impl[r].apply(this.impl,e)}},o="log,debug,info,warn,warning,error,critical,global,configure,handleUncaughtException,handleAnonymousErrors,handleUnhandledRejection,_createItem,wrap,loadFull,shimId,captureEvent,captureDomContentLoaded,captureLoad".split(","),n=0;n<o.length;n++)r[o[n]]=e(o[n])}(n.prototype)}n.prototype._swapAndProcessMessages=function(r,e){var o,n,t;for(this.impl=r(this.options);o=e.shift();)n=o.method,t=o.args,this[n]&&"function"==typeof this[n]&&("captureDomContentLoaded"===n||"captureLoad"===n?this[n].apply(this,[t[0],o.ts]):this[n].apply(this,t));return this},r.exports=n},function(r,e,o){"use strict";r.exports=function(r){return function(e){if(!e&&!window._rollbarInitialized){for(var o,n,t=(r=r||{}).globalAlias||"Rollbar",a=window.rollbar,l=function(r){return new a(r)},i=0;o=window._rollbarShims[i++];)n||(n=o.handler),o.handler._swapAndProcessMessages(l,o.messages);window[t]=n,window._rollbarInitialized=!0}}}}]);\r\n                // End Rollbar Snippet\r\n            })();\r\n        }\r\n    </script>\r\n<script>\r\n    window.__CONFIG__ = {"admin":null,"antiForgeryTokenKey":"__RequestVerificationToken","cdn":{"enabled":true,"transformations":{"/content/":{"baseUrl":"https://cdn.static.gamefound.com/content/","versionNumber":"20260525.3-13"},"/image/":{"baseUrl":"https://imgcdn.gamefound.com/","versionNumber":null},"/video/":{"baseUrl":"https://vcdn.gamefound.com/","versionNumber":null}}},"comments":{"tagPattern":"([^a-zA-Z0-9_\\u003E]|^)#([a-zA-Z0-9]{3,30})\\\\b"},"currentUser":{"hasAccessToAdminMode":false},"debug":false,"environment":"Production","externalPMV2Enabled":true,"externalScripts":{"googlePayUrl":"https://pay.google.com/gp/p/js/pay.js","applePayUrl":"https://applepay.cdn-apple.com/jsapi/v1/apple-pay-sdk.js","googleSignInUrl":"https://accounts.google.com/gsi/client","facebookSignInUrl":"https://connect.facebook.net/en_US/sdk.js","reCaptchaUrl":"https://www.recaptcha.net/recaptcha/enterprise.js","stripeScriptUrl":"https://js.stripe.com/v3/","youTubeApiScriptUrl":"https://www.youtube.com/iframe_api","appleSignInUrl":"https://appleid.cdn-apple.com/appleauth/static/jsapi/appleid/1/en_US/appleid.auth.js"},"externalUrls":{"careerUrl":"https://career.gamefound.com/","creating

In [26]:
re.search(r'"projectTags"\s*:\s*(\[.+?\])\s*,\s*"projectProperties"', response.text).group(1)

'[{"projectTagID":1,"isSystem":false,"isVisible":true,"name":"fantasy","url":"/en/projects/search?projectTags=1","urlName":"fantasy"},{"projectTagID":7,"isSystem":false,"isVisible":true,"name":"mythology","url":"/en/projects/search?projectTags=7","urlName":"mythology"},{"projectTagID":34,"isSystem":false,"isVisible":true,"name":"cooperative","url":"/en/projects/search?projectTags=34","urlName":"cooperative"},{"projectTagID":40,"isSystem":false,"isVisible":true,"name":"campaign","url":"/en/projects/search?projectTags=40","urlName":"campaign"},{"projectTagID":41,"isSystem":false,"isVisible":true,"name":"civilization","url":"/en/projects/search?projectTags=41","urlName":"civilization"}]'

In [29]:
import requests
import re

url = "https://gamefound.com/en/projects/oomm-games/stonesaga-second-printing"

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'
}

print("페이지 요청 중...")
response = requests.get(url, headers=headers)
response.raise_for_status()

# 💡 정규식 패턴 설명:
# https://imgcdn.gamefound.com/richtextimage/richtext/ 로 시작하고,
# 그 뒤에 영문자, 숫자, 하이픈(-)이 1개 이상 오며,
# 마지막이 .png, .jpg, .jpeg, .gif, .webp 중 하나로 끝나는 문자열을 모두 찾습니다.
image_pattern = r'https://imgcdn\.gamefound\.com/richtextimage/richtext/[a-zA-Z0-9-]+\.(?:png|jpg|jpeg|gif|webp)'

# re.findall()을 사용하면 패턴과 일치하는 모든 문자열을 리스트 형태로 반환합니다.
extracted_images = re.findall(image_pattern, response.text)

# 중복된 이미지 URL이 있을 수 있으므로 set을 이용해 중복 제거 후 다시 리스트로 변환
unique_images = list(set(extracted_images))

print(f"총 {len(unique_images)}개의 고유한 이미지를 찾았습니다!\n")

print("수집된 이미지 URL:")
for img_url in unique_images:
    print(img_url)

페이지 요청 중...
총 22개의 고유한 이미지를 찾았습니다!

수집된 이미지 URL:
https://imgcdn.gamefound.com/richtextimage/richtext/25f1a889-9952-482d-96dd-3b1c575e28a2.png
https://imgcdn.gamefound.com/richtextimage/richtext/ba2241fe-942b-4414-8189-49c820ba3fbb.png
https://imgcdn.gamefound.com/richtextimage/richtext/a7a5f5ad-73cb-450c-8991-f62c392dcb13.png
https://imgcdn.gamefound.com/richtextimage/richtext/0ce2b5fa-35ae-486b-90e6-af2e5c6c8f37.png
https://imgcdn.gamefound.com/richtextimage/richtext/7ca7440a-a066-49b4-b564-b9d6d24c7dd6.png
https://imgcdn.gamefound.com/richtextimage/richtext/f2c518ef-e1a6-4201-9085-1867893c73ab.png
https://imgcdn.gamefound.com/richtextimage/richtext/efbfc57a-b380-400c-94cb-75aae12d5c1c.png
https://imgcdn.gamefound.com/richtextimage/richtext/a09ab81f-d2b0-4e08-b7c4-2b8dd80e1ecb.png
https://imgcdn.gamefound.com/richtextimage/richtext/aa473ff2-8967-4dfb-b07b-ed6304b19bf0.png
https://imgcdn.gamefound.com/richtextimage/richtext/8d8d973f-fe20-4ed1-a0e9-09d5be5cec37.png
https://imgcdn.gamefound.com/richtextimage/richtext/8d1079dd-f64b-4fe2-b6ba-9306ba04f091.png
https://imgcdn.gamefound.com/richtextimage/richtext/8b462f61-081c-414f-afe3-dc147e2aa80b.png
https://imgcdn.gamefound.com/richtextimage/richtext/f8401b08-a647-423d-941b-e9d0220a8fbb.png
https://imgcdn.gamefound.com/richtextimage/richtext/3cac5ea8-871a-453c-ba3f-5d55cb39b228.png
https://imgcdn.gamefound.com/richtextimage/richtext/e841d753-2d50-472d-90ff-0062a62fd89f.png
https://imgcdn.gamefound.com/richtextimage/richtext/8d19fdd6-ef18-48bb-9910-6e726e67e18d.png
https://imgcdn.gamefound.com/richtextimage/richtext/6a1a85b6-a6bd-44b7-8f8a-2914e2d23270.png
https://imgcdn.gamefound.com/richtextimage/richtext/4052a2be-957b-47d9-8fac-2656729c239c.png
https://imgcdn.gamefound.com/richtextimage/richtext/a91f3b6b-d44e-4ff0-8fdc-e897c7cec842.png
https://imgcdn.gamefound.com/richtextimage/richtext/839faad9-124d-4a3d-8226-430a6b336cbd.png
https://imgcdn.gamefound.com/richtextimage/richtext/c1eb8217-e127-4043-a6fd-21228ed7f80d.png
https://imgcdn.gamefound.com/richtextimage/richtext/50b220ea-9d93-4781-bdeb-76f467432078.png

In [ ]:
https://imgcdn.gamefound.com/richtextimage/richtext/0ce2b5fa-35ae-486b-90e6-af2e5c6c8f37.png