In [385]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import OrdinalEncoder

In [386]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.metrics import RocCurveDisplay

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RandomizedSearchCV

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression

In [389]:
import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    median_absolute_error,
    r2_score
)

from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

In [387]:
plt.rcParams["font.family"] = "Malgun Gothic"
plt.rcParams["axes.unicode_minus"] = False

# <b>Load Dataset</b>

In [421]:
df = pd.read_csv('data/0611raw_final.csv') # 이미지(밝기, 명도 안 들어감)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 483 entries, 0 to 482
Columns: 149 entries, Unnamed: 0 to rewards_count
dtypes: float64(56), int64(84), object(9)
memory usage: 562.4+ KB

In [423]:
df_con = pd.read_csv('data/contrast.csv')

In [425]:
df = df.merge(
    df_con[[
        "projectID",
        "edge_density",
        "saturation",
        "brightness",
        "contrast"
    ]],
    on="projectID",
    how="left"
)

In [432]:
post_cols = [
    "fundedInSeconds", "likes_0", "likes_1", "is_backer_0", "is_backer_1"
]

text_cols = [
    "creator_id_0", "creator_id_1",
    "is_pledge_master_0", "is_pledge_master_1",
    
    "is_prior_backer_0", "is_prior_backer_1",
    "is_pathfinder_0", "is_pathfinder_1",
     "is_normal_0", "is_normal_1"
]

text_cols_api = [
    "Product_Question_count_0", "Product_Question_count_1",
    "Suggestion_Idea_count_0", "Suggestion_Idea_count_1",
    "Praise_Support_count_0", "Praise_Support_count_1",
    "Shipping_Fulfillment_count_0", "Shipping_Fulfillment_count_1",
    "Complaint_Refund_count_0", "Complaint_Refund_count_1",
    "Spam_Irrelevant_count_0", "Spam_Irrelevant_count_1"
]

text_cols_sen = [
    "긍정_0", "긍정_1",
    "부정_0", "부정_1",
    "중립_0", "중립_1"
    ]

text_cols_topic = [
    "Campaign / Pledge_0", "Campaign / Pledge_1",
    "Community Reaction_0", "Community Reaction_1",
    "Components & Production_0", "Components & Production_1",
    "Gameplay / Rules / Content_0", "Gameplay / Rules / Content_1",
    "Language & Localization_0", "Language & Localization_1",
    "Schedule / Updates_0", "Schedule / Updates_1",
    "Shipping / Price / Tax_0", "Shipping / Price / Tax_1"
]

one_month_cols = [
    "campaignGoal_usd_1m",
    "fundsGathered_usd_1m",
    "price_usd_1m"
]

six_month_cols = [
    "campaignGoal_usd_6m",
    "fundsGathered_usd_6m",
    "price_usd_6m"
]

color_cols1 = [
    "R1", "G1", "B1",
    "R2", "G2", "B2",
    "R3", "G3", "B3",
    "R4", "G4", "B4"]
color_cols2= [
    "ks_color_1", "ks_color_2", "ks_color_3", "ks_color_4"] # mae줄음
color_cols3=[
    "emotion_adjective_1", "emotion_adjective_2",
    "emotion_adjective_3", "emotion_adjective_4"
]

edge_cols1 = ["edge_density"]
edge_cols2 = ["saturation"]
edge_cols3 = ["brightness"]
edge_cols4 = ["contrast"]

In [433]:
# drop_cols = post_cols + text_cols_api + text_cols_sen + text_cols_topic + one_month_cols + color_cols
drop_cols = (post_cols + six_month_cols
             + color_cols1 + color_cols3
             + edge_cols1 + edge_cols2 + edge_cols3 + edge_cols4 
             + text_cols_topic + text_cols_api)# 고정


# drop_cols = (post_cols + six_month_cols
             # + color_cols1 + color_cols3
             # + edge_cols1 + edge_cols2 + edge_cols3 + edge_cols4 
             # + text_cols_topic)# 고정
            

df.drop(columns=drop_cols, errors="ignore", inplace=True)

# <b>이상치 제거</b>

In [436]:
# ======================================================================
# 1.5 IQR 기준으로 fundsGathered_usd_1m 상방 이상치 제거
# ======================================================================

col_target = "fundsGathered_usd_1m"

# Q1, Q3, IQR 계산
q1 = df[col_target].quantile(0.25)
q3 = df[col_target].quantile(0.75)
iqr = q3 - q1

# 상한선 계산
upper_bound = q3 + 1.5 * iqr

# 상한선 이하 데이터만 남기기
df = df.loc[df[col_target] <= upper_bound].reset_index(drop=True)

print("📊 [IQR 기준 이상치 제거 완료]")
print(f"Q1: ${q1:,.2f}")
print(f"Q3: ${q3:,.2f}")
print(f"IQR: ${iqr:,.2f}")
print(f"IQR 상한선: ${upper_bound:,.2f}")
print(f"남은 데이터 크기: {df.shape}")

📊 [IQR 기준 이상치 제거 완료]
Q1: $3,989.53
Q3: $224,294.09
IQR: $220,304.56
IQR 상한선: $554,750.94
남은 데이터 크기: (418, 98)

# <b>train test split</b>

In [440]:
from sklearn.model_selection import train_test_split

df_trn, df_tst = train_test_split(
    df,
    test_size=0.2,
    random_state=42
)

# <b>EDA</b>

In [84]:
df_trn.info()

<class 'pandas.core.frame.DataFrame'>
Index: 334 entries, 336 to 102
Data columns (total 88 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   projectID                  334 non-null    int64
 1   currencySymbol             334 non-null    object
 2   enableBoardGameProperties  334 non-null    int64
 3   minPlayers                 323 non-null    float64
 4   maxPlayers                 323 non-null    float64
 5   minAge                     314 non-null    float64
 6   playTime                   317 non-null    float64
 7   isDiscounted               334 non-null    int64
 8   previous_campaigns_count   334 non-null    int64
 9   duration_days              334 non-null    int64
 10  softclose                  334 non-null    int64
 11  campaignGoal_usd_1m        334 non-null    float64
 12  fundsGathered_usd_1m       334 non-null    float64
 13  price_usd_1m               334 non-null    float64
 14  creator_id_0               334 non-null    float64
 15  creator_id_1               334 non-null    float64
 16  is_pledge_master_0         334 non-null    float64
 17  is_pledge_master_1         334 non-null    float64
 18  is_prior_backer_0          334 non-null    float64
 19  is_prior_backer_1          334 non-null    float64
 20  is_pathfinder_0            334 non-null    float64
 21  is_pathfinder_1            334 non-null    float64
 22  is_normal_0                334 non-null    float64
 23  is_normal_1                334 non-null    float64
 24  4X                         334 non-null    int64
 25  AR Next                    334 non-null    int64
 26  ARNext26                   334 non-null    int64
 27  Action                     334 non-null    int64
 28  Adventure                  334 non-null    int64
 29  Area Control               334 non-null    int64
 30  Asymmetric                 334 non-null    int64
 31  Campaign                   334 non-null    int64
 32  Card Game                  334 non-null    int64
 33  Cats                       334 non-null    int64
 34  Civilization               334 non-null    int64
 35  Collectible                334 non-null    int64
 36  Collectible Models         334 non-null    int64
 37  Competitive                334 non-null    int64
 38  Cooperative                334 non-null    int64
 39  Deck Building              334 non-null    int64
 40  Deduction                  334 non-null    int64
 41  Dexterity                  334 non-null    int64
 42  Dice Game                  334 non-null    int64
 43  Digital                    334 non-null    int64
 44  Economic                   334 non-null    int64
 45  Educational                334 non-null    int64
 46  Exploration                334 non-null    int64
 47  Family                     334 non-null    int64
 48  Fantasy                    334 non-null    int64
 49  Feast                      334 non-null    int64
 50  First-Timers               334 non-null    int64
 51  Game Components            334 non-null    int64
 52  History                    334 non-null    int64
 53  Horror                     334 non-null    int64
 54  Humor                      334 non-null    int64
 55  Legacy                     334 non-null    int64
 56  Logical                    334 non-null    int64
 57  MOBA                       334 non-null    int64
 58  Major Creators             334 non-null    int64
 59  Media                      334 non-null    int64
 60  Modern                     334 non-null    int64
 61  Multiplayer                334 non-null    int64
 62  Mythology                  334 non-null    int64
 63  Narrative                  334 non-null    int64
 64  OctoberFeast25             334 non-null    int64
 65  Paint                      334 non-null    int64
 66  Party game                 334 non-null    int64
 67  Political                  334 non-null    int64
 68  Print and Play             334 non-null    int64
 69  RPG                        334 non-null    int64
 70  Racing                     334 non-null    int64
 71  Reprints                   334 non-null    int64
 72  Resource management        334 non-null    int64
 73  Science Fiction            334 non-null    int64
 74  Set Collection             334 non-null    int64
 75  Sport                      334 non-null    int64
 76  Strategy                   334 non-null    int64
 77  Survival                   334 non-null    int64
 78  TTRPG                      334 non-null    int64
 79  Terrain Building           334 non-null    int64
 80  Tower Defense              334 non-null    int64
 81  Video Game                 334 non-null    int64
 82  Video Game Theme           334 non-null    int64
 83  Wargame                    334 non-null    int64
 84  WinterFeast2026            334 non-null    int64
 85  Worker placement           334 non-null    int64
 86  dinotuesday                334 non-null    int64
 87  rewards_count              334 non-null    int64
dtypes: float64(17), int64(70), object(1)
memory usage: 232.2+ KB

In [85]:
df_tst.info()

<class 'pandas.core.frame.DataFrame'>
Index: 84 entries, 321 to 66
Data columns (total 88 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   projectID                  84 non-null     int64
 1   currencySymbol             84 non-null     object
 2   enableBoardGameProperties  84 non-null     int64
 3   minPlayers                 81 non-null     float64
 4   maxPlayers                 81 non-null     float64
 5   minAge                     79 non-null     float64
 6   playTime                   79 non-null     float64
 7   isDiscounted               84 non-null     int64
 8   previous_campaigns_count   84 non-null     int64
 9   duration_days              84 non-null     int64
 10  softclose                  84 non-null     int64
 11  campaignGoal_usd_1m        84 non-null     float64
 12  fundsGathered_usd_1m       84 non-null     float64
 13  price_usd_1m               84 non-null     float64
 14  creator_id_0               84 non-null     float64
 15  creator_id_1               84 non-null     float64
 16  is_pledge_master_0         84 non-null     float64
 17  is_pledge_master_1         84 non-null     float64
 18  is_prior_backer_0          84 non-null     float64
 19  is_prior_backer_1          84 non-null     float64
 20  is_pathfinder_0            84 non-null     float64
 21  is_pathfinder_1            84 non-null     float64
 22  is_normal_0                84 non-null     float64
 23  is_normal_1                84 non-null     float64
 24  4X                         84 non-null     int64
 25  AR Next                    84 non-null     int64
 26  ARNext26                   84 non-null     int64
 27  Action                     84 non-null     int64
 28  Adventure                  84 non-null     int64
 29  Area Control               84 non-null     int64
 30  Asymmetric                 84 non-null     int64
 31  Campaign                   84 non-null     int64
 32  Card Game                  84 non-null     int64
 33  Cats                       84 non-null     int64
 34  Civilization               84 non-null     int64
 35  Collectible                84 non-null     int64
 36  Collectible Models         84 non-null     int64
 37  Competitive                84 non-null     int64
 38  Cooperative                84 non-null     int64
 39  Deck Building              84 non-null     int64
 40  Deduction                  84 non-null     int64
 41  Dexterity                  84 non-null     int64
 42  Dice Game                  84 non-null     int64
 43  Digital                    84 non-null     int64
 44  Economic                   84 non-null     int64
 45  Educational                84 non-null     int64
 46  Exploration                84 non-null     int64
 47  Family                     84 non-null     int64
 48  Fantasy                    84 non-null     int64
 49  Feast                      84 non-null     int64
 50  First-Timers               84 non-null     int64
 51  Game Components            84 non-null     int64
 52  History                    84 non-null     int64
 53  Horror                     84 non-null     int64
 54  Humor                      84 non-null     int64
 55  Legacy                     84 non-null     int64
 56  Logical                    84 non-null     int64
 57  MOBA                       84 non-null     int64
 58  Major Creators             84 non-null     int64
 59  Media                      84 non-null     int64
 60  Modern                     84 non-null     int64
 61  Multiplayer                84 non-null     int64
 62  Mythology                  84 non-null     int64
 63  Narrative                  84 non-null     int64
 64  OctoberFeast25             84 non-null     int64
 65  Paint                      84 non-null     int64
 66  Party game                 84 non-null     int64
 67  Political                  84 non-null     int64
 68  Print and Play             84 non-null     int64
 69  RPG                        84 non-null     int64
 70  Racing                     84 non-null     int64
 71  Reprints                   84 non-null     int64
 72  Resource management        84 non-null     int64
 73  Science Fiction            84 non-null     int64
 74  Set Collection             84 non-null     int64
 75  Sport                      84 non-null     int64
 76  Strategy                   84 non-null     int64
 77  Survival                   84 non-null     int64
 78  TTRPG                      84 non-null     int64
 79  Terrain Building           84 non-null     int64
 80  Tower Defense              84 non-null     int64
 81  Video Game                 84 non-null     int64
 82  Video Game Theme           84 non-null     int64
 83  Wargame                    84 non-null     int64
 84  WinterFeast2026            84 non-null     int64
 85  Worker placement           84 non-null     int64
 86  dinotuesday                84 non-null     int64
 87  rewards_count              84 non-null     int64
dtypes: float64(17), int64(70), object(1)
memory usage: 58.4+ KB

In [86]:
df.columns

Index(['projectID', 'currencySymbol', 'enableBoardGameProperties',
       'minPlayers', 'maxPlayers', 'minAge', 'playTime', 'isDiscounted',
       'previous_campaigns_count', 'duration_days', 'softclose',
       'campaignGoal_usd_1m', 'fundsGathered_usd_1m', 'price_usd_1m',
       'creator_id_0', 'creator_id_1', 'is_pledge_master_0',
       'is_pledge_master_1', 'is_prior_backer_0', 'is_prior_backer_1',
       'is_pathfinder_0', 'is_pathfinder_1', 'is_normal_0', 'is_normal_1',
       '4X', 'AR Next', 'ARNext26', 'Action', 'Adventure', 'Area Control',
       'Asymmetric', 'Campaign', 'Card Game', 'Cats', 'Civilization',
       'Collectible', 'Collectible Models', 'Competitive', 'Cooperative',
       'Deck Building', 'Deduction', 'Dexterity', 'Dice Game', 'Digital',
       'Economic', 'Educational', 'Exploration', 'Family', 'Fantasy', 'Feast',
       'First-Timers', 'Game Components', 'History', 'Horror', 'Humor',
       'Legacy', 'Logical', 'MOBA', 'Major Creators', 'Media', 'Modern',
       'Multiplayer', 'Mythology', 'Narrative', 'OctoberFeast25', 'Paint',
       'Party game', 'Political', 'Print and Play', 'RPG', 'Racing',
       'Reprints', 'Resource management', 'Science Fiction', 'Set Collection',
       'Sport', 'Strategy', 'Survival', 'TTRPG', 'Terrain Building',
       'Tower Defense', 'Video Game', 'Video Game Theme', 'Wargame',
       'WinterFeast2026', 'Worker placement', 'dinotuesday', 'rewards_count'],
      dtype='object')

In [ ]:
import matplotlib.pyplot as plt
import math

# 한글 폰트 깨짐 해결 - 윈도우 기준
plt.rcParams["font.family"] = "Malgun Gothic"
plt.rcParams["axes.unicode_minus"] = False

tag_cols = [
    "4X", "Action", "Adventure",
    "Area Control", "Asymmetric", "Campaign", "Card Game", "Cats",
    "Civilization", "Collectible", "Collectible Models", "Competitive",
    "Cooperative", "Deck Building", "Deduction", "Dexterity", "Dice Game",
    "Digital", "Economic", "Educational", "Exploration", "Family",
    "Fantasy", "Feast", "First-Timers", "Game Components", "History",
    "Horror", "Humor", "Legacy", "Logical", "MOBA", 
    "Media", "Modern", "Multiplayer", "Mythology", "Narrative",
    "OctoberFeast25", "Paint", "Party game", "Political",
    "Print and Play", "RPG", "Racing", "Reprints",
    "Resource management", "Science Fiction", "Set Collection", "Sport",
    "Strategy", "Survival", "TTRPG", "Terrain Building", "Tower Defense",
    "Video Game", "Video Game Theme", "Wargame", "WinterFeast2026",
    "Worker placement", "dinotuesday"
]

drop_cols_eda = color_cols + tag_cols

# tag 컬럼 + color 컬럼 빼기
df_trn_no = df_trn.drop(columns=drop_cols_eda, errors="ignore")

# 숫자형 컬럼만 선택
num_cols = df_trn_no.select_dtypes(include="number").columns

# 한 행에 4개씩
n_cols = 4
n_rows = math.ceil(len(num_cols) / n_cols)

fig, axes = plt.subplots(
    n_rows,
    n_cols,
    figsize=(20, n_rows * 3)
)

axes = axes.flatten()

for i, col in enumerate(num_cols):
    axes[i].hist(df_trn_no[col].dropna(), bins=30)
    axes[i].set_title(col, fontsize=10)
    axes[i].grid(True)

# 남는 빈 그래프 삭제
for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import math

# 한글 폰트 깨짐 해결 - 윈도우 기준
plt.rcParams["font.family"] = "Malgun Gothic"
plt.rcParams["axes.unicode_minus"] = False

tag_cols = [
    "4X", "Action", "Adventure",
    "Area Control", "Asymmetric", "Campaign", "Card Game", "Cats",
    "Civilization", "Collectible", "Collectible Models", "Competitive",
    "Cooperative", "Deck Building", "Deduction", "Dexterity", "Dice Game",
    "Digital", "Economic", "Educational", "Exploration", "Family",
    "Fantasy", "Feast", "First-Timers", "Game Components", "History",
    "Horror", "Humor", "Legacy", "Logical", "MOBA", 
    "Media", "Modern", "Multiplayer", "Mythology", "Narrative",
    "OctoberFeast25", "Paint", "Party game", "Political",
    "Print and Play", "RPG", "Racing", "Reprints",
    "Resource management", "Science Fiction", "Set Collection", "Sport",
    "Strategy", "Survival", "TTRPG", "Terrain Building", "Tower Defense",
    "Video Game", "Video Game Theme", "Wargame", "WinterFeast2026",
    "Worker placement", "dinotuesday"
]

drop_cols_eda = color_cols + tag_cols

# tag 컬럼 + color 컬럼 빼기
df_tst_no = df_tst.drop(columns=drop_cols_eda, errors="ignore")

# 숫자형 컬럼만 선택
num_cols = df_tst_no.select_dtypes(include="number").columns

# 한 행에 4개씩
n_cols = 4
n_rows = math.ceil(len(num_cols) / n_cols)

fig, axes = plt.subplots(
    n_rows,
    n_cols,
    figsize=(20, n_rows * 3)
)

axes = axes.flatten()

for i, col in enumerate(num_cols):
    axes[i].hist(df_tst_no[col].dropna(), bins=30)
    axes[i].set_title(col, fontsize=10)
    axes[i].grid(True)

# 남는 빈 그래프 삭제
for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

# <b>Preprocessing</b>

In [248]:
dummy_cols = [
    "4X",
    "AR Next",
    "ARNext26",
    "Action",
    "Adventure",
    "Area Control",
    "Asymmetric",
    "Campaign",
    "Card Game",
    "Cats",
    "Civilization",
    "Collectible",
    "Collectible Models",
    "Competitive",
    "Cooperative",
    "Deck Building",
    "Deduction",
    "Dexterity",
    "Dice Game",
    "Digital",
    "Economic",
    "Educational",
    "Exploration",
    "Family",
    "Fantasy",
    "Feast",
    "First-Timers",
    "Game Components",
    "History",
    "Horror",
    "Humor",
    "Legacy",
    "Logical",
    "MOBA",
    "Major Creators",
    "Media",
    "Modern",
    "Multiplayer",
    "Mythology",
    "Narrative",
    "OctoberFeast25",
    "Paint",
    "Party game",
    "Political",
    "Print and Play",
    "RPG",
    "Racing",
    "Reprints",
    "Resource management",
    "Science Fiction",
    "Set Collection",
    "Sport",
    "Strategy",
    "Survival",
    "TTRPG",
    "Terrain Building",
    "Tower Defense",
    "Video Game",
    "Video Game Theme",
    "Wargame",
    "WinterFeast2026",
    "Worker placement",
    "dinotuesday"
]

In [ ]:
df_trn[dummy_cols].sum().sort_values(ascending=False)

In [ ]:
df_tst[dummy_cols].sum().sort_values(ascending=False)

In [447]:
df_trn.drop(columns=['AR Next', 'ARNext26', 'Major Creators'], inplace=True)
df_tst.drop(columns=['AR Next', 'ARNext26', 'Major Creators'], inplace=True)

In [444]:
tag_cols = [
    "4X", "Action", "Adventure",
    "Area Control", "Asymmetric", "Campaign", "Card Game", "Cats",
    "Civilization", "Collectible", "Collectible Models", "Competitive",
    "Cooperative", "Deck Building", "Deduction", "Dexterity", "Dice Game",
    "Digital", "Economic", "Educational", "Exploration", "Family",
    "Fantasy", "Feast", "First-Timers", "Game Components", "History",
    "Horror", "Humor", "Legacy", "Logical", "MOBA", 
    "Media", "Modern", "Multiplayer", "Mythology", "Narrative",
    "OctoberFeast25", "Paint", "Party game", "Political",
    "Print and Play", "RPG", "Racing", "Reprints",
    "Resource management", "Science Fiction", "Set Collection", "Sport",
    "Strategy", "Survival", "TTRPG", "Terrain Building", "Tower Defense",
    "Video Game", "Video Game Theme", "Wargame", "WinterFeast2026",
    "Worker placement", "dinotuesday"
]

In [ ]:
genre_cols = tag_cols

In [446]:
target = "fundsGathered_usd_1m"

genre_y_summary = []

for col in genre_cols:
    temp = df_trn.groupby(col)[target].agg(["count", "mean", "median", "std"])
    temp["genre"] = col
    
    if 1 in temp.index:
        genre_y_summary.append(temp.loc[1])

genre_y_summary = pd.DataFrame(genre_y_summary)

genre_y_summary = genre_y_summary[["genre", "count", "mean", "median", "std"]]

# count > 10인 장르만 남기기
genre_y_summary = genre_y_summary[genre_y_summary["count"] >= 10].copy()

# median이 전체 y 분포에서 상위 몇 %인지
genre_y_summary["median_top_pct"] = genre_y_summary["median"].apply(
    lambda x: (df_trn[target] >= x).mean() * 100
).round(2)

# median 높은 순 정렬 + 인덱스 초기화
genre_y_summary = genre_y_summary.sort_values("median", ascending=False).reset_index(drop=True)

# 순위 열 추가
genre_y_summary["rank"] = genre_y_summary.index + 1
genre_y_summary["rank"] = genre_y_summary["rank"].apply(lambda x: str(x) + "위")

# 열 순서 정리
genre_y_summary = genre_y_summary[
    ["rank", "genre", "count", "mean", "median", "std", "median_top_pct"]
]

genre_y_summary

,rank,genre,count,mean,median,std,median_top_pct
0,1위,Narrative,22,163921.86,128780.09,172814.29,20.06
1,2위,Collectible Models,14,140181.42,96152.52,143742.73,23.95
2,3위,Video Game Theme,10,154824.65,64442.29,178865.16,32.34
3,4위,Worker placement,24,148610.71,56152.86,177708.54,34.73
4,5위,Terrain Building,11,74896.47,50202.71,90292.36,37.43
5,6위,Cooperative,73,128392.04,50202.71,150321.24,37.43
6,7위,Exploration,44,121547.42,48282.33,154470.08,38.32
7,8위,Horror,35,110013.67,46984.72,155944.23,38.92
8,9위,Area Control,35,136756.15,45765.07,175568.52,40.12
9,10위,Adventure,78,118050.87,44318.17,148944.50,40.72
10,11위,Asymmetric,49,120082.73,43425.13,150887.15,41.02
11,12위,Game Components,17,116124.27,43425.13,156742.26,41.02
12,13위,Economic,24,86959.22,42417.05,105761.03,41.32
13,14위,Campaign,37,94308.02,39205.99,134045.80,42.51
14,15위,Science Fiction,60,85636.87,37898.39,133026.77,42.81
15,16위,Action,43,87246.02,36636.89,131457.44,43.41
16,17위,History,67,82242.50,36636.89,102796.00,43.41
17,18위,Wargame,44,73599.26,36391.66,101853.97,43.71
18,19위,Deck Building,34,76474.43,32359.81,108498.58,46.41
19,20위,Fantasy,91,113907.52,30538.27,163809.16,47.60
20,21위,Set Collection,33,97445.31,29404.70,144816.06,48.80
21,22위,Resource management,57,91193.50,29404.70,129761.90,48.80
22,23위,Competitive,153,85253.25,28681.94,128774.26,49.40
23,24위,Mythology,19,112658.77,28347.67,157091.37,49.70
24,25위,Strategy,178,90843.54,28200.98,135439.61,49.70
25,26위,Modern,40,47827.13,23701.45,74610.87,51.50
26,27위,Sport,18,98320.08,17216.47,173439.87,55.39
27,28위,Deduction,12,100257.13,17190.61,144487.49,55.39
28,29위,RPG,20,82022.22,15577.07,130123.27,56.89
29,30위,Multiplayer,148,70689.94,15558.45,118013.92,56.89
30,31위,Survival,43,88900.12,13595.18,134627.04,57.78
31,32위,Political,10,70698.70,13595.13,117442.77,57.78
32,33위,Racing,12,42234.51,13432.51,81521.60,57.78
33,34위,Card Game,163,60969.24,13098.26,111228.12,58.08
34,35위,Dice Game,78,64054.99,8829.01,107991.71,62.57
35,36위,Educational,17,17868.44,7786.13,35843.40,64.37
36,37위,Family,69,37650.57,4705.80,84461.56,70.66
37,38위,Logical,35,62488.02,4347.64,106678.82,71.86
38,39위,Humor,27,47263.00,2879.81,86151.67,76.65
39,40위,Collectible,20,73404.88,2179.36,117169.85,79.34
40,41위,Party game,41,13200.43,1883.29,31267.49,81.74
41,42위,Digital,13,4982.16,768.98,13220.02,88.32

# <b>결측치</b>

In [448]:
cols = ["minPlayers", "maxPlayers", "minAge", "playTime"]

for col in cols:
    med = df_trn[col].median()

    df_trn[col] = df_trn[col].fillna(med)
    df_tst[col] = df_tst[col].fillna(med)

# <b>X Y split</b>

In [450]:
total_cols = [x for x in df_trn.columns]

id_cols = ['projectID']
y_cols = ['fundsGathered_usd_1m']
x_cols = [col for col in total_cols if col not in id_cols+y_cols]

df_trn_x = df_trn[x_cols]
df_trn_y = df_trn[y_cols]

# df_tst.drop(columns='fundsGathered_usd_6m', inplace=True)
df_tst_x = df_tst[x_cols]
df_tst_y = df_tst[y_cols]

# <b>인코딩 & 피처 엔지니어링</b>

In [453]:
df_trn_x = pd.get_dummies(
    df_trn_x,
    columns=["currencySymbol"],
    prefix="currencySymbol",
    drop_first=False
)

df_tst_x = pd.get_dummies(
    df_tst_x,
    columns=["currencySymbol"],
    prefix="currencySymbol",
    drop_first=False
)

In [456]:
def genre_performance_group(top_pct):
    if top_pct < 31:
        return "top_30%"
    elif top_pct <= 50:
        return "top_30%_50%"
    elif top_pct <= 70:
        return "top_50%_70%"
    else:
        return "bottom_30%"

genre_y_summary["genre_perf_group"] = genre_y_summary["median_top_pct"].apply(
    genre_performance_group
)

genre_y_summary.head(5)

,rank,genre,count,mean,median,std,median_top_pct,genre_perf_group
0,1위,Narrative,22,163921.86,128780.09,172814.29,20.06,top_30%
1,2위,Collectible Models,14,140181.42,96152.52,143742.73,23.95,top_30%
2,3위,Video Game Theme,10,154824.65,64442.29,178865.16,32.34,top_30%_50%
3,4위,Worker placement,24,148610.71,56152.86,177708.54,34.73,top_30%_50%
4,5위,Terrain Building,11,74896.47,50202.71,90292.36,37.43,top_30%_50%

In [457]:
top_30_genres = genre_y_summary.loc[
    genre_y_summary["genre_perf_group"] == "top_30%",
    "genre"
].tolist()

top_30_50_genres = genre_y_summary.loc[
    genre_y_summary["genre_perf_group"] == "top_30%_50%",
    "genre"
].tolist()

top_50_70_genres = genre_y_summary.loc[
    genre_y_summary["genre_perf_group"] == "top_50%_70%",
    "genre"
].tolist()

bottom_30_genres = genre_y_summary.loc[
    genre_y_summary["genre_perf_group"] == "bottom_30%",
    "genre"
].tolist()

print("top_30_genres:", top_30_genres)
print("top_30_50_genres:", top_30_50_genres)
print("top_50_70_genres:", top_50_70_genres)
print("bottom_30_genres:", bottom_30_genres)

top_30_genres: ['Narrative', 'Collectible Models']
top_30_50_genres: ['Video Game Theme', 'Worker placement', 'Terrain Building', 'Cooperative', 'Exploration', 'Horror', 'Area Control', 'Adventure', 'Asymmetric', 'Game Components', 'Economic', 'Campaign', 'Science Fiction', 'Action', 'History', 'Wargame', 'Deck Building', 'Fantasy', 'Set Collection', 'Resource management', 'Competitive', 'Mythology', 'Strategy']
top_50_70_genres: ['Modern', 'Sport', 'Deduction', 'RPG', 'Multiplayer', 'Survival', 'Political', 'Racing', 'Card Game', 'Dice Game', 'Educational']
bottom_30_genres: ['Family', 'Logical', 'Humor', 'Collectible', 'Party game', 'Digital']

In [458]:
df_trn_x["top_30_genre_count"] = df_trn_x[top_30_genres].sum(axis=1)
df_tst_x["top_30_genre_count"] = df_tst_x[top_30_genres].sum(axis=1)

df_trn_x["top_30_50_genre_count"] = df_trn_x[top_30_50_genres].sum(axis=1)
df_tst_x["top_30_50_genre_count"] = df_tst_x[top_30_50_genres].sum(axis=1)

df_trn_x["top_50_70_genre_count"] = df_trn_x[top_50_70_genres].sum(axis=1)
df_tst_x["top_50_70_genre_count"] = df_tst_x[top_50_70_genres].sum(axis=1)

df_trn_x["bottom_30_genre_count"] = df_trn_x[bottom_30_genres].sum(axis=1)
df_tst_x["bottom_30_genre_count"] = df_tst_x[bottom_30_genres].sum(axis=1)

In [459]:
df_trn_x["total_genre_count"] = df_trn_x[genre_cols].sum(axis=1)
df_tst_x["total_genre_count"] = df_tst_x[genre_cols].sum(axis=1)

df_trn_x["top_30_genre_ratio"] = (
    df_trn_x["top_30_genre_count"] / df_trn_x["total_genre_count"].replace(0, np.nan)
).fillna(0)
df_tst_x["top_30_genre_ratio"] = (
    df_tst_x["top_30_genre_count"] / df_tst_x["total_genre_count"].replace(0, np.nan)
).fillna(0)

df_trn_x["top_30_50_genre_ratio"] = (
    df_trn_x["top_30_50_genre_count"] / df_trn_x["total_genre_count"].replace(0, np.nan)
).fillna(0)
df_tst_x["top_30_50_genre_ratio"] = (
    df_tst_x["top_30_50_genre_count"] / df_tst_x["total_genre_count"].replace(0, np.nan)
).fillna(0)

df_trn_x["top_50_70_genre_ratio"] = (
    df_trn_x["top_50_70_genre_count"] / df_trn_x["total_genre_count"].replace(0, np.nan)
).fillna(0)
df_tst_x["top_50_70_genre_ratio"] = (
    df_tst_x["top_50_70_genre_count"] / df_tst_x["total_genre_count"].replace(0, np.nan)
).fillna(0)

df_trn_x["bottom_30_genre_ratio"] = (
    df_trn_x["bottom_30_genre_count"] / df_trn_x["total_genre_count"].replace(0, np.nan)
).fillna(0)
df_tst_x["bottom_30_genre_ratio"] = (
    df_tst_x["bottom_30_genre_count"] / df_tst_x["total_genre_count"].replace(0, np.nan)
).fillna(0)

In [460]:
new_genre_features = [
    "top_30_genre_count",
    "top_30_50_genre_count",
    "top_50_70_genre_count",
    "bottom_30_genre_count",
    "total_genre_count",
    "top_30_genre_ratio",
    "top_30_50_genre_ratio",
    "top_50_70_genre_ratio",
    "bottom_30_genre_ratio"
]

In [461]:
df_trn_x.drop(columns=["top_30_genre_count",
    "top_30_50_genre_count",
    "top_50_70_genre_count",
    "bottom_30_genre_count",
    "total_genre_count"], inplace=True)
df_tst_x.drop(columns=["top_30_genre_count",
    "top_30_50_genre_count",
    "top_50_70_genre_count",
    "bottom_30_genre_count",
    "total_genre_count"], inplace=True)

In [463]:
df_trn_x.drop(columns=tag_cols, inplace=True)
df_tst_x.drop(columns=tag_cols, inplace=True)

In [464]:
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd
import numpy as np

# 라벨을 통일해야 하는 컬럼 묶음
ks_color_cols = ["ks_color_1", "ks_color_2", "ks_color_3", "ks_color_4"]

adjective_cols = [
    "emotion_adjective_1", 
    "emotion_adjective_2", 
    "emotion_adjective_3", 
    "emotion_adjective_4"
]

# 원본 보존
df_trn_encoded_x = df_trn_x.copy()
df_tst_encoded_x = df_tst_x.copy()

In [465]:
# ks_color_1~4에 등장하는 모든 값을 하나로 모아서 fit
ks_values = df_trn_x[ks_color_cols].values.reshape(-1, 1)

ks_encoder = OrdinalEncoder(
    handle_unknown="use_encoded_value",
    unknown_value=-1
)

ks_encoder.fit(ks_values)

# train 변환
for col in ks_color_cols:
    df_trn_encoded_x[col] = ks_encoder.transform(df_trn_x[[col]])

# test 변환
for col in ks_color_cols:
    df_tst_encoded_x[col] = ks_encoder.transform(df_tst_x[[col]])

C:\Users\Dell5371\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but OrdinalEncoder was fitted without feature names
  warnings.warn(
C:\Users\Dell5371\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but OrdinalEncoder was fitted without feature names
  warnings.warn(
C:\Users\Dell5371\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but OrdinalEncoder was fitted without feature names
  warnings.warn(
C:\Users\Dell5371\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but OrdinalEncoder was fitted without feature names
  warnings.warn(
C:\Users\Dell5371\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but OrdinalEncoder was fitted without feature names
  warnings.warn(
C:\Users\Dell5371\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but OrdinalEncoder was fitted without feature names
  warnings.warn(
C:\Users\Dell5371\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but OrdinalEncoder was fitted without feature names
  warnings.warn(
C:\Users\Dell5371\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but OrdinalEncoder was fitted without feature names
  warnings.warn(

# <b>Train model</b>

In [353]:
# =========================
# 최종 모델 학습 + test 평가
# =========================

final_model2 = XGBRegressor(
        random_state=42,
        objective="reg:squarederror",
        n_estimators=300,
        learning_rate=0.03,
        max_depth=3,
        subsample=0.8,
        colsample_bytree=0.8,
        min_child_weight=5,
        reg_alpha=0.1,
        reg_lambda=5,
        gamma=0.1
    )

# 전체 train y 로그변환
df_trn_y_log = np.log1p(df_trn_y.values.ravel())

# 전체 train으로 학습
final_model2.fit(df_trn_encoded_x, df_trn_y_log)

# train / test 예측
y_train_pred_log = final_model2.predict(df_trn_encoded_x)
y_test_pred_log = final_model2.predict(df_tst_encoded_x)

# 원래 금액 단위 복원
y_train_pred = np.expm1(y_train_pred_log)
y_test_pred = np.expm1(y_test_pred_log)

# 음수 방지
y_train_pred = np.maximum(y_train_pred, 0)
y_test_pred = np.maximum(y_test_pred, 0)

# 실제값
y_train_true = df_trn_y.values.ravel()
y_test_true = df_tst_y.values.ravel()

# 최종 성능
final_result = pd.DataFrame([{
    "model": "XGBoost_final",
    
    "Train_MAE": mean_absolute_error(y_train_true, y_train_pred),
    "Test_MAE": mean_absolute_error(y_test_true, y_test_pred),
    
    "Train_MedianAE": median_absolute_error(y_train_true, y_train_pred),
    "Test_MedianAE": median_absolute_error(y_test_true, y_test_pred),
    
    "Train_RMSE": np.sqrt(mean_squared_error(y_train_true, y_train_pred)),
    "Test_RMSE": np.sqrt(mean_squared_error(y_test_true, y_test_pred)),
    
    "Train_R2": r2_score(y_train_true, y_train_pred),
    "Test_R2": r2_score(y_test_true, y_test_pred)
}])

final_result.round(4)

,model,Train_MAE,Test_MAE,Train_MedianAE,Test_MedianAE,Train_RMSE,Test_RMSE,Train_R2,Test_R2
0,XGBoost_final,20133.97,22250.93,4773.60,6663.77,40994.97,49416.46,0.90,0.85

# optuna

In [124]:
import time
import numpy as np
import pandas as pd
import optuna

from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

# =========================
# 전체 시작 시간
# =========================

total_start_time = time.time()

# =========================
# 1. X, y 준비
# =========================

prep_start_time = time.time()

X_train = df_trn_encoded_x.copy()
X_test = df_tst_encoded_x.copy()

y_train_true = df_trn_y.values.ravel()
y_test_true = df_tst_y.values.ravel()

# y 로그변환
y_train_log = np.log1p(y_train_true)

prep_end_time = time.time()
print(f"[1] 데이터 준비 시간: {prep_end_time - prep_start_time:.2f}초")

# =========================
# 2. train 내부에서 train/valid 분리
# =========================

split_start_time = time.time()

X_train_sub, X_valid, y_train_sub_log, y_valid_log, y_train_sub_true, y_valid_true = train_test_split(
    X_train,
    y_train_log,
    y_train_true,
    test_size=0.2,
    random_state=42
)

split_end_time = time.time()
print(f"[2] train/valid 분리 시간: {split_end_time - split_start_time:.2f}초")

# =========================
# 3. Optuna objective 함수
# =========================

def objective(trial):
    
    trial_start_time = time.time()
    
    params = {
        "random_state": 42,
        "objective": "reg:absoluteerror",
        "eval_metric": "mae",
        "tree_method": "hist",
        "n_jobs": -1,
        
        # 학습량
        "n_estimators": trial.suggest_int("n_estimators", 200, 1000),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.1, log=True),
        
        # 트리 복잡도
        "max_depth": trial.suggest_int("max_depth", 2, 5),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 20),
        
        # 샘플링
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
        
        # 정규화
        "gamma": trial.suggest_float("gamma", 0.0, 2.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 0.0, 3.0),
        "reg_lambda": trial.suggest_float("reg_lambda", 1.0, 30.0),
    }
    
    model = XGBRegressor(**params)
    
    model.fit(
        X_train_sub,
        y_train_sub_log,
        verbose=False
    )
    
    # validation 예측: 로그 스케일
    y_valid_pred_log = model.predict(X_valid)
    
    # 원래 금액 단위 복원
    y_valid_pred = np.expm1(y_valid_pred_log)
    y_valid_pred = np.maximum(y_valid_pred, 0)
    
    # 원래 금액 단위 MAE
    valid_mae = mean_absolute_error(y_valid_true, y_valid_pred)
    
    trial_end_time = time.time()
    
    print(
        f"Trial {trial.number} | "
        f"Valid MAE: {valid_mae:.4f} | "
        f"시간: {trial_end_time - trial_start_time:.2f}초"
    )
    
    return valid_mae

[1] 데이터 준비 시간: 0.00초
[2] train/valid 분리 시간: 0.00초

In [125]:
study = optuna.create_study(direction="minimize")

study.optimize(
    objective,
    n_trials=50
)

print("Best MAE:", study.best_value)
print("Best params:", study.best_params)

[I 2026-06-15 19:49:09,625] A new study created in memory with name: no-name-05e39fd4-4fb3-4c51-8260-8215fc51755f
[I 2026-06-15 19:49:11,796] Trial 0 finished with value: 44037.57920158267 and parameters: {'n_estimators': 667, 'learning_rate': 0.01028210013882417, 'max_depth': 4, 'min_child_weight': 5, 'subsample': 0.9422102512012669, 'colsample_bytree': 0.611086023248821, 'gamma': 0.6817432790251585, 'reg_alpha': 1.2934979838536582, 'reg_lambda': 28.824763433084176}. Best is trial 0 with value: 44037.57920158267.

Trial 0 | Valid MAE: 44037.5792 | 시간: 2.17초

[I 2026-06-15 19:49:14,844] Trial 1 finished with value: 40464.80434310456 and parameters: {'n_estimators': 925, 'learning_rate': 0.05931115470976229, 'max_depth': 2, 'min_child_weight': 10, 'subsample': 0.8892081360801996, 'colsample_bytree': 0.7691717143809905, 'gamma': 0.31109397935163874, 'reg_alpha': 2.7332443966098667, 'reg_lambda': 18.074116199497862}. Best is trial 1 with value: 40464.80434310456.

Trial 1 | Valid MAE: 40464.8043 | 시간: 3.04초

[I 2026-06-15 19:49:18,802] Trial 2 finished with value: 43666.37544591133 and parameters: {'n_estimators': 756, 'learning_rate': 0.030392135755336214, 'max_depth': 4, 'min_child_weight': 10, 'subsample': 0.9276859328628119, 'colsample_bytree': 0.8820899554537467, 'gamma': 0.5084437221638898, 'reg_alpha': 1.591255217295007, 'reg_lambda': 17.983957403575314}. Best is trial 1 with value: 40464.80434310456.

Trial 2 | Valid MAE: 43666.3754 | 시간: 3.95초

[I 2026-06-15 19:49:20,582] Trial 3 finished with value: 43349.68324813325 and parameters: {'n_estimators': 404, 'learning_rate': 0.06152352341937884, 'max_depth': 3, 'min_child_weight': 19, 'subsample': 0.7560588650809951, 'colsample_bytree': 0.8442271007386116, 'gamma': 1.3232344125814457, 'reg_alpha': 1.3689795449723607, 'reg_lambda': 18.635111552918207}. Best is trial 1 with value: 40464.80434310456.

Trial 3 | Valid MAE: 43349.6832 | 시간: 1.78초

[I 2026-06-15 19:49:24,089] Trial 4 finished with value: 41143.3838106884 and parameters: {'n_estimators': 799, 'learning_rate': 0.018501723768125207, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.8685679824866499, 'colsample_bytree': 0.8151287805337625, 'gamma': 0.8046191321465275, 'reg_alpha': 1.2935272425474111, 'reg_lambda': 10.730286638854096}. Best is trial 1 with value: 40464.80434310456.

Trial 4 | Valid MAE: 41143.3838 | 시간: 3.50초

[I 2026-06-15 19:49:25,286] Trial 5 finished with value: 42526.04671539301 and parameters: {'n_estimators': 232, 'learning_rate': 0.04371029468152022, 'max_depth': 4, 'min_child_weight': 10, 'subsample': 0.7625577832418086, 'colsample_bytree': 0.7274489008691719, 'gamma': 0.4316920850400585, 'reg_alpha': 1.430424570825827, 'reg_lambda': 28.368886998834466}. Best is trial 1 with value: 40464.80434310456.

Trial 5 | Valid MAE: 42526.0467 | 시간: 1.19초

[I 2026-06-15 19:49:26,358] Trial 6 finished with value: 40482.795662026816 and parameters: {'n_estimators': 208, 'learning_rate': 0.01907787147352936, 'max_depth': 4, 'min_child_weight': 15, 'subsample': 0.6210803291830247, 'colsample_bytree': 0.6113380399446257, 'gamma': 1.924257207860047, 'reg_alpha': 0.21815186773097783, 'reg_lambda': 1.1270897703404934}. Best is trial 1 with value: 40464.80434310456.

Trial 6 | Valid MAE: 40482.7957 | 시간: 1.07초

[I 2026-06-15 19:49:28,654] Trial 7 finished with value: 42874.83214729085 and parameters: {'n_estimators': 446, 'learning_rate': 0.045839776134176294, 'max_depth': 4, 'min_child_weight': 9, 'subsample': 0.8904785423180451, 'colsample_bytree': 0.8349003448331781, 'gamma': 1.3555224861329602, 'reg_alpha': 2.6269105121648115, 'reg_lambda': 11.964183589622797}. Best is trial 1 with value: 40464.80434310456.

Trial 7 | Valid MAE: 42874.8321 | 시간: 2.29초

[I 2026-06-15 19:49:31,545] Trial 8 finished with value: 40262.725010350325 and parameters: {'n_estimators': 500, 'learning_rate': 0.07341799936600431, 'max_depth': 5, 'min_child_weight': 17, 'subsample': 0.745186950698743, 'colsample_bytree': 0.7964646608168671, 'gamma': 0.0697546253114063, 'reg_alpha': 0.280538215657008, 'reg_lambda': 8.594318999685955}. Best is trial 8 with value: 40262.725010350325.

Trial 8 | Valid MAE: 40262.7250 | 시간: 2.89초

[I 2026-06-15 19:49:34,081] Trial 9 finished with value: 45091.58868001305 and parameters: {'n_estimators': 600, 'learning_rate': 0.08883720470156481, 'max_depth': 3, 'min_child_weight': 10, 'subsample': 0.7411812467809432, 'colsample_bytree': 0.6265984393622422, 'gamma': 1.0848719585251956, 'reg_alpha': 2.8792658308328347, 'reg_lambda': 16.053263847182613}. Best is trial 8 with value: 40262.725010350325.

Trial 9 | Valid MAE: 45091.5887 | 시간: 2.53초

[I 2026-06-15 19:49:37,117] Trial 10 finished with value: 43122.86497834974 and parameters: {'n_estimators': 484, 'learning_rate': 0.010385891104085651, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.6061046729579538, 'colsample_bytree': 0.9886686745729155, 'gamma': 0.0032196031165284134, 'reg_alpha': 0.05691531148936235, 'reg_lambda': 1.0603735116230997}. Best is trial 8 with value: 40262.725010350325.

Trial 10 | Valid MAE: 43122.8650 | 시간: 3.03초

[I 2026-06-15 19:49:40,518] Trial 11 finished with value: 37469.23994671136 and parameters: {'n_estimators': 985, 'learning_rate': 0.09596970984771967, 'max_depth': 2, 'min_child_weight': 15, 'subsample': 0.9990471098481485, 'colsample_bytree': 0.7398936534273078, 'gamma': 0.018176468692449634, 'reg_alpha': 2.2145725303165333, 'reg_lambda': 6.864862375848334}. Best is trial 11 with value: 37469.23994671136.

Trial 11 | Valid MAE: 37469.2399 | 시간: 3.40초

[I 2026-06-15 19:49:43,944] Trial 12 finished with value: 41352.40029255523 and parameters: {'n_estimators': 993, 'learning_rate': 0.08807321481423008, 'max_depth': 2, 'min_child_weight': 16, 'subsample': 0.8184595935876272, 'colsample_bytree': 0.7500705682829498, 'gamma': 0.0006971968923861482, 'reg_alpha': 0.615195624411105, 'reg_lambda': 6.677503687928013}. Best is trial 11 with value: 37469.23994671136.

Trial 12 | Valid MAE: 41352.4003 | 시간: 3.42초

[I 2026-06-15 19:49:48,889] Trial 13 finished with value: 38577.55774139206 and parameters: {'n_estimators': 830, 'learning_rate': 0.09758037441688636, 'max_depth': 5, 'min_child_weight': 15, 'subsample': 0.6842376885820948, 'colsample_bytree': 0.7050444575427137, 'gamma': 0.16149164467501895, 'reg_alpha': 2.1245182202776585, 'reg_lambda': 6.594989860003941}. Best is trial 11 with value: 37469.23994671136.

Trial 13 | Valid MAE: 38577.5577 | 시간: 4.94초

[I 2026-06-15 19:49:52,069] Trial 14 finished with value: 38773.37525981736 and parameters: {'n_estimators': 888, 'learning_rate': 0.09728674794094631, 'max_depth': 2, 'min_child_weight': 14, 'subsample': 0.9809036285637915, 'colsample_bytree': 0.6850395336758661, 'gamma': 0.2835133480133597, 'reg_alpha': 2.1374069872647157, 'reg_lambda': 5.142422578656786}. Best is trial 11 with value: 37469.23994671136.

Trial 14 | Valid MAE: 38773.3753 | 시간: 3.18초

[I 2026-06-15 19:49:56,952] Trial 15 finished with value: 41513.78751909387 and parameters: {'n_estimators': 839, 'learning_rate': 0.06761455398296597, 'max_depth': 5, 'min_child_weight': 13, 'subsample': 0.6649306507146442, 'colsample_bytree': 0.6924587629883855, 'gamma': 0.2502732423983903, 'reg_alpha': 2.1091447124638005, 'reg_lambda': 13.223055393668476}. Best is trial 11 with value: 37469.23994671136.

Trial 15 | Valid MAE: 41513.7875 | 시간: 4.88초

[I 2026-06-15 19:50:01,017] Trial 16 finished with value: 39188.65946712686 and parameters: {'n_estimators': 991, 'learning_rate': 0.04895429575016932, 'max_depth': 3, 'min_child_weight': 20, 'subsample': 0.6833682357136506, 'colsample_bytree': 0.6638259268204216, 'gamma': 0.678074054563939, 'reg_alpha': 1.9954324244683928, 'reg_lambda': 4.518522489246971}. Best is trial 11 with value: 37469.23994671136.

Trial 16 | Valid MAE: 39188.6595 | 시간: 4.06초

[I 2026-06-15 19:50:02,399] Trial 17 finished with value: 38549.86515194606 and parameters: {'n_estimators': 720, 'learning_rate': 0.03454682440206207, 'max_depth': 2, 'min_child_weight': 13, 'subsample': 0.8262787292669458, 'colsample_bytree': 0.9353002780686687, 'gamma': 0.19836183240176544, 'reg_alpha': 2.3525309691215517, 'reg_lambda': 22.311035395771572}. Best is trial 11 with value: 37469.23994671136.

Trial 17 | Valid MAE: 38549.8652 | 시간: 1.38초

[I 2026-06-15 19:50:04,870] Trial 18 finished with value: 39167.65432076691 and parameters: {'n_estimators': 706, 'learning_rate': 0.023787055274774295, 'max_depth': 2, 'min_child_weight': 12, 'subsample': 0.816171747412246, 'colsample_bytree': 0.948223376313248, 'gamma': 0.5001054916419755, 'reg_alpha': 2.526310259732397, 'reg_lambda': 24.133081151185927}. Best is trial 11 with value: 37469.23994671136.

Trial 18 | Valid MAE: 39167.6543 | 시간: 2.47초

[I 2026-06-15 19:50:06,797] Trial 19 finished with value: 42201.87629954489 and parameters: {'n_estimators': 591, 'learning_rate': 0.032001615655988414, 'max_depth': 2, 'min_child_weight': 18, 'subsample': 0.9904253593536787, 'colsample_bytree': 0.8923710038028353, 'gamma': 0.8992007054359138, 'reg_alpha': 1.7355100329615198, 'reg_lambda': 21.765786738083143}. Best is trial 11 with value: 37469.23994671136.

Trial 19 | Valid MAE: 42201.8763 | 시간: 1.92초

[I 2026-06-15 19:50:09,941] Trial 20 finished with value: 41833.85191024262 and parameters: {'n_estimators': 918, 'learning_rate': 0.014761517415731678, 'max_depth': 2, 'min_child_weight': 12, 'subsample': 0.8350503606859122, 'colsample_bytree': 0.9336563595851004, 'gamma': 0.3850990365369452, 'reg_alpha': 2.501479562515885, 'reg_lambda': 24.305701156270963}. Best is trial 11 with value: 37469.23994671136.

Trial 20 | Valid MAE: 41833.8519 | 시간: 3.14초

[I 2026-06-15 19:50:13,657] Trial 21 finished with value: 41375.73154896847 and parameters: {'n_estimators': 830, 'learning_rate': 0.03467505886714153, 'max_depth': 3, 'min_child_weight': 15, 'subsample': 0.6766263613200756, 'colsample_bytree': 0.7342014893254597, 'gamma': 0.16986401600800824, 'reg_alpha': 2.2633973240476775, 'reg_lambda': 9.716463306197205}. Best is trial 11 with value: 37469.23994671136.

Trial 21 | Valid MAE: 41375.7315 | 시간: 3.71초

[I 2026-06-15 19:50:17,000] Trial 22 finished with value: 37618.16045998369 and parameters: {'n_estimators': 741, 'learning_rate': 0.07854956502692007, 'max_depth': 3, 'min_child_weight': 17, 'subsample': 0.7074492571180653, 'colsample_bytree': 0.6547636801020709, 'gamma': 0.15274228933610268, 'reg_alpha': 1.8782032220056095, 'reg_lambda': 13.563305859899582}. Best is trial 11 with value: 37469.23994671136.

Trial 22 | Valid MAE: 37618.1605 | 시간: 3.34초

[I 2026-06-15 19:50:20,037] Trial 23 finished with value: 39329.57537193527 and parameters: {'n_estimators': 669, 'learning_rate': 0.07639801171364245, 'max_depth': 3, 'min_child_weight': 17, 'subsample': 0.7964106972707248, 'colsample_bytree': 0.6508380601327433, 'gamma': 0.17846586887888238, 'reg_alpha': 1.0214903190712707, 'reg_lambda': 13.730694280367553}. Best is trial 11 with value: 37469.23994671136.

Trial 23 | Valid MAE: 39329.5754 | 시간: 3.03초

[I 2026-06-15 19:50:22,668] Trial 24 finished with value: 41468.649673233806 and parameters: {'n_estimators': 739, 'learning_rate': 0.05583846951393879, 'max_depth': 2, 'min_child_weight': 13, 'subsample': 0.9402581750971318, 'colsample_bytree': 0.9939675589308199, 'gamma': 0.6220945823791201, 'reg_alpha': 1.8303691075030055, 'reg_lambda': 15.273584490500383}. Best is trial 11 with value: 37469.23994671136.

Trial 24 | Valid MAE: 41468.6497 | 시간: 2.63초

[I 2026-06-15 19:50:24,808] Trial 25 finished with value: 39374.409879328436 and parameters: {'n_estimators': 594, 'learning_rate': 0.03609036279184158, 'max_depth': 2, 'min_child_weight': 20, 'subsample': 0.7111467539790841, 'colsample_bytree': 0.7726403715171484, 'gamma': 0.3818667019972072, 'reg_alpha': 2.349634801700983, 'reg_lambda': 21.32704476250141}. Best is trial 11 with value: 37469.23994671136.

Trial 25 | Valid MAE: 39374.4099 | 시간: 2.14초

[I 2026-06-15 19:50:26,473] Trial 26 finished with value: 40550.72737855597 and parameters: {'n_estimators': 367, 'learning_rate': 0.026171705581854478, 'max_depth': 3, 'min_child_weight': 18, 'subsample': 0.640413096226046, 'colsample_bytree': 0.645707407485383, 'gamma': 0.08293104572958604, 'reg_alpha': 1.893514885915674, 'reg_lambda': 3.5003312038503993}. Best is trial 11 with value: 37469.23994671136.

Trial 26 | Valid MAE: 40550.7274 | 시간: 1.66초

[I 2026-06-15 19:50:28,500] Trial 27 finished with value: 39828.161201592986 and parameters: {'n_estimators': 648, 'learning_rate': 0.07828431573490935, 'max_depth': 2, 'min_child_weight': 12, 'subsample': 0.853194191618663, 'colsample_bytree': 0.9381438399246577, 'gamma': 1.8251555588945645, 'reg_alpha': 2.370039851829209, 'reg_lambda': 26.33150419529743}. Best is trial 11 with value: 37469.23994671136.

Trial 27 | Valid MAE: 39828.1612 | 시간: 2.02초

[I 2026-06-15 19:50:31,950] Trial 28 finished with value: 39678.51336889464 and parameters: {'n_estimators': 772, 'learning_rate': 0.039685153087732176, 'max_depth': 3, 'min_child_weight': 16, 'subsample': 0.7906458351690124, 'colsample_bytree': 0.8939914151714802, 'gamma': 0.2464814131947202, 'reg_alpha': 0.9428506348483408, 'reg_lambda': 8.136361290657765}. Best is trial 11 with value: 37469.23994671136.

Trial 28 | Valid MAE: 39678.5134 | 시간: 3.45초

[I 2026-06-15 19:50:34,347] Trial 29 finished with value: 40816.02233401264 and parameters: {'n_estimators': 695, 'learning_rate': 0.05550371665086345, 'max_depth': 2, 'min_child_weight': 5, 'subsample': 0.96336457032609, 'colsample_bytree': 0.8609825156612747, 'gamma': 0.5152535274332433, 'reg_alpha': 2.930033212456432, 'reg_lambda': 29.695413618625587}. Best is trial 11 with value: 37469.23994671136.

Trial 29 | Valid MAE: 40816.0223 | 시간: 2.39초

[I 2026-06-15 19:50:38,246] Trial 30 finished with value: 42516.4742921812 and parameters: {'n_estimators': 886, 'learning_rate': 0.013208778888880866, 'max_depth': 3, 'min_child_weight': 14, 'subsample': 0.9108286499362752, 'colsample_bytree': 0.6739587138609808, 'gamma': 0.8243378071279511, 'reg_alpha': 1.6249160715948352, 'reg_lambda': 19.60909740192346}. Best is trial 11 with value: 37469.23994671136.

Trial 30 | Valid MAE: 42516.4743 | 시간: 3.89초

[I 2026-06-15 19:50:43,350] Trial 31 finished with value: 38970.34139666045 and parameters: {'n_estimators': 844, 'learning_rate': 0.09788206094114392, 'max_depth': 5, 'min_child_weight': 15, 'subsample': 0.6996709004212047, 'colsample_bytree': 0.6994999256876222, 'gamma': 0.15604680893046347, 'reg_alpha': 2.1360895465502265, 'reg_lambda': 6.544023774570324}. Best is trial 11 with value: 37469.23994671136.

Trial 31 | Valid MAE: 38970.3414 | 시간: 5.10초

[I 2026-06-15 19:50:48,520] Trial 32 finished with value: 36038.26457479449 and parameters: {'n_estimators': 955, 'learning_rate': 0.08085052167943471, 'max_depth': 4, 'min_child_weight': 17, 'subsample': 0.7200247864446896, 'colsample_bytree': 0.7138505770668886, 'gamma': 0.3206907131215627, 'reg_alpha': 1.977447861369854, 'reg_lambda': 3.2939769332775097}. Best is trial 32 with value: 36038.26457479449.

Trial 32 | Valid MAE: 36038.2646 | 시간: 5.16초

[I 2026-06-15 19:50:53,470] Trial 33 finished with value: 38415.234977391345 and parameters: {'n_estimators': 945, 'learning_rate': 0.06379554903463067, 'max_depth': 4, 'min_child_weight': 18, 'subsample': 0.713479188890466, 'colsample_bytree': 0.6046096493328563, 'gamma': 0.3579878284043524, 'reg_alpha': 2.7665834498211908, 'reg_lambda': 3.684604693501102}. Best is trial 32 with value: 36038.26457479449.

Trial 33 | Valid MAE: 38415.2350 | 시간: 4.94초

[I 2026-06-15 19:50:58,443] Trial 34 finished with value: 39458.24191734188 and parameters: {'n_estimators': 950, 'learning_rate': 0.06574295953572112, 'max_depth': 4, 'min_child_weight': 18, 'subsample': 0.7225663723420582, 'colsample_bytree': 0.6061852601620247, 'gamma': 0.34761308456501966, 'reg_alpha': 2.726842323871198, 'reg_lambda': 2.787830819697744}. Best is trial 32 with value: 36038.26457479449.

Trial 34 | Valid MAE: 39458.2419 | 시간: 4.97초

[I 2026-06-15 19:51:03,308] Trial 35 finished with value: 39211.938103346896 and parameters: {'n_estimators': 953, 'learning_rate': 0.08325926990657226, 'max_depth': 4, 'min_child_weight': 19, 'subsample': 0.6400496431637676, 'colsample_bytree': 0.6348794805251721, 'gamma': 0.6142841852475778, 'reg_alpha': 1.5277625416573375, 'reg_lambda': 3.571048136912626}. Best is trial 32 with value: 36038.26457479449.

Trial 35 | Valid MAE: 39211.9381 | 시간: 4.86초

[I 2026-06-15 19:51:08,082] Trial 36 finished with value: 42293.41722091772 and parameters: {'n_estimators': 914, 'learning_rate': 0.05239099210744701, 'max_depth': 4, 'min_child_weight': 17, 'subsample': 0.7704650835423766, 'colsample_bytree': 0.7579163570325287, 'gamma': 0.5065500297244787, 'reg_alpha': 1.7319526355259816, 'reg_lambda': 10.667103898328161}. Best is trial 32 with value: 36038.26457479449.

Trial 36 | Valid MAE: 42293.4172 | 시간: 4.77초

[I 2026-06-15 19:51:13,112] Trial 37 finished with value: 39387.76886006794 and parameters: {'n_estimators': 967, 'learning_rate': 0.06098786023550655, 'max_depth': 4, 'min_child_weight': 19, 'subsample': 0.7255624699346752, 'colsample_bytree': 0.7329000583254599, 'gamma': 0.3173308275232269, 'reg_alpha': 2.756482974861988, 'reg_lambda': 2.0620755220895592}. Best is trial 32 with value: 36038.26457479449.

Trial 37 | Valid MAE: 39387.7689 | 시간: 5.02초

[I 2026-06-15 19:51:17,662] Trial 38 finished with value: 42522.85439684295 and parameters: {'n_estimators': 871, 'learning_rate': 0.06965177099862738, 'max_depth': 4, 'min_child_weight': 16, 'subsample': 0.6509422960826506, 'colsample_bytree': 0.7897417249690072, 'gamma': 0.09086177554355071, 'reg_alpha': 1.1203706270002416, 'reg_lambda': 5.673860021882008}. Best is trial 32 with value: 36038.26457479449.

Trial 38 | Valid MAE: 42522.8544 | 시간: 4.55초

[I 2026-06-15 19:51:21,789] Trial 39 finished with value: 42844.185996612374 and parameters: {'n_estimators': 788, 'learning_rate': 0.06180966197046531, 'max_depth': 4, 'min_child_weight': 20, 'subsample': 0.7719510805496538, 'colsample_bytree': 0.7168290715117216, 'gamma': 0.45035612367823125, 'reg_alpha': 1.9733485676349354, 'reg_lambda': 8.527277202331284}. Best is trial 32 with value: 36038.26457479449.

Trial 39 | Valid MAE: 42844.1860 | 시간: 4.12초

[I 2026-06-15 19:51:26,674] Trial 40 finished with value: 42364.65260047057 and parameters: {'n_estimators': 930, 'learning_rate': 0.08333364338452404, 'max_depth': 4, 'min_child_weight': 18, 'subsample': 0.8728253941148443, 'colsample_bytree': 0.6240565665355069, 'gamma': 0.7604218146278681, 'reg_alpha': 1.4749485757869452, 'reg_lambda': 16.478626434612043}. Best is trial 32 with value: 36038.26457479449.

Trial 40 | Valid MAE: 42364.6526 | 시간: 4.88초

[I 2026-06-15 19:51:29,937] Trial 41 finished with value: 40076.767710333894 and parameters: {'n_estimators': 734, 'learning_rate': 0.07243112140985022, 'max_depth': 3, 'min_child_weight': 17, 'subsample': 0.7342757763738177, 'colsample_bytree': 0.6003841985490228, 'gamma': 0.18630808541038102, 'reg_alpha': 2.4867666439167384, 'reg_lambda': 4.556906236264338}. Best is trial 32 with value: 36038.26457479449.

Trial 41 | Valid MAE: 40076.7677 | 시간: 3.26초

[I 2026-06-15 19:51:34,292] Trial 42 finished with value: 42193.39188538279 and parameters: {'n_estimators': 997, 'learning_rate': 0.02599891355364738, 'max_depth': 3, 'min_child_weight': 14, 'subsample': 0.9068158113552284, 'colsample_bytree': 0.651979823613588, 'gamma': 0.29227057018916935, 'reg_alpha': 2.284822876743753, 'reg_lambda': 12.639405768969795}. Best is trial 32 with value: 36038.26457479449.

Trial 42 | Valid MAE: 42193.3919 | 시간: 4.35초

[I 2026-06-15 19:51:37,170] Trial 43 finished with value: 41430.33888499342 and parameters: {'n_estimators': 804, 'learning_rate': 0.043486822269808344, 'max_depth': 2, 'min_child_weight': 16, 'subsample': 0.703485013953236, 'colsample_bytree': 0.8232838760492371, 'gamma': 0.08236305230890834, 'reg_alpha': 2.6607657633821606, 'reg_lambda': 2.4281902552533836}. Best is trial 32 with value: 36038.26457479449.

Trial 43 | Valid MAE: 41430.3389 | 시간: 2.87초

[I 2026-06-15 19:51:39,645] Trial 44 finished with value: 41606.92966207821 and parameters: {'n_estimators': 548, 'learning_rate': 0.09080557448244467, 'max_depth': 3, 'min_child_weight': 11, 'subsample': 0.9582885430862257, 'colsample_bytree': 0.6698499603478559, 'gamma': 0.012901245407471368, 'reg_alpha': 2.988704611280805, 'reg_lambda': 11.15330207913393}. Best is trial 32 with value: 36038.26457479449.

Trial 44 | Valid MAE: 41606.9297 | 시간: 2.47초

[I 2026-06-15 19:51:42,966] Trial 45 finished with value: 43834.48968122697 and parameters: {'n_estimators': 638, 'learning_rate': 0.0798312183375263, 'max_depth': 4, 'min_child_weight': 9, 'subsample': 0.6033015242058393, 'colsample_bytree': 0.6230253495141398, 'gamma': 0.24544398928655828, 'reg_alpha': 2.7989226172687873, 'reg_lambda': 18.59534232082956}. Best is trial 32 with value: 36038.26457479449.

Trial 45 | Valid MAE: 43834.4897 | 시간: 3.32초

[I 2026-06-15 19:51:45,972] Trial 46 finished with value: 39386.35053878498 and parameters: {'n_estimators': 867, 'learning_rate': 0.021444838085480165, 'max_depth': 2, 'min_child_weight': 13, 'subsample': 0.7525481484346599, 'colsample_bytree': 0.8640515112589616, 'gamma': 0.5661347786382476, 'reg_alpha': 2.5606264030810464, 'reg_lambda': 14.417410533084151}. Best is trial 32 with value: 36038.26457479449.

Trial 46 | Valid MAE: 39386.3505 | 시간: 3.00초

[I 2026-06-15 19:51:51,173] Trial 47 finished with value: 39946.410416706116 and parameters: {'n_estimators': 907, 'learning_rate': 0.06525934368708727, 'max_depth': 5, 'min_child_weight': 19, 'subsample': 0.7926620696044842, 'colsample_bytree': 0.8000936475289095, 'gamma': 0.39247595043287153, 'reg_alpha': 2.028147421992481, 'reg_lambda': 7.525096748294926}. Best is trial 32 with value: 36038.26457479449.

Trial 47 | Valid MAE: 39946.4104 | 시간: 5.20초

[I 2026-06-15 19:51:56,075] Trial 48 finished with value: 42102.095711059264 and parameters: {'n_estimators': 965, 'learning_rate': 0.04924045093167034, 'max_depth': 4, 'min_child_weight': 16, 'subsample': 0.6670223059969614, 'colsample_bytree': 0.7094730983638105, 'gamma': 0.08368731462372603, 'reg_alpha': 2.3567886821080974, 'reg_lambda': 17.069378782312214}. Best is trial 32 with value: 36038.26457479449.

Trial 48 | Valid MAE: 42102.0957 | 시간: 4.90초

[I 2026-06-15 19:51:59,273] Trial 49 finished with value: 41085.1232903314 and parameters: {'n_estimators': 756, 'learning_rate': 0.09039958879503071, 'max_depth': 3, 'min_child_weight': 1, 'subsample': 0.7030427357436209, 'colsample_bytree': 0.6867924192489668, 'gamma': 1.7250298567181688, 'reg_alpha': 2.2173369540523318, 'reg_lambda': 9.720700103997167}. Best is trial 32 with value: 36038.26457479449.

Trial 49 | Valid MAE: 41085.1233 | 시간: 3.19초
Best MAE: 36038.26457479449
Best params: {'n_estimators': 955, 'learning_rate': 0.08085052167943471, 'max_depth': 4, 'min_child_weight': 17, 'subsample': 0.7200247864446896, 'colsample_bytree': 0.7138505770668886, 'gamma': 0.3206907131215627, 'reg_alpha': 1.977447861369854, 'reg_lambda': 3.2939769332775097}

In [126]:
best_params = study.best_params.copy()

final_model = XGBRegressor(
    random_state=42,
    objective="reg:absoluteerror",
    eval_metric="mae",
    tree_method="hist",
    n_jobs=-1,
    **best_params
)

final_model.fit(
    X_train,
    y_train_log,
    verbose=False
)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.7138505770668886, device=None,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric='mae', feature_types=None, feature_weights=None,
             gamma=0.3206907131215627, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.08085052167943471,
             max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=4, max_leaves=None,
             min_child_weight=17, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=955, n_jobs=-1,
             num_parallel_tree=None, ...)

In [127]:
from sklearn.metrics import (
    mean_absolute_error,
    median_absolute_error,
    mean_squared_error,
    r2_score
)

y_train_pred_log = final_model.predict(X_train)
y_test_pred_log = final_model.predict(X_test)

# 원래 금액 단위 복원
y_train_pred = np.expm1(y_train_pred_log)
y_test_pred = np.expm1(y_test_pred_log)

# 음수 방지
y_train_pred = np.maximum(y_train_pred, 0)
y_test_pred = np.maximum(y_test_pred, 0)

train_r2 = r2_score(y_train_true, y_train_pred)
test_r2 = r2_score(y_test_true, y_test_pred)

final_result = pd.DataFrame([{
    "model": "XGBoost_Optuna_no_KFold",
    
    "Train_MAE": mean_absolute_error(y_train_true, y_train_pred),
    "Test_MAE": mean_absolute_error(y_test_true, y_test_pred),
    
    "Train_MedianAE": median_absolute_error(y_train_true, y_train_pred),
    "Test_MedianAE": median_absolute_error(y_test_true, y_test_pred),
    
    "Train_RMSE": np.sqrt(mean_squared_error(y_train_true, y_train_pred)),
    "Test_RMSE": np.sqrt(mean_squared_error(y_test_true, y_test_pred)),
    
    "Train_R2": train_r2,
    "Test_R2": test_r2,
    "R2_gap": train_r2 - test_r2
}])

final_result.round(4)

,model,Train_MAE,Test_MAE,Train_MedianAE,Test_MedianAE,Train_RMSE,Test_RMSE,Train_R2,Test_R2,R2_gap
0,XGBoost_Optuna_no_KFold,9425.03,19750.69,243.71,6707.42,27273.46,41900.75,0.96,0.89,0.06

In [129]:
# =========================
# 9. Optuna 결과 상위 10개
# =========================

trials_df = study.trials_dataframe()

trials_view = trials_df.sort_values("value", ascending=True)

trials_view[[
    "number",
    "value",
    "params_n_estimators",
    "params_learning_rate",
    "params_max_depth",
    "params_min_child_weight",
    "params_subsample",
    "params_colsample_bytree",
    "params_gamma",
    "params_reg_alpha",
    "params_reg_lambda"
]].head(10)

,number,value,params_n_estimators,params_learning_rate,params_max_depth,params_min_child_weight,params_subsample,params_colsample_bytree,params_gamma,params_reg_alpha,params_reg_lambda
32,32,36038.26,955,0.08,4,17,0.72,0.71,0.32,1.98,3.29
11,11,37469.24,985,0.10,2,15,1.00,0.74,0.02,2.21,6.86
22,22,37618.16,741,0.08,3,17,0.71,0.65,0.15,1.88,13.56
33,33,38415.23,945,0.06,4,18,0.71,0.60,0.36,2.77,3.68
17,17,38549.87,720,0.03,2,13,0.83,0.94,0.20,2.35,22.31
13,13,38577.56,830,0.10,5,15,0.68,0.71,0.16,2.12,6.59
14,14,38773.38,888,0.10,2,14,0.98,0.69,0.28,2.14,5.14
31,31,38970.34,844,0.10,5,15,0.70,0.70,0.16,2.14,6.54
18,18,39167.65,706,0.02,2,12,0.82,0.95,0.50,2.53,24.13
16,16,39188.66,991,0.05,3,20,0.68,0.66,0.68,2.00,4.52

In [130]:
trials_view[[
    "number",
    "value",
    "params_n_estimators",
    "params_learning_rate",
    "params_max_depth",
    "params_min_child_weight",
    "params_subsample",
    "params_colsample_bytree",
    "params_gamma",
    "params_reg_alpha",
    "params_reg_lambda"
]].head(10).to_csv('params1.csv',encoding='utf-8-sig')